// Cantrips (level 0) — full SRD 5.1 list, enriched with 2024 PHB / SRD 5.2 detail
// (concentration/ritual flags, full descriptions, scaling tables, AoE, damage types).

import type { SrdSpell } from './types'

export const CANTRIPS: SrdSpell[] = [
  {
    name: 'Acid Splash',
    level: 0,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    saveAbility: 'dex',
    damage: '1d6',
    damageType: 'acid',
    classes: ['sorcerer', 'wizard', 'artificer'],
    concentration: false,
    ritual: false,
    targets: 'One or two creatures within 5 ft of each other',
    notes: 'Dex save or take acid damage. Can target two creatures within 5 ft of each other.',
    fullDescription:
      'You create an acidic bubble at a point within range, then choose one or two creatures within 5 feet of that point. Each target must succeed on a Dexterity saving throw or take 1d6 acid damage.',
    cantripScaling: { l5: '2d6', l11: '3d6', l17: '4d6' },
    source: 'srd-5.2',
  },
  {
    name: 'Blade Ward',
    level: 0,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: '1 round',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'Self',
    notes: 'Gain resistance to bludgeoning, piercing, and slashing damage from weapon attacks until end of next turn.',
    fullDescription:
      'You extend your hand and trace a sigil of warding in the air. Until the end of your next turn, you have resistance against bludgeoning, piercing, and slashing damage dealt by weapon attacks.',
    source: 'srd-5.2',
  },
  {
    name: 'Chill Touch',
    level: 0,
    school: 'Necromancy',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: '1 round',
    attackRoll: true,
    damage: '1d8',
    damageType: 'necrotic',
    classes: ['sorcerer', 'warlock', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'One creature within range',
    notes: 'Ranged spell attack; necrotic damage, and target cannot regain HP until start of your next turn.',
    fullDescription:
      'You create a ghostly, skeletal hand in the space of a creature within range. Make a ranged spell attack. On a hit, the target takes 1d8 necrotic damage, and it can\'t regain hit points until the start of your next turn. Until then, the hand clings to the target. If you hit an undead target, it also has disadvantage on attack rolls against you until the end of your next turn.',
    cantripScaling: { l5: '2d8', l11: '3d8', l17: '4d8' },
    source: 'srd-5.2',
  },
  {
    name: 'Dancing Lights',
    level: 0,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    classes: ['bard', 'sorcerer', 'wizard', 'artificer'],
    concentration: true,
    ritual: false,
    targets: 'Up to four lights',
    notes: 'Create up to four floating, torch-sized lights that can move up to 60 ft per turn.',
    fullDescription:
      'You create up to four torch-sized lights within range, making them appear as torches, lanterns, or glowing orbs that hover in the air for the duration. You can combine the lights into one glowing humanoid form. Whichever form you choose, each light sheds dim light in a 10-foot radius. As a bonus action on your turn, you can move the lights up to 60 feet to a new spot within range.',
    source: 'srd-5.2',
  },
  {
    name: 'Druidcraft',
    level: 0,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['druid'],
    concentration: false,
    ritual: false,
    notes: 'Minor nature-themed effects: predict weather, make a flower bloom, create a breeze, etc.',
    fullDescription:
      'Whispering to the spirits of nature, you create one of the following effects within range: a tiny, harmless sensory effect that predicts the weather at your location for the next 24 hours; you instantly make a flower blossom, a seed pod open, or a leaf bud bloom; you create an instantaneous, harmless sensory effect such as falling leaves, a puff of wind, or the sound of a small animal; or you instantly light or snuff out a candle, a torch, or a small campfire.',
    source: 'srd-5.2',
  },
  {
    name: 'Eldritch Blast',
    level: 0,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    attackRoll: true,
    damage: '1d10',
    damageType: 'force',
    classes: ['warlock'],
    concentration: false,
    ritual: false,
    targets: 'One creature per beam',
    notes: 'Ranged spell attack, force damage. Multiple beams at higher levels.',
    fullDescription:
      'A beam of crackling energy streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 force damage. The spell creates more than one beam when you reach higher levels: two beams at 5th level, three at 11th level, and four at 17th level. You can direct the beams at the same target or at different ones. Make a separate attack roll for each beam.',
    higherLevels:
      'At higher caster levels you fire additional beams instead of larger dice — 2 beams at 5th, 3 at 11th, 4 at 17th. Each beam still deals 1d10 force damage.',
    // Eldritch Blast scales by beam count, not die size. We store the per-beam dice
    // and the consumers (SpellsPanel/SpellDashboard) read higherLevels to know the
    // total number of beams.
    cantripScaling: { l5: '1d10 (×2 beams)', l11: '1d10 (×3 beams)', l17: '1d10 (×4 beams)' },
    source: 'srd-5.2',
  },
  {
    name: 'Fire Bolt',
    level: 0,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    attackRoll: true,
    damage: '1d10',
    damageType: 'fire',
    classes: ['sorcerer', 'wizard', 'artificer'],
    concentration: false,
    ritual: false,
    targets: 'One creature or object within range',
    notes: 'Ranged spell attack, deals fire damage.',
    fullDescription:
      'You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn\'t being worn or carried.',
    cantripScaling: { l5: '2d10', l11: '3d10', l17: '4d10' },
    source: 'srd-5.2',
  },
  {
    name: 'Friends',
    level: 0,
    school: 'Enchantment',
    castingTime: '1 action',
    range: 'Self',
    components: 'S, M',
    duration: 'Up to 1 minute (concentration)',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
    concentration: true,
    ritual: false,
    targets: 'One creature (non-hostile)',
    notes: 'Advantage on Charisma checks against one non-hostile creature. The creature becomes hostile afterward.',
    fullDescription:
      'For the duration, you have advantage on all Charisma checks directed at one creature of your choice that isn\'t hostile toward you. When the spell ends, the creature realizes that you used magic to influence its mood and becomes hostile toward you. A creature prone to violence might attack you. Another creature might seek retribution in other ways depending on its nature and demeanor.',
    source: 'srd-5.2',
  },
  {
    name: 'Guidance',
    level: 0,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    classes: ['cleric', 'druid', 'artificer'],
    concentration: true,
    ritual: false,
    targets: 'One willing creature you touch',
    notes: 'Touch a willing creature; it adds 1d4 to one ability check of its choice.',
    fullDescription:
      'You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends.',
    source: 'srd-5.2',
  },
  {
    name: 'Light',
    level: 0,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, M',
    duration: '1 hour',
    classes: ['bard', 'cleric', 'sorcerer', 'wizard', 'artificer'],
    concentration: false,
    ritual: false,
    targets: 'One object (no larger than 10 ft in any dimension)',
    notes: 'Object sheds bright light in 20-ft radius, dim light an additional 20 ft. Dex save to avoid if held by unwilling creature.',
    fullDescription:
      'You touch one object that is no larger than 10 feet in any dimension. Until the spell ends, the object sheds bright light in a 20-foot radius and dim light for an additional 20 feet. The light can be colored as you like. Completely covering the object with something opaque blocks the light. The spell ends if you cast it again or dismiss it as an action. If you target an object held or worn by a hostile creature, that creature must succeed on a Dexterity saving throw to avoid the spell.',
    source: 'srd-5.2',
  },
  {
    name: 'Mage Hand',
    level: 0,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: '1 minute',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard', 'artificer'],
    concentration: false,
    ritual: false,
    targets: 'A spectral hand',
    notes: 'Spectral floating hand manipulates objects up to 10 lb, opens doors, carries items, etc.',
    fullDescription:
      'A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration or until you dismiss it as an action. The hand vanishes if it is ever more than 30 feet away from you or if you cast this spell again. You can use your action to control the hand. You can use the hand to manipulate an object, open an unlocked door or container, stow or retrieve an item from an open container, or pour the contents out of a vial. You can move the hand up to 30 feet each time you use it. The hand can\'t attack, activate magic items, or carry more than 10 pounds.',
    source: 'srd-5.2',
  },
  {
    name: 'Mending',
    level: 0,
    school: 'Transmutation',
    castingTime: '1 minute',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    classes: ['bard', 'cleric', 'druid', 'sorcerer', 'wizard', 'artificer'],
    concentration: false,
    ritual: false,
    targets: 'One damaged object',
    notes: 'Repair a single break or tear in an object. Magic items can be repaired but their magical properties are not restored.',
    fullDescription:
      'This spell repairs a single break or tear in an object you touch, such as a broken chain link, two halves of a broken key, a torn cloak, or a leaking wineskin. As long as the break or tear is no larger than 1 foot in any dimension, you mend it, leaving no trace of the former damage. This spell can physically repair a magic item or construct, but the spell can\'t restore magic to such an object.',
    source: 'srd-5.2',
  },
  {
    name: 'Message',
    level: 0,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: '1 round',
    classes: ['bard', 'sorcerer', 'wizard', 'artificer'],
    concentration: false,
    ritual: false,
    targets: 'One creature within range',
    notes: 'Whisper a message to a creature; it can whisper a reply that only you hear.',
    fullDescription:
      'You point your finger toward a creature within range and whisper a message. The target (and only the target) hears the message and can reply in a whisper that only you can hear. You can cast this spell through solid objects if you are familiar with the target and know it is beyond the barrier. Magical silence, 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood blocks the spell. The spell doesn\'t have to follow a straight line and can travel freely around corners or through openings.',
    source: 'srd-5.2',
  },
  {
    name: 'Minor Illusion',
    level: 0,
    school: 'Illusion',
    castingTime: '1 action',
    range: '30 feet',
    components: 'S, M',
    duration: '1 minute',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'A sound or image',
    notes: 'Create a sound or image of an object. Investigation check against your spell save DC to discern the illusion.',
    fullDescription:
      'You create a sound or an image of an object within range that lasts for the duration. The illusion also ends if you dismiss it as an action or cast this spell again. If you create a sound, its volume can range from a whisper to a scream. It can be your voice, someone else\'s voice, a lion\'s roar, a beating of drums, or any other sound you choose. If you create an image of an object — such as a chair, muddy footprints, or a small chest — it must fit within a 5-foot cube. The image can\'t create sound, light, smell, or any other sensory effect. Physical interaction with the image reveals it to be an illusion, because things can pass through it. If a creature uses its action to examine the sound or image, the creature can determine that it is an illusion with a successful Intelligence (Investigation) check against your spell save DC.',
    source: 'srd-5.2',
  },
  {
    name: 'Poison Spray',
    level: 0,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '10 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    saveAbility: 'con',
    damage: '1d12',
    damageType: 'poison',
    classes: ['druid', 'sorcerer', 'wizard', 'warlock', 'artificer'],
    concentration: false,
    ritual: false,
    targets: 'One creature within 10 ft',
    notes: 'Con save or take poison damage.',
    fullDescription:
      'You extend your hand toward a creature you can see within range and project a puff of noxious gas from your palm. The creature must succeed on a Constitution saving throw or take 1d12 poison damage.',
    cantripScaling: { l5: '2d12', l11: '3d12', l17: '4d12' },
    source: 'srd-5.2',
  },
  {
    name: 'Prestidigitation',
    level: 0,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '10 feet',
    components: 'V, S',
    duration: 'Up to 1 hour',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard', 'artificer'],
    concentration: false,
    ritual: false,
    notes: 'Minor magical tricks: clean, soil, light/snuff a small flame, chill/warm/flavor food, make a small mark, etc.',
    fullDescription:
      'This spell is a minor magical trick that novice spellcasters use for practice. You create one of the following magical effects within range: an instantaneous, harmless sensory effect; instantly light or snuff out a candle, a torch, or a small campfire; instantaneously clean or soil an object no larger than 1 cubic foot; chill, warm, or flavor up to 1 cubic foot of nonliving material for 1 hour; make a color, a small mark, or a symbol appear on an object or a surface for 1 hour; or create a nonmagical trinket or an illusory image that fits in your hand and lasts until the end of your next turn. If you cast this spell multiple times, you can have up to three of its non-instantaneous effects active at a time, and you can dismiss such an effect as an action.',
    source: 'srd-5.2',
  },
  {
    name: 'Produce Flame',
    level: 0,
    school: 'Conjuration',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: '10 minutes',
    attackRoll: true,
    damage: '1d8',
    damageType: 'fire',
    classes: ['druid'],
    concentration: false,
    ritual: false,
    targets: 'One creature within 30 ft when hurled',
    notes: 'Flame in hand provides light. Can hurl it as a ranged spell attack for fire damage.',
    fullDescription:
      'A flickering flame appears in your hand. The flame remains there for the duration and harms neither you nor your equipment. The flame sheds bright light in a 10-foot radius and dim light for an additional 10 feet. The spell ends if you dismiss it as an action or if you cast it again. You can also attack with the flame, although doing so ends the spell. When you cast this spell, or as an action on a later turn, you can hurl the flame at a creature within 30 feet of you. Make a ranged spell attack. On a hit, the target takes 1d8 fire damage.',
    cantripScaling: { l5: '2d8', l11: '3d8', l17: '4d8' },
    source: 'srd-5.2',
  },
  {
    name: 'Ray of Frost',
    level: 0,
    school: 'Evocation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    attackRoll: true,
    damage: '1d8',
    damageType: 'cold',
    classes: ['sorcerer', 'wizard', 'artificer'],
    concentration: false,
    ritual: false,
    targets: 'One creature within range',
    notes: 'Ranged spell attack, cold damage, reduces target speed by 10 ft until start of your next turn.',
    fullDescription:
      'A frigid beam of blue-white light streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, it takes 1d8 cold damage, and its speed is reduced by 10 feet until the start of your next turn.',
    cantripScaling: { l5: '2d8', l11: '3d8', l17: '4d8' },
    source: 'srd-5.2',
  },
  {
    name: 'Resistance',
    level: 0,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    classes: ['cleric', 'druid', 'artificer'],
    concentration: true,
    ritual: false,
    targets: 'One willing creature you touch',
    notes: 'Touch a willing creature; it adds 1d4 to one saving throw of its choice.',
    fullDescription:
      'You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one saving throw of its choice. It can roll the die before or after making the saving throw. The spell then ends.',
    source: 'srd-5.2',
  },
  {
    name: 'Sacred Flame',
    level: 0,
    school: 'Evocation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    saveAbility: 'dex',
    damage: '1d8',
    damageType: 'radiant',
    classes: ['cleric'],
    concentration: false,
    ritual: false,
    targets: 'One creature within range',
    notes: 'Dex save (no cover benefit) for radiant damage.',
    fullDescription:
      'Flame-like radiance descends on a creature that you can see within range. The target must succeed on a Dexterity saving throw or take 1d8 radiant damage. The target gains no benefit from cover for this saving throw.',
    cantripScaling: { l5: '2d8', l11: '3d8', l17: '4d8' },
    source: 'srd-5.2',
  },
  {
    name: 'Shillelagh',
    level: 0,
    school: 'Transmutation',
    castingTime: '1 bonus action',
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 minute',
    classes: ['druid'],
    concentration: false,
    ritual: false,
    targets: 'A club or quarterstaff',
    notes: 'Imbue a club or quarterstaff; use your spellcasting modifier for attack/damage rolls and the damage die becomes 1d8.',
    fullDescription:
      'The wood of a club or quarterstaff you are holding is imbued with nature\'s power. For the duration, you can use your spellcasting ability instead of Strength for the attack and damage rolls of melee attacks using that weapon, and the weapon\'s damage die becomes a d8. The weapon also becomes magical, if it isn\'t already. The spell ends if you cast it again or if you let go of the weapon.',
    source: 'srd-5.2',
  },
  {
    name: 'Shocking Grasp',
    level: 0,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Instantaneous',
    attackRoll: true,
    damage: '1d8',
    damageType: 'lightning',
    classes: ['sorcerer', 'wizard', 'artificer'],
    concentration: false,
    ritual: false,
    targets: 'One creature you touch',
    notes: 'Melee spell attack, lightning damage. Advantage if target wears metal armor. Target cannot take reactions until its next turn.',
    fullDescription:
      'Lightning springs from your hand to deliver a shock to a creature you try to touch. Make a melee spell attack against the target. You have advantage on the attack roll if the target is wearing armor made of metal. On a hit, the target takes 1d8 lightning damage, and it can\'t take reactions until the start of its next turn.',
    cantripScaling: { l5: '2d8', l11: '3d8', l17: '4d8' },
    source: 'srd-5.2',
  },
  {
    name: 'Spare the Dying',
    level: 0,
    school: 'Necromancy',
    castingTime: '1 bonus action',
    range: '15 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['cleric', 'druid', 'artificer'],
    concentration: false,
    ritual: false,
    targets: 'One creature at 0 HP',
    notes: 'Stabilize a creature at 0 HP. No effect on undead or constructs.',
    fullDescription:
      'Choose a creature within range that has 0 hit points and isn\'t dead. The creature becomes stable. (In the 2024 PHB this is now a Bonus Action at 15-foot range — a meaningful buff for emergencies.) This spell has no effect on undead or constructs.',
    source: 'srd-5.2',
  },
  {
    name: 'Thaumaturgy',
    level: 0,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V',
    duration: 'Up to 1 minute',
    classes: ['cleric'],
    concentration: false,
    ritual: false,
    notes: 'Minor divine miracle: amplify voice, make eyes flare, cause tremors, change flame color, open/shut doors, etc.',
    fullDescription:
      'You manifest a minor wonder, a sign of supernatural power, within range. You create one of the following magical effects within range: your voice booms up to three times as loud as normal for 1 minute; you cause flames to flicker, brighten, dim, or change color for 1 minute; you cause harmless tremors in the ground for 1 minute; you create an instantaneous sound that originates from a point of your choice within range; you instantaneously cause an unlocked door or window to fly open or slam shut; you alter the appearance of your eyes for 1 minute. If you cast this spell multiple times, you can have up to three of its 1-minute effects active at a time, and you can dismiss such an effect as an action.',
    source: 'srd-5.2',
  },
  {
    name: 'True Strike',
    level: 0,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Self (weapon\'s range)',
    components: 'V, S, M',
    duration: 'Instantaneous',
    attackRoll: true,
    damage: '1d6 (weapon)',
    damageType: 'radiant',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'One creature within weapon range',
    notes: '2024 PHB: now an attack — use a weapon you\'re holding, substitute spell mod, deals radiant damage on hit (scales).',
    fullDescription:
      'Guided by a flash of magical insight, you make one attack with the weapon used as the spell\'s focus. You use your spellcasting ability for the attack and damage rolls. On a hit, the weapon deals its normal damage, and you can replace its damage type with Radiant. (2024 PHB rework — the old "advantage on your next attack" version is gone.)',
    cantripScaling: { l5: 'weapon +1d6', l11: 'weapon +2d6', l17: 'weapon +3d6' },
    source: 'srd-5.2',
  },
  {
    name: 'Vicious Mockery',
    level: 0,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V',
    duration: 'Instantaneous',
    saveAbility: 'wis',
    damage: '1d4',
    damageType: 'psychic',
    classes: ['bard'],
    concentration: false,
    ritual: false,
    targets: 'One creature within range',
    notes: 'Wis save or take psychic damage and have disadvantage on its next attack roll.',
    fullDescription:
      'You unleash a string of insults laced with subtle enchantments at a creature you can see within range. If the target can hear you (though it need not understand you), it must succeed on a Wisdom saving throw or take 1d4 psychic damage and have disadvantage on the next attack roll it makes before the end of its next turn.',
    cantripScaling: { l5: '2d4', l11: '3d4', l17: '4d4' },
    source: 'srd-5.2',
  },
]
