// Cantrips (level 0) — full SRD 5.1 list

import type { SrdSpell } from './types'

export const CANTRIPS: SrdSpell[] = [
  {
    name: 'Acid Splash',
    level: 0,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    saveAbility: 'dex',
    damage: '1d6',
    notes: 'Dex save or take acid damage. Can target two creatures within 5 ft of each other.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Blade Ward',
    level: 0,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: '1 round',
    notes: 'Gain resistance to bludgeoning, piercing, and slashing damage from weapon attacks until end of next turn.',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Chill Touch',
    level: 0,
    school: 'Necromancy',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: '1 round',
    attackRoll: true,
    damage: '1d8',
    notes: 'Ranged spell attack; necrotic damage, and target cannot regain HP until start of your next turn.',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Dancing Lights',
    level: 0,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    notes: 'Create up to four floating, torch-sized lights that can move up to 60 ft per turn.',
    classes: ['bard', 'sorcerer', 'wizard'],
  },
  {
    name: 'Druidcraft',
    level: 0,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    notes: 'Minor nature-themed effects: predict weather, make a flower bloom, create a breeze, etc.',
    classes: ['druid'],
  },
  {
    name: 'Eldritch Blast',
    level: 0,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    attackRoll: true,
    damage: '1d10',
    notes: 'Ranged spell attack, force damage. Multiple beams at higher levels.',
    classes: ['warlock'],
  },
  {
    name: 'Fire Bolt',
    level: 0,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    attackRoll: true,
    damage: '1d10',
    notes: 'Ranged spell attack, deals fire damage.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Friends',
    level: 0,
    school: 'Enchantment',
    castingTime: '1 action',
    range: 'Self',
    components: 'S, M',
    duration: 'Up to 1 minute (concentration)',
    notes: 'Advantage on Charisma checks against one non-hostile creature. The creature becomes hostile afterward.',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Guidance',
    level: 0,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    notes: 'Touch a willing creature; it adds 1d4 to one ability check of its choice.',
    classes: ['cleric', 'druid'],
  },
  {
    name: 'Light',
    level: 0,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, M',
    duration: '1 hour',
    notes: 'Object sheds bright light in 20-ft radius, dim light an additional 20 ft. Dex save to avoid if held by unwilling creature.',
    classes: ['bard', 'cleric', 'sorcerer', 'wizard'],
  },
  {
    name: 'Mage Hand',
    level: 0,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: '1 minute',
    notes: 'Spectral floating hand manipulates objects up to 10 lb, opens doors, carries items, etc.',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Mending',
    level: 0,
    school: 'Transmutation',
    castingTime: '1 minute',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Repair a single break or tear in an object. Magic items can be repaired but their magical properties are not restored.',
    classes: ['bard', 'cleric', 'druid', 'sorcerer', 'wizard'],
  },
  {
    name: 'Message',
    level: 0,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: '1 round',
    notes: 'Whisper a message to a creature; it can whisper a reply that only you hear.',
    classes: ['bard', 'sorcerer', 'wizard'],
  },
  {
    name: 'Minor Illusion',
    level: 0,
    school: 'Illusion',
    castingTime: '1 action',
    range: '30 feet',
    components: 'S, M',
    duration: '1 minute',
    notes: 'Create a sound or image of an object. Investigation check against your spell save DC to discern the illusion.',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Poison Spray',
    level: 0,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '10 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    saveAbility: 'con',
    damage: '1d12',
    notes: 'Con save or take poison damage.',
    classes: ['druid', 'sorcerer', 'wizard'],
  },
  {
    name: 'Prestidigitation',
    level: 0,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '10 feet',
    components: 'V, S',
    duration: 'Up to 1 hour',
    notes: 'Minor magical tricks: clean, soil, light/snuff a small flame, chill/warm/flavor food, make a small mark, etc.',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Produce Flame',
    level: 0,
    school: 'Conjuration',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: '10 minutes',
    attackRoll: true,
    damage: '1d8',
    notes: 'Flame in hand provides light. Can hurl it as a ranged spell attack for fire damage.',
    classes: ['druid'],
  },
  {
    name: 'Ray of Frost',
    level: 0,
    school: 'Evocation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    attackRoll: true,
    damage: '1d8',
    notes: 'Ranged spell attack, cold damage, reduces target speed by 10 ft until start of your next turn.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Resistance',
    level: 0,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    notes: 'Touch a willing creature; it adds 1d4 to one saving throw of its choice.',
    classes: ['cleric', 'druid'],
  },
  {
    name: 'Sacred Flame',
    level: 0,
    school: 'Evocation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    saveAbility: 'dex',
    damage: '1d8',
    notes: 'Dex save (no cover benefit) for radiant damage.',
    classes: ['cleric'],
  },
  {
    name: 'Shillelagh',
    level: 0,
    school: 'Transmutation',
    castingTime: '1 bonus action',
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 minute',
    notes: 'Imbue a club or quarterstaff; use your spellcasting modifier for attack/damage rolls and the damage die becomes 1d8.',
    classes: ['druid'],
  },
  {
    name: 'Shocking Grasp',
    level: 0,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Instantaneous',
    attackRoll: true,
    damage: '1d8',
    notes: 'Melee spell attack, lightning damage. Advantage if target wears metal armor. Target cannot take reactions until its next turn.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Spare the Dying',
    level: 0,
    school: 'Necromancy',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Instantaneous',
    notes: 'Stabilize a creature at 0 HP. No effect on undead or constructs.',
    classes: ['cleric'],
  },
  {
    name: 'Thaumaturgy',
    level: 0,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V',
    duration: 'Up to 1 minute',
    notes: 'Minor divine miracle: amplify voice, make eyes flare, cause tremors, change flame color, open/shut doors, etc.',
    classes: ['cleric'],
  },
  {
    name: 'True Strike',
    level: 0,
    school: 'Divination',
    castingTime: '1 action',
    range: '30 feet',
    components: 'S',
    duration: 'Up to 1 round (concentration)',
    notes: 'Gain advantage on your next attack roll against the target before the end of your next turn.',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Vicious Mockery',
    level: 0,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V',
    duration: 'Instantaneous',
    saveAbility: 'wis',
    damage: '1d4',
    notes: 'Wis save or take psychic damage and have disadvantage on its next attack roll.',
    classes: ['bard'],
  },
]
