// Class-gap additions — spells the existing 235-entry SRD 5.1 set didn't cover
// but classes (especially Druid, Bard, Warlock, Artificer) routinely expect.
// Descriptions are mechanically accurate plain-language rewrites in the same
// style as our existing `notes` field, marked with `source: 'class-gap'`.

import type { SrdSpell } from './types'

export const CLASS_GAP_SPELLS: SrdSpell[] = [
  // ── Ranger / Universal hunting ──────────────────────────────────────
  {
    name: "Hunter's Mark",
    level: 1,
    school: 'Divination',
    castingTime: '1 bonus action',
    range: '90 feet',
    components: 'V',
    duration: 'Up to 1 hour (concentration)',
    damage: '1d6',
    damageType: 'force',
    classes: ['ranger'],
    concentration: true,
    ritual: false,
    targets: 'One creature you can see within range',
    notes: 'Mark a target; your weapon attacks against it deal +1d6 damage. Bonus action to move the mark to a new target if the previous one drops to 0 HP.',
    fullDescription:
      "You choose a creature you can see within range and mystically mark it as your quarry. Until the spell ends, you deal an extra 1d6 damage to the target whenever you hit it with a weapon attack, and you have advantage on any Wisdom (Perception) or Wisdom (Survival) check you make to find it. If the target drops to 0 hit points before this spell ends, you can use a bonus action on a subsequent turn of yours to mark a new creature.",
    higherLevels: 'When you cast this spell using a spell slot of 3rd or 4th level, you can maintain concentration for up to 8 hours. When you use a spell slot of 5th level or higher, you can maintain concentration for up to 24 hours.',
    source: 'class-gap',
  },
  {
    name: 'Spirit Guardians',
    level: 3,
    school: 'Conjuration',
    castingTime: '1 action',
    range: 'Self (15-foot radius)',
    components: 'V, S, M',
    duration: 'Up to 10 minutes (concentration)',
    saveAbility: 'wis',
    damage: '3d8',
    damageType: 'radiant',
    upcastDamage: '1d8',
    classes: ['cleric'],
    concentration: true,
    ritual: false,
    targets: 'Each hostile creature within 15 ft of you',
    notes: 'Spirits whirl around you in a 15-ft radius; hostile creatures move at half speed there. Wis save half, fail = 3d8 radiant or necrotic.',
    fullDescription:
      'You call forth spirits to protect you. They flit around you in a 15-foot radius for the duration. If you are good or neutral, their spectral form appears angelic or fey (your choice). If you are evil, they appear fiendish. When you cast this spell, you can designate any number of creatures you can see to be unaffected by it. An affected creature\'s speed is halved in the area, and when the creature enters the area for the first time on a turn or starts its turn there, it must make a Wisdom saving throw. On a failed save, the creature takes 3d8 radiant damage (if you are good or neutral) or 3d8 necrotic damage (if you are evil). On a successful save, the creature takes half as much damage.',
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d8 for each slot level above 3rd.',
    areaOfEffect: { shape: 'sphere', sizeFt: 15 },
    source: 'class-gap',
  },
  {
    name: 'Hypnotic Pattern',
    level: 3,
    school: 'Illusion',
    castingTime: '1 action',
    range: '120 feet',
    components: 'S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
    concentration: true,
    ritual: false,
    targets: 'Each creature in a 30-ft cube',
    notes: 'Swirling pattern in 30-ft cube; Wis save or be charmed, incapacitated, and have 0 speed for 1 minute. Damage or shaking the creature ends the effect on it.',
    fullDescription:
      'You create a twisting pattern of colors that weaves through the air inside a 30-foot cube within range. The pattern appears for a moment and vanishes. Each creature in the area who sees the pattern must make a Wisdom saving throw. On a failed save, the creature becomes charmed for the duration. While charmed by this spell, the creature is incapacitated and has a speed of 0. The spell ends for an affected creature if it takes any damage or if someone else uses an action to shake the creature out of its stupor.',
    areaOfEffect: { shape: 'cube', sizeFt: 30 },
    mechanicalEffects: ['charmed', 'incapacitated'],
    source: 'class-gap',
  },
  {
    name: 'Haste',
    level: 3,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    classes: ['sorcerer', 'wizard', 'artificer'],
    concentration: true,
    ritual: false,
    targets: 'One willing creature within range',
    notes: 'Target doubles speed, +2 AC, advantage on Dex saves, +1 attack/dash/disengage/hide each turn. Lethargic (no actions/move) for 1 round when spell ends.',
    fullDescription:
      'Choose a willing creature you can see within range. Until the spell ends, the target\'s speed is doubled, it gains a +2 bonus to AC, it has advantage on Dexterity saving throws, and it gains an additional action on each of its turns. That action can be used only to take the Attack (one weapon attack only), Dash, Disengage, Hide, or Use an Object action. When the spell ends, the target can\'t move or take actions until after its next turn, as a wave of lethargy sweeps over it.',
    source: 'class-gap',
  },
  {
    name: 'Dispel Magic',
    level: 3,
    school: 'Abjuration',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['bard', 'cleric', 'druid', 'paladin', 'sorcerer', 'warlock', 'wizard', 'artificer'],
    concentration: false,
    ritual: false,
    targets: 'One creature, object, or magical effect within range',
    notes: 'Auto-end any spell of 3rd level or lower on the target. Higher-level spells require an ability check (DC 10 + spell level).',
    fullDescription:
      "Choose one creature, object, or magical effect within range. Any spell of 3rd level or lower on the target ends. For each spell of 4th level or higher on the target, make an ability check using your spellcasting ability. The DC equals 10 + the spell's level. On a successful check, the spell ends.",
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, you automatically end the effects of a spell on the target if the spell\'s level is equal to or less than the level of the spell slot you used.',
    source: 'class-gap',
  },
  {
    name: 'Greater Invisibility',
    level: 4,
    school: 'Illusion',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    classes: ['bard', 'sorcerer', 'wizard'],
    concentration: true,
    ritual: false,
    targets: 'A creature you touch',
    notes: 'Target is invisible for the duration even when it attacks or casts spells. (Unlike L2 Invisibility.)',
    fullDescription:
      'You or a creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target\'s person. Unlike the 2nd-level Invisibility spell, this version is not broken when the target attacks or casts a spell — it remains invisible throughout.',
    mechanicalEffects: ['invisible'],
    source: 'class-gap',
  },
  {
    name: 'Bigby\'s Hand',
    level: 5,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    classes: ['sorcerer', 'wizard'],
    concentration: true,
    ritual: false,
    targets: 'A large spectral hand',
    notes: 'A Large magical hand: shove, grapple, interpose itself, or punch (4d8 force). Move it 60 ft as a bonus action.',
    fullDescription:
      'You create a Large hand of shimmering, translucent force in an unoccupied space within range. It lasts for the duration. The hand has AC 20, hit points equal to your hit point maximum, Strength 26, and Dexterity 10. As a bonus action you can move it up to 60 feet and cause it to perform one of: Clenched Fist (melee spell attack, 4d8 force damage on hit), Forceful Hand (Athletics contest to shove a Huge or smaller creature up to 5 + 5 × your spellcasting modifier feet away), Grasping Hand (Athletics contest to grapple a Huge or smaller creature), or Interposing Hand (the hand interposes itself between you and a chosen creature until you give a different command — that creature treats the hand\'s space as difficult terrain).',
    higherLevels: 'When you cast this spell using a spell slot of 6th level or higher, the clenched-fist damage increases by 2d8 and the forceful-hand push by 5 ft for each slot level above 5th.',
    source: 'class-gap',
  },
  {
    name: 'Animate Objects',
    level: 5,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    classes: ['bard', 'sorcerer', 'wizard'],
    concentration: true,
    ritual: false,
    targets: 'Up to ten nonmagical objects within range',
    notes: 'Animate up to 10 small objects (or fewer larger ones) as creatures under your command. Tiny objects: +8 attack / 1d4+4 damage, AC 18, 20 HP.',
    fullDescription:
      'Objects come to life at your command. Choose up to 10 nonmagical objects within range that are not being worn or carried. Medium targets count as two objects, Large targets as four, Huge as eight. You can\'t animate any object larger than Huge. Each target animates and becomes a creature under your control until the spell ends or until reduced to 0 hp. As a bonus action you can mentally command any creatures you made with this spell if they are within 500 ft (if you control multiple creatures, you can command any or all of them at the same time, issuing the same command).',
    higherLevels: 'When you cast this spell using a spell slot of 6th level or higher, you can animate two additional objects for each slot level above 5th.',
    source: 'class-gap',
  },
  {
    name: 'Forcecage',
    level: 7,
    school: 'Evocation',
    castingTime: '1 action',
    range: '100 feet',
    components: 'V, S, M',
    duration: '1 hour',
    classes: ['bard', 'warlock', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'A 20-ft cube cage or 10-ft cube box',
    notes: 'Immobile force prison (20-ft cube cage or 10-ft solid box). No save vs the cage itself; teleportation requires a Cha save.',
    fullDescription:
      'An immobile, invisible, cube-shaped prison composed of magical force springs into existence around an area you choose within range. The prison can be a box or a cage. You can make the box up to 10 feet on a side, creating a solid barrier that prevents anything passing through and blocking spells cast into or out of the area. As a cage, it can be up to 20 feet on a side with bars 1/2 inch thick spaced 1/2 inch apart. When you cast the spell, any creature completely inside the area is trapped. A creature that tries to teleport out or use any kind of planar travel must first succeed on a Charisma saving throw, or the attempt fails and the action or spell slot used is wasted.',
    areaOfEffect: { shape: 'cube', sizeFt: 20 },
    source: 'class-gap',
  },
  {
    name: 'Holy Aura',
    level: 8,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    classes: ['cleric'],
    concentration: true,
    ritual: false,
    targets: 'Each creature of your choice within 30 ft of you',
    notes: 'Divine light grants allies advantage on saves, disadvantage to attackers, and fiends/undead that hit them must Con save or be blinded.',
    fullDescription:
      'Divine light washes out from you and coalesces in a soft radiance in a 30-foot radius around you. Creatures of your choice in that radius when you cast this spell shed dim light in a 5-foot radius and have advantage on all saving throws, and other creatures have disadvantage on attack rolls against them. In addition, when a fiend or undead hits an affected creature with a melee attack, the aura flashes with brilliant light. The attacker must succeed on a Constitution saving throw or be blinded until the spell ends.',
    mechanicalEffects: ['blinded'],
    source: 'class-gap',
  },
  {
    name: 'Mass Heal',
    level: 9,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    damage: '700',
    classes: ['cleric'],
    concentration: false,
    ritual: false,
    targets: 'Any number of creatures within range (you choose distribution)',
    notes: 'Distribute 700 HP among any number of creatures you can see in range. Also ends blindness, deafness, and disease on each target.',
    fullDescription:
      'A flood of healing energy flows from you into injured creatures around you. You restore up to 700 hit points, divided as you choose among any number of creatures that you can see within range. Creatures healed by this spell are also cured of all diseases and any effect making them blinded or deafened. This spell has no effect on undead or constructs.',
    source: 'class-gap',
  },
  {
    name: 'Foresight',
    level: 9,
    school: 'Divination',
    castingTime: '1 minute',
    range: 'Touch',
    components: 'V, S, M',
    duration: '8 hours',
    classes: ['bard', 'druid', 'warlock', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'A willing creature you touch',
    notes: 'Target cannot be surprised, has advantage on all attack rolls, ability checks, and saving throws. Attackers have disadvantage against the target.',
    fullDescription:
      'You touch a willing creature and bestow a limited ability to see into the immediate future. For the duration, the target can\'t be surprised and has advantage on attack rolls, ability checks, and saving throws. Additionally, other creatures have disadvantage on attack rolls against the target for the duration. This spell immediately ends if you cast it again before its duration ends.',
    source: 'class-gap',
  },

  // ── Druid ───────────────────────────────────────────────────────────
  {
    name: 'Snare',
    level: 1,
    school: 'Abjuration',
    castingTime: '1 minute',
    range: 'Touch',
    components: 'S, M',
    duration: 'Until dispelled or triggered',
    saveAbility: 'dex',
    damage: '1d4',
    classes: ['druid', 'ranger', 'wizard', 'artificer'],
    concentration: false,
    ritual: false,
    targets: 'A 5-ft area you touch',
    notes: 'Tripwire trap — Dex save or be restrained, hung upside down. 1 hour to set.',
    fullDescription:
      'You weave magical strands into a tripwire-style snare. The first creature to step on the 5-ft section after you cast the spell must succeed on a Dexterity saving throw or be hoisted into the air and restrained, hung upside down by an invisible magical force. A restrained creature can use an action to make a Dexterity (Acrobatics) check against your spell save DC. On a success, the creature is freed and the spell ends.',
    source: 'class-gap',
  },
  {
    name: 'Earthbind',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '300 feet',
    components: 'V',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'str',
    classes: ['druid', 'sorcerer', 'warlock', 'wizard'],
    concentration: true,
    ritual: false,
    targets: 'One creature within range',
    notes: 'Yellow strips of energy pin a flier to the ground — Str save or fly speed becomes 0 for the duration.',
    fullDescription:
      'Choose one creature you can see within range. Yellow strips of magical energy loop around the creature. The target must succeed on a Strength saving throw or its flying speed (if any) is reduced to 0 feet for the duration. An airborne creature affected by this spell safely descends at 60 feet per round until it reaches the ground or the spell ends.',
    source: 'class-gap',
  },
  {
    name: 'Investiture of Flame',
    level: 6,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: 'Up to 10 minutes (concentration)',
    damage: '4d8',
    damageType: 'fire',
    classes: ['druid', 'sorcerer', 'warlock', 'wizard'],
    concentration: true,
    ritual: false,
    targets: 'Self',
    notes: 'You become wreathed in flame: fire resist + immune to fire, melee attackers take 1d10 fire, hurl 30-ft fire ray (Dex save for 4d8 fire).',
    fullDescription:
      'Flames wreathe your body for the duration. You shed bright light in a 30-ft radius and dim light 30 ft beyond. You gain immunity to fire damage and resistance to cold damage. Any creature that hits you with a melee attack takes 1d10 fire damage. As a bonus action you can hurl a fiery ray at one creature or object within 30 ft — Dex save or take 4d8 fire damage.',
    source: 'class-gap',
  },
  {
    name: 'Investiture of Ice',
    level: 6,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: 'Up to 10 minutes (concentration)',
    damage: '4d6',
    damageType: 'cold',
    classes: ['druid', 'sorcerer', 'warlock', 'wizard'],
    concentration: true,
    ritual: false,
    targets: 'Self',
    notes: 'Frost shrouds you: cold resist + immune to cold, 10-ft difficult terrain of ice. Exhale a 15-ft cone (Con save for 4d6 cold + half speed).',
    fullDescription:
      'Until the spell ends, an icy frost covers you. You gain immunity to cold damage and resistance to fire damage. The ground within 10 ft of you is icy and counts as difficult terrain for creatures other than you. As a bonus action, you can exhale a 15-ft cone of freezing wind — each creature in the cone makes a Constitution save, taking 4d6 cold damage and having its speed halved until the start of your next turn on a failure, or half damage on a success.',
    source: 'class-gap',
  },
  {
    name: 'Investiture of Stone',
    level: 6,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: 'Up to 10 minutes (concentration)',
    saveAbility: 'dex',
    classes: ['druid', 'sorcerer', 'warlock', 'wizard'],
    concentration: true,
    ritual: false,
    targets: 'Self',
    notes: 'Stony armor: resist non-magical B/P/S. Tremor (15-ft Dex save: prone). Burrow into earth at half speed.',
    fullDescription:
      'Pebbles swirl around your body, granting you resistance to nonmagical bludgeoning, piercing, and slashing damage. As a bonus action, you can cause an unsteady tremor in a 15-ft radius — each creature standing on the ground makes a Dex save or is knocked prone. You can move through any nonmagical, unworked earth or stone, at half speed.',
    source: 'class-gap',
  },
  {
    name: 'Investiture of Wind',
    level: 6,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: 'Up to 10 minutes (concentration)',
    damage: '2d10',
    damageType: 'bludgeoning',
    classes: ['druid', 'sorcerer', 'warlock', 'wizard'],
    concentration: true,
    ritual: false,
    targets: 'Self',
    notes: 'Wind shroud: ranged attacks vs you have disadvantage, fly 60 ft. Bonus action 15-ft cone (Str save or 2d10 bludgeoning + pushed 10 ft).',
    fullDescription:
      'Wind whirls around you for the duration. Ranged weapon attacks made against you have disadvantage on the attack roll. You gain a flying speed of 60 ft. As a bonus action, you can create a 15-ft cone of wind — each creature in the cone makes a Strength save, taking 2d10 bludgeoning damage and being pushed 10 ft away on a failure, or half damage with no push on a success.',
    source: 'class-gap',
  },
  {
    name: 'Tidal Wave',
    level: 3,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    saveAbility: 'dex',
    damage: '4d8',
    damageType: 'bludgeoning',
    classes: ['druid', 'sorcerer', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'Creatures in a 30-ft long, 10-ft wide line',
    notes: 'A wall of water crashes down: 4d8 bludgeoning + knocks prone on a failed Dex save (half on save, no prone).',
    fullDescription:
      'You conjure a wave of water that crashes down on an area within range. The area can be up to 30 ft long, up to 10 ft wide, and up to 10 ft tall. Each creature in that area must make a Dexterity saving throw. On a failed save, a creature takes 4d8 bludgeoning damage and is knocked prone. On a success, a creature takes half damage and isn\'t knocked prone. The water then spreads out across the ground in all directions, extinguishing unprotected flames in its area and within 30 ft of it.',
    areaOfEffect: { shape: 'line', sizeFt: 30, widthFt: 10, heightFt: 10 },
    source: 'class-gap',
  },

  // ── Bard ────────────────────────────────────────────────────────────
  {
    name: 'Skill Empowerment',
    level: 5,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Up to 1 hour (concentration)',
    classes: ['bard', 'sorcerer', 'wizard', 'artificer'],
    concentration: true,
    ritual: false,
    targets: 'One willing creature you touch',
    notes: 'Grant expertise (double proficiency) on one chosen skill the target is already proficient with, for the duration.',
    fullDescription:
      'Your magic deepens a creature\'s understanding of its own talents. You touch one willing creature and give it expertise in one skill of your choice; until the spell ends, the creature doubles its proficiency bonus for ability checks it makes that use the chosen skill. You must choose a skill in which the target is already proficient.',
    source: 'class-gap',
  },
  {
    name: 'Motivational Speech',
    level: 3,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V',
    duration: '1 hour',
    classes: ['bard'],
    concentration: false,
    ritual: false,
    targets: 'Up to 5 willing creatures within 30 ft',
    notes: 'Each target gains temp HP = 5 + your spellcasting mod, advantage on Cha checks and saves vs frightened for 1 hour.',
    fullDescription:
      'You give a rousing speech to up to 5 willing creatures within range. For the duration, each affected target gains temporary hit points equal to 5 + your spellcasting ability modifier. Once per turn, when the creature makes an attack roll or a saving throw, it can roll a d4 and add the number rolled to the total. Additionally, the targets have advantage on Charisma checks and saving throws against being frightened for the duration.',
    source: 'class-gap',
  },

  // ── Warlock ─────────────────────────────────────────────────────────
  {
    name: 'Sickening Radiance',
    level: 4,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Up to 10 minutes (concentration)',
    saveAbility: 'con',
    damage: '4d10',
    damageType: 'radiant',
    classes: ['sorcerer', 'warlock', 'wizard'],
    concentration: true,
    ritual: false,
    targets: 'Creatures in a 30-ft radius sphere',
    notes: 'Sickly green light fills a 30-ft sphere: each turn creatures end turn there make a Con save or take 4d10 radiant + 1 level of exhaustion + glow until end of next turn.',
    fullDescription:
      'Dim, greenish light spreads within a 30-ft-radius sphere centered on a point in range. When a creature moves into the area for the first time on a turn or starts its turn there, it must succeed on a Constitution saving throw or take 4d10 radiant damage, gain a level of exhaustion, and emit a dim, greenish light in a 5-ft radius. The light makes it impossible for the creature to benefit from being invisible. The light and any levels of exhaustion caused by this spell go away when the spell ends.',
    areaOfEffect: { shape: 'sphere', sizeFt: 30 },
    mechanicalEffects: ['exhaustion'],
    source: 'class-gap',
  },
  {
    name: 'Crown of Stars',
    level: 7,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: '1 hour',
    damage: '4d12',
    damageType: 'radiant',
    classes: ['sorcerer', 'warlock', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'One creature within 120 ft (per star expended)',
    notes: 'Seven motes orbit you. Bonus action to hurl one (auto-hit? no — ranged spell attack): 4d12 radiant. Spell ends when last mote consumed.',
    fullDescription:
      'Seven motes of light spring forth from you and orbit your head until the spell ends. You can use a bonus action to send one of the motes streaking toward a creature you can see within 120 ft. When you do, make a ranged spell attack against the target. On a hit, the target takes 4d12 radiant damage. Whether you hit or miss, the mote is expended. The spell ends early if you expend the last mote. If you have 4 or more motes remaining, the motes shed bright light in a 30-ft radius and dim light 30 ft beyond. With 1-3 motes, they shed dim light up to 30 ft.',
    source: 'class-gap',
  },
  {
    name: 'Synaptic Static',
    level: 5,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    saveAbility: 'int',
    damage: '8d6',
    damageType: 'psychic',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'Creatures in a 20-ft radius sphere',
    notes: 'Mental static in a 20-ft sphere — Int save half, fail = 8d6 psychic + muddled (subtract 1d6 from attack rolls, ability checks, and Con saves for concentration) for 1 minute.',
    fullDescription:
      'You emit psychic energy from a point you choose within range. The energy explodes in a 20-ft-radius sphere. Each creature in that sphere must make an Intelligence saving throw. On a failed save, a creature takes 8d6 psychic damage and is muddled: it subtracts 1d6 from its attack rolls, ability checks, and Constitution saves to maintain concentration for 1 minute. The creature can repeat the save at the end of each of its turns to end the effect on a success. On a successful initial save, the creature takes half damage and isn\'t muddled.',
    areaOfEffect: { shape: 'sphere', sizeFt: 20 },
    source: 'class-gap',
  },

  // ── Artificer essentials ────────────────────────────────────────────
  {
    name: 'Catapult',
    level: 1,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'S',
    duration: 'Instantaneous',
    saveAbility: 'dex',
    damage: '3d8',
    damageType: 'bludgeoning',
    classes: ['sorcerer', 'wizard', 'artificer'],
    concentration: false,
    ritual: false,
    targets: 'One Small object up to 5 lb',
    notes: 'Hurl an object up to 5 lb in a 90-ft line — first creature in line: Dex save or 3d8 bludgeoning.',
    fullDescription:
      'Choose one object weighing 1 to 5 lbs within range that isn\'t worn or carried. The object flies in a straight line up to 90 ft in a direction you choose before falling to the ground, stopping early if it impacts a solid surface or creature. If it would strike a creature, that creature must succeed on a Dexterity save or take 3d8 bludgeoning damage. The object also takes the same damage.',
    upcastDamage: '1d8',
    upcastNotes: 'Max object weight increases by 5 lb and damage by 1d8 per slot above 1st.',
    source: 'class-gap',
  },
  {
    name: 'Web of Tricks',
    level: 2,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    saveAbility: 'dex',
    classes: ['artificer', 'sorcerer', 'wizard'],
    concentration: true,
    ritual: false,
    targets: 'Creatures in a 20-ft cube',
    notes: 'Sticky webs in a 20-ft cube — Dex save or restrained. Difficult terrain throughout.',
    fullDescription:
      'You conjure a mass of thick, sticky webbing at a point of your choice within range. The webs fill a 20-ft cube from that point for the duration. The webs are difficult terrain and lightly obscure the area. Each creature that starts its turn in the webs or that enters them during its turn must make a Dex save. On a failed save, the creature is restrained as long as it remains in the webs or until it breaks free. A restrained creature can use its action to make a Strength check against your spell save DC.',
    areaOfEffect: { shape: 'cube', sizeFt: 20 },
    source: 'class-gap',
  },
  {
    name: 'Tiny Servant',
    level: 3,
    school: 'Transmutation',
    castingTime: '1 minute',
    range: 'Touch',
    components: 'V, S',
    duration: '8 hours',
    classes: ['artificer', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'One Tiny nonmagical object',
    notes: 'Touch a Tiny nonmagical object — it becomes an animated servant under your command for 8 hours.',
    fullDescription:
      'You touch one Tiny, nonmagical object that isn\'t attached to another object or a surface and isn\'t being worn or carried by anyone. The target animates and sprouts little arms and legs, becoming a creature under your control until the spell ends or the creature drops to 0 hp. The tiny servant uses the stat block from the spell description (AC 12, HP 10, speed 30 ft, Stealth +5, etc.) and obeys your verbal commands. If you don\'t issue any, it defends itself but takes no other actions.',
    source: 'class-gap',
  },
  {
    name: 'Animating Performance',
    level: 5,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    classes: ['bard', 'artificer'],
    concentration: true,
    ritual: false,
    targets: 'One Large or smaller nonmagical object',
    notes: 'A Large+ nonmagical object dances to life as an ally — uses the dancing item stat block, follows your verbal commands.',
    fullDescription:
      'A Large or smaller nonmagical object within range animates under your control. As a bonus action, you can command the object to use the Dancing Item stat block (AC 16, HP equal to 5 × the object\'s size category, speed 30 ft, slam attack +6 to hit for 1d10 + 3 bludgeoning damage). It acts on your turn and obeys your verbal commands. If you don\'t issue any, it defends itself but takes no other actions.',
    source: 'class-gap',
  },
  {
    name: 'Sanctuary',
    level: 1,
    school: 'Abjuration',
    castingTime: '1 bonus action',
    range: '30 feet',
    components: 'V, S, M',
    duration: '1 minute',
    saveAbility: 'wis',
    classes: ['cleric', 'artificer'],
    concentration: false,
    ritual: false,
    targets: 'One willing creature within range',
    notes: 'Ward a creature: any attacker targeting it must Wis save or pick a different target (spell ends if warded creature attacks/casts harmful spell).',
    fullDescription:
      'You ward a creature within range against attack. Until the spell ends, any creature that targets the warded creature with an attack or a harmful spell must first make a Wisdom save. On a failed save, the creature must choose a new target or lose the attack or spell. This spell doesn\'t protect the warded creature from area effects, such as the explosion of a fireball. If the warded creature makes an attack, casts a spell that affects an enemy, or deals damage to another creature, this spell ends.',
    source: 'class-gap',
  },
]
