// 9th-level spells — full SRD 5.1 list

import type { SrdSpell } from './types'

export const LEVEL9_SPELLS: SrdSpell[] = [
  {
    name: 'Astral Projection',
    level: 9,
    school: 'Necromancy',
    castingTime: '1 hour',
    range: '10 feet',
    components: 'V, S, M',
    duration: 'Special',
    notes: 'Project yourself and up to 8 willing creatures into the Astral Plane with astral bodies. Your body remains inert until you return.',
    classes: ['cleric', 'warlock', 'wizard'],
  },
  {
    name: 'Foresight',
    level: 9,
    school: 'Divination',
    castingTime: '1 minute',
    range: 'Touch',
    components: 'V, S, M',
    duration: '8 hours',
    notes: 'Target cannot be surprised, has advantage on attacks/checks/saves, and attacks against it have disadvantage.',
    classes: ['bard', 'druid', 'warlock', 'wizard'],
  },
  {
    name: 'Gate',
    level: 9,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    notes: 'Open a circular portal (5–20 ft) to another plane. A named specific entity may be called to pass through.',
    classes: ['cleric', 'sorcerer', 'wizard'],
  },
  {
    name: 'Imprisonment',
    level: 9,
    school: 'Abjuration',
    castingTime: '1 minute',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Until dispelled',
    saveAbility: 'wis',
    notes: 'Wis save or imprisoned. Choose form: Burial, Chaining, Hedged Prison, Minimus Containment, Slumber.',
    classes: ['warlock', 'wizard'],
  },
  {
    name: 'Invulnerability',
    level: 9,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'You are immune to all damage for the duration.',
    classes: ['wizard'],
  },
  {
    name: 'Mass Heal',
    level: 9,
    school: 'Evocation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    damage: '700',
    notes: 'Restore up to 700 HP total among creatures you choose. Also ends blindness, deafness, and diseases.',
    classes: ['cleric'],
  },
  {
    name: 'Meteor Swarm',
    level: 9,
    school: 'Evocation',
    castingTime: '1 action',
    range: '1 mile',
    components: 'V, S',
    duration: 'Instantaneous',
    saveAbility: 'dex',
    damage: '40d6',
    damageType: 'fire',
    notes: 'Four meteors each deal 20d6 fire + 20d6 bludgeoning in 40-ft radius (Dex save for half). Can target the same or different points.',
    classes: ['sorcerer', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'Each creature in four 40-ft radius spheres',
    fullDescription:
      'Blazing orbs of fire plummet to the ground at four different points you can see within range. Each creature in a 40-foot-radius sphere centered on each point you choose must make a Dexterity saving throw. The sphere spreads around corners. A creature takes 20d6 fire damage and 20d6 bludgeoning damage on a failed save, or half as much damage on a successful one. A creature in the area of more than one fiery burst is affected only once. The spell damages objects in the area and ignites flammable objects that aren\'t being worn or carried.',
    areaOfEffect: { shape: 'sphere', sizeFt: 40 },
    source: 'srd-5.2',
  },
  {
    name: 'Power Word Heal',
    level: 9,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V',
    duration: 'Instantaneous',
    notes: 'Restore all HP. Also ends charmed, frightened, paralyzed, stunned conditions and grants spend up to all hit dice.',
    classes: ['bard', 'cleric'],
  },
  {
    name: 'Power Word Kill',
    level: 9,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V',
    duration: 'Instantaneous',
    notes: 'If target has 100 HP or fewer, it dies instantly. No save.',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Prismatic Wall',
    level: 9,
    school: 'Abjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: '10 minutes',
    saveAbility: 'dex',
    damage: '50d6',
    notes: 'Seven-layered wall (plane or sphere): each layer has a color, damage type, and is dispelled differently. Touching it triggers all layers.',
    classes: ['wizard'],
  },
  {
    name: 'Shapechange',
    level: 9,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Transform into any creature of your CR or lower (including legendary creatures). Keep your mental scores and class features.',
    classes: ['druid', 'wizard'],
  },
  {
    name: 'Storm of Vengeance',
    level: 9,
    school: 'Conjuration',
    castingTime: '1 action',
    range: 'Sight',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'con',
    damage: '2d6',
    notes: 'Thunderstorm (360-ft radius): each round different effects (deafened, lightning, acid, hail). Con save for 2d6 thunder on rounds 2+.',
    classes: ['druid'],
  },
  {
    name: 'Time Stop',
    level: 9,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Self',
    components: 'V',
    duration: 'Instantaneous',
    notes: 'Gain 1d4+1 extra turns. Time resumes if you move >1000 ft away or affect another creature.',
    classes: ['sorcerer', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'Self',
    fullDescription:
      'You briefly stop the flow of time for everyone but yourself. No time passes for other creatures while you take 1d4 + 1 turns in a row, during which you can use actions and move as normal. This spell ends if one of the actions you use during this period, or any effects that you create during this period, affects a creature other than you or an object being worn or carried by someone other than you. In addition, the spell ends if you move to a place more than 1,000 feet from the location where you cast it.',
    source: 'srd-5.2',
  },
  {
    name: 'True Polymorph',
    level: 9,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    saveAbility: 'wis',
    notes: 'Transform a creature into any other creature/object, or an object into a creature. Wis save to resist. Permanent if concentration lasts full duration.',
    classes: ['bard', 'warlock', 'wizard'],
  },
  {
    name: 'True Resurrection',
    level: 9,
    school: 'Necromancy',
    castingTime: '1 hour',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Return a creature dead up to 200 years to life. Can recreate the body even if it no longer exists. No penalties.',
    classes: ['cleric', 'druid'],
  },
  {
    name: 'Weird',
    level: 9,
    school: 'Illusion',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    damage: '4d10',
    notes: 'Wis save or frightened. While frightened, takes 4d10 psychic at start of each turn (save for half). Repeats save each turn to end.',
    classes: ['wizard'],
  },
  {
    name: 'Wish',
    level: 9,
    school: 'Conjuration',
    castingTime: '1 action',
    range: 'Self',
    components: 'V',
    duration: 'Instantaneous',
    notes: 'Reshape reality as you desire with risks for going beyond duplicating lower spells. No standard save/damage; DM adjudication.',
    classes: ['sorcerer', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'Reality itself',
    fullDescription:
      'Wish is the mightiest spell a mortal creature can cast. By simply speaking aloud, you can alter the very foundations of reality in accord with your desires. The basic use of this spell is to duplicate any other spell of 8th level or lower. You don\'t need to meet any requirements in that spell, including costly components. The spell simply takes effect. Alternatively, you can create one of the following effects of your choice: create one object of up to 25,000 gp in value; allow up to 20 creatures you can see to regain all hit points and end all effects on them; grant up to 10 creatures resistance to a damage type for 8 hours; grant up to 10 creatures immunity to a single spell or magical effect for 8 hours; undo a single recent event by forcing a reroll of any roll made within the last round. You might be able to achieve more by casting Wish, but doing so carries enormous risk: the stress of casting deals 1d10 necrotic damage per level of any spell you cast this way (no save), you can\'t cast any spell with a casting time of greater than 1 action, your Strength drops to 3 for 2d4 days, and there is a 33% chance you cannot cast Wish ever again.',
    source: 'srd-5.2',
  },
]
