// 3rd-level spells — full SRD 5.1 list

import type { SrdSpell } from './types'

export const LEVEL3_SPELLS: SrdSpell[] = [
  {
    name: 'Animate Dead',
    level: 3,
    school: 'Necromancy',
    castingTime: '1 minute',
    range: '10 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Create a skeleton or zombie from a corpse. It obeys your verbal commands for 24 hours.',
    classes: ['cleric', 'wizard'],
  },
  {
    name: 'Aura of Vitality',
    level: 3,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Self (30-foot radius)',
    components: 'V',
    duration: 'Up to 1 minute (concentration)',
    damage: '2d6',
    notes: 'As a bonus action, heal a creature within 30 ft for 2d6 HP.',
    classes: ['paladin'],
  },
  {
    name: 'Beacon of Hope',
    level: 3,
    school: 'Abjuration',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    notes: 'Up to 3 creatures have advantage on Wis saves and death saves, and regain max HP from healing.',
    classes: ['cleric'],
  },
  {
    name: 'Bestow Curse',
    level: 3,
    school: 'Necromancy',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    notes: 'Wis save or cursed. Choose: disadvantage on one ability, disadvantage on attacks vs. you, wasting action on Wis save, or +1d8 necrotic damage from your attacks.',
    classes: ['bard', 'cleric', 'wizard'],
  },
  {
    name: 'Blink',
    level: 3,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: '1 minute',
    notes: 'At end of each turn, roll d20: on 11+, shift to Ethereal Plane until start of next turn.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Call Lightning',
    level: 3,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Up to 10 minutes (concentration)',
    saveAbility: 'dex',
    damage: '3d10',
    notes: 'Storm cloud summons lightning bolt as action each turn (Dex save for half). Outdoors = 4d10.',
    upcastDamage: '1d10',
    classes: ['druid'],
  },
  {
    name: 'Clairvoyance',
    level: 3,
    school: 'Divination',
    castingTime: '10 minutes',
    range: '1 mile',
    components: 'V, S, M',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Create an invisible sensor at a known location; use it to see or hear.',
    classes: ['bard', 'cleric', 'sorcerer', 'wizard'],
  },
  {
    name: 'Conjure Animals',
    level: 3,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Summon fey spirits as beasts: one CR 2, two CR 1, four CR 1/2, or eight CR 1/4.',
    classes: ['druid', 'ranger'],
  },
  {
    name: 'Counterspell',
    level: 3,
    school: 'Abjuration',
    castingTime: '1 reaction',
    range: '60 feet',
    components: 'S',
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    targets: 'One creature within range that is casting a spell',
    fullDescription:
      'You attempt to interrupt a creature in the process of casting a spell. If the creature is casting a spell of 3rd level or lower, its spell fails and has no effect. If it is casting a spell of 4th level or higher, make an ability check using your spellcasting ability — the DC equals 10 + the spell\'s level. On a success, the creature\'s spell fails and has no effect. (2024 PHB note: at higher slot levels Counterspell automatically defeats spells whose level ≤ this slot.)',
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the interrupted spell has no effect if its level is less than or equal to the level of the spell slot you used.',
    source: 'srd-5.2',
    notes: 'Interrupt a spell of 3rd level or lower (auto-succeeds). Higher level spells require an ability check.',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    name: "Crusader's Mantle",
    level: 3,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Self (30-foot radius)',
    components: 'V',
    duration: 'Up to 1 minute (concentration)',
    concentration: true,
    ritual: false,
    damage: '1d4',
    damageType: 'radiant',
    areaOfEffect: { shape: 'sphere', sizeFt: 30 },
    targets: 'Each friendly creature (including you) in a 30-foot-radius aura',
    fullDescription:
      'Holy power radiates from you in an aura with a 30-foot radius, awakening boldness in friendly creatures. Until the spell ends, the aura moves with you, centered on you. While in the aura, each friendly creature in the aura (including you) deals an extra 1d4 Radiant damage when it hits with a weapon or an unarmed strike.',
    notes: 'Aura moves with you. Friendly creatures in range deal +1d4 radiant damage on weapon/unarmed hits.',
    source: 'srd-5.2',
    classes: ['paladin', 'cleric'],
  },
  {
    name: 'Create Food and Water',
    level: 3,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    notes: 'Create 45 pounds of food and 30 gallons of water for up to 15 humanoids.',
    classes: ['cleric', 'paladin'],
  },
  {
    name: 'Daylight',
    level: 3,
    school: 'Evocation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: '1 hour',
    notes: 'Bright light fills a 60-ft radius (120-ft dim light). Dispels magical darkness of 3rd level or lower.',
    classes: ['cleric', 'druid', 'paladin', 'ranger', 'sorcerer'],
  },
  {
    name: 'Dispel Magic',
    level: 3,
    school: 'Abjuration',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    notes: 'End one spell of 3rd level or lower on target. Higher level spells require ability check (DC 10 + spell level).',
    classes: ['bard', 'cleric', 'druid', 'paladin', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Elemental Weapon',
    level: 3,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Up to 1 hour (concentration)',
    damage: '1d4',
    notes: 'Nonmagical weapon becomes +1 and deals extra 1d4 of chosen element (acid, cold, fire, lightning, thunder).',
    classes: ['paladin'],
  },
  {
    name: 'Fear',
    level: 3,
    school: 'Illusion',
    castingTime: '1 action',
    range: 'Self (30-foot cone)',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    notes: 'Wis save or drop held items, become frightened, and Dash away. Repeats save at end of each turn.',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Fireball',
    level: 3,
    school: 'Evocation',
    castingTime: '1 action',
    range: '150 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    saveAbility: 'dex',
    damage: '8d6',
    damageType: 'fire',
    notes: 'Dex save for half fire damage in 20-ft radius.',
    upcastDamage: '1d6',
    classes: ['sorcerer', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'Each creature in a 20-ft radius sphere',
    fullDescription:
      'A bright streak flashes from you to a point you choose within range and then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere centered on that point must make a Dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much damage on a successful one. The fire spreads around corners. It ignites flammable objects in the area that aren\'t being worn or carried.',
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
    areaOfEffect: { shape: 'sphere', sizeFt: 20 },
    source: 'srd-5.2',
  },
  {
    name: 'Fly',
    level: 3,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Willing creature gains a flying speed of 60 ft.',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Gaseous Form',
    level: 3,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Willing creature becomes a misty cloud: 10 ft fly speed, resistance to nonmagical damage, can squeeze through tiny spaces.',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Glyph of Warding',
    level: 3,
    school: 'Abjuration',
    castingTime: '1 hour',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Until dispelled or triggered',
    saveAbility: 'dex',
    damage: '5d8',
    notes: 'Inscribe a glyph that triggers when entered. Explosive rune: 5d8 of chosen damage type (Dex half) in 20-ft radius.',
    classes: ['bard', 'cleric', 'wizard'],
  },
  {
    name: 'Haste',
    level: 3,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    notes: 'Double speed, +2 AC, advantage on Dex saves, gain extra action (attack, Dash, Disengage, Hide, Use Object).',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Hunger of Hadar',
    level: 3,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '150 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'dex',
    damage: '2d6',
    notes: 'Darkness in 20-ft sphere; start of turn in sphere: 2d6 cold. End of turn: Dex save or 2d6 acid. Heavily obscured.',
    classes: ['warlock'],
  },
  {
    name: 'Hypnotic Pattern',
    level: 3,
    school: 'Illusion',
    castingTime: '1 action',
    range: '120 feet',
    components: 'S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    notes: 'Wis save or incapacitated and speed 0 for duration. Ends if shaken or damaged.',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: "Leomund's Tiny Hut",
    level: 3,
    school: 'Evocation',
    castingTime: '1 minute (ritual)',
    range: 'Self (10-foot-radius hemisphere)',
    components: 'V, S, M',
    duration: '8 hours',
    notes: 'Dome shelters up to 9 creatures; blocks weather, projectiles, and certain spells. Opaque from outside.',
    classes: ['bard', 'wizard'],
  },
  {
    name: 'Lightning Bolt',
    level: 3,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Self (100-foot line)',
    components: 'V, S, M',
    duration: 'Instantaneous',
    saveAbility: 'dex',
    damage: '8d6',
    damageType: 'lightning',
    notes: 'Dex save for half lightning damage in a 5-ft wide, 100-ft long line.',
    upcastDamage: '1d6',
    classes: ['sorcerer', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'Each creature in the line',
    fullDescription:
      'A stroke of lightning forming a line 100 feet long and 5 feet wide blasts out from you in a direction you choose. Each creature in the line must make a Dexterity saving throw. A creature takes 8d6 lightning damage on a failed save, or half as much damage on a successful one. The lightning ignites flammable objects in the area that aren\'t being worn or carried.',
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
    areaOfEffect: { shape: 'line', sizeFt: 100, widthFt: 5 },
    source: 'srd-5.2',
  },
  {
    name: 'Magic Circle',
    level: 3,
    school: 'Abjuration',
    castingTime: '1 minute',
    range: '10 feet',
    components: 'V, S, M',
    duration: '1 hour',
    notes: '10-ft radius cylinder blocks celestials, elementals, fey, fiends, or undead: attacks have disadvantage, cannot charm/frighten/possess inside.',
    classes: ['cleric', 'paladin', 'warlock', 'wizard'],
  },
  {
    name: 'Major Image',
    level: 3,
    school: 'Illusion',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Create a realistic illusion up to 20-ft cube with sound, smell, temperature. Investigation vs. spell save DC.',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Mass Healing Word',
    level: 3,
    school: 'Evocation',
    castingTime: '1 bonus action',
    range: '60 feet',
    components: 'V',
    duration: 'Instantaneous',
    damage: '1d4+3',
    upcastDamage: '1d4',
    notes: 'Up to 6 creatures each regain 1d4 + spellcasting modifier HP.',
    classes: ['bard', 'cleric'],
    concentration: false,
    ritual: false,
    targets: 'Up to six creatures within 60 ft',
    fullDescription:
      'As you call out words of restoration, up to six creatures of your choice that you can see within range regain hit points equal to 1d4 + your spellcasting ability modifier. This spell has no effect on undead or constructs.',
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the healing increases by 1d4 for each slot level above 3rd.',
    source: 'srd-5.2',
  },
  {
    name: 'Meld into Stone',
    level: 3,
    school: 'Transmutation',
    castingTime: '1 action (ritual)',
    range: 'Touch',
    components: 'V, S',
    duration: '8 hours',
    notes: 'Step inside a Large or bigger stone object. You cannot move, attack, or cast. Emerge as bonus action.',
    classes: ['cleric', 'druid'],
  },
  {
    name: 'Nondetection',
    level: 3,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: '8 hours',
    notes: 'Target cannot be targeted by divination magic or perceived through magical scrying sensors.',
    classes: ['bard', 'ranger', 'wizard'],
  },
  {
    name: 'Phantom Steed',
    level: 3,
    school: 'Illusion',
    castingTime: '1 minute (ritual)',
    range: '30 feet',
    components: 'V, S',
    duration: '1 hour',
    notes: 'Semi-real horse-like creature with 100 ft speed. Vanishes if attacked.',
    classes: ['wizard'],
  },
  {
    name: 'Plant Growth',
    level: 3,
    school: 'Transmutation',
    castingTime: '1 action or 8 hours',
    range: '150 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    notes: 'Enrich plants for bountiful harvest (8 hrs), or overgrow in 100-ft radius making difficult terrain (1 action).',
    classes: ['bard', 'druid', 'ranger'],
  },
  {
    name: 'Protection from Energy',
    level: 3,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Willing creature gains resistance to one damage type: acid, cold, fire, lightning, or thunder.',
    classes: ['cleric', 'druid', 'ranger', 'sorcerer', 'wizard'],
  },
  {
    name: 'Remove Curse',
    level: 3,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Instantaneous',
    notes: "End all curses affecting a creature or object (cursed magic items are released, not destroyed).",
    classes: ['cleric', 'paladin', 'warlock', 'wizard'],
  },
  {
    name: 'Revivify',
    level: 3,
    school: 'Conjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Restore a creature that died within the last minute to 1 HP.',
    classes: ['cleric', 'paladin', 'artificer'],
    concentration: false,
    ritual: false,
    targets: 'A creature that has died within the last minute',
    fullDescription:
      'You touch a creature that has died within the last minute. That creature returns to life with 1 hit point. This spell can\'t return to life a creature that has died of old age, nor can it restore any missing body parts. The 300 gp diamond is consumed.',
    source: 'srd-5.2',
  },
  {
    name: 'Sending',
    level: 3,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Unlimited',
    components: 'V, S, M',
    duration: '1 round',
    notes: 'Send a 25-word message to a known creature on the same plane. It can reply with 25 words.',
    classes: ['bard', 'cleric', 'wizard'],
  },
  {
    name: 'Sleet Storm',
    level: 3,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '150 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'dex',
    notes: 'Freezing rain and sleet in 40-ft radius, 20-ft tall cylinder: difficult terrain, Dex save or fall prone, concentration checks DC 10.',
    classes: ['druid', 'sorcerer', 'wizard'],
  },
  {
    name: 'Slow',
    level: 3,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    notes: 'Up to 6 creatures: halved speed, −2 AC and Dex saves, lose bonus actions and reactions, and can only attack or cast (not both) each turn.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Speak with Dead',
    level: 3,
    school: 'Necromancy',
    castingTime: '1 action',
    range: '10 feet',
    components: 'V, S, M',
    duration: '10 minutes',
    notes: 'A corpse answers up to 5 questions. It knows only what it knew in life.',
    classes: ['bard', 'cleric'],
  },
  {
    name: 'Speak with Plants',
    level: 3,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Self (30-foot radius)',
    components: 'V, S',
    duration: '10 minutes',
    notes: 'Communicate with plants within 30 ft; they obey simple commands and report on recent events.',
    classes: ['bard', 'druid', 'ranger'],
  },
  {
    name: 'Spirit Guardians',
    level: 3,
    school: 'Conjuration',
    castingTime: '1 action',
    range: 'Self (15-foot radius)',
    components: 'V, S, M',
    duration: 'Up to 10 minutes (concentration)',
    saveAbility: 'wis',
    damage: '3d8',
    notes: 'Spectral spirits swirl; area is difficult terrain for enemies. Wis save for half radiant (or necrotic) damage.',
    classes: ['cleric'],
  },
  {
    name: 'Stinking Cloud',
    level: 3,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '90 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'con',
    notes: 'Heavily obscured 20-ft radius yellow gas. Con save or waste action retching. Wind disperses it.',
    classes: ['bard', 'sorcerer', 'wizard'],
  },
  {
    name: 'Tongues',
    level: 3,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, M',
    duration: '1 hour',
    notes: 'Creature understands any spoken language and any creature that knows at least one language understands it.',
    classes: ['bard', 'cleric', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Vampiric Touch',
    level: 3,
    school: 'Necromancy',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    attackRoll: true,
    damage: '3d6',
    notes: 'Melee spell attack; 3d6 necrotic damage, and you regain HP equal to half the damage dealt.',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Water Breathing',
    level: 3,
    school: 'Transmutation',
    castingTime: '1 action (ritual)',
    range: '30 feet',
    components: 'V, S, M',
    duration: '24 hours',
    notes: 'Up to 10 willing creatures can breathe underwater.',
    classes: ['druid', 'ranger', 'sorcerer', 'wizard'],
  },
  {
    name: 'Water Walk',
    level: 3,
    school: 'Transmutation',
    castingTime: '1 action (ritual)',
    range: '30 feet',
    components: 'V, S, M',
    duration: '1 hour',
    notes: 'Up to 10 willing creatures can move across liquid surfaces as if solid ground.',
    classes: ['cleric', 'druid', 'ranger', 'sorcerer'],
  },
  {
    name: 'Wind Wall',
    level: 3,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'str',
    damage: '3d8',
    notes: 'Wall of strong wind (50 ft × 15 ft × 1 ft). Str save for bludgeoning damage; Small or smaller creatures knocked prone. Blocks gas, fog, ranged attacks.',
    classes: ['druid', 'ranger'],
  },
]
