// 6th-level spells — full SRD 5.1 list

import type { SrdSpell } from './types'

export const LEVEL6_SPELLS: SrdSpell[] = [
  {
    name: 'Arcane Gate',
    level: 6,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '500 feet',
    components: 'V, S',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Create linked teleportation portals (up to 10-ft diameter) within range. Travel through them instantaneously.',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Blade Barrier',
    level: 6,
    school: 'Evocation',
    castingTime: '1 action',
    range: '90 feet',
    components: 'V, S',
    duration: 'Up to 10 minutes (concentration)',
    saveAbility: 'dex',
    damage: '6d10',
    notes: 'Wall of whirling blades (up to 100 × 20 × 5 ft). Dex save for slashing damage when passing through.',
    classes: ['cleric'],
  },
  {
    name: 'Chain Lightning',
    level: 6,
    school: 'Evocation',
    castingTime: '1 action',
    range: '150 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    saveAbility: 'dex',
    damage: '10d8',
    damageType: 'lightning',
    notes: 'Dex save for lightning damage to primary target; bolt arcs to up to 3 secondary targets (same save).',
    classes: ['sorcerer', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'One primary creature + up to three secondaries within 30 ft of it',
    fullDescription:
      'You unleash a stroke of lightning that arcs toward a target of your choice that you can see within range. Three bolts then leap from that target to as many as three other targets, each of which must be within 30 feet of the first target. A target can be a creature or an object and can be targeted by only one of the bolts. A target must make a Dexterity saving throw. The target takes 10d8 lightning damage on a failed save, or half as much damage on a successful one.',
    higherLevels: 'When you cast this spell using a spell slot of 7th level or higher, one additional bolt leaps from the first target to another target for each slot level above 6th.',
    source: 'srd-5.2',
  },
  {
    name: 'Circle of Death',
    level: 6,
    school: 'Necromancy',
    castingTime: '1 action',
    range: '150 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    saveAbility: 'con',
    damage: '8d6',
    notes: 'Con save for half necrotic damage in a 60-ft radius sphere.',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Conjure Fey',
    level: 6,
    school: 'Conjuration',
    castingTime: '1 minute',
    range: '90 feet',
    components: 'V, S',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Summon a fey creature of CR 6 or lower, or a fey spirit that takes the form of a beast of CR 6 or lower.',
    classes: ['druid', 'warlock'],
  },
  {
    name: 'Contingency',
    level: 6,
    school: 'Evocation',
    castingTime: '10 minutes',
    range: 'Self',
    components: 'V, S, M',
    duration: '10 days',
    notes: 'Pair this spell with a 5th-level-or-lower spell. The paired spell triggers automatically when a condition you specify is met.',
    classes: ['wizard'],
  },
  {
    name: 'Create Undead',
    level: 6,
    school: 'Necromancy',
    castingTime: '1 minute',
    range: '10 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Create up to 3 ghouls from corpses. They obey your commands.',
    classes: ['cleric', 'warlock', 'wizard'],
  },
  {
    name: 'Disintegrate',
    level: 6,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    saveAbility: 'dex',
    damage: '10d6+40',
    damageType: 'force',
    notes: 'Dex save or massive force damage. Creature reduced to 0 HP is completely destroyed.',
    upcastDamage: '3d6',
    classes: ['sorcerer', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'One creature, object, or force barrier you can see',
    fullDescription:
      'A thin green ray springs from your pointing finger to a target that you can see within range. The target can be a creature, an object, or a creation of magical force, such as the wall created by Wall of Force. A creature targeted by this spell must make a Dexterity saving throw. On a failed save, the target takes 10d6 + 40 force damage. If this damage reduces the target to 0 hit points, it is disintegrated. A disintegrated creature and everything it is wearing and carrying, except magic items, are reduced to a pile of fine gray dust. The creature can be restored to life only by means of a True Resurrection or Wish spell.',
    higherLevels: 'When you cast this spell using a spell slot of 7th level or higher, the damage increases by 3d6 for each slot level above 6th.',
    source: 'srd-5.2',
  },
  {
    name: "Drawmij's Instant Summons",
    level: 6,
    school: 'Conjuration',
    castingTime: '1 minute (ritual)',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Until dispelled',
    notes: 'Inscribe a Tiny object; can speak its name to summon it to your hand from anywhere on the same plane.',
    classes: ['wizard'],
  },
  {
    name: 'Eyebite',
    level: 6,
    school: 'Necromancy',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    notes: 'Wis save each turn or target suffers one of: Asleep (unconscious until damaged), Panicked (frightened, Dash away), Sickened (disadvantage on attacks and ability checks).',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Find the Path',
    level: 6,
    school: 'Divination',
    castingTime: '1 minute',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Up to 1 day (concentration)',
    notes: 'Know the shortest route to a location you are familiar with on the same plane.',
    classes: ['bard', 'cleric', 'druid'],
  },
  {
    name: 'Flesh to Stone',
    level: 6,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'con',
    notes: 'Con save or restrained. Fails 3 saves = permanently petrified. Succeeds 3 = spell ends.',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Forbiddance',
    level: 6,
    school: 'Abjuration',
    castingTime: '10 minutes (ritual)',
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 day',
    saveAbility: 'cha',
    damage: '5d10',
    notes: 'Ward up to 40,000 sq ft. Blocks planar travel and deals 5d10 necrotic or radiant damage to designated creature types that enter.',
    classes: ['cleric'],
  },
  {
    name: "Otiluke's Freezing Sphere",
    level: 6,
    school: 'Evocation',
    castingTime: '1 action',
    range: '300 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    saveAbility: 'con',
    damage: '10d6',
    notes: 'Con save for half cold damage in a 60-ft radius sphere. Can be stored as a bead and thrown later.',
    classes: ['wizard'],
  },
  {
    name: 'Globe of Invulnerability',
    level: 6,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Self (10-foot radius)',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    notes: 'Any spell of 5th level or lower cast from outside the sphere cannot affect those inside.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Guards and Wards',
    level: 6,
    school: 'Abjuration',
    castingTime: '10 minutes',
    range: 'Touch',
    components: 'V, S, M',
    duration: '24 hours',
    notes: 'Protect up to 2500 sq ft: confusing corridors, magical darkness, magical locks, webs, suggestion, and dancing lights.',
    classes: ['bard', 'wizard'],
  },
  {
    name: 'Harm',
    level: 6,
    school: 'Necromancy',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    saveAbility: 'con',
    damage: '14d6',
    notes: 'Con save for half necrotic damage. Reduces max HP by the amount dealt (min 1) until a long rest.',
    classes: ['cleric'],
  },
  {
    name: 'Heal',
    level: 6,
    school: 'Evocation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    damage: '70',
    notes: 'Restore 70 HP and end blindness, deafness, and diseases.',
    classes: ['cleric', 'druid'],
    concentration: false,
    ritual: false,
    targets: 'A creature you can see within 60 ft',
    fullDescription:
      'Choose a creature that you can see within range. A surge of positive energy washes through the creature, causing it to regain 70 hit points. This spell also ends blindness, deafness, and any diseases affecting the target. This spell has no effect on constructs or undead.',
    higherLevels: 'When you cast this spell using a spell slot of 7th level or higher, the amount of healing increases by 10 for each slot level above 6th.',
    source: 'srd-5.2',
  },
  {
    name: "Heroes' Feast",
    level: 6,
    school: 'Conjuration',
    castingTime: '10 minutes',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Up to 12 creatures feast: cured of disease/poison, immune to poison and frightened, Wis saves with advantage, max HP +2d10 for 24 hours.',
    classes: ['cleric', 'druid'],
  },
  {
    name: 'Investiture of Flame',
    level: 6,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: 'Up to 10 minutes (concentration)',
    saveAbility: 'dex',
    damage: '1d10',
    notes: 'Flame sheathing; immune to fire, vulnerable creatures take 1d10 fire when moving through within 5 ft. Also as action: 4d8 fire in 15-ft cone (Dex half).',
    classes: ['druid', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Investiture of Ice',
    level: 6,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: 'Up to 10 minutes (concentration)',
    saveAbility: 'con',
    damage: '4d6',
    notes: 'Icy armor: immune to cold, resistance to fire. 15-ft cone action: Con save for 4d6 cold (half on success).',
    classes: ['druid', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Investiture of Stone',
    level: 6,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Stone shell: resistance to bludgeoning/piercing/slashing nonmagical, move through difficult terrain of rock/earth without extra cost.',
    classes: ['druid', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Investiture of Wind',
    level: 6,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Wind shell: flying speed 60 ft, ranged attacks against you have disadvantage. 15-ft radius wind action pushes creatures 10 ft (Str save).',
    classes: ['druid', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Magic Jar',
    level: 6,
    school: 'Necromancy',
    castingTime: '1 minute',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Until dispelled',
    saveAbility: 'cha',
    notes: 'Your soul enters a container. Possess nearby humanoids (Cha save to resist) while your body remains inert.',
    classes: ['wizard'],
  },
  {
    name: 'Mass Suggestion',
    level: 6,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, M',
    duration: '24 hours',
    saveAbility: 'wis',
    notes: 'Suggest a reasonable course of action to up to 12 creatures. Wis save or follow it.',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Move Earth',
    level: 6,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Up to 2 hours (concentration)',
    notes: 'Shape earth, sand, and clay in a 40-ft cube. Alter terrain: create trenches, hills, inclines, or platforms.',
    classes: ['druid', 'sorcerer', 'wizard'],
  },
  {
    name: "Otto's Irresistible Dance",
    level: 6,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    notes: 'Auto-fails initial Wis save; forced to dance (no movement, disadvantage on Dex saves and attacks against it have advantage). Wis save each turn to end.',
    classes: ['bard', 'sorcerer', 'wizard'],
  },
  {
    name: 'Programmed Illusion',
    level: 6,
    school: 'Illusion',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Until dispelled',
    notes: 'Create a pre-programmed illusion (up to 30-ft cube) that plays when a trigger is met. Runs for 5 minutes then resets.',
    classes: ['bard', 'wizard'],
  },
  {
    name: 'Sunbeam',
    level: 6,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Self (60-foot line)',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'con',
    damage: '6d8',
    notes: 'Con save or blinded and 6d8 radiant damage (half on success). Undead and oozes have disadvantage. Each turn, fire again as action.',
    classes: ['druid', 'sorcerer', 'wizard'],
  },
  {
    name: 'Transport via Plants',
    level: 6,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '10 feet',
    components: 'V, S',
    duration: '1 round',
    notes: 'Step into a large plant and teleport to another plant of the same species on the same plane.',
    classes: ['druid'],
  },
  {
    name: 'True Seeing',
    level: 6,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 hour',
    notes: 'Creature gains truesight (120 ft), sees secret doors, and can see into the Ethereal Plane.',
    classes: ['bard', 'cleric', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Wall of Ice',
    level: 6,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Up to 10 minutes (concentration)',
    saveAbility: 'dex',
    damage: '10d6',
    notes: 'Wall of ice panels (up to 10 × 10 ft each). Passing through: Dex save for cold damage. Sphere option also available.',
    classes: ['wizard'],
  },
  {
    name: 'Wall of Thorns',
    level: 6,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Up to 10 minutes (concentration)',
    saveAbility: 'dex',
    damage: '7d8',
    notes: 'Wall of thorns (up to 60 × 10 × 5 ft). Dex save for slashing damage passing through. Difficult terrain.',
    classes: ['druid'],
  },
  {
    name: 'Wind Walk',
    level: 6,
    school: 'Transmutation',
    castingTime: '1 minute',
    range: '30 feet',
    components: 'V, S, M',
    duration: '8 hours',
    notes: 'Up to 10 creatures become gaseous with a 300-ft fly speed. Can solidify or gasify as bonus action.',
    classes: ['druid'],
  },
  {
    name: 'Word of Recall',
    level: 6,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '5 feet',
    components: 'V',
    duration: 'Instantaneous',
    notes: 'Teleport yourself and up to 5 willing creatures to a previously sanctified location of your deity.',
    classes: ['cleric'],
  },
]
