// 7th-level spells — full SRD 5.1 list

import type { SrdSpell } from './types'

export const LEVEL7_SPELLS: SrdSpell[] = [
  {
    name: 'Conjure Celestial',
    level: 7,
    school: 'Conjuration',
    castingTime: '1 minute',
    range: '90 feet',
    components: 'V, S',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Summon a celestial of CR 4 or lower (or CR 11 or lower with a 9th-level slot).',
    classes: ['cleric'],
  },
  {
    name: 'Delayed Blast Fireball',
    level: 7,
    school: 'Evocation',
    castingTime: '1 action',
    range: '150 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'dex',
    damage: '12d6',
    notes: 'Glowing bead explodes at end of duration or when triggered. Dex save for half fire damage in 20-ft radius. Damage increases 1d6 per round held.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Divine Word',
    level: 7,
    school: 'Evocation',
    castingTime: '1 bonus action',
    range: '30 feet',
    components: 'V',
    duration: 'Instantaneous',
    saveAbility: 'cha',
    notes: 'Cha save or suffer based on current HP: ≤50 deafened, ≤40 blinded + deafened, ≤30 stunned 1 hour, ≤20 dies instantly. Fiends/celestials/fey/elementals banished on a fail.',
    classes: ['cleric'],
  },
  {
    name: 'Etherealness',
    level: 7,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: 'Up to 8 hours',
    notes: 'Step into the Border Ethereal. Move in any direction (up/down costs extra). Can see and hear the Material Plane.',
    classes: ['bard', 'cleric', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Finger of Death',
    level: 7,
    school: 'Necromancy',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    saveAbility: 'con',
    damage: '7d8+30',
    damageType: 'necrotic',
    notes: 'Con save for half necrotic damage. Humanoid killed rises as zombie permanently under your control.',
    classes: ['sorcerer', 'warlock', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'A creature you can see within 60 ft',
    fullDescription:
      'You send negative energy coursing through a creature that you can see within range, causing it searing pain. The target must make a Constitution saving throw. It takes 7d8 + 30 necrotic damage on a failed save, or half as much damage on a successful one. A humanoid killed by this spell rises at the start of your next turn as a zombie that is permanently under your command, following your verbal orders to the best of its ability.',
    source: 'srd-5.2',
  },
  {
    name: 'Fire Storm',
    level: 7,
    school: 'Evocation',
    castingTime: '1 action',
    range: '150 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    saveAbility: 'dex',
    damage: '7d10',
    notes: 'Dex save for half fire damage in up to 10 contiguous 10-ft cubes you arrange.',
    classes: ['cleric', 'druid'],
  },
  {
    name: 'Forcecage',
    level: 7,
    school: 'Evocation',
    castingTime: '1 action',
    range: '100 feet',
    components: 'V, S, M',
    duration: '1 hour',
    saveAbility: 'cha',
    notes: 'Create a motionless cage of force (20-ft cube with bars or 10-ft box). Creatures inside cannot leave except by teleportation (Cha save to escape).',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Mirage Arcane',
    level: 7,
    school: 'Illusion',
    castingTime: '10 minutes',
    range: 'Sight',
    components: 'V, S',
    duration: '10 days',
    notes: 'Transform up to 1 square mile of terrain into any other terrain type (mountain, swamp, forest, etc.) with sound, smell, and temperature.',
    classes: ['bard', 'druid', 'wizard'],
  },
  {
    name: "Mordenkainen's Magnificent Mansion",
    level: 7,
    school: 'Conjuration',
    castingTime: '1 minute',
    range: '300 feet',
    components: 'V, S, M',
    duration: '24 hours',
    notes: 'Create an extradimensional dwelling (up to 50 10-ft cubes) with furnishings, 100 servants, and food.',
    classes: ['bard', 'wizard'],
  },
  {
    name: "Mordenkainen's Sword",
    level: 7,
    school: 'Evocation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    attackRoll: true,
    damage: '3d10',
    notes: 'Floating force sword; bonus action to move it 20 ft and attack (melee spell attack for 3d10 force damage).',
    classes: ['bard', 'wizard'],
  },
  {
    name: 'Plane Shift',
    level: 7,
    school: 'Conjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    saveAbility: 'cha',
    notes: 'Transport up to 8 willing creatures to another plane, or banish a creature (Cha save to resist).',
    classes: ['cleric', 'druid', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Power Word Pain',
    level: 7,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V',
    duration: 'Instantaneous',
    saveAbility: 'con',
    notes: 'Con save or wracked with pain: speed halved, cannot take reactions, disadvantage on attacks and ability checks. Repeats save at end of each turn.',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Prismatic Spray',
    level: 7,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Self (60-foot cone)',
    components: 'V, S',
    duration: 'Instantaneous',
    saveAbility: 'dex',
    damage: '10d6',
    notes: 'Each creature in cone struck by random color: red (10d6 fire), orange (10d6 acid), yellow (10d6 lightning), green (death), blue (petrified), indigo (restrained→petrified), violet (blinded→teleported), or hit by two colors.',
    classes: ['bard', 'sorcerer', 'wizard'],
  },
  {
    name: 'Project Image',
    level: 7,
    school: 'Illusion',
    castingTime: '1 action',
    range: '500 miles',
    components: 'V, S, M',
    duration: 'Up to 1 day (concentration)',
    notes: 'Create an illusory double of yourself anywhere on the same plane; see/hear through it and cast spells from its location.',
    classes: ['bard', 'wizard'],
  },
  {
    name: 'Regenerate',
    level: 7,
    school: 'Transmutation',
    castingTime: '1 minute',
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 hour',
    damage: '4d8+15',
    notes: 'Target regains 4d8+15 HP. For 1 hour, regains 1 HP at start of each turn. Severed body parts reattach or regrow.',
    classes: ['bard', 'cleric', 'druid'],
  },
  {
    name: 'Resurrection',
    level: 7,
    school: 'Necromancy',
    castingTime: '1 hour',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Return a creature dead up to 100 years to life with full HP. Can restore a destroyed body.',
    classes: ['bard', 'cleric'],
    concentration: false,
    ritual: false,
    targets: 'A deceased creature you touch',
    fullDescription:
      'You touch a dead creature that has been dead for no more than a century, that didn\'t die of old age, and that isn\'t undead. If its soul is free and willing, the target is restored to life with all its hit points. This spell closes all mortal wounds and restores any missing body parts. Coming back from the dead is an ordeal — the target takes a −4 penalty to all attack rolls, saving throws, and ability checks. Every time the target finishes a long rest, the penalty is reduced by 1 until it disappears. Casting this spell to restore life to a creature that has been dead for more than a year ages you by 1d10 years. The 1,000 gp diamond is consumed.',
    source: 'srd-5.2',
  },
  {
    name: 'Reverse Gravity',
    level: 7,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '100 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'dex',
    notes: 'Reverse gravity in a 50-ft radius, 100-ft tall cylinder. Unsecured objects and creatures fall upward (Dex save to grab something).',
    classes: ['druid', 'sorcerer', 'wizard'],
    concentration: true,
    ritual: false,
    targets: 'A 50-ft radius, 100-ft tall cylinder',
    fullDescription:
      'This spell reverses gravity in a 50-foot-radius, 100-foot-high cylinder centered on a point within range. All creatures and objects that aren\'t somehow anchored to the ground in the area fall upward and reach the top of the area when you cast this spell. A creature can make a Dexterity saving throw to grab onto a fixed object it can reach, thus avoiding the fall. If some solid object (such as a ceiling) is encountered in this fall, falling objects and creatures strike it just as they would during a normal downward fall. If an object or creature reaches the top of the area without striking anything, it remains there, oscillating slightly, for the duration. At the end of the duration, affected objects and creatures fall back down.',
    areaOfEffect: { shape: 'cylinder', sizeFt: 50, heightFt: 100 },
    source: 'srd-5.2',
  },
  {
    name: 'Sequester',
    level: 7,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Until dispelled',
    notes: 'Willing creature or object becomes invisible and imperceptible to divination. Creature enters suspended animation until a trigger condition.',
    classes: ['wizard'],
  },
  {
    name: 'Symbol',
    level: 7,
    school: 'Abjuration',
    castingTime: '1 minute',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Until dispelled or triggered',
    saveAbility: 'con',
    notes: 'Inscribe a harmful sigil. Choose effect: Death (10d10 necrotic), Discord (fighting each other), Fear (Wis save), Hopelessness (Cha save), Insanity (Wis save), Pain (Con save), Sleep (all ≤10 HD sleep), Stunning (Wis save).',
    classes: ['bard', 'cleric', 'wizard'],
  },
  {
    name: 'Teleport',
    level: 7,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '10 feet',
    components: 'V',
    duration: 'Instantaneous',
    notes: 'Teleport yourself and up to 8 willing creatures to a known destination on the same plane. Mishap chance based on familiarity.',
    classes: ['bard', 'sorcerer', 'wizard'],
  },
  {
    name: 'Whirlwind',
    level: 7,
    school: 'Evocation',
    castingTime: '1 action',
    range: '300 feet',
    components: 'V, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'dex',
    damage: '10d6',
    notes: 'Create a 10-ft radius, 30-ft tall column of swirling air. Dex save or 10d6 bludgeoning; str save or flung 20 ft and knocked prone.',
    classes: ['druid', 'sorcerer', 'wizard'],
  },
]
