// 8th-level spells — full SRD 5.1 list

import type { SrdSpell } from './types'

export const LEVEL8_SPELLS: SrdSpell[] = [
  {
    name: "Abi-Dalzim's Horrid Wilting",
    level: 8,
    school: 'Necromancy',
    castingTime: '1 action',
    range: '150 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    saveAbility: 'con',
    damage: '12d8',
    notes: 'Con save for half necrotic damage in 30-ft cube. Plants and water elementals have disadvantage on the save.',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Animal Shapes',
    level: 8,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: 'Up to 24 hours (concentration)',
    notes: "Transform any number of willing creatures into beasts of CR 4 or lower. Each creature chooses its beast form.",
    classes: ['druid'],
  },
  {
    name: 'Antipathy/Sympathy',
    level: 8,
    school: 'Enchantment',
    castingTime: '1 hour',
    range: '60 feet',
    components: 'V, S, M',
    duration: '10 days',
    saveAbility: 'wis',
    notes: 'Target an object or area. Antipathy: designated creatures must Wis save or flee. Sympathy: designated creatures must Wis save or drawn to approach.',
    classes: ['bard', 'druid', 'wizard'],
  },
  {
    name: 'Clone',
    level: 8,
    school: 'Necromancy',
    castingTime: '1 hour',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Grow an inert duplicate of a creature. When the original dies, its soul transfers to the clone (fully healed).',
    classes: ['wizard'],
  },
  {
    name: 'Control Weather',
    level: 8,
    school: 'Transmutation',
    castingTime: '10 minutes',
    range: 'Self (5-mile radius)',
    components: 'V, S, M',
    duration: 'Up to 8 hours (concentration)',
    notes: 'Alter weather conditions: precipitation, wind, temperature. Changes take 1d4 × 10 minutes to take effect.',
    classes: ['cleric', 'druid', 'wizard'],
  },
  {
    name: 'Demiplane',
    level: 8,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: 'S',
    duration: '1 hour',
    notes: 'Create a door to a 30-ft-cube demiplane. Creatures inside are trapped if the door closes.',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Dominate Monster',
    level: 8,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Up to 1 hour (concentration)',
    saveAbility: 'wis',
    notes: 'Wis save or charmed and telepathically controlled (any creature type). Repeats save when damaged.',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
    concentration: true,
    ritual: false,
    targets: 'One creature you can see within range',
    fullDescription:
      'You attempt to beguile a creature that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration. If you or creatures friendly to you are fighting it, it has advantage on the saving throw. While the creature is charmed, you have a telepathic link with it as long as the two of you are on the same plane of existence. You can use this telepathic link to issue commands to the creature while you are conscious (no action required), which it does its best to obey. You can specify a simple and general course of action, such as "Attack that creature," "Run over there," or "Fetch that object." Each time the target takes damage, it makes a new Wisdom saving throw against the spell. If the saving throw succeeds, the spell ends.',
    higherLevels: 'When you cast this spell using a 9th-level spell slot, the duration is concentration, up to 8 hours.',
    mechanicalEffects: ['charmed'],
    source: 'srd-5.2',
  },
  {
    name: 'Earthquake',
    level: 8,
    school: 'Evocation',
    castingTime: '1 action',
    range: '500 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'dex',
    notes: 'Violent shaking in a 100-ft radius: difficult terrain, Dex save to stay standing, concentration DC 15, fissures open (Dex save or fall in).',
    classes: ['cleric', 'druid', 'sorcerer'],
  },
  {
    name: 'Feeblemind',
    level: 8,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '150 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    saveAbility: 'int',
    damage: '4d6',
    notes: 'Int save or Int and Cha become 1, cannot cast spells or use magic items. Takes 4d6 psychic damage. Repeats save every 30 days.',
    classes: ['bard', 'druid', 'warlock', 'wizard'],
  },
  {
    name: 'Glibness',
    level: 8,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Self',
    components: 'V',
    duration: '1 hour',
    notes: 'Treat any Charisma check as a roll of 15. Magical lie detection always reads as truthful.',
    classes: ['bard', 'warlock'],
  },
  {
    name: 'Holy Aura',
    level: 8,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Self (30-foot radius)',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'str',
    notes: 'Allies gain +4 AC, advantage on saves, advantage vs. fiends/undead. Undead hitting allies: Str save or blinded.',
    classes: ['cleric'],
  },
  {
    name: 'Illusory Dragon',
    level: 8,
    school: 'Illusion',
    castingTime: '1 action',
    range: '120 feet',
    components: 'S',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'int',
    damage: '7d6',
    notes: 'Create a dragon illusion. As bonus action, move it 60 ft and breathe in a 60-ft cone. Int save or 7d6 of chosen damage type.',
    classes: ['wizard'],
  },
  {
    name: 'Incendiary Cloud',
    level: 8,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '150 feet',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'dex',
    damage: '10d8',
    notes: 'Roiling cloud of flame-like smoke (20-ft radius, heavily obscured). Dex save for fire damage at start of each turn in the area.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Maddening Darkness',
    level: 8,
    school: 'Evocation',
    castingTime: '1 action',
    range: '150 feet',
    components: 'V, M',
    duration: 'Up to 10 minutes (concentration)',
    saveAbility: 'wis',
    damage: '8d8',
    notes: 'Magical darkness fills a 60-ft sphere; maddening whispers force a Wis save for psychic damage each turn.',
    classes: ['warlock', 'wizard'],
  },
  {
    name: 'Maze',
    level: 8,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Banish a creature to a labyrinthine extradimensional space. DC 20 Int check (action) to escape.',
    classes: ['wizard'],
  },
  {
    name: 'Mind Blank',
    level: 8,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: '24 hours',
    notes: 'Target is immune to psychic damage, all mind-reading and emotion-sensing, and scrying effects.',
    classes: ['bard', 'wizard'],
  },
  {
    name: 'Power Word Stun',
    level: 8,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V',
    duration: 'Instantaneous',
    saveAbility: 'con',
    notes: 'If the creature has 150 HP or fewer, it is stunned. Con save at end of each turn to end the effect.',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Sunburst',
    level: 8,
    school: 'Evocation',
    castingTime: '1 action',
    range: '150 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    saveAbility: 'con',
    damage: '12d6',
    damageType: 'radiant',
    notes: 'Brilliant light in 60-ft radius. Con save for radiant damage (half on success) and blinded for 1 minute (save each turn to end).',
    classes: ['cleric', 'druid', 'sorcerer', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'Each creature in a 60-ft radius sphere',
    fullDescription:
      'Brilliant sunlight flashes in a 60-foot radius centered on a point you choose within range. Each creature in that light must make a Constitution saving throw. On a failed save, a creature takes 12d6 radiant damage and is blinded for 1 minute. On a successful save, it takes half as much damage and isn\'t blinded by this spell. Undead and oozes have disadvantage on this saving throw. A creature blinded by this spell makes another Constitution save at the end of each of its turns. On a successful save, it is no longer blinded. This spell dispels any darkness in its area that was created by a spell.',
    areaOfEffect: { shape: 'sphere', sizeFt: 60 },
    mechanicalEffects: ['blinded'],
    source: 'srd-5.2',
  },
  {
    name: 'Telepathy',
    level: 8,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Unlimited',
    components: 'V, S, M',
    duration: '24 hours',
    notes: 'Establish two-way telepathic communication with a willing creature on the same plane. Can probe and affect thoughts.',
    classes: ['wizard'],
  },
  {
    name: 'Tsunami',
    level: 8,
    school: 'Conjuration',
    castingTime: '1 minute',
    range: 'Sight',
    components: 'V, S',
    duration: 'Up to 6 rounds (concentration)',
    saveAbility: 'str',
    damage: '6d10',
    notes: 'Wall of water (300 × 300 × 50 ft) surges forward. Str save or 6d10 bludgeoning and pushed to far edge. Wall shrinks 50 ft per round.',
    classes: ['druid'],
  },
]
