// 4th-level spells — full SRD 5.1 list

import type { SrdSpell } from './types'

export const LEVEL4_SPELLS: SrdSpell[] = [
  {
    name: 'Arcane Eye',
    level: 4,
    school: 'Divination',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Create an invisible magical eye that moves up to 30 ft per round. Darkvision 30 ft.',
    classes: ['wizard'],
  },
  {
    name: 'Aura of Life',
    level: 4,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Self (30-foot radius)',
    components: 'V',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Allies in range gain resistance to necrotic damage and max HP cannot be reduced. Unconscious allies regain 1 HP at turn start.',
    classes: ['paladin'],
  },
  {
    name: 'Aura of Purity',
    level: 4,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Self (30-foot radius)',
    components: 'V',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Allies in range cannot be diseased, have resistance to poison, and advantage on saves against blindness, deafness, paralysis, poison, and stun.',
    classes: ['paladin'],
  },
  {
    name: 'Banishment',
    level: 4,
    school: 'Abjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'cha',
    notes: 'Cha save or banished to a harmless demiplane (native plane creatures are permanently banished if concentration is held).',
    classes: ['cleric', 'paladin', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Blight',
    level: 4,
    school: 'Necromancy',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    saveAbility: 'con',
    damage: '8d8',
    notes: 'Con save for half necrotic damage. Plants and undead are unaffected or affected differently.',
    classes: ['druid', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Compulsion',
    level: 4,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    notes: 'Wis save or you choose which direction the creature moves each turn (can still act). Repeats save each turn.',
    classes: ['bard'],
  },
  {
    name: 'Confusion',
    level: 4,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '90 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    notes: 'Wis save or confused for duration (roll d10 for random action). Repeats save each turn.',
    classes: ['bard', 'druid', 'sorcerer', 'wizard'],
  },
  {
    name: 'Conjure Minor Elementals',
    level: 4,
    school: 'Conjuration',
    castingTime: '1 minute',
    range: '90 feet',
    components: 'V, S',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Summon elementals: one CR 2, two CR 1, four CR 1/2, or eight CR 1/4.',
    classes: ['druid', 'wizard'],
  },
  {
    name: 'Conjure Woodland Beings',
    level: 4,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Summon fey creatures: one CR 2, two CR 1, four CR 1/2, or eight CR 1/4.',
    classes: ['druid', 'ranger'],
  },
  {
    name: 'Control Water',
    level: 4,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '300 feet',
    components: 'V, S, M',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Control water in a 100-ft cube: Flood, Part Water, Redirect Flow, or Whirlpool (Str save or 2d8 damage).',
    classes: ['cleric', 'druid', 'wizard'],
  },
  {
    name: 'Death Ward',
    level: 4,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: '8 hours',
    notes: 'First time the creature would drop to 0 HP, it drops to 1 HP instead (expends the ward).',
    classes: ['cleric', 'paladin'],
  },
  {
    name: 'Dimension Door',
    level: 4,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '500 feet',
    components: 'V',
    duration: 'Instantaneous',
    notes: 'Teleport yourself and one willing creature to a location within 500 ft.',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Divination',
    level: 4,
    school: 'Divination',
    castingTime: '1 action (ritual)',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Ask one question about a goal, event, or activity within 7 days. DM gives a truthful omen.',
    classes: ['cleric', 'druid'],
  },
  {
    name: 'Dominate Beast',
    level: 4,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    notes: 'Wis save or charmed and telepathically controlled. Repeats save each time it takes damage.',
    classes: ['druid', 'sorcerer'],
  },
  {
    name: "Evard's Black Tentacles",
    level: 4,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '90 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'dex',
    damage: '3d6',
    notes: 'Tentacles fill 20-ft square (difficult terrain). Dex save or restrained and 3d6 bludgeoning at start of each turn.',
    classes: ['wizard'],
  },
  {
    name: 'Fire Shield',
    level: 4,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S, M',
    duration: '10 minutes',
    damage: '2d8',
    notes: 'Warm (cold resistance, 2d8 fire to melee attackers) or Chill (fire resistance, 2d8 cold to melee attackers) shield.',
    classes: ['wizard'],
  },
  {
    name: 'Freedom of Movement',
    level: 4,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 hour',
    notes: 'Ignore difficult terrain, and spells/effects cannot reduce speed or paralyze/restrain the creature.',
    classes: ['bard', 'cleric', 'druid', 'ranger'],
  },
  {
    name: 'Giant Insect',
    level: 4,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Transform up to 10 centipedes, 3 wasps, 5 beetles, or 1 spider into giant versions under your control.',
    classes: ['druid'],
  },
  {
    name: 'Greater Invisibility',
    level: 4,
    school: 'Illusion',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    notes: 'Target stays invisible even while attacking or casting spells.',
    classes: ['bard', 'sorcerer', 'wizard'],
  },
  {
    name: 'Guardian of Faith',
    level: 4,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V',
    duration: '8 hours',
    saveAbility: 'dex',
    damage: '20',
    notes: 'Large spectral guardian attacks hostile creatures within 10 ft: Dex save or 20 radiant damage (save = half).',
    classes: ['cleric'],
  },
  {
    name: 'Hallucinatory Terrain',
    level: 4,
    school: 'Illusion',
    castingTime: '10 minutes',
    range: '300 feet',
    components: 'V, S, M',
    duration: '24 hours',
    notes: 'Make a 150-ft cube of natural terrain look, sound, and smell like a different type of natural terrain.',
    classes: ['bard', 'druid', 'warlock', 'wizard'],
  },
  {
    name: 'Ice Storm',
    level: 4,
    school: 'Evocation',
    castingTime: '1 action',
    range: '300 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    saveAbility: 'dex',
    damage: '2d8+4d6',
    notes: 'Hailstones hit 20-ft radius, 40-ft cylinder. Dex save for bludgeoning + cold damage (half on success). Difficult terrain afterward.',
    upcastDamage: '1d8',
    classes: ['druid', 'sorcerer', 'wizard'],
  },
  {
    name: "Leomund's Secret Chest",
    level: 4,
    school: 'Conjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Hide a chest on the Ethereal Plane. Recall it as an action.',
    classes: ['wizard'],
  },
  {
    name: 'Locate Creature',
    level: 4,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Know the direction to a specific creature or species within 1000 ft (blocked by running water).',
    classes: ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'wizard'],
  },
  {
    name: "Mordenkainen's Private Sanctum",
    level: 4,
    school: 'Abjuration',
    castingTime: '10 minutes',
    range: '120 feet',
    components: 'V, S, M',
    duration: '24 hours',
    notes: 'Protect an area (5 to 100 ft cube): no sound in/out, opaque, teleportation blocked, divination blocked.',
    classes: ['wizard'],
  },
  {
    name: "Otiluke's Resilient Sphere",
    level: 4,
    school: 'Evocation',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'dex',
    notes: 'Dex save or enclosed in a 10-ft sphere (nothing in or out). Creature rolls to move. Sphere is immune to damage.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Phantasmal Killer',
    level: 4,
    school: 'Illusion',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    damage: '4d10',
    notes: 'Wis save or frightened. Takes 4d10 psychic at end of each turn (save for half). Ends on successful save.',
    classes: ['wizard'],
  },
  {
    name: 'Polymorph',
    level: 4,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    saveAbility: 'wis',
    notes: 'Transform creature into a beast of equal or lower CR. Reverts if reduced to 0 HP.',
    classes: ['bard', 'druid', 'sorcerer', 'wizard'],
  },
  {
    name: 'Stone Shape',
    level: 4,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Reshape a Medium-sized stone into any form, or create a door, window, or passage.',
    classes: ['cleric', 'druid', 'wizard'],
  },
  {
    name: 'Stoneskin',
    level: 4,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Target gains resistance to bludgeoning, piercing, and slashing damage from nonmagical attacks.',
    classes: ['druid', 'ranger', 'sorcerer', 'wizard'],
  },
  {
    name: 'Wall of Fire',
    level: 4,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'dex',
    damage: '5d8',
    notes: 'Create a wall of fire (60 × 20 × 1 ft or ring 20 ft diameter). Dex save for fire damage on the specified side.',
    classes: ['druid', 'sorcerer', 'wizard'],
  },
]
