// 4th-level spells — full SRD 5.1 list

import type { SrdSpell } from './types'

export const LEVEL4_SPELLS: SrdSpell[] = [
  {
    name: 'Arcane Eye',
    level: 4,
    school: 'Divination',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Create an invisible magical eye that moves up to 30 ft per round. Darkvision 30 ft.',
    classes: ['wizard'],
  },
  {
    name: 'Aura of Life',
    level: 4,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Self (30-foot radius)',
    components: 'V',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Allies in range gain resistance to necrotic damage and max HP cannot be reduced. Unconscious allies regain 1 HP at turn start.',
    classes: ['paladin'],
  },
  {
    name: 'Aura of Purity',
    level: 4,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Self (30-foot radius)',
    components: 'V',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Allies in range cannot be diseased, have resistance to poison, and advantage on saves against blindness, deafness, paralysis, poison, and stun.',
    classes: ['paladin'],
  },
  {
    name: 'Banishment',
    level: 4,
    school: 'Abjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'cha',
    notes: 'Cha save or banished to a harmless demiplane (native plane creatures are permanently banished if concentration is held).',
    classes: ['cleric', 'paladin', 'sorcerer', 'warlock', 'wizard'],
    concentration: true,
    ritual: false,
    targets: 'One creature you can see within range',
    fullDescription:
      'You attempt to send one creature that you can see within range to another plane of existence. The target must succeed on a Charisma saving throw or be banished. If the target is native to the plane of existence you\'re on, you banish the target to a harmless demiplane. While there, the target is incapacitated. The target remains there until the spell ends, at which point the target reappears in the space it left or in the nearest unoccupied space if that space is occupied. If the target is native to a different plane of existence than the one you\'re on, the target is banished with a faint popping noise, returning to its home plane. If the spell ends before 1 minute has passed, the target reappears in the space it left or in the nearest unoccupied space. Otherwise, the target doesn\'t return.',
    higherLevels: 'When you cast this spell using a spell slot of 5th level or higher, you can target one additional creature for each slot level above 4th.',
    mechanicalEffects: ['incapacitated'],
    source: 'srd-5.2',
  },
  {
    name: 'Blight',
    level: 4,
    school: 'Necromancy',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    saveAbility: 'con',
    damage: '8d8',
    notes: 'Con save for half necrotic damage. Plants and undead are unaffected or affected differently.',
    classes: ['druid', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Compulsion',
    level: 4,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    notes: 'Wis save or you choose which direction the creature moves each turn (can still act). Repeats save each turn.',
    classes: ['bard'],
  },
  {
    name: 'Confusion',
    level: 4,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '90 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    notes: 'Wis save or confused for duration (roll d10 for random action). Repeats save each turn.',
    classes: ['bard', 'druid', 'sorcerer', 'wizard'],
  },
  {
    name: 'Conjure Minor Elementals',
    level: 4,
    school: 'Conjuration',
    castingTime: '1 minute',
    range: '90 feet',
    components: 'V, S',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Summon elementals: one CR 2, two CR 1, four CR 1/2, or eight CR 1/4.',
    classes: ['druid', 'wizard'],
  },
  {
    name: 'Conjure Woodland Beings',
    level: 4,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Summon fey creatures: one CR 2, two CR 1, four CR 1/2, or eight CR 1/4.',
    classes: ['druid', 'ranger'],
  },
  {
    name: 'Control Water',
    level: 4,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '300 feet',
    components: 'V, S, M',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Control water in a 100-ft cube: Flood, Part Water, Redirect Flow, or Whirlpool (Str save or 2d8 damage).',
    classes: ['cleric', 'druid', 'wizard'],
  },
  {
    name: 'Death Ward',
    level: 4,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: '8 hours',
    notes: 'First time the creature would drop to 0 HP, it drops to 1 HP instead (expends the ward).',
    classes: ['cleric', 'paladin'],
  },
  {
    name: 'Dimension Door',
    level: 4,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '500 feet',
    components: 'V',
    duration: 'Instantaneous',
    notes: 'Teleport yourself and one willing creature to a location within 500 ft.',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Divination',
    level: 4,
    school: 'Divination',
    castingTime: '1 action (ritual)',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Ask one question about a goal, event, or activity within 7 days. DM gives a truthful omen.',
    classes: ['cleric', 'druid'],
  },
  {
    name: 'Dominate Beast',
    level: 4,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    notes: 'Wis save or charmed and telepathically controlled. Repeats save each time it takes damage.',
    classes: ['druid', 'sorcerer'],
  },
  {
    name: "Evard's Black Tentacles",
    level: 4,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '90 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'dex',
    damage: '3d6',
    notes: 'Tentacles fill 20-ft square (difficult terrain). Dex save or restrained and 3d6 bludgeoning at start of each turn.',
    classes: ['wizard'],
  },
  {
    name: 'Fire Shield',
    level: 4,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S, M',
    duration: '10 minutes',
    damage: '2d8',
    notes: 'Warm (cold resistance, 2d8 fire to melee attackers) or Chill (fire resistance, 2d8 cold to melee attackers) shield.',
    classes: ['wizard'],
  },
  {
    name: 'Freedom of Movement',
    level: 4,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 hour',
    notes: 'Ignore difficult terrain, and spells/effects cannot reduce speed or paralyze/restrain the creature.',
    classes: ['bard', 'cleric', 'druid', 'ranger'],
  },
  {
    name: 'Giant Insect',
    level: 4,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Transform up to 10 centipedes, 3 wasps, 5 beetles, or 1 spider into giant versions under your control.',
    classes: ['druid'],
  },
  {
    name: 'Greater Invisibility',
    level: 4,
    school: 'Illusion',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    notes: 'Target stays invisible even while attacking or casting spells.',
    classes: ['bard', 'sorcerer', 'wizard'],
  },
  {
    name: 'Guardian of Faith',
    level: 4,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V',
    duration: '8 hours',
    saveAbility: 'dex',
    damage: '20',
    notes: 'Large spectral guardian attacks hostile creatures within 10 ft: Dex save or 20 radiant damage (save = half).',
    classes: ['cleric'],
  },
  {
    name: 'Hallucinatory Terrain',
    level: 4,
    school: 'Illusion',
    castingTime: '10 minutes',
    range: '300 feet',
    components: 'V, S, M',
    duration: '24 hours',
    notes: 'Make a 150-ft cube of natural terrain look, sound, and smell like a different type of natural terrain.',
    classes: ['bard', 'druid', 'warlock', 'wizard'],
  },
  {
    name: 'Ice Storm',
    level: 4,
    school: 'Evocation',
    castingTime: '1 action',
    range: '300 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    saveAbility: 'dex',
    damage: '2d8+4d6',
    notes: 'Hailstones hit 20-ft radius, 40-ft cylinder. Dex save for bludgeoning + cold damage (half on success). Difficult terrain afterward.',
    upcastDamage: '1d8',
    classes: ['druid', 'sorcerer', 'wizard'],
  },
  {
    name: "Leomund's Secret Chest",
    level: 4,
    school: 'Conjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Hide a chest on the Ethereal Plane. Recall it as an action.',
    classes: ['wizard'],
  },
  {
    name: 'Locate Creature',
    level: 4,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Know the direction to a specific creature or species within 1000 ft (blocked by running water).',
    classes: ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'wizard'],
  },
  {
    name: "Mordenkainen's Private Sanctum",
    level: 4,
    school: 'Abjuration',
    castingTime: '10 minutes',
    range: '120 feet',
    components: 'V, S, M',
    duration: '24 hours',
    notes: 'Protect an area (5 to 100 ft cube): no sound in/out, opaque, teleportation blocked, divination blocked.',
    classes: ['wizard'],
  },
  {
    name: "Otiluke's Resilient Sphere",
    level: 4,
    school: 'Evocation',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'dex',
    notes: 'Dex save or enclosed in a 10-ft sphere (nothing in or out). Creature rolls to move. Sphere is immune to damage.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Phantasmal Killer',
    level: 4,
    school: 'Illusion',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    damage: '4d10',
    notes: 'Wis save or frightened. Takes 4d10 psychic at end of each turn (save for half). Ends on successful save.',
    classes: ['wizard'],
  },
  {
    name: 'Polymorph',
    level: 4,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    saveAbility: 'wis',
    notes: 'Transform creature into a beast of equal or lower CR. Reverts if reduced to 0 HP.',
    classes: ['bard', 'druid', 'sorcerer', 'wizard'],
    concentration: true,
    ritual: false,
    targets: 'One creature you can see within range',
    fullDescription:
      'This spell transforms a creature that you can see within range into a new form. An unwilling creature must make a Wisdom saving throw to avoid the effect. The spell has no effect on a shapechanger or a creature with 0 hit points. The transformation lasts for the duration, or until the target drops to 0 hit points or dies. The new form can be any beast whose challenge rating is equal to or less than the target\'s (or the target\'s level, if it doesn\'t have a challenge rating). The target\'s game statistics, including mental ability scores, are replaced by the statistics of the chosen beast. The target retains its alignment and personality. The target assumes the hit points of its new form, and when it reverts, the creature returns to the number of hit points it had before it transformed. If it reverts as a result of dropping to 0 hit points, any excess damage carries over.',
    source: 'srd-5.2',
  },
  {
    name: 'Stone Shape',
    level: 4,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Reshape a Medium-sized stone into any form, or create a door, window, or passage.',
    classes: ['cleric', 'druid', 'wizard'],
  },
  {
    name: 'Stoneskin',
    level: 4,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Target gains resistance to bludgeoning, piercing, and slashing damage from nonmagical attacks.',
    classes: ['druid', 'ranger', 'sorcerer', 'wizard'],
  },
  {
    name: 'Wall of Fire',
    level: 4,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'dex',
    damage: '5d8',
    notes: 'Create a wall of fire (60 × 20 × 1 ft or ring 20 ft diameter). Dex save for fire damage on the specified side.',
    damageType: 'fire',
    upcastDamage: '1d8',
    classes: ['druid', 'sorcerer', 'wizard'],
    concentration: true,
    ritual: false,
    targets: 'Creatures within 10 ft of the wall',
    fullDescription:
      'You create a wall of fire on a solid surface within range. You can make the wall up to 60 feet long, 20 feet high, and 1 foot thick, or a ringed wall up to 20 feet in diameter, 20 feet high, and 1 foot thick. The wall is opaque and lasts for the duration. When the wall appears, each creature within its area must make a Dexterity saving throw. On a failed save, a creature takes 5d8 fire damage, or half as much damage on a successful save. One side of the wall, selected by you when you cast this spell, deals 5d8 fire damage to each creature that ends its turn within 10 feet of that side or inside the wall. A creature takes the same damage when it enters the wall for the first time on a turn or ends its turn there. The other side of the wall deals no damage.',
    higherLevels: 'When you cast this spell using a spell slot of 5th level or higher, the damage increases by 1d8 for each slot level above 4th.',
    areaOfEffect: { shape: 'line', sizeFt: 60, widthFt: 1, heightFt: 20 },
    source: 'srd-5.2',
  },
]
