// 1st-level spells — full SRD 5.1 list

import type { SrdSpell } from './types'

export const LEVEL1_SPELLS: SrdSpell[] = [
  {
    name: 'Alarm',
    level: 1,
    school: 'Abjuration',
    castingTime: '1 minute (ritual)',
    range: '30 feet',
    components: 'V, S, M',
    duration: '8 hours',
    notes: 'Set an alarm against unwanted intrusion in an area up to 20-ft cube. Mental or audible alarm when triggered.',
    classes: ['ranger', 'wizard'],
  },
  {
    name: 'Animal Friendship',
    level: 1,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: '24 hours',
    saveAbility: 'wis',
    notes: 'Wis save or beast is charmed by you. No effect if Intelligence is 4 or higher.',
    classes: ['bard', 'druid', 'ranger'],
  },
  {
    name: 'Bane',
    level: 1,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'cha',
    notes: 'Up to 3 creatures subtract 1d4 from attack rolls and saving throws on a failed Cha save.',
    classes: ['bard', 'cleric'],
    concentration: true,
    ritual: false,
    targets: 'Up to three creatures within range',
    fullDescription:
      'Up to three creatures of your choice that you can see within range must make a Charisma saving throw. Whenever a target that fails this saving throw makes an attack roll or a saving throw before the spell ends, the target must roll a d4 and subtract the number rolled from the attack roll or saving throw.',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.',
    source: 'srd-5.2',
  },
  {
    name: 'Bless',
    level: 1,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    concentration: true,
    ritual: false,
    classes: ['cleric', 'paladin'],
    targets: 'Up to three creatures within range',
    notes: 'Up to 3 creatures add 1d4 to attack rolls and saving throws.',
    fullDescription:
      'You bless up to three creatures of your choice within range. Whenever a target makes an attack roll or a saving throw before the spell ends, the target can roll a d4 and add the number rolled to the attack roll or saving throw.',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.',
    source: 'srd-5.2',
  },
  {
    name: 'Burning Hands',
    level: 1,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Self (15-foot cone)',
    components: 'V, S',
    duration: 'Instantaneous',
    saveAbility: 'dex',
    damage: '3d6',
    damageType: 'fire',
    notes: 'Dex save for half, fire damage.',
    upcastDamage: '1d6',
    classes: ['sorcerer', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'Each creature in a 15-ft cone',
    fullDescription:
      'As you hold your hands with thumbs touching and fingers spread, a thin sheet of flames shoots forth from your outstretched fingertips. Each creature in a 15-foot cone must make a Dexterity save. A creature takes 3d6 fire damage on a failed save, or half as much damage on a successful one. The fire ignites any flammable objects in the area that aren\'t being worn or carried.',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.',
    areaOfEffect: { shape: 'cone', sizeFt: 15 },
    source: 'srd-5.2',
  },
  {
    name: 'Charm Person',
    level: 1,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: '1 hour',
    saveAbility: 'wis',
    notes: 'Wis save or humanoid is charmed by you. It knows it was charmed when the spell ends.',
    classes: ['bard', 'druid', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Color Spray',
    level: 1,
    school: 'Illusion',
    castingTime: '1 action',
    range: 'Self (15-foot cone)',
    components: 'V, S, M',
    duration: '1 round',
    damage: '6d10',
    notes: 'Blind creatures with up to that many combined HP (lowest first) until end of your next turn. No attack roll or save.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Command',
    level: 1,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V',
    duration: '1 round',
    saveAbility: 'wis',
    notes: 'Wis save or creature follows a one-word command: Approach, Drop, Flee, Grovel, Halt.',
    classes: ['cleric', 'paladin'],
  },
  {
    name: 'Comprehend Languages',
    level: 1,
    school: 'Divination',
    castingTime: '1 action (ritual)',
    range: 'Self',
    components: 'V, S, M',
    duration: '1 hour',
    notes: 'Understand literal meaning of any spoken language or written language you see.',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Create or Destroy Water',
    level: 1,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Create up to 10 gallons of water or destroy water in an open container.',
    classes: ['cleric', 'druid'],
  },
  {
    name: 'Cure Wounds',
    level: 1,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Instantaneous',
    damage: '1d8+3',
    notes: 'Heals instead of damage; use the roller for the amount.',
    upcastDamage: '1d8',
    classes: ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'artificer'],
    concentration: false,
    ritual: false,
    targets: 'A creature you touch',
    fullDescription:
      'A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d8 for each slot level above 1st.',
    source: 'srd-5.2',
  },
  {
    name: 'Detect Evil and Good',
    level: 1,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Know if an aberration, celestial, elemental, fey, fiend, or undead is within 30 ft, and where.',
    classes: ['cleric', 'paladin'],
  },
  {
    name: 'Detect Magic',
    level: 1,
    school: 'Divination',
    castingTime: '1 action (ritual)',
    range: 'Self',
    components: 'V, S',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Sense the presence and school of magic within 30 ft.',
    classes: ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'sorcerer', 'wizard'],
  },
  {
    name: 'Detect Poison and Disease',
    level: 1,
    school: 'Divination',
    castingTime: '1 action (ritual)',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Sense the presence and location of poisons, poisonous creatures, and diseases within 30 ft.',
    classes: ['cleric', 'druid', 'paladin', 'ranger'],
  },
  {
    name: 'Disguise Self',
    level: 1,
    school: 'Illusion',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: '1 hour',
    notes: 'Change appearance of your body and equipment. Investigation vs. spell save DC to discern.',
    classes: ['bard', 'sorcerer', 'wizard'],
  },
  {
    name: 'Divine Favor',
    level: 1,
    school: 'Evocation',
    castingTime: '1 bonus action',
    range: 'Self',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    damage: '1d4',
    notes: 'Your weapon attacks deal an extra 1d4 radiant damage.',
    classes: ['paladin'],
  },
  {
    name: 'Entangle',
    level: 1,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '90 feet',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'str',
    notes: 'Str save or restrained in a 20-ft square of grasping plants. Creatures can repeat the save each turn.',
    classes: ['druid'],
  },
  {
    name: 'Expeditious Retreat',
    level: 1,
    school: 'Transmutation',
    castingTime: '1 bonus action',
    range: 'Self',
    components: 'V, S',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Take the Dash action as a bonus action on each of your turns.',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Faerie Fire',
    level: 1,
    school: 'Evocation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'dex',
    notes: 'Dex save or outlined in blue/green/violet light. Attacks against lit creatures have advantage; they cannot benefit from invisibility.',
    classes: ['bard', 'druid', 'artificer'],
    concentration: true,
    ritual: false,
    targets: 'Each creature in a 20-ft cube',
    fullDescription:
      'Each object in a 20-foot cube within range is outlined in blue, green, or violet light (your choice). Any creature in the area when the spell is cast is also outlined in light if it fails a Dexterity saving throw. For the duration, objects and affected creatures shed dim light in a 10-foot radius. Any attack roll against an affected creature or object has advantage if the attacker can see it, and the affected creature or object can\'t benefit from being invisible.',
    areaOfEffect: { shape: 'cube', sizeFt: 20 },
    source: 'srd-5.2',
  },
  {
    name: 'False Life',
    level: 1,
    school: 'Necromancy',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S, M',
    duration: '1 hour',
    damage: '1d4+4',
    notes: 'Bolster yourself with necromantic energy, gaining temporary hit points.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Feather Fall',
    level: 1,
    school: 'Transmutation',
    castingTime: '1 reaction',
    range: '60 feet',
    components: 'V, M',
    duration: '1 minute',
    notes: 'Up to 5 falling creatures descend 60 ft per round and take no fall damage.',
    classes: ['bard', 'sorcerer', 'wizard'],
  },
  {
    name: 'Find Familiar',
    level: 1,
    school: 'Conjuration',
    castingTime: '1 hour (ritual)',
    range: '10 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Summon a familiar (spirit taking animal form). Can deliver touch spells and share senses.',
    classes: ['wizard'],
  },
  {
    name: 'Fog Cloud',
    level: 1,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Up to 1 hour (concentration)',
    notes: '20-ft radius sphere of fog; heavily obscures the area.',
    classes: ['druid', 'ranger', 'sorcerer', 'wizard'],
  },
  {
    name: 'Goodberry',
    level: 1,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Up to 10 berries appear; each heals 1 HP and provides nourishment for a day.',
    classes: ['druid', 'ranger'],
  },
  {
    name: 'Grease',
    level: 1,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: '1 minute',
    saveAbility: 'dex',
    notes: 'Slick grease covers a 10-ft square. Dex save or fall prone when entering or starting turn in the area.',
    classes: ['wizard'],
  },
  {
    name: 'Guiding Bolt',
    level: 1,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: '1 round',
    attackRoll: true,
    damage: '4d6',
    damageType: 'radiant',
    notes: 'Ranged spell attack, radiant damage. Next attack against the target has advantage.',
    upcastDamage: '1d6',
    classes: ['cleric'],
    concentration: false,
    ritual: false,
    targets: 'One creature within range',
    fullDescription:
      'A flash of light streaks toward a creature of your choice within range. Make a ranged spell attack against the target. On a hit, the target takes 4d6 radiant damage, and the next attack roll made against this target before the end of your next turn has advantage, thanks to the mystical dim light glittering on the target until then.',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.',
    source: 'srd-5.2',
  },
  {
    name: 'Healing Word',
    level: 1,
    school: 'Evocation',
    castingTime: '1 bonus action',
    range: '60 feet',
    components: 'V',
    duration: 'Instantaneous',
    damage: '1d4+3',
    notes: 'Restore HP as a bonus action.',
    upcastDamage: '1d4',
    classes: ['bard', 'cleric', 'druid'],
    concentration: false,
    ritual: false,
    targets: 'A creature within 60 ft',
    fullDescription:
      'A creature of your choice that you can see within range regains hit points equal to 1d4 + your spellcasting ability modifier. This spell has no effect on undead or constructs.',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d4 for each slot level above 1st.',
    source: 'srd-5.2',
  },
  {
    name: 'Heroism',
    level: 1,
    school: 'Enchantment',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    notes: 'Willing creature is immune to being frightened and gains temp HP equal to your spellcasting modifier at the start of each turn.',
    classes: ['bard', 'paladin'],
  },
  {
    name: 'Hideous Laughter',
    level: 1,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    notes: 'Wis save or creature falls prone, incapacitated with laughter. Repeats save at end of each turn and when damaged.',
    classes: ['bard', 'wizard'],
  },
  {
    name: "Hunter's Mark",
    level: 1,
    school: 'Divination',
    castingTime: '1 bonus action',
    range: '90 feet',
    components: 'V',
    duration: 'Up to 1 hour (concentration)',
    damage: '1d6',
    notes: "Mark a creature; deal extra 1d6 damage on hits against it, and have advantage on Perception and Survival checks to find it.",
    classes: ['ranger'],
  },
  {
    name: 'Identify',
    level: 1,
    school: 'Divination',
    castingTime: '1 minute (ritual)',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: "Learn an item's magical properties and how to use them, or learn what spells are affecting a creature.",
    classes: ['bard', 'wizard'],
  },
  {
    name: 'Illusory Script',
    level: 1,
    school: 'Illusion',
    castingTime: '1 minute (ritual)',
    range: 'Touch',
    components: 'S, M',
    duration: '10 days',
    notes: 'Writing appears normal to you and designated readers; others see gibberish or a different message.',
    classes: ['bard', 'warlock', 'wizard'],
  },
  {
    name: 'Inflict Wounds',
    level: 1,
    school: 'Necromancy',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Instantaneous',
    attackRoll: true,
    damage: '3d10',
    notes: 'Melee spell attack, necrotic damage.',
    upcastDamage: '1d10',
    classes: ['cleric'],
  },
  {
    name: 'Jump',
    level: 1,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 minute',
    notes: "Triple a creature's jump distance.",
    classes: ['druid', 'ranger', 'sorcerer', 'wizard'],
  },
  {
    name: 'Longstrider',
    level: 1,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 hour',
    notes: "Increase a creature's speed by 10 ft.",
    classes: ['bard', 'druid', 'ranger', 'wizard'],
  },
  {
    name: 'Mage Armor',
    level: 1,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: '8 hours',
    notes: "Willing creature's AC becomes 13 + Dex modifier (if not wearing armor).",
    classes: ['sorcerer', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'A willing creature you touch (not wearing armor)',
    fullDescription:
      'You touch a willing creature who isn\'t wearing armor, and a protective magical force surrounds it until the spell ends. The target\'s base AC becomes 13 + its Dexterity modifier. The spell ends if the target dons armor or if you dismiss the spell as an action.',
    source: 'srd-5.2',
  },
  {
    name: 'Magic Missile',
    level: 1,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    damage: '3d4+3',
    damageType: 'force',
    notes: 'Three darts, each auto-hitting for 1d4+1 force damage.',
    upcastDamage: '1d4+1',
    upcastNotes: 'Adds one dart per slot level above 1st.',
    classes: ['sorcerer', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'Up to three creatures you can see within range',
    fullDescription:
      'You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4 + 1 force damage to its target. The darts all strike simultaneously, and you can direct them to hit one creature or several. Magic Missile cannot miss.',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the spell creates one more dart for each slot level above 1st.',
    source: 'srd-5.2',
  },
  {
    name: 'Protection from Evil and Good',
    level: 1,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Protection against aberrations, celestials, elementals, fey, fiends, and undead: attacks have disadvantage, immunity to charm/fright/possession.',
    classes: ['cleric', 'paladin', 'warlock', 'wizard'],
  },
  {
    name: 'Purify Food and Drink',
    level: 1,
    school: 'Transmutation',
    castingTime: '1 action (ritual)',
    range: '10 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    notes: 'All nonmagical food and drink in a 5-ft radius sphere is purified and cleansed of poison and disease.',
    classes: ['cleric', 'druid', 'paladin'],
  },
  {
    name: 'Ray of Sickness',
    level: 1,
    school: 'Necromancy',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    attackRoll: true,
    damage: '2d8',
    notes: 'Ranged spell attack, poison damage. On hit, Con save or poisoned until end of your next turn.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Sanctuary',
    level: 1,
    school: 'Abjuration',
    castingTime: '1 bonus action',
    range: '30 feet',
    components: 'V, S, M',
    duration: '1 minute',
    saveAbility: 'wis',
    notes: "Ward a creature; attackers must make a Wis save or choose a new target. Ends if the warded creature attacks or casts a harmful spell.",
    classes: ['cleric'],
  },
  {
    name: 'Shield',
    level: 1,
    school: 'Abjuration',
    castingTime: '1 reaction',
    range: 'Self',
    components: 'V, S',
    duration: '1 round',
    notes: '+5 to AC until start of your next turn, including triggering attack. Also immune to Magic Missile.',
    classes: ['sorcerer', 'wizard', 'warlock'],
    concentration: false,
    ritual: false,
    targets: 'Self',
    fullDescription:
      'An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from Magic Missile. Cast as a reaction when you are hit by an attack or targeted by the Magic Missile spell.',
    source: 'srd-5.2',
  },
  {
    name: 'Shield of Faith',
    level: 1,
    school: 'Abjuration',
    castingTime: '1 bonus action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 10 minutes (concentration)',
    notes: '+2 bonus to AC for one creature.',
    classes: ['cleric', 'paladin'],
  },
  {
    name: 'Silent Image',
    level: 1,
    school: 'Illusion',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Create a visual illusion up to 15-ft cube. Investigation vs. spell save DC to discern.',
    classes: ['bard', 'sorcerer', 'wizard'],
  },
  {
    name: 'Sleep',
    level: 1,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '90 feet',
    components: 'V, S, M',
    duration: '1 minute',
    damage: '5d8',
    notes: 'Creatures within 20-ft radius with lowest HP fall unconscious (total HP affected = 5d8). No save.',
    upcastDamage: '2d8',
    classes: ['bard', 'sorcerer', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'Creatures in a 20-ft radius',
    fullDescription:
      'This spell sends creatures into a magical slumber. Roll 5d8; the total is how many hit points of creatures this spell can affect. Creatures within 20 feet of a point you choose within range are affected in ascending order of their current hit points (ignoring unconscious creatures). Starting with the creature that has the lowest current hit points, each creature affected by this spell falls unconscious until the spell ends, the sleeper takes damage, or someone uses an action to shake or slap the sleeper awake. Subtract each creature\'s hit points from the total before moving on to the creature with the next lowest hit points. Undead and creatures immune to being charmed aren\'t affected by this spell.',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, roll an additional 2d8 for each slot level above 1st.',
    areaOfEffect: { shape: 'sphere', sizeFt: 20 },
    mechanicalEffects: ['unconscious'],
    source: 'srd-5.2',
  },
  {
    name: 'Speak with Animals',
    level: 1,
    school: 'Divination',
    castingTime: '1 action (ritual)',
    range: 'Self',
    components: 'V, S',
    duration: '10 minutes',
    notes: 'Comprehend and verbally communicate with beasts.',
    classes: ['bard', 'druid', 'ranger'],
  },
  {
    name: 'Thunderwave',
    level: 1,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Self (15-foot cube)',
    components: 'V, S',
    duration: 'Instantaneous',
    saveAbility: 'con',
    damage: '2d8',
    damageType: 'thunder',
    notes: 'Con save or take thunder damage and be pushed 10 ft. Loud boom audible 300 ft away.',
    upcastDamage: '1d8',
    classes: ['bard', 'druid', 'sorcerer', 'wizard'],
    concentration: false,
    ritual: false,
    targets: 'Each creature in a 15-ft cube originating from you',
    fullDescription:
      'A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube originating from you must make a Constitution saving throw. On a failed save, a creature takes 2d8 thunder damage and is pushed 10 feet away from you. On a successful save, the creature takes half as much damage and isn\'t pushed. In addition, unsecured objects that are completely within the area of effect are automatically pushed 10 feet away from you, and the spell emits a thunderous boom audible out to 300 feet.',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d8 for each slot level above 1st.',
    areaOfEffect: { shape: 'cube', sizeFt: 15 },
    source: 'srd-5.2',
  },
  {
    name: 'Unseen Servant',
    level: 1,
    school: 'Conjuration',
    castingTime: '1 action (ritual)',
    range: '60 feet',
    components: 'V, S, M',
    duration: '1 hour',
    notes: 'Summon an invisible, mindless force that performs simple tasks within 60 ft. STR 2, cannot attack or carry more than 10 lb.',
    classes: ['bard', 'warlock', 'wizard'],
  },
  {
    name: 'Witch Bolt',
    level: 1,
    school: 'Evocation',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    attackRoll: true,
    damage: '1d12',
    notes: 'Ranged spell attack, lightning damage. On subsequent turns, use action to deal 1d12 lightning damage automatically.',
    upcastDamage: '1d12',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Wrathful Smite',
    level: 1,
    school: 'Evocation',
    castingTime: '1 bonus action',
    range: 'Self',
    components: 'V',
    duration: 'Up to 1 minute (concentration)',
    damage: '1d6',
    notes: 'Next weapon hit deals extra 1d6 psychic damage and target must make Wis save or be frightened.',
    classes: ['paladin'],
  },
]
