// 9th-level spells — full SRD 5.1 list

import type { SrdSpell } from './types'

export const LEVEL9_SPELLS: SrdSpell[] = [
  {
    name: 'Astral Projection',
    level: 9,
    school: 'Necromancy',
    castingTime: '1 hour',
    range: '10 feet',
    components: 'V, S, M',
    duration: 'Special',
    notes: 'Project yourself and up to 8 willing creatures into the Astral Plane with astral bodies. Your body remains inert until you return.',
    classes: ['cleric', 'warlock', 'wizard'],
  },
  {
    name: 'Foresight',
    level: 9,
    school: 'Divination',
    castingTime: '1 minute',
    range: 'Touch',
    components: 'V, S, M',
    duration: '8 hours',
    notes: 'Target cannot be surprised, has advantage on attacks/checks/saves, and attacks against it have disadvantage.',
    classes: ['bard', 'druid', 'warlock', 'wizard'],
  },
  {
    name: 'Gate',
    level: 9,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    notes: 'Open a circular portal (5–20 ft) to another plane. A named specific entity may be called to pass through.',
    classes: ['cleric', 'sorcerer', 'wizard'],
  },
  {
    name: 'Imprisonment',
    level: 9,
    school: 'Abjuration',
    castingTime: '1 minute',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Until dispelled',
    saveAbility: 'wis',
    notes: 'Wis save or imprisoned. Choose form: Burial, Chaining, Hedged Prison, Minimus Containment, Slumber.',
    classes: ['warlock', 'wizard'],
  },
  {
    name: 'Invulnerability',
    level: 9,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'You are immune to all damage for the duration.',
    classes: ['wizard'],
  },
  {
    name: 'Mass Heal',
    level: 9,
    school: 'Evocation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    damage: '700',
    notes: 'Restore up to 700 HP total among creatures you choose. Also ends blindness, deafness, and diseases.',
    classes: ['cleric'],
  },
  {
    name: 'Meteor Swarm',
    level: 9,
    school: 'Evocation',
    castingTime: '1 action',
    range: '1 mile',
    components: 'V, S',
    duration: 'Instantaneous',
    saveAbility: 'dex',
    damage: '40d6',
    notes: 'Four meteors each deal 20d6 fire + 20d6 bludgeoning in 40-ft radius (Dex save for half). Can target the same or different points.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Power Word Heal',
    level: 9,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V',
    duration: 'Instantaneous',
    notes: 'Restore all HP. Also ends charmed, frightened, paralyzed, stunned conditions and grants spend up to all hit dice.',
    classes: ['bard', 'cleric'],
  },
  {
    name: 'Power Word Kill',
    level: 9,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V',
    duration: 'Instantaneous',
    notes: 'If target has 100 HP or fewer, it dies instantly. No save.',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Prismatic Wall',
    level: 9,
    school: 'Abjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: '10 minutes',
    saveAbility: 'dex',
    damage: '50d6',
    notes: 'Seven-layered wall (plane or sphere): each layer has a color, damage type, and is dispelled differently. Touching it triggers all layers.',
    classes: ['wizard'],
  },
  {
    name: 'Shapechange',
    level: 9,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Transform into any creature of your CR or lower (including legendary creatures). Keep your mental scores and class features.',
    classes: ['druid', 'wizard'],
  },
  {
    name: 'Storm of Vengeance',
    level: 9,
    school: 'Conjuration',
    castingTime: '1 action',
    range: 'Sight',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'con',
    damage: '2d6',
    notes: 'Thunderstorm (360-ft radius): each round different effects (deafened, lightning, acid, hail). Con save for 2d6 thunder on rounds 2+.',
    classes: ['druid'],
  },
  {
    name: 'Time Stop',
    level: 9,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Self',
    components: 'V',
    duration: 'Instantaneous',
    notes: 'Gain 1d4+1 extra turns. Time resumes if you move >1000 ft away or affect another creature.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'True Polymorph',
    level: 9,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    saveAbility: 'wis',
    notes: 'Transform a creature into any other creature/object, or an object into a creature. Wis save to resist. Permanent if concentration lasts full duration.',
    classes: ['bard', 'warlock', 'wizard'],
  },
  {
    name: 'True Resurrection',
    level: 9,
    school: 'Necromancy',
    castingTime: '1 hour',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Return a creature dead up to 200 years to life. Can recreate the body even if it no longer exists. No penalties.',
    classes: ['cleric', 'druid'],
  },
  {
    name: 'Weird',
    level: 9,
    school: 'Illusion',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    damage: '4d10',
    notes: 'Wis save or frightened. While frightened, takes 4d10 psychic at start of each turn (save for half). Repeats save each turn to end.',
    classes: ['wizard'],
  },
  {
    name: 'Wish',
    level: 9,
    school: 'Conjuration',
    castingTime: '1 action',
    range: 'Self',
    components: 'V',
    duration: 'Instantaneous',
    notes: 'Reshape reality as you desire with risks for going beyond duplicating lower spells. No standard save/damage; DM adjudication.',
    classes: ['sorcerer', 'wizard'],
  },
]
