// 5th-level spells — full SRD 5.1 list

import type { SrdSpell } from './types'

export const LEVEL5_SPELLS: SrdSpell[] = [
  {
    name: 'Animate Objects',
    level: 5,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    notes: 'Animate up to 10 nonmagical objects (Tiny=+8 atk/1d4+4; up to Huge=+6 atk/2d12+2). Bonus action to command.',
    classes: ['bard', 'sorcerer', 'wizard'],
  },
  {
    name: 'Antilife Shell',
    level: 5,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Self (10-foot radius)',
    components: 'V, S',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Shimmering barrier prevents living creatures (not undead/constructs) from entering or passing through.',
    classes: ['druid'],
  },
  {
    name: 'Awaken',
    level: 5,
    school: 'Transmutation',
    castingTime: '8 hours',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Grant a beast or plant an Intelligence of 10 and ability to speak one language.',
    classes: ['bard', 'druid'],
  },
  {
    name: 'Banishing Smite',
    level: 5,
    school: 'Abjuration',
    castingTime: '1 bonus action',
    range: 'Self',
    components: 'V',
    duration: 'Up to 1 minute (concentration)',
    damage: '5d10',
    notes: 'Next weapon hit adds 5d10 force damage. If this drops the target to 50 HP or fewer, it is banished.',
    classes: ['paladin'],
  },
  {
    name: 'Bigby\'s Hand',
    level: 5,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    notes: 'Large hand: Clenched Fist (4d8 force attack), Forceful Hand (push), Grasping Hand (grapple/squeeze 2d6+mod), Interposing Hand (half cover).',
    classes: ['wizard'],
  },
  {
    name: 'Circle of Power',
    level: 5,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Self (30-foot radius)',
    components: 'V',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Allies in range have advantage on saves against spells and magical effects; on a success vs. save-for-half they take no damage.',
    classes: ['paladin'],
  },
  {
    name: 'Cloudkill',
    level: 5,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Up to 10 minutes (concentration)',
    saveAbility: 'con',
    damage: '5d8',
    notes: 'Heavily obscured 20-ft radius cloud of poison. Con save or 5d8 poison damage at start of each turn (half on success). Moves 10 ft away from you each round.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Commune',
    level: 5,
    school: 'Divination',
    castingTime: '1 minute (ritual)',
    range: 'Self',
    components: 'V, S, M',
    duration: '1 minute',
    notes: 'Ask your deity three yes/no questions. Answers are truthful.',
    classes: ['cleric'],
  },
  {
    name: 'Commune with Nature',
    level: 5,
    school: 'Divination',
    castingTime: '1 minute (ritual)',
    range: 'Self',
    components: 'V, S',
    duration: 'Instantaneous',
    notes: 'Gain up to 3 facts about the surrounding territory (3-mile radius outdoors, 300-ft underground).',
    classes: ['druid', 'ranger'],
  },
  {
    name: 'Cone of Cold',
    level: 5,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Self (60-foot cone)',
    components: 'V, S, M',
    duration: 'Instantaneous',
    saveAbility: 'con',
    damage: '8d8',
    notes: 'Con save for half cold damage.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Conjure Elemental',
    level: 5,
    school: 'Conjuration',
    castingTime: '1 minute',
    range: '90 feet',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Summon an elemental of CR 5 or lower from the appropriate plane (air, earth, fire, or water).',
    classes: ['druid', 'wizard'],
  },
  {
    name: 'Conjure Volley',
    level: 5,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '150 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    saveAbility: 'dex',
    damage: '8d8',
    notes: 'Nonmagical ammunition rains down in a 40-ft radius, 20-ft tall cylinder. Dex save for half piercing/slashing damage.',
    classes: ['ranger'],
  },
  {
    name: 'Contact Other Plane',
    level: 5,
    school: 'Divination',
    castingTime: '1 minute (ritual)',
    range: 'Self',
    components: 'V',
    duration: '1 minute',
    notes: 'Contact a demigod or extraplanar being for 5 questions (yes/no or brief). Int save DC 15 or go insane for 1d10 days.',
    classes: ['warlock', 'wizard'],
  },
  {
    name: 'Contagion',
    level: 5,
    school: 'Necromancy',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: '7 days',
    attackRoll: true,
    notes: 'Melee spell attack; on hit, Con save at start of each turn for 3 turns. Three failures = fully infected with chosen disease.',
    classes: ['cleric', 'druid'],
  },
  {
    name: 'Creation',
    level: 5,
    school: 'Illusion',
    castingTime: '1 minute',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Special',
    notes: 'Create a nonliving object from shadow stuff (size and duration based on material type; vegetable matter lasts 1 day, metals 1 minute).',
    classes: ['bard', 'sorcerer', 'wizard'],
  },
  {
    name: 'Destructive Wave',
    level: 5,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Self (30-foot radius)',
    components: 'V',
    duration: 'Instantaneous',
    saveAbility: 'con',
    damage: '5d6',
    notes: 'Con save or 5d6 thunder + 5d6 radiant/necrotic damage and knocked prone (half damage on success).',
    classes: ['paladin'],
  },
  {
    name: 'Dispel Evil and Good',
    level: 5,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    notes: 'Aura disrupts aberrations, celestials, elementals, fey, fiends, undead. Options: Break Enchantment, Dismissal (Cha save or returned to native plane).',
    classes: ['cleric', 'paladin'],
  },
  {
    name: 'Dominate Person',
    level: 5,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    notes: 'Wis save or telepathically controlled. Repeats save when damaged.',
    classes: ['bard', 'sorcerer', 'wizard'],
  },
  {
    name: 'Dream',
    level: 5,
    school: 'Illusion',
    castingTime: '1 minute',
    range: 'Special',
    components: 'V, S, M',
    duration: '8 hours',
    saveAbility: 'wis',
    damage: '3d6',
    notes: 'Enter the dreams of a sleeping creature. Can be a pleasant message or a nightmare (Wis save or 3d6 psychic and no benefit from rest).',
    classes: ['bard', 'warlock', 'wizard'],
  },
  {
    name: 'Flame Strike',
    level: 5,
    school: 'Evocation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    saveAbility: 'dex',
    damage: '4d6',
    notes: 'Dex save for half in a 10-ft radius, 40-ft tall cylinder: 4d6 fire + 4d6 radiant damage.',
    classes: ['cleric'],
  },
  {
    name: 'Geas',
    level: 5,
    school: 'Enchantment',
    castingTime: '1 minute',
    range: '60 feet',
    components: 'V',
    duration: '30 days',
    saveAbility: 'wis',
    notes: 'Wis save or compelled to carry out a task. Takes 5d10 psychic damage for disobeying.',
    classes: ['bard', 'cleric', 'druid', 'paladin', 'wizard'],
  },
  {
    name: 'Greater Restoration',
    level: 5,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'End one: charmed, exhaustion (reduce by 1), petrified, cursed, one ability score reduction, max HP reduction.',
    classes: ['bard', 'cleric', 'druid'],
  },
  {
    name: 'Hold Monster',
    level: 5,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '90 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    notes: 'Wis save or paralyzed (any creature type). Repeats save each turn.',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Insect Plague',
    level: 5,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '300 feet',
    components: 'V, S, M',
    duration: 'Up to 10 minutes (concentration)',
    saveAbility: 'con',
    damage: '4d10',
    notes: 'Stinging insects fill a 20-ft radius sphere (heavily obscured). Con save for half piercing damage at start of each turn in the area.',
    classes: ['cleric', 'druid', 'sorcerer'],
  },
  {
    name: 'Legend Lore',
    level: 5,
    school: 'Divination',
    castingTime: '10 minutes',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Learn lore about a legendary person, place, or object. More detail for artifacts and famous items.',
    classes: ['bard', 'cleric', 'wizard'],
  },
  {
    name: 'Mass Cure Wounds',
    level: 5,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    damage: '3d8+3',
    notes: 'Up to 6 creatures each regain 3d8 + spellcasting modifier HP.',
    classes: ['bard', 'cleric', 'druid'],
  },
  {
    name: 'Mislead',
    level: 5,
    school: 'Illusion',
    castingTime: '1 action',
    range: 'Self',
    components: 'S',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Become invisible and create an illusory double. Use the double\'s senses; can speak and gesture through it.',
    classes: ['bard', 'wizard'],
  },
  {
    name: 'Modify Memory',
    level: 5,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    notes: 'Wis save or charmed; alter one memory from the last 24 hours (alter, suppress, eliminate, or implant).',
    classes: ['bard', 'wizard'],
  },
  {
    name: 'Passwall',
    level: 5,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: '1 hour',
    notes: 'Create a 5-ft wide, 8-ft tall, 20-ft deep passage through wood, stone, or plaster.',
    classes: ['wizard'],
  },
  {
    name: 'Planar Binding',
    level: 5,
    school: 'Abjuration',
    castingTime: '1 hour',
    range: '60 feet',
    components: 'V, S, M',
    duration: '24 hours',
    saveAbility: 'cha',
    notes: 'Bind a celestial, elemental, fey, or fiend. Cha save or bound to serve you for the duration.',
    classes: ['bard', 'cleric', 'druid', 'wizard'],
  },
  {
    name: 'Raise Dead',
    level: 5,
    school: 'Necromancy',
    castingTime: '1 hour',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Return a creature dead up to 10 days to 1 HP. Penalties (−4) to attacks, saves, ability checks until long rest.',
    classes: ['bard', 'cleric', 'paladin'],
  },
  {
    name: 'Reincarnate',
    level: 5,
    school: 'Transmutation',
    castingTime: '1 hour',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Soul of a creature dead up to 10 days inhabits a new body (random race on a d100 table).',
    classes: ['druid'],
  },
  {
    name: 'Scrying',
    level: 5,
    school: 'Divination',
    castingTime: '10 minutes',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Up to 10 minutes (concentration)',
    saveAbility: 'wis',
    notes: 'Wis save (modified by familiarity) or observe the target anywhere on the same plane through a magical sensor.',
    classes: ['bard', 'cleric', 'druid', 'warlock', 'wizard'],
  },
  {
    name: 'Seeming',
    level: 5,
    school: 'Illusion',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: '8 hours',
    saveAbility: 'wis',
    notes: 'Give any number of creatures a new appearance (size ±1 category). Investigation vs. spell save DC to discern.',
    classes: ['bard', 'sorcerer', 'wizard'],
  },
  {
    name: 'Swift Quiver',
    level: 5,
    school: 'Transmutation',
    castingTime: '1 bonus action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    notes: 'Quiver produces endless nonmagical ammunition. Make two ranged attacks as bonus action each turn.',
    classes: ['ranger'],
  },
  {
    name: 'Synaptic Static',
    level: 5,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    saveAbility: 'int',
    damage: '8d6',
    notes: 'Int save for half psychic damage in 20-ft sphere. Failures subtract 1d6 from attack rolls, ability checks, and concentration saves for 1 minute (repeat save each turn).',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Telekinesis',
    level: 5,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Up to 10 minutes (concentration)',
    saveAbility: 'str',
    notes: 'Move a Large or smaller object (up to 1000 lb) or creature (Str save to resist). Sustained fine manipulation also possible.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: "Rary's Telepathic Bond",
    level: 5,
    school: 'Divination',
    castingTime: '1 action (ritual)',
    range: '30 feet',
    components: 'V, S, M',
    duration: '1 hour',
    notes: 'Up to 8 willing creatures can communicate telepathically regardless of language across any distance (same plane).',
    classes: ['wizard'],
  },
  {
    name: 'Tree Stride',
    level: 5,
    school: 'Conjuration',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    notes: 'Enter a tree and teleport to another of the same species within 500 ft. Move twice per turn.',
    classes: ['cleric', 'druid', 'ranger'],
  },
  {
    name: 'Wall of Force',
    level: 5,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Invisible immune-to-damage wall of force (up to 10 panels 10 × 10 ft). Nothing passes through.',
    classes: ['wizard'],
  },
  {
    name: 'Wall of Stone',
    level: 5,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Create a wall of stone panels (up to 10 panels 10 × 10 × 6 in). Becomes permanent if concentration lasts full duration.',
    classes: ['cleric', 'druid', 'sorcerer', 'wizard'],
  },
]
