// 2nd-level spells — full SRD 5.1 list

import type { SrdSpell } from './types'

export const LEVEL2_SPELLS: SrdSpell[] = [
  {
    name: 'Aid',
    level: 2,
    school: 'Abjuration',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: '8 hours',
    notes: 'Up to 3 creatures gain +5 max and current HP for the duration.',
    classes: ['cleric', 'paladin'],
  },
  {
    name: 'Alter Self',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Transform yourself: Aquatic Adaptation, Change Appearance, or Natural Weapons (1d6 damage).',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Animal Messenger',
    level: 2,
    school: 'Enchantment',
    castingTime: '1 action (ritual)',
    range: '30 feet',
    components: 'V, S, M',
    duration: '24 hours',
    notes: 'Compel a Tiny beast to deliver a message to a target you describe.',
    classes: ['bard', 'druid', 'ranger'],
  },
  {
    name: 'Arcane Lock',
    level: 2,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Until dispelled',
    notes: 'A door, window, gate, or chest is magically locked. DC to break/pick increased by 10.',
    classes: ['wizard'],
  },
  {
    name: 'Augury',
    level: 2,
    school: 'Divination',
    castingTime: '1 minute (ritual)',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Receive an omen (weal, woe, weal and woe, or nothing) about a course of action within the next 30 minutes.',
    classes: ['cleric', 'druid'],
  },
  {
    name: 'Barkskin',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    notes: "Target's AC can't be less than 16 while not wearing heavy armor.",
    classes: ['druid', 'ranger'],
  },
  {
    name: 'Beast Sense',
    level: 2,
    school: 'Divination',
    castingTime: '1 action (ritual)',
    range: 'Touch',
    components: 'S',
    duration: 'Up to 1 hour (concentration)',
    notes: "Use a willing beast's senses (sight and hearing) instead of your own.",
    classes: ['druid', 'ranger'],
  },
  {
    name: 'Blindness/Deafness',
    level: 2,
    school: 'Necromancy',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V',
    duration: '1 minute',
    saveAbility: 'con',
    notes: 'Con save or blinded or deafened. Repeats save at end of each turn.',
    classes: ['bard', 'cleric', 'sorcerer', 'wizard'],
  },
  {
    name: 'Blur',
    level: 2,
    school: 'Illusion',
    castingTime: '1 action',
    range: 'Self',
    components: 'V',
    duration: 'Up to 1 minute (concentration)',
    notes: 'Your body becomes blurred; attack rolls against you have disadvantage unless the attacker uses another sense.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Branding Smite',
    level: 2,
    school: 'Evocation',
    castingTime: '1 bonus action',
    range: 'Self',
    components: 'V',
    duration: 'Up to 1 minute (concentration)',
    damage: '2d6',
    notes: 'Next weapon hit deals extra 2d6 radiant damage and the target becomes visible if invisible.',
    classes: ['paladin'],
  },
  {
    name: 'Calm Emotions',
    level: 2,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'cha',
    notes: 'Cha save or suppress charm/fear, or make creatures indifferent in a 20-ft radius.',
    classes: ['bard', 'cleric'],
  },
  {
    name: 'Cloud of Daggers',
    level: 2,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    damage: '4d4',
    notes: '5-ft cube filled with spinning daggers. Any creature that enters or starts its turn there takes 4d4 slashing damage.',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Continual Flame',
    level: 2,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Until dispelled',
    notes: 'Flame-like radiance erupts from an object; equivalent to torch light but produces no heat and cannot be smothered.',
    classes: ['cleric', 'wizard'],
  },
  {
    name: 'Cordon of Arrows',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '5 feet',
    components: 'V, S, M',
    duration: '8 hours',
    saveAbility: 'dex',
    damage: '1d6',
    notes: 'Plant 4 arrows; each fires at first creature that comes within 30 ft (Dex save or 1d6 piercing). Friendly creatures can be designated safe.',
    classes: ['ranger'],
  },
  {
    name: 'Crown of Madness',
    level: 2,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    notes: 'Wis save or charmed; must use action to attack nearest creature each turn. Repeat save at end of each turn.',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Darkness',
    level: 2,
    school: 'Evocation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, M',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Magical darkness in a 15-ft radius; even darkvision cannot penetrate it.',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Darkvision',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: '8 hours',
    notes: 'Grant a willing creature darkvision out to 60 ft.',
    classes: ['druid', 'ranger', 'sorcerer', 'wizard'],
  },
  {
    name: 'Detect Thoughts',
    level: 2,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    notes: 'Read the surface thoughts of creatures within 30 ft. Probing deeper requires a Wis save.',
    classes: ['bard', 'sorcerer', 'wizard'],
  },
  {
    name: "Dragon's Breath",
    level: 2,
    school: 'Transmutation',
    castingTime: '1 bonus action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'dex',
    damage: '3d6',
    notes: 'Touched creature can exhale a 15-ft cone of chosen damage type (acid, cold, fire, lightning, or poison) as an action.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Enhance Ability',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Grant one of: Bear\'s Endurance (con advantage + 2d6 temp HP), Bull\'s Strength (str advantage), Cat\'s Grace (dex advantage + no fall damage ≤20ft), Eagle\'s Splendor (cha advantage), Fox\'s Cunning (int advantage), Owl\'s Wisdom (wis advantage).',
    classes: ['bard', 'cleric', 'druid', 'sorcerer', 'wizard'],
  },
  {
    name: 'Enlarge/Reduce',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'con',
    notes: 'Enlarge: double size, advantage on Str, +1d4 damage. Reduce: halve size, disadvantage on Str, −1d4 damage.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Enthrall',
    level: 2,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: '1 minute',
    saveAbility: 'wis',
    notes: 'Wis save or creature has disadvantage on Perception checks not directed at you.',
    classes: ['bard', 'warlock'],
  },
  {
    name: 'Find Steed',
    level: 2,
    school: 'Conjuration',
    castingTime: '10 minutes',
    range: '30 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    notes: 'Summon a spirit as a loyal steed (warhorse, pony, camel, elk, or mastiff). Can share spells.',
    classes: ['paladin'],
  },
  {
    name: 'Find Traps',
    level: 2,
    school: 'Divination',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    notes: 'Sense if there are one or more traps within range. Does not reveal location, only presence.',
    classes: ['cleric', 'druid', 'ranger'],
  },
  {
    name: 'Flaming Sphere',
    level: 2,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'dex',
    damage: '2d6',
    notes: '5-ft diameter ball of fire; Dex save for fire damage at start of turn for adjacent creatures. Move sphere up to 30 ft as bonus action.',
    classes: ['druid', 'wizard'],
  },
  {
    name: 'Gentle Repose',
    level: 2,
    school: 'Necromancy',
    castingTime: '1 action (ritual)',
    range: 'Touch',
    components: 'V, S, M',
    duration: '10 days',
    notes: 'Preserve a corpse from decay; the time limit for resurrection spells does not advance.',
    classes: ['cleric', 'wizard'],
  },
  {
    name: 'Gust of Wind',
    level: 2,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Self (60-foot line)',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'str',
    notes: 'Str save or pushed 15 ft when entering/starting in line. Movement into the wind is halved.',
    classes: ['druid', 'sorcerer', 'wizard'],
  },
  {
    name: 'Heat Metal',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'con',
    damage: '2d8',
    notes: 'Metal object glows red-hot; creature in contact takes fire damage each turn (Con save or drop). Bonus action to reheat.',
    classes: ['bard', 'druid'],
  },
  {
    name: 'Hold Person',
    level: 2,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'wis',
    notes: 'Wis save or humanoid is paralyzed. Repeats save at end of each turn.',
    classes: ['bard', 'cleric', 'druid', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Invisibility',
    level: 2,
    school: 'Illusion',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Creature becomes invisible until it attacks or casts a spell.',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Knock',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V',
    duration: 'Instantaneous',
    notes: 'Open a locked, stuck, or held door, chest, shackles, or lock. Loud knock audible 300 ft away.',
    classes: ['bard', 'sorcerer', 'wizard'],
  },
  {
    name: 'Lesser Restoration',
    level: 2,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Instantaneous',
    notes: 'End one disease or one condition: blinded, deafened, paralyzed, or poisoned.',
    classes: ['bard', 'cleric', 'druid', 'paladin', 'ranger'],
  },
  {
    name: 'Levitate',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 10 minutes (concentration)',
    saveAbility: 'con',
    notes: 'Con save (unwilling). Rise/descend up to 20 ft per turn. Cannot move horizontally.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Locate Animals or Plants',
    level: 2,
    school: 'Divination',
    castingTime: '1 action (ritual)',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Instantaneous',
    notes: 'Know the direction and distance to the closest creature or plant of a specified kind within 5 miles.',
    classes: ['bard', 'druid', 'ranger'],
  },
  {
    name: 'Locate Object',
    level: 2,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'Sense the direction of a specific object or type of object within 1000 ft.',
    classes: ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'wizard'],
  },
  {
    name: 'Magic Mouth',
    level: 2,
    school: 'Illusion',
    castingTime: '1 minute (ritual)',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Until dispelled',
    notes: 'Implant a message in an object that speaks when a trigger condition is met.',
    classes: ['bard', 'wizard'],
  },
  {
    name: 'Magic Weapon',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 bonus action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Nonmagical weapon becomes +1 magic weapon (higher bonus at higher slots).',
    classes: ['paladin', 'wizard'],
  },
  {
    name: "Melf's Acid Arrow",
    level: 2,
    school: 'Evocation',
    castingTime: '1 action',
    range: '90 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    attackRoll: true,
    damage: '4d4',
    notes: 'Ranged spell attack; 4d4 acid damage on hit plus 2d4 acid damage at end of target\'s next turn. Miss: half initial damage, no ongoing.',
    classes: ['wizard'],
  },
  {
    name: 'Mirror Image',
    level: 2,
    school: 'Illusion',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: '1 minute',
    notes: 'Create 3 duplicates. When hit, roll d20 to see if a duplicate is hit instead (AC 10 + Dex).',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Misty Step',
    level: 2,
    school: 'Conjuration',
    castingTime: '1 bonus action',
    range: 'Self',
    components: 'V',
    duration: 'Instantaneous',
    notes: 'Teleport up to 30 ft to an unoccupied space you can see.',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Moonbeam',
    level: 2,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'con',
    damage: '2d10',
    notes: '5-ft cylinder of moonlight; Con save for radiant damage at start of each turn. Shapechangers have disadvantage.',
    classes: ['druid'],
  },
  {
    name: "Nystul's Magic Aura",
    level: 2,
    school: 'Illusion',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: '24 hours',
    notes: 'Change what Detect Magic and identify reveal about a creature or object.',
    classes: ['wizard'],
  },
  {
    name: 'Pass Without Trace',
    level: 2,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    notes: 'You and up to 10 creatures get +10 to Dexterity (Stealth) checks and can\'t be tracked by nonmagical means.',
    classes: ['druid', 'ranger'],
  },
  {
    name: 'Phantasmal Force',
    level: 2,
    school: 'Illusion',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'int',
    damage: '1d6',
    notes: 'Int save or creature believes in a crafted illusion. Takes 1d6 psychic damage per turn from it.',
    classes: ['bard', 'sorcerer', 'wizard'],
  },
  {
    name: 'Prayer of Healing',
    level: 2,
    school: 'Evocation',
    castingTime: '10 minutes',
    range: '30 feet',
    components: 'V',
    duration: 'Instantaneous',
    damage: '2d8+3',
    notes: 'Up to 6 creatures each regain 2d8 + spellcasting modifier HP.',
    classes: ['cleric'],
  },
  {
    name: 'Protection from Poison',
    level: 2,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: '1 hour',
    notes: 'Neutralize one poison affecting target; advantage on saves against poison, resistance to poison damage.',
    classes: ['cleric', 'druid', 'paladin', 'ranger'],
  },
  {
    name: 'Ray of Enfeeblement',
    level: 2,
    school: 'Necromancy',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Up to 1 minute (concentration)',
    saveAbility: 'con',
    notes: 'Ranged spell attack; on hit, Con save each turn or deal only half damage with Str-based attacks.',
    classes: ['warlock', 'wizard'],
  },
  {
    name: 'Rope Trick',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 hour',
    notes: 'Rope hangs in air; space at top holds up to 8 creatures in an extradimensional space.',
    classes: ['wizard'],
  },
  {
    name: 'Scorching Ray',
    level: 2,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    attackRoll: true,
    damage: '2d6',
    notes: 'Three ranged spell attack rays, each dealing 2d6 fire damage on hit.',
    upcastDamage: '2d6',
    upcastNotes: 'Adds one additional ray per slot level above 2nd.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'See Invisibility',
    level: 2,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S, M',
    duration: '1 hour',
    notes: 'See invisible creatures and objects, and the Ethereal Plane.',
    classes: ['bard', 'sorcerer', 'wizard'],
  },
  {
    name: 'Shatter',
    level: 2,
    school: 'Evocation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    saveAbility: 'con',
    damage: '3d8',
    notes: 'Con save for thunder damage in 10-ft radius. Inorganic material automatically fails.',
    upcastDamage: '1d8',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Silence',
    level: 2,
    school: 'Illusion',
    castingTime: '1 action (ritual)',
    range: '120 feet',
    components: 'V, S',
    duration: 'Up to 10 minutes (concentration)',
    notes: 'No sound can be created within or pass through a 20-ft radius sphere.',
    classes: ['bard', 'cleric', 'ranger'],
  },
  {
    name: 'Spider Climb',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    notes: 'Creature can climb difficult surfaces and ceilings without ability checks.',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Spike Growth',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '150 feet',
    components: 'V, S, M',
    duration: 'Up to 10 minutes (concentration)',
    damage: '2d4',
    notes: 'Ground in 20-ft radius becomes difficult terrain of spikes; 2d4 piercing per 5 ft of movement through it.',
    classes: ['druid', 'ranger'],
  },
  {
    name: 'Spiritual Weapon',
    level: 2,
    school: 'Evocation',
    castingTime: '1 bonus action',
    range: '60 feet',
    components: 'V, S',
    duration: '1 minute',
    attackRoll: true,
    damage: '1d8+3',
    notes: 'Create a floating weapon; bonus action to move it 20 ft and make a melee spell attack.',
    classes: ['cleric'],
  },
  {
    name: 'Suggestion',
    level: 2,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, M',
    duration: 'Up to 8 hours (concentration)',
    saveAbility: 'wis',
    notes: 'Wis save or creature carries out a reasonable suggested course of action.',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    name: 'Warding Bond',
    level: 2,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 hour',
    notes: 'Bonded creature gets +1 AC, +1 saves, resistance to all damage; you take half the damage it takes. Ends if >60 ft apart.',
    classes: ['cleric'],
  },
  {
    name: 'Web',
    level: 2,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 hour (concentration)',
    saveAbility: 'dex',
    notes: 'Webs fill a 20-ft cube. Dex save or restrained. Str check (DC 12) to escape. Flammable.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    name: 'Zone of Truth',
    level: 2,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: '10 minutes',
    saveAbility: 'cha',
    notes: 'Cha save or cannot tell deliberate lies while in a 15-ft radius sphere.',
    classes: ['bard', 'cleric', 'paladin'],
  },
]
