// Maps a monster name to its bundled artwork in /public/monsters.
//
// Filenames are the PascalCase of the monster's name (e.g. "Young Red Dragon"
// → YoungRedDragon.png). We match on a normalized key (lowercase, alphanumeric
// only) so spacing/casing differences don't matter. Monsters with no matching
// image return null and fall back to the plain colored token.

export const MONSTER_IMAGE_FILES: string[] = [
  // MuddBot share — 116 new monster cards + summons
  'adult_blue_dragon.png',
  'adult_brass_dragon.png',
  'adult_bronze_dragon.png',
  'adult_copper_dragon.png',
  'adult_gold_dragon.png',
  'adult_green_dragon.png',
  'adult_silver_dragon.png',
  'adult_white_dragon.png',
  'allosaurus.png',
  'ancient_black_dragon.png',
  'ancient_blue_dragon.png',
  'ancient_brass_dragon.png',
  'ancient_bronze_dragon.png',
  'ancient_copper_dragon.png',
  'ancient_gold_dragon.png',
  'ancient_silver_dragon.png',
  'ancient_white_dragon.png',
  'animated_object.png',
  'ankheg.png',
  'ankylosaurus.png',
  'ape.png',
  'archelon.png',
  'avatar_of_death.png',
  'awakened_shrub.png',
  'awakened_tree.png',
  'axe_beak.png',
  'azer_sentinel.png',
  'baboon.png',
  'badger.png',
  'blink_dog.png',
  'blood_hawk.png',
  'boar.png',
  'brass_dragon_wyrmling.png',
  'bronze_dragon_wyrmling.png',
  'camel.png',
  'cat.png',
  'chittering_horror.png',
  'constrictor_snake.png',
  'copper_dragon_wyrmling.png',
  'crab.png',
  'darkmantle.png',
  'deer.png',
  'draconic_spirit.png',
  'draft_horse.png',
  'drider.png',
  'dust_mephit.png',
  'eagle.png',
  'elk.png',
  'flying_snake.png',
  'frog.png',
  'giant_badger.png',
  'giant_crab.png',
  'giant_elk.png',
  'giant_fire_beetle.png',
  'giant_fly.png',
  'giant_goat.png',
  'giant_insect.png',
  'giant_lizard.png',
  'giant_owl.png',
  'giant_scorpion.png',
  'giant_seahorse.png',
  'giant_shark.png',
  'giant_vulture.png',
  'giant_wasp.png',
  'giant_weasel.png',
  'goat.png',
  'goblin_boss.png',
  'goblin_minion.png',
  'gold_dragon_wyrmling.png',
  'guardian_naga.png',
  'half_dragon.png',
  'hawk.png',
  'hippopotamus.png',
  'homunculus.png',
  'hyena.png',
  'jackal.png',
  'killer_whale.png',
  'lizard.png',
  'magma_mephit.png',
  'merfolk_skirmisher.png',
  'merrow.png',
  'minotaur_skeleton.png',
  'mule.png',
  'nalfeshnee.png',
  'octopus.png',
  'ogre_zombie.png',
  'otherworldly_steed.png',
  'owl.png',
  'piranha.png',
  'plesiosaurus.png',
  'pony.png',
  'pteranodon.png',
  'raven.png',
  'reef_shark.png',
  'remorhaz.png',
  'roc.png',
  'scorpion.png',
  'seahorse.png',
  'silver_dragon_wyrmling.png',
  'sphinx_of_lore.png',
  'sphinx_of_valor.png',
  'sphinx_of_wonder.png',
  'spider.png',
  'spirit_naga.png',
  'succubus.png',
  'triceratops.png',
  'troll_limb.png',
  'tyrannosaurus_rex.png',
  'vulture.png',
  'warhorse_skeleton.png',
  'weasel.png',
  'young_brass_dragon.png',
  'young_bronze_dragon.png',
  'young_copper_dragon.png',
  'young_gold_dragon.png',
  'young_silver_dragon.png',
  'Aboleth.png', 'AirElemental.png', 'AnimatedArmor.png', 'Bandit.png', 'Banshee.png',
  'Basilisk.png', 'BeardedDevil.png', 'BogWisp.png', 'BoneDevil.png', 'Bugbear.png',
  'BugbearChief.png', 'Chimera.png', 'CloudGiant.png', 'Cockatrice.png', 'Cyclops.png',
  'DireWolf.png', 'Doppelganger.png', 'Dretch.png', 'EarthElemental.png', 'Ettin.png',
  'FireElemental.png', 'FireGiant.png', 'FrostGiant.png', 'Gargoyle.png', 'GelatinousCube.png',
  'Ghoul.png', 'GiantBat.png', 'GiantCentipede.png', 'GiantFrog.png', 'GiantRat.png',
  'GiantSpider.png', 'Glabrezu.png', 'Gnoll.png', 'Goblin.png', 'Gorgon.png',
  'Grick.png', 'Grimlock.png', 'Harpy.png', 'HellHound.png', 'HillGiant.png',
  'Hippogriff.png', 'Hobgoblin.png', 'HobgoblinWarlord.png', 'HookHorror.png', 'HornedDevil.png',
  'Hydra.png', 'IceMephit.png', 'Imp.png', 'Kenku.png', 'Kobold.png',
  'Lemure.png', 'Lich.png', 'Manticore.png', 'Medusa.png', 'Mimic.png',
  'Minotaur.png', 'NeedleBlight.png', 'Ogre.png', 'Orc.png', 'OrcWarchief.png',
  'Otyugh.png', 'Owlbear.png', 'Pseudodragon.png', 'PurpleWorm.png', 'Quasit.png',
  'Roper.png', 'RustMonster.png', 'Sahuagin.png', 'Salamander.png', 'Skeleton.png',
  'SteamMephit.png', 'Stirge.png', 'StoneGiant.png', 'StoneGolem.png', 'Troll.png',
  'TwigBlight.png', 'Vampire.png', 'WaterElemental.png', 'Werewolf.png', 'Wight.png',
  'Wolf.png', 'Wraith.png', 'Wyvern.png', 'YoungBlackDragon.png', 'YoungBlueDragon.png',
  'YoungGreenDragon.png', 'YoungRedDragon.png', 'YoungWhiteDragon.png', 'Zombie.png',
]

const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '')

// 2024 rules renamed several classic humanoids — point the new names at the
// existing 2014-named art so they don't fall back to blank tokens.
const NAME_ALIASES: Record<string, string> = {
  'Bugbear Warrior': 'Bugbear',
  'Bugbear Stalker': 'BugbearChief',
  'Gnoll Warrior': 'Gnoll',
  'Hobgoblin Warrior': 'Hobgoblin',
  'Hobgoblin Captain': 'HobgoblinWarlord',
  'Kobold Warrior': 'Kobold',
  'Minotaur of Baphomet': 'Minotaur',
  'Sahuagin Warrior': 'Sahuagin',
}

// normalized monster name → "/monsters/<File>.png"
const INDEX: Record<string, string> = Object.fromEntries([
  ...MONSTER_IMAGE_FILES.map((f) => [norm(f.replace(/\.png$/i, '')), `/monsters/${f}`]),
  ...Object.entries(NAME_ALIASES).map(([name, file]) => [norm(name), `/monsters/${file}.png`]),
])

/** Resolve a monster's bundled artwork URL by name, or null if none exists. */
export function monsterImageUrl(name: string | null | undefined): string | null {
  if (!name) return null
  return INDEX[norm(name)] ?? null
}
