import type { Monster } from './types'

export const ABERRATIONS: Monster[] = [
  {
    id: 'aberration-aboleth',
    name: 'Aboleth',
    cr: 10,
    size: 'Large',
    type: 'aberration',
    alignment: 'lawful evil',
    armorClass: 17,
    hitPoints: 135,
    hitDice: '18d10+36',
    speed: '10 ft., swim 40 ft.',
    abilities: { str: 21, dex: 9, con: 15, int: 18, wis: 15, cha: 18 },
    skills: ['History +12', 'Perception +10'],
    senses: ['Darkvision 120 ft.', 'Passive Perception 20'],
    languages: ['Deep Speech', 'telepathy 120 ft.'],
    traits: [
      { name: 'Amphibious', type: 'trait', description: 'The aboleth can breathe air and water.' },
      { name: 'Mucous Cloud', type: 'trait', description: 'While underwater, the aboleth is surrounded by transformative mucus. A creature that touches the aboleth or hits it with a melee attack while within 5 ft. must succeed on a DC 14 Constitution saving throw or be diseased for 1d4 hours, able to breathe only underwater.' },
      { name: 'Probing Telepathy', type: 'trait', description: "If a creature communicates telepathically with the aboleth, the aboleth learns the creature's greatest desires if the aboleth can see the creature." },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The aboleth makes three tentacle attacks.' },
      { name: 'Tentacle', type: 'attack', description: 'Melee Weapon Attack: +9 to hit, reach 10 ft., one target. Hit: 12 (2d6+5) bludgeoning damage. On a hit, the target must succeed on a DC 14 Constitution saving throw or become diseased.', attackBonus: 9, damage: '2d6+5 bludgeoning', saveDc: 14, saveType: 'con' },
      { name: 'Tail', type: 'attack', description: 'Melee Weapon Attack: +9 to hit, reach 10 ft., one target. Hit: 15 (3d6+5) bludgeoning damage.', attackBonus: 9, damage: '3d6+5 bludgeoning' },
      { name: 'Enslave (3/Day)', type: 'ability', description: 'The aboleth targets one creature it can see within 30 ft. The target must succeed on a DC 14 Wisdom saving throw or be magically charmed by the aboleth until the aboleth dies or until it is on a different plane of existence.', saveDc: 14, saveType: 'wis' },
    ],
    legendaryActions: [
      { name: 'Detect', type: 'ability', description: 'The aboleth makes a Wisdom (Perception) check.' },
      { name: 'Tail Swipe', type: 'attack', description: 'The aboleth makes one tail attack.', attackBonus: 9, damage: '3d6+5 bludgeoning' },
      { name: 'Psychic Drain (Costs 2 Actions)', type: 'ability', description: 'One creature charmed by the aboleth takes 10 (3d6) psychic damage, and the aboleth regains hit points equal to the damage dealt.', saveDc: 14, saveType: 'int' },
    ],
    tags: ['legendary', 'water', 'psionic'],
  },
  {
    id: 'aberration-chuul',
    name: 'Chuul',
    cr: 4,
    size: 'Large',
    type: 'aberration',
    alignment: 'chaotic evil',
    armorClass: 16,
    hitPoints: 93,
    hitDice: '11d10+33',
    speed: '30 ft., swim 30 ft.',
    abilities: { str: 19, dex: 10, con: 16, int: 5, wis: 11, cha: 5 },
    skills: ['Perception +4'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 14'],
    languages: ['understands Deep Speech but cannot speak'],
    traits: [
      { name: 'Amphibious', type: 'trait', description: 'The chuul can breathe air and water.' },
      { name: 'Sense Magic', type: 'trait', description: 'The chuul senses magic within 120 ft. of it at will. This trait otherwise works like the detect magic spell but is not itself magical.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The chuul makes two pincer attacks. If the chuul is grappling a creature, the chuul can also use its tentacles once.' },
      { name: 'Pincer', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 10 ft., one target. Hit: 11 (2d6+4) bludgeoning damage. The target is grappled (escape DC 14) if it is a Large or smaller creature.', attackBonus: 6, damage: '2d6+4 bludgeoning' },
      { name: 'Tentacles', type: 'ability', description: 'One creature grappled by the chuul must succeed on a DC 13 Constitution saving throw or be paralyzed for 1 minute. The target can repeat the saving throw at the end of each of its turns.', saveDc: 13, saveType: 'con' },
    ],
    tags: ['water', 'grappler'],
  },
  {
    id: 'aberration-cloaker',
    name: 'Cloaker',
    cr: 8,
    size: 'Large',
    type: 'aberration',
    alignment: 'chaotic neutral',
    armorClass: 14,
    hitPoints: 78,
    hitDice: '12d10+12',
    speed: '10 ft., fly 40 ft.',
    abilities: { str: 17, dex: 15, con: 12, int: 13, wis: 12, cha: 14 },
    skills: ['Stealth +5'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 11'],
    languages: ['Deep Speech', 'Undercommon'],
    traits: [
      { name: 'Damage Transfer', type: 'trait', description: 'While attached to a creature, the cloaker takes only half the damage dealt to it (rounded down), and that creature takes the other half.' },
      { name: 'False Appearance', type: 'trait', description: 'While the cloaker remains motionless without its underside exposed, it is indistinguishable from a dark leather cloak.' },
      { name: 'Light Sensitivity', type: 'trait', description: 'While in bright light, the cloaker has disadvantage on attack rolls and Wisdom (Perception) checks that rely on sight.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The cloaker makes two attacks: one with its bite and one with its tail.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one creature. Hit: 10 (2d6+3) piercing damage, and if the target is Large or smaller, the cloaker attaches to it. While attached, the cloaker can make only bite attacks against the attached creature.', attackBonus: 6, damage: '2d6+3 piercing' },
      { name: 'Tail', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 10 ft., one creature not grappled by the cloaker. Hit: 7 (1d8+3) slashing damage.', attackBonus: 6, damage: '1d8+3 slashing' },
      { name: 'Moan', type: 'ability', description: 'Each creature within 60 ft. that can hear the cloaker\'s moan must succeed on a DC 13 Wisdom saving throw or become frightened until the end of the cloaker\'s next turn. If a creature\'s saving throw is successful, it is immune to this moan for 24 hours.', saveDc: 13, saveType: 'wis' },
      { name: 'Phantasms (Recharges after a Short or Long Rest)', type: 'ability', description: 'The cloaker magically creates three illusory duplicates of itself if it isn\'t in bright light. The duplicates move with the cloaker. DC 13 Intelligence saving throw or be unable to distinguish the cloaker from its duplicates.', saveDc: 13, saveType: 'int' },
    ],
    tags: ['ambusher', 'underdark'],
  },
  {
    id: 'aberration-gibbering-mouther',
    name: 'Gibbering Mouther',
    cr: 2,
    size: 'Medium',
    type: 'aberration',
    alignment: 'neutral',
    armorClass: 9,
    hitPoints: 67,
    hitDice: '9d8+27',
    speed: '10 ft., swim 10 ft.',
    abilities: { str: 10, dex: 8, con: 16, int: 3, wis: 10, cha: 6 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 10'],
    traits: [
      { name: 'Aberrant Ground', type: 'trait', description: 'The ground within 10 ft. of the mouther is dough-like difficult terrain. Each creature that starts its turn in that area must succeed on a DC 10 Strength saving throw or have its speed reduced to 0 until the start of its next turn.', saveDc: 10, saveType: 'str' },
      { name: 'Gibbering', type: 'trait', description: 'The mouther babbles incoherently while it can see any creature and isn\'t incapacitated. Each creature that starts its turn within 20 ft. and can hear the gibbering must succeed on a DC 10 Wisdom saving throw or be confused until the start of its next turn.', saveDc: 10, saveType: 'wis' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The gibbering mouther makes one bite attack and, if it can, uses its Blinding Spittle.' },
      { name: 'Bites', type: 'attack', description: 'Melee Weapon Attack: +2 to hit, reach 5 ft., one creature. Hit: 17 (5d6) piercing damage. If the target is Medium or smaller, it must succeed on a DC 10 Strength saving throw or be knocked prone. If the target is killed by this damage, it is absorbed into the mouther.', attackBonus: 2, damage: '5d6 piercing', saveDc: 10, saveType: 'str' },
      { name: 'Blinding Spittle (Recharge 5-6)', type: 'ability', description: 'The mouther spits a chemical glob at a point it can see within 15 ft. The glob explodes in a blinding flash. Each creature within 5 ft. must succeed on a DC 13 Dexterity saving throw or be blinded until the end of the mouther\'s next turn.', saveDc: 13, saveType: 'dex' },
    ],
    tags: ['aberration', 'ooze-like'],
  },
  {
    id: 'aberration-grick',
    name: 'Grick',
    cr: 2,
    size: 'Medium',
    type: 'aberration',
    alignment: 'neutral',
    armorClass: 14,
    hitPoints: 27,
    hitDice: '6d8',
    speed: '30 ft., climb 30 ft.',
    abilities: { str: 14, dex: 14, con: 11, int: 3, wis: 14, cha: 5 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 12'],
    traits: [
      { name: 'Stone Camouflage', type: 'trait', description: 'The grick has advantage on Dexterity (Stealth) checks made to hide in rocky terrain.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The grick makes one attack with its tentacles. If that attack hits, the grick can make one beak attack against the same target.' },
      { name: 'Tentacles', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 9 (2d6+2) slashing damage.', attackBonus: 4, damage: '2d6+2 slashing' },
      { name: 'Beak', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6+2) piercing damage.', attackBonus: 4, damage: '1d6+2 piercing' },
    ],
    tags: ['underdark', 'ambusher'],
  },
  {
    id: 'aberration-grick-alpha',
    name: 'Grick Alpha',
    cr: 7,
    size: 'Large',
    type: 'aberration',
    alignment: 'neutral',
    armorClass: 18,
    hitPoints: 75,
    hitDice: '10d10+20',
    speed: '30 ft., climb 30 ft.',
    abilities: { str: 18, dex: 16, con: 15, int: 4, wis: 14, cha: 9 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 12'],
    traits: [
      { name: 'Stone Camouflage', type: 'trait', description: 'The grick has advantage on Dexterity (Stealth) checks made to hide in rocky terrain.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The grick alpha makes two attacks: one with its tentacles and one with its beak, or two with its rocks.' },
      { name: 'Tentacles', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 10 ft., one target. Hit: 20 (3d10+4) slashing damage.', attackBonus: 7, damage: '3d10+4 slashing' },
      { name: 'Beak', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 10 ft., one target. Hit: 13 (2d8+4) piercing damage.', attackBonus: 7, damage: '2d8+4 piercing' },
      { name: 'Rock', type: 'attack', description: 'Ranged Weapon Attack: +7 to hit, range 60/240 ft., one target. Hit: 30 (4d12+4) bludgeoning damage.', attackBonus: 7, damage: '4d12+4 bludgeoning' },
    ],
    tags: ['underdark', 'elite'],
  },
  {
    id: 'aberration-intellect-devourer',
    name: 'Intellect Devourer',
    cr: 2,
    size: 'Tiny',
    type: 'aberration',
    alignment: 'lawful evil',
    armorClass: 12,
    hitPoints: 21,
    hitDice: '6d4+6',
    speed: '40 ft.',
    abilities: { str: 6, dex: 14, con: 13, int: 12, wis: 11, cha: 10 },
    skills: ['Perception +2', 'Stealth +4'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 12'],
    languages: ['understands Deep Speech and the languages of its host; telepathy 60 ft.'],
    traits: [
      { name: 'Detect Sentience', type: 'trait', description: 'The intellect devourer can sense the presence and location of any creature within 300 ft. of it that has an Intelligence of 3 or higher, regardless of interposing barriers.' },
    ],
    actions: [
      { name: 'Claws', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4+2) slashing damage.', attackBonus: 4, damage: '2d4+2 slashing' },
      { name: 'Devour Intellect', type: 'ability', description: 'The intellect devourer targets one creature it can see within 10 ft. The target must contest its Intelligence (Arcana) check against the intellect devourer\'s Intelligence (Arcana) check. If the devourer wins, it deals 2d10 psychic damage and the target\'s Intelligence score is reduced.', saveDc: 12, saveType: 'int' },
      { name: 'Body Thief', type: 'ability', description: 'The intellect devourer initiates a contest of Intelligence (Arcana) against an incapacitated creature within 5 ft. If it wins, it teleports into the target\'s skull and takes control of the body.', saveDc: 12, saveType: 'int' },
    ],
    tags: ['psionic', 'underdark', 'mind flayer ally'],
  },
  {
    id: 'aberration-nothic',
    name: 'Nothic',
    cr: 2,
    size: 'Medium',
    type: 'aberration',
    alignment: 'neutral evil',
    armorClass: 15,
    hitPoints: 45,
    hitDice: '6d8+18',
    speed: '30 ft.',
    abilities: { str: 14, dex: 16, con: 16, int: 13, wis: 10, cha: 8 },
    skills: ['Arcana +3', 'Insight +4', 'Perception +2', 'Stealth +5'],
    senses: ['Truesight 120 ft.', 'Passive Perception 12'],
    languages: ['Undercommon'],
    traits: [
      { name: 'Keen Sight', type: 'trait', description: 'The nothic has advantage on Wisdom (Perception) checks that rely on sight.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The nothic makes two claw attacks.' },
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 6 (1d6+3) slashing damage.', attackBonus: 4, damage: '1d6+3 slashing' },
      { name: 'Rotting Gaze', type: 'ability', description: 'The nothic targets one creature it can see within 30 ft. The target must succeed on a DC 12 Constitution saving throw against this magic or take 10 (3d6) necrotic damage.', saveDc: 12, saveType: 'con' },
      { name: 'Weird Insight', type: 'ability', description: 'The nothic targets one creature it can see within 30 ft. The target must contest its Charisma (Deception) check against the nothic\'s Wisdom (Insight) check. If the nothic wins, it magically learns one fact or secret about the target.' },
    ],
    tags: ['aberration', 'wizard curse'],
  },
  {
    id: 'aberration-otyugh',
    name: 'Otyugh',
    cr: 5,
    size: 'Large',
    type: 'aberration',
    alignment: 'neutral',
    armorClass: 14,
    hitPoints: 114,
    hitDice: '12d10+48',
    speed: '30 ft., swim 30 ft.',
    abilities: { str: 16, dex: 11, con: 19, int: 6, wis: 13, cha: 8 },
    senses: ['Darkvision 120 ft.', 'Passive Perception 11'],
    languages: ['Otyugh'],
    traits: [
      { name: 'Limited Telepathy', type: 'trait', description: 'The otyugh can magically transmit simple messages and images to any creature within 120 ft. that can understand a language. This form of telepathy doesn\'t allow the receiving creature to telepathically respond.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The otyugh makes three attacks: one with its bite and two with its tentacles.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 12 (2d8+3) piercing damage. If the target is a creature, it must succeed on a DC 15 Constitution saving throw or become diseased.', attackBonus: 6, damage: '2d8+3 piercing', saveDc: 15, saveType: 'con' },
      { name: 'Tentacle', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 10 ft., one target. Hit: 7 (1d8+3) bludgeoning plus 4 (1d8) piercing damage. If the target is Medium or smaller, it is grappled (escape DC 13).', attackBonus: 6, damage: '1d8+3 bludgeoning' },
      { name: 'Tentacle Slam', type: 'ability', description: 'The otyugh slams creatures grappled by it into each other or a solid surface. Each creature must succeed on a DC 14 Strength saving throw or take 10 (2d6+3) bludgeoning damage and be stunned until end of next turn. On a successful save, the target takes half the bludgeoning damage and isn\'t stunned.', saveDc: 14, saveType: 'str' },
    ],
    tags: ['sewer', 'disease'],
  },
  {
    id: 'aberration-roper',
    name: 'Roper',
    cr: 5,
    size: 'Large',
    type: 'aberration',
    alignment: 'neutral evil',
    armorClass: 20,
    hitPoints: 93,
    hitDice: '11d10+33',
    speed: '10 ft., climb 10 ft.',
    abilities: { str: 18, dex: 8, con: 17, int: 7, wis: 16, cha: 6 },
    skills: ['Perception +6', 'Stealth +5'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 16'],
    traits: [
      { name: 'False Appearance', type: 'trait', description: 'While the roper remains motionless, it is indistinguishable from a normal cave formation such as a stalagmite.' },
      { name: 'Grasping Tendrils', type: 'trait', description: 'The roper can have up to six tendrils at a time. Each tendril can be attacked (AC 20, 10 hp, immunity to poison and psychic damage). Destroying a tendril deals no damage to the roper.' },
      { name: 'Spider Climb', type: 'trait', description: 'The roper can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The roper makes four attacks with its tendrils, uses Reel, and makes one bite attack.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 22 (4d8+4) piercing damage.', attackBonus: 7, damage: '4d8+4 piercing' },
      { name: 'Tendril', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 50 ft., one creature. Hit: The target is grappled (escape DC 15). Until the grapple ends, the target is restrained and has disadvantage on Strength checks.', attackBonus: 7, damage: '0' },
      { name: 'Reel', type: 'ability', description: 'The roper pulls each creature grappled by it up to 25 ft. straight toward it.' },
    ],
    tags: ['underdark', 'ambusher', 'cave'],
  },
  {
    id: 'aberration-spectator',
    name: 'Spectator',
    cr: 3,
    size: 'Medium',
    type: 'aberration',
    alignment: 'lawful neutral',
    armorClass: 14,
    hitPoints: 39,
    hitDice: '6d8+12',
    speed: '0 ft., fly 30 ft. (hover)',
    abilities: { str: 8, dex: 14, con: 14, int: 13, wis: 14, cha: 11 },
    senses: ['Darkvision 120 ft.', 'Passive Perception 12'],
    languages: ['Deep Speech', 'Undercommon', 'telepathy 120 ft.'],
    traits: [
      { name: '360-Degree Vision', type: 'trait', description: 'The spectator is not surprised and can\'t be flanked.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The spectator makes two bite attacks or uses its Eye Rays twice.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +1 to hit, reach 5 ft., one target. Hit: 2 (1d6-1) piercing damage.', attackBonus: 1, damage: '1d6-1 piercing' },
      { name: 'Eye Rays', type: 'ability', description: 'The spectator shoots two magical eye rays at one or two creatures it can see within 90 ft. It can use each ray only once on a turn. 1—Confusion Ray (DC 13 WIS or confused 1 min), 2—Paralyzing Ray (DC 13 CON or paralyzed 1 min), 3—Fear Ray (DC 13 WIS or frightened 1 min), 4—Wounding Ray (4d10 necrotic).', saveDc: 13, saveType: 'wis' },
    ],
    tags: ['beholder-kin', 'guardian'],
  },
]
