import type { Monster } from './types'

export const BEASTS: Monster[] = [
  // ─── COMMON BEASTS ────────────────────────────────────────────────────────
  {
    id: 'beast-wolf',
    name: 'Wolf',
    cr: 0.25,
    size: 'Medium',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 13,
    hitPoints: 11,
    hitDice: '2d8+2',
    speed: '40 ft.',
    abilities: { str: 12, dex: 15, con: 12, int: 3, wis: 12, cha: 6 },
    skills: ['Perception +3', 'Stealth +4'],
    senses: ['Passive Perception 13'],
    traits: [
      { name: 'Keen Hearing and Smell', type: 'trait', description: 'The wolf has advantage on Wisdom (Perception) checks that rely on hearing or smell.' },
      { name: 'Pack Tactics', type: 'trait', description: 'The wolf has advantage on an attack roll against a creature if at least one of the wolf\'s allies is adjacent to the creature and the ally isn\'t incapacitated.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4+2) piercing damage. If the target is a creature, it must succeed on a DC 11 Strength saving throw or be knocked prone.', attackBonus: 4, damage: '2d4+2 piercing', saveDc: 11, saveType: 'str' },
    ],
    tags: ['beast', 'canine', 'pack', 'forest'],
  },
  {
    id: 'beast-dire-wolf',
    name: 'Dire Wolf',
    cr: 1,
    size: 'Large',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 14,
    hitPoints: 37,
    hitDice: '5d10+10',
    speed: '50 ft.',
    abilities: { str: 17, dex: 15, con: 15, int: 3, wis: 12, cha: 7 },
    skills: ['Perception +3', 'Stealth +4'],
    senses: ['Passive Perception 13'],
    traits: [
      { name: 'Keen Hearing and Smell', type: 'trait', description: 'The wolf has advantage on Wisdom (Perception) checks that rely on hearing or smell.' },
      { name: 'Pack Tactics', type: 'trait', description: 'The wolf has advantage on an attack roll against a creature if at least one of the wolf\'s allies is adjacent to the creature and the ally isn\'t incapacitated.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6+3) piercing damage. If the target is a creature, it must succeed on a DC 13 Strength saving throw or be knocked prone.', attackBonus: 5, damage: '2d6+3 piercing', saveDc: 13, saveType: 'str' },
    ],
    tags: ['beast', 'canine', 'large', 'forest'],
  },
  {
    id: 'beast-brown-bear',
    name: 'Brown Bear',
    cr: 1,
    size: 'Large',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 11,
    hitPoints: 34,
    hitDice: '4d10+12',
    speed: '40 ft., climb 30 ft.',
    abilities: { str: 19, dex: 10, con: 16, int: 2, wis: 13, cha: 7 },
    skills: ['Perception +3'],
    senses: ['Passive Perception 13'],
    traits: [
      { name: 'Keen Smell', type: 'trait', description: 'The bear has advantage on Wisdom (Perception) checks that rely on smell.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The bear makes two attacks: one with its bite and one with its claws.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 8 (1d8+4) piercing damage.', attackBonus: 6, damage: '1d8+4 piercing' },
      { name: 'Claws', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 11 (2d6+4) slashing damage.', attackBonus: 6, damage: '2d6+4 slashing' },
    ],
    tags: ['beast', 'bear', 'forest'],
  },
  {
    id: 'beast-black-bear',
    name: 'Black Bear',
    cr: 0.5,
    size: 'Medium',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 11,
    hitPoints: 19,
    hitDice: '3d8+6',
    speed: '40 ft., climb 30 ft.',
    abilities: { str: 15, dex: 10, con: 14, int: 2, wis: 12, cha: 7 },
    skills: ['Perception +3'],
    senses: ['Passive Perception 13'],
    traits: [
      { name: 'Keen Smell', type: 'trait', description: 'The bear has advantage on Wisdom (Perception) checks that rely on smell.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The bear makes two attacks: one with its bite and one with its claws.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6+2) piercing damage.', attackBonus: 4, damage: '1d6+2 piercing' },
      { name: 'Claws', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4+2) slashing damage.', attackBonus: 4, damage: '2d4+2 slashing' },
    ],
    tags: ['beast', 'bear', 'forest'],
  },
  {
    id: 'beast-lion',
    name: 'Lion',
    cr: 1,
    size: 'Large',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 12,
    hitPoints: 26,
    hitDice: '4d10+4',
    speed: '50 ft.',
    abilities: { str: 17, dex: 15, con: 13, int: 3, wis: 12, cha: 8 },
    skills: ['Perception +3', 'Stealth +6'],
    senses: ['Passive Perception 13'],
    traits: [
      { name: 'Keen Smell', type: 'trait', description: 'The lion has advantage on Wisdom (Perception) checks that rely on smell.' },
      { name: 'Pack Tactics', type: 'trait', description: 'The lion has advantage on an attack roll against a creature if at least one of the lion\'s allies is adjacent to the creature and the ally isn\'t incapacitated.' },
      { name: 'Pounce', type: 'trait', description: 'If the lion moves at least 20 ft. straight toward a creature and then hits it with a claw attack on the same turn, that target must succeed on a DC 13 Strength saving throw or be knocked prone. If the target is prone, the lion can make one bite attack against it as a bonus action.', saveDc: 13, saveType: 'str' },
      { name: 'Running Leap', type: 'trait', description: 'With a 10-ft. running start, the lion can long jump up to 25 ft.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 7 (1d8+3) piercing damage.', attackBonus: 5, damage: '1d8+3 piercing' },
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6+3) slashing damage.', attackBonus: 5, damage: '1d6+3 slashing' },
    ],
    tags: ['beast', 'feline', 'savanna', 'pack'],
  },
  {
    id: 'beast-tiger',
    name: 'Tiger',
    cr: 1,
    size: 'Large',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 12,
    hitPoints: 37,
    hitDice: '5d10+10',
    speed: '40 ft.',
    abilities: { str: 17, dex: 15, con: 14, int: 3, wis: 12, cha: 8 },
    skills: ['Perception +3', 'Stealth +6'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 13'],
    traits: [
      { name: 'Keen Smell', type: 'trait', description: 'The tiger has advantage on Wisdom (Perception) checks that rely on smell.' },
      { name: 'Pounce', type: 'trait', description: 'If the tiger moves at least 20 ft. straight toward a creature and then hits it with a claw attack on the same turn, that target must succeed on a DC 13 Strength saving throw or be knocked prone. If the target is prone, the tiger can make one bite attack against it as a bonus action.', saveDc: 13, saveType: 'str' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 8 (1d10+3) piercing damage.', attackBonus: 5, damage: '1d10+3 piercing' },
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 7 (1d8+3) slashing damage.', attackBonus: 5, damage: '1d8+3 slashing' },
    ],
    tags: ['beast', 'feline', 'jungle'],
  },
  {
    id: 'beast-giant-spider',
    name: 'Giant Spider',
    cr: 1,
    size: 'Large',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 14,
    hitPoints: 26,
    hitDice: '4d10+4',
    speed: '30 ft., climb 30 ft.',
    abilities: { str: 14, dex: 16, con: 12, int: 2, wis: 11, cha: 4 },
    skills: ['Stealth +7'],
    senses: ['Blindsight 10 ft.', 'Darkvision 60 ft.', 'Passive Perception 10'],
    traits: [
      { name: 'Spider Climb', type: 'trait', description: 'The spider can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check.' },
      { name: 'Web Sense', type: 'trait', description: 'While in contact with a web, the spider knows the exact location of any other creature in contact with the same web.' },
      { name: 'Web Walker', type: 'trait', description: 'The spider ignores movement restrictions caused by webbing.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one creature. Hit: 7 (1d8+3) piercing damage, and the target must make a DC 11 Constitution saving throw, taking 9 (2d8) poison damage on a failed save, or half as much on a successful one. If the poison damage reduces the target to 0 hit points, the target is stable but poisoned for 1 hour.', attackBonus: 5, damage: '1d8+3 piercing', saveDc: 11, saveType: 'con' },
      { name: 'Web (Recharge 5-6)', type: 'ability', description: 'Ranged Weapon Attack: +5 to hit, range 30/60 ft., one creature. Hit: The target is restrained by webbing. As an action, the restrained target can make a DC 12 Strength check, escaping from the webbing on a success. The effect ends if the webbing is destroyed (AC 10, 5 HP, vulnerability to fire).', attackBonus: 5, damage: '0' },
    ],
    tags: ['beast', 'spider', 'web', 'cave'],
  },
  {
    id: 'beast-giant-toad',
    name: 'Giant Toad',
    cr: 1,
    size: 'Large',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 11,
    hitPoints: 39,
    hitDice: '6d10+6',
    speed: '20 ft., swim 40 ft.',
    abilities: { str: 15, dex: 13, con: 13, int: 2, wis: 10, cha: 3 },
    senses: ['Darkvision 30 ft.', 'Passive Perception 10'],
    traits: [
      { name: 'Amphibious', type: 'trait', description: 'The toad can breathe air and water.' },
      { name: 'Standing Leap', type: 'trait', description: 'The toad\'s long jump is up to 20 ft. and its high jump is up to 10 ft., with or without a running start.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (1d10+2) piercing damage plus 5 (1d10) poison damage, and the target is grappled (escape DC 13). Until this grapple ends, the target is restrained, and the toad can\'t bite another target.', attackBonus: 4, damage: '1d10+2 piercing + 1d10 poison' },
      { name: 'Swallow', type: 'ability', description: 'The toad makes one bite attack against a Medium or smaller target it is grappling. If the attack hits, the target is swallowed, and the grapple ends. The swallowed target is blinded and restrained, it has total cover against attacks and other effects outside the toad, and it takes 10 (3d6) acid damage at the start of each of the toad\'s turns. The toad can have only one target swallowed at a time.' },
    ],
    tags: ['beast', 'frog', 'swamp', 'swallow'],
  },
  {
    id: 'beast-crocodile',
    name: 'Crocodile',
    cr: 0.5,
    size: 'Large',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 12,
    hitPoints: 19,
    hitDice: '3d10+3',
    speed: '20 ft., swim 30 ft.',
    abilities: { str: 15, dex: 10, con: 13, int: 2, wis: 10, cha: 5 },
    skills: ['Stealth +2'],
    senses: ['Passive Perception 10'],
    traits: [
      { name: 'Hold Breath', type: 'trait', description: 'The crocodile can hold its breath for 15 minutes.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 7 (1d10+2) piercing damage, and the target is grappled (escape DC 12). Until this grapple ends, the target is restrained, and the crocodile can\'t bite another target.', attackBonus: 4, damage: '1d10+2 piercing' },
    ],
    tags: ['beast', 'reptile', 'water', 'grappler'],
  },
  {
    id: 'beast-giant-crocodile',
    name: 'Giant Crocodile',
    cr: 5,
    size: 'Huge',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 14,
    hitPoints: 114,
    hitDice: '12d12+36',
    speed: '30 ft., swim 50 ft.',
    abilities: { str: 21, dex: 9, con: 17, int: 2, wis: 10, cha: 7 },
    skills: ['Stealth +5'],
    senses: ['Passive Perception 10'],
    traits: [
      { name: 'Hold Breath', type: 'trait', description: 'The crocodile can hold its breath for 30 minutes.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The crocodile makes two attacks: one with its bite and one with its tail.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 21 (3d10+5) piercing damage, and the target is grappled (escape DC 16). Until this grapple ends, the target is restrained, and the crocodile can\'t bite another target.', attackBonus: 8, damage: '3d10+5 piercing' },
      { name: 'Tail', type: 'attack', description: 'Melee Weapon Attack: +8 to hit, reach 10 ft., one target not grappled by the crocodile. Hit: 14 (2d8+5) bludgeoning damage. If the target is a creature, it must succeed on a DC 16 Strength saving throw or be knocked prone.', attackBonus: 8, damage: '2d8+5 bludgeoning', saveDc: 16, saveType: 'str' },
    ],
    tags: ['beast', 'reptile', 'water', 'grappler', 'large'],
  },
  {
    id: 'beast-giant-eagle',
    name: 'Giant Eagle',
    cr: 1,
    size: 'Large',
    type: 'beast',
    alignment: 'neutral good',
    armorClass: 13,
    hitPoints: 26,
    hitDice: '4d10+4',
    speed: '10 ft., fly 80 ft.',
    abilities: { str: 16, dex: 17, con: 13, int: 8, wis: 14, cha: 10 },
    skills: ['Perception +4'],
    senses: ['Passive Perception 14'],
    languages: ['Giant Eagle; understands Common and Auran but can\'t speak them'],
    traits: [
      { name: 'Keen Sight', type: 'trait', description: 'The eagle has advantage on Wisdom (Perception) checks that rely on sight.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The eagle makes two attacks: one with its beak and one with its talons.' },
      { name: 'Beak', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6+3) piercing damage.', attackBonus: 5, damage: '1d6+3 piercing' },
      { name: 'Talons', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6+3) slashing damage.', attackBonus: 5, damage: '2d6+3 slashing' },
    ],
    tags: ['beast', 'bird', 'flying', 'mount'],
  },
  {
    id: 'beast-giant-ape',
    name: 'Giant Ape',
    cr: 7,
    size: 'Huge',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 12,
    hitPoints: 157,
    hitDice: '15d12+60',
    speed: '40 ft., climb 40 ft.',
    abilities: { str: 23, dex: 14, con: 18, int: 7, wis: 12, cha: 7 },
    skills: ['Athletics +9', 'Perception +4'],
    senses: ['Passive Perception 14'],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The ape makes two fist attacks.' },
      { name: 'Fist', type: 'attack', description: 'Melee Weapon Attack: +9 to hit, reach 10 ft., one target. Hit: 22 (3d10+6) bludgeoning damage.', attackBonus: 9, damage: '3d10+6 bludgeoning' },
      { name: 'Rock', type: 'attack', description: 'Ranged Weapon Attack: +9 to hit, range 50/100 ft., one target. Hit: 30 (7d6+6) bludgeoning damage.', attackBonus: 9, damage: '7d6+6 bludgeoning' },
    ],
    tags: ['beast', 'ape', 'jungle', 'large'],
  },
  {
    id: 'beast-giant-constrictor-snake',
    name: 'Giant Constrictor Snake',
    cr: 2,
    size: 'Huge',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 12,
    hitPoints: 60,
    hitDice: '8d12+8',
    speed: '30 ft., swim 30 ft.',
    abilities: { str: 19, dex: 14, con: 12, int: 1, wis: 10, cha: 3 },
    skills: ['Perception +2'],
    senses: ['Blindsight 10 ft.', 'Passive Perception 12'],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 10 ft., one creature. Hit: 11 (2d6+4) piercing damage.', attackBonus: 6, damage: '2d6+4 piercing' },
      { name: 'Constrict', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one creature. Hit: 13 (2d8+4) bludgeoning damage, and the target is grappled (escape DC 16). Until this grapple ends, the creature is restrained, and the snake can\'t constrict another target.', attackBonus: 6, damage: '2d8+4 bludgeoning' },
    ],
    tags: ['beast', 'snake', 'grappler', 'jungle'],
  },
  {
    id: 'beast-winter-wolf',
    name: 'Winter Wolf',
    cr: 3,
    size: 'Large',
    type: 'beast',
    alignment: 'neutral evil',
    armorClass: 13,
    hitPoints: 75,
    hitDice: '10d10+20',
    speed: '50 ft.',
    abilities: { str: 18, dex: 13, con: 14, int: 7, wis: 12, cha: 8 },
    skills: ['Perception +5', 'Stealth +3'],
    senses: ['Passive Perception 15'],
    languages: ['Common', 'Giant', 'Winter Wolf'],
    traits: [
      { name: 'Keen Hearing and Smell', type: 'trait', description: 'The wolf has advantage on Wisdom (Perception) checks that rely on hearing or smell.' },
      { name: 'Pack Tactics', type: 'trait', description: 'The wolf has advantage on an attack roll against a creature if at least one of the wolf\'s allies is adjacent to the creature and the ally isn\'t incapacitated.' },
      { name: 'Snow Camouflage', type: 'trait', description: 'The wolf has advantage on Dexterity (Stealth) checks made to hide in snowy terrain.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 11 (2d6+4) piercing damage. If the target is a creature, it must succeed on a DC 14 Strength saving throw or be knocked prone.', attackBonus: 6, damage: '2d6+4 piercing', saveDc: 14, saveType: 'str' },
      { name: 'Cold Breath (Recharge 5-6)', type: 'ability', description: 'The wolf exhales a blast of freezing wind in a 15-ft. cone. Each creature in that area must make a DC 12 Dexterity saving throw, taking 18 (4d8) cold damage on a failed save, or half as much on a successful one.', saveDc: 12, saveType: 'dex' },
    ],
    tags: ['beast', 'canine', 'cold', 'arctic'],
  },
  {
    id: 'beast-worg',
    name: 'Worg',
    cr: 0.5,
    size: 'Large',
    type: 'beast',
    alignment: 'neutral evil',
    armorClass: 13,
    hitPoints: 26,
    hitDice: '4d10+4',
    speed: '50 ft.',
    abilities: { str: 16, dex: 13, con: 13, int: 7, wis: 11, cha: 8 },
    skills: ['Perception +4'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 14'],
    languages: ['Goblin', 'Worg'],
    traits: [
      { name: 'Keen Hearing and Smell', type: 'trait', description: 'The worg has advantage on Wisdom (Perception) checks that rely on hearing or smell.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6+3) piercing damage. If the target is a creature, it must succeed on a DC 13 Strength saving throw or be knocked prone.', attackBonus: 5, damage: '2d6+3 piercing', saveDc: 13, saveType: 'str' },
    ],
    tags: ['beast', 'canine', 'goblin mount', 'evil'],
  },
  {
    id: 'beast-elephant',
    name: 'Elephant',
    cr: 4,
    size: 'Huge',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 12,
    hitPoints: 76,
    hitDice: '8d12+24',
    speed: '40 ft.',
    abilities: { str: 22, dex: 9, con: 17, int: 3, wis: 11, cha: 6 },
    senses: ['Passive Perception 10'],
    traits: [
      { name: 'Trampling Charge', type: 'trait', description: 'If the elephant moves at least 20 ft. straight toward a creature and then hits it with a gore attack on the same turn, that target must succeed on a DC 12 Strength saving throw or be knocked prone. If the target is prone, the elephant can make one stomp attack against it as a bonus action.', saveDc: 12, saveType: 'str' },
    ],
    actions: [
      { name: 'Gore', type: 'attack', description: 'Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 19 (3d8+6) piercing damage.', attackBonus: 8, damage: '3d8+6 piercing' },
      { name: 'Stomp', type: 'attack', description: 'Melee Weapon Attack: +8 to hit, reach 5 ft., one prone creature. Hit: 22 (3d10+6) bludgeoning damage.', attackBonus: 8, damage: '3d10+6 bludgeoning' },
    ],
    tags: ['beast', 'elephant', 'savanna', 'large'],
  },
  {
    id: 'beast-mammoth',
    name: 'Mammoth',
    cr: 6,
    size: 'Huge',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 13,
    hitPoints: 126,
    hitDice: '11d12+55',
    speed: '40 ft.',
    abilities: { str: 24, dex: 9, con: 21, int: 3, wis: 11, cha: 6 },
    senses: ['Passive Perception 10'],
    traits: [
      { name: 'Trampling Charge', type: 'trait', description: 'If the mammoth moves at least 20 ft. straight toward a creature and then hits it with a gore attack on the same turn, that target must succeed on a DC 18 Strength saving throw or be knocked prone. If the target is prone, the mammoth can make one stomp attack against it as a bonus action.', saveDc: 18, saveType: 'str' },
    ],
    actions: [
      { name: 'Gore', type: 'attack', description: 'Melee Weapon Attack: +10 to hit, reach 10 ft., one target. Hit: 25 (4d8+7) piercing damage.', attackBonus: 10, damage: '4d8+7 piercing' },
      { name: 'Stomp', type: 'attack', description: 'Melee Weapon Attack: +10 to hit, reach 5 ft., one prone creature. Hit: 29 (4d10+7) bludgeoning damage.', attackBonus: 10, damage: '4d10+7 bludgeoning' },
    ],
    tags: ['beast', 'elephant', 'tundra', 'prehistoric'],
  },
  {
    id: 'beast-saber-toothed-tiger',
    name: 'Saber-Toothed Tiger',
    cr: 2,
    size: 'Large',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 12,
    hitPoints: 52,
    hitDice: '7d10+14',
    speed: '40 ft.',
    abilities: { str: 18, dex: 14, con: 15, int: 3, wis: 12, cha: 8 },
    skills: ['Perception +3', 'Stealth +6'],
    senses: ['Passive Perception 13'],
    traits: [
      { name: 'Keen Smell', type: 'trait', description: 'The tiger has advantage on Wisdom (Perception) checks that rely on smell.' },
      { name: 'Pounce', type: 'trait', description: 'If the tiger moves at least 20 ft. straight toward a creature and then hits it with a claw attack on the same turn, that target must succeed on a DC 14 Strength saving throw or be knocked prone. If the target is prone, the tiger can make one bite attack against it as a bonus action.', saveDc: 14, saveType: 'str' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 10 (1d10+5) piercing damage.', attackBonus: 6, damage: '1d10+5 piercing' },
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 12 (2d6+5) slashing damage.', attackBonus: 6, damage: '2d6+5 slashing' },
    ],
    tags: ['beast', 'feline', 'prehistoric', 'large'],
  },
  {
    id: 'beast-giant-boar',
    name: 'Giant Boar',
    cr: 2,
    size: 'Large',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 12,
    hitPoints: 42,
    hitDice: '5d10+15',
    speed: '40 ft.',
    abilities: { str: 17, dex: 10, con: 16, int: 2, wis: 7, cha: 5 },
    senses: ['Passive Perception 8'],
    traits: [
      { name: 'Charge', type: 'trait', description: 'If the boar moves at least 20 ft. straight toward a target and then hits it with a tusk attack on the same turn, the target takes an extra 7 (2d6) slashing damage. If the target is a creature, it must succeed on a DC 13 Strength saving throw or be knocked prone.', saveDc: 13, saveType: 'str' },
      { name: 'Relentless (Recharges after a Short or Long Rest)', type: 'trait', description: 'If the boar takes 10 damage or less that would reduce it to 0 hit points, it is reduced to 1 hit point instead.' },
    ],
    actions: [
      { name: 'Tusk', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6+3) slashing damage.', attackBonus: 5, damage: '2d6+3 slashing' },
    ],
    tags: ['beast', 'boar', 'forest', 'charge'],
  },
  {
    id: 'beast-polar-bear',
    name: 'Polar Bear',
    cr: 2,
    size: 'Large',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 12,
    hitPoints: 42,
    hitDice: '5d10+15',
    speed: '40 ft., swim 30 ft.',
    abilities: { str: 20, dex: 10, con: 16, int: 2, wis: 13, cha: 7 },
    skills: ['Perception +3'],
    senses: ['Passive Perception 13'],
    traits: [
      { name: 'Keen Smell', type: 'trait', description: 'The bear has advantage on Wisdom (Perception) checks that rely on smell.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The bear makes two attacks: one with its bite and one with its claws.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 9 (1d8+5) piercing damage.', attackBonus: 7, damage: '1d8+5 piercing' },
      { name: 'Claws', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 12 (2d6+5) slashing damage.', attackBonus: 7, damage: '2d6+5 slashing' },
    ],
    tags: ['beast', 'bear', 'arctic'],
  },
  {
    id: 'beast-giant-hyena',
    name: 'Giant Hyena',
    cr: 1,
    size: 'Large',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 12,
    hitPoints: 45,
    hitDice: '6d10+12',
    speed: '50 ft.',
    abilities: { str: 16, dex: 14, con: 14, int: 2, wis: 12, cha: 7 },
    skills: ['Perception +3'],
    senses: ['Passive Perception 13'],
    traits: [
      { name: 'Rampage', type: 'trait', description: 'When the hyena reduces a creature to 0 hit points with a melee attack on its turn, the hyena can take a bonus action to move up to half its speed and make a bite attack.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6+3) piercing damage.', attackBonus: 5, damage: '2d6+3 piercing' },
    ],
    tags: ['beast', 'hyena', 'savanna', 'scavenger'],
  },
  {
    id: 'beast-rhinoceros',
    name: 'Rhinoceros',
    cr: 2,
    size: 'Large',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 11,
    hitPoints: 45,
    hitDice: '6d10+12',
    speed: '40 ft.',
    abilities: { str: 21, dex: 8, con: 15, int: 2, wis: 12, cha: 6 },
    senses: ['Passive Perception 11'],
    traits: [
      { name: 'Charge', type: 'trait', description: 'If the rhinoceros moves at least 20 ft. straight toward a target and then hits it with a gore attack on the same turn, the target takes an extra 9 (2d8) bludgeoning damage. If the target is a creature, it must succeed on a DC 15 Strength saving throw or be knocked prone.', saveDc: 15, saveType: 'str' },
    ],
    actions: [
      { name: 'Gore', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 14 (2d8+5) bludgeoning damage.', attackBonus: 7, damage: '2d8+5 bludgeoning' },
    ],
    tags: ['beast', 'savanna', 'charge', 'tough'],
  },
  {
    id: 'beast-hunter-shark',
    name: 'Hunter Shark',
    cr: 2,
    size: 'Large',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 12,
    hitPoints: 45,
    hitDice: '6d10+12',
    speed: '0 ft., swim 40 ft.',
    abilities: { str: 18, dex: 13, con: 15, int: 1, wis: 10, cha: 4 },
    skills: ['Perception +2'],
    senses: ['Blindsight 30 ft.', 'Passive Perception 12'],
    traits: [
      { name: 'Blood Frenzy', type: 'trait', description: 'The shark has advantage on melee attack rolls against any creature that doesn\'t have all its hit points.' },
      { name: 'Water Breathing', type: 'trait', description: 'The shark can breathe only underwater.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 13 (2d8+4) piercing damage.', attackBonus: 6, damage: '2d8+4 piercing' },
    ],
    tags: ['beast', 'shark', 'ocean', 'water'],
  },
  {
    id: 'beast-giant-octopus',
    name: 'Giant Octopus',
    cr: 1,
    size: 'Large',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 11,
    hitPoints: 52,
    hitDice: '8d10+8',
    speed: '10 ft., swim 60 ft.',
    abilities: { str: 17, dex: 13, con: 13, int: 4, wis: 10, cha: 4 },
    skills: ['Perception +4', 'Stealth +5'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 14'],
    traits: [
      { name: 'Hold Breath', type: 'trait', description: 'While out of water, the octopus can hold its breath for 1 hour.' },
      { name: 'Underwater Camouflage', type: 'trait', description: 'The octopus has advantage on Dexterity (Stealth) checks made while underwater.' },
      { name: 'Water Breathing', type: 'trait', description: 'The octopus can breathe only underwater.' },
    ],
    actions: [
      { name: 'Tentacles', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 15 ft., one target. Hit: 10 (2d6+3) bludgeoning damage. If the target is a creature, it is grappled (escape DC 16). Until this grapple ends, the target is restrained, and the octopus can\'t use its tentacles on another target.', attackBonus: 5, damage: '2d6+3 bludgeoning' },
      { name: 'Ink Cloud (Recharges after a Short or Long Rest)', type: 'ability', description: 'A 20-ft. radius cloud of ink extends all around the octopus if it is underwater. The area is heavily obscured for 1 minute, although a significant current can disperse the ink. After releasing the ink, the octopus can use the Dash action as a bonus action.' },
    ],
    tags: ['beast', 'octopus', 'water', 'grappler'],
  },
  {
    id: 'beast-panther',
    name: 'Panther',
    cr: 0.25,
    size: 'Medium',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 12,
    hitPoints: 13,
    hitDice: '3d8',
    speed: '50 ft., climb 40 ft.',
    abilities: { str: 14, dex: 15, con: 10, int: 3, wis: 14, cha: 7 },
    skills: ['Perception +4', 'Stealth +6'],
    senses: ['Passive Perception 14'],
    traits: [
      { name: 'Keen Smell', type: 'trait', description: 'The panther has advantage on Wisdom (Perception) checks that rely on smell.' },
      { name: 'Pounce', type: 'trait', description: 'If the panther moves at least 20 ft. straight toward a creature and then hits it with a claw attack on the same turn, that target must succeed on a DC 12 Strength saving throw or be knocked prone. If the target is prone, the panther can make one bite attack against it as a bonus action.', saveDc: 12, saveType: 'str' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6+2) piercing damage.', attackBonus: 4, damage: '1d6+2 piercing' },
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4+2) slashing damage.', attackBonus: 4, damage: '1d4+2 slashing' },
    ],
    tags: ['beast', 'feline', 'jungle', 'stealthy'],
  },
  // ─── SMALL BEASTS ─────────────────────────────────────────────────────────
  {
    id: 'beast-rat',
    name: 'Rat',
    cr: 0,
    size: 'Tiny',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 10,
    hitPoints: 1,
    hitDice: '1d4-1',
    speed: '20 ft.',
    abilities: { str: 2, dex: 11, con: 9, int: 2, wis: 10, cha: 4 },
    senses: ['Darkvision 30 ft.', 'Passive Perception 10'],
    traits: [
      { name: 'Keen Smell', type: 'trait', description: 'The rat has advantage on Wisdom (Perception) checks that rely on smell.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +0 to hit, reach 5 ft., one target. Hit: 1 piercing damage.', attackBonus: 0, damage: '1 piercing' },
    ],
    tags: ['beast', 'rodent', 'tiny', 'vermin'],
  },
  {
    id: 'beast-bat',
    name: 'Bat',
    cr: 0,
    size: 'Tiny',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 12,
    hitPoints: 1,
    hitDice: '1d4-1',
    speed: '5 ft., fly 30 ft.',
    abilities: { str: 2, dex: 15, con: 8, int: 2, wis: 12, cha: 4 },
    senses: ['Blindsight 60 ft.', 'Passive Perception 11'],
    traits: [
      { name: 'Echolocation', type: 'trait', description: 'The bat can\'t use its blindsight while deafened.' },
      { name: 'Keen Hearing', type: 'trait', description: 'The bat has advantage on Wisdom (Perception) checks that rely on hearing.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +0 to hit, reach 5 ft., one creature. Hit: 1 piercing damage.', attackBonus: 0, damage: '1 piercing' },
    ],
    tags: ['beast', 'bat', 'tiny', 'flying'],
  },
  {
    id: 'beast-giant-bat',
    name: 'Giant Bat',
    cr: 0.25,
    size: 'Large',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 13,
    hitPoints: 22,
    hitDice: '4d10',
    speed: '10 ft., fly 60 ft.',
    abilities: { str: 15, dex: 16, con: 11, int: 2, wis: 12, cha: 6 },
    senses: ['Blindsight 60 ft.', 'Passive Perception 11'],
    traits: [
      { name: 'Echolocation', type: 'trait', description: 'The bat can\'t use its blindsight while deafened.' },
      { name: 'Keen Hearing', type: 'trait', description: 'The bat has advantage on Wisdom (Perception) checks that rely on hearing.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 5 (1d6+2) piercing damage.', attackBonus: 4, damage: '1d6+2 piercing' },
    ],
    tags: ['beast', 'bat', 'flying', 'cave'],
  },
  {
    id: 'beast-giant-rat',
    name: 'Giant Rat',
    cr: 0.125,
    size: 'Small',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 12,
    hitPoints: 7,
    hitDice: '2d6',
    speed: '30 ft.',
    abilities: { str: 7, dex: 15, con: 11, int: 2, wis: 10, cha: 4 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 10'],
    traits: [
      { name: 'Keen Smell', type: 'trait', description: 'The rat has advantage on Wisdom (Perception) checks that rely on smell.' },
      { name: 'Pack Tactics', type: 'trait', description: 'The rat has advantage on an attack roll against a creature if at least one of the rat\'s allies is adjacent to the creature and the ally isn\'t incapacitated.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4+2) piercing damage.', attackBonus: 4, damage: '1d4+2 piercing' },
    ],
    tags: ['beast', 'rodent', 'small', 'vermin'],
  },
  {
    id: 'beast-giant-wolf-spider',
    name: 'Giant Wolf Spider',
    cr: 0.25,
    size: 'Medium',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 13,
    hitPoints: 11,
    hitDice: '2d8+2',
    speed: '40 ft., climb 40 ft.',
    abilities: { str: 12, dex: 16, con: 13, int: 3, wis: 12, cha: 4 },
    skills: ['Perception +3', 'Stealth +7'],
    senses: ['Blindsight 10 ft.', 'Darkvision 60 ft.', 'Passive Perception 13'],
    traits: [
      { name: 'Spider Climb', type: 'trait', description: 'The spider can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check.' },
      { name: 'Web Sense', type: 'trait', description: 'While in contact with a web, the spider knows the exact location of any other creature in contact with the same web.' },
      { name: 'Web Walker', type: 'trait', description: 'The spider ignores movement restrictions caused by webbing.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one creature. Hit: 4 (1d6+1) piercing damage, and the target must make a DC 11 Constitution saving throw, taking 7 (2d6) poison damage on a failed save, or half as much on a successful one. If the poison damage reduces the target to 0 hit points, the target is stable but poisoned for 1 hour even after regaining hit points, and is paralyzed while poisoned in this way.', attackBonus: 3, damage: '1d6+1 piercing', saveDc: 11, saveType: 'con' },
    ],
    tags: ['beast', 'spider', 'poison'],
  },
  // ─── SWARMS ───────────────────────────────────────────────────────────────
  {
    id: 'beast-swarm-of-rats',
    name: 'Swarm of Rats',
    cr: 0.25,
    size: 'Medium',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 10,
    hitPoints: 24,
    hitDice: '7d8-7',
    speed: '30 ft.',
    abilities: { str: 9, dex: 11, con: 9, int: 2, wis: 10, cha: 3 },
    senses: ['Darkvision 30 ft.', 'Passive Perception 10'],
    traits: [
      { name: 'Keen Smell', type: 'trait', description: 'The swarm has advantage on Wisdom (Perception) checks that rely on smell.' },
      { name: 'Swarm', type: 'trait', description: 'The swarm can occupy another creature\'s space and vice versa, and the swarm can move through any opening large enough for a Tiny rat. The swarm can\'t regain hit points or gain temporary hit points.' },
    ],
    actions: [
      { name: 'Bites', type: 'attack', description: 'Melee Weapon Attack: +2 to hit, reach 0 ft., one target in the swarm\'s space. Hit: 7 (2d6) piercing damage, or 3 (1d6) piercing damage if the swarm has half of its hit points or fewer.', attackBonus: 2, damage: '2d6 piercing' },
    ],
    tags: ['beast', 'swarm', 'rodent', 'vermin'],
  },
  {
    id: 'beast-swarm-of-bats',
    name: 'Swarm of Bats',
    cr: 0.25,
    size: 'Medium',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 12,
    hitPoints: 22,
    hitDice: '5d8',
    speed: '0 ft., fly 30 ft.',
    abilities: { str: 5, dex: 15, con: 10, int: 2, wis: 12, cha: 4 },
    senses: ['Blindsight 60 ft.', 'Passive Perception 11'],
    traits: [
      { name: 'Echolocation', type: 'trait', description: 'The swarm can\'t use its blindsight while deafened.' },
      { name: 'Keen Hearing', type: 'trait', description: 'The swarm has advantage on Wisdom (Perception) checks that rely on hearing.' },
      { name: 'Swarm', type: 'trait', description: 'The swarm can occupy another creature\'s space and vice versa, and the swarm can move through any opening large enough for a Tiny bat. The swarm can\'t regain hit points or gain temporary hit points.' },
    ],
    actions: [
      { name: 'Bites', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 0 ft., one creature in the swarm\'s space. Hit: 5 (2d4) piercing damage, or 2 (1d4) piercing damage if the swarm has half of its hit points or fewer.', attackBonus: 4, damage: '2d4 piercing' },
    ],
    tags: ['beast', 'swarm', 'bat', 'cave'],
  },
  {
    id: 'beast-swarm-of-insects',
    name: 'Swarm of Insects',
    cr: 0.5,
    size: 'Medium',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 12,
    hitPoints: 22,
    hitDice: '5d8',
    speed: '20 ft., climb 20 ft.',
    abilities: { str: 3, dex: 13, con: 10, int: 1, wis: 7, cha: 1 },
    senses: ['Blindsight 10 ft.', 'Passive Perception 8'],
    traits: [
      { name: 'Swarm', type: 'trait', description: 'The swarm can occupy another creature\'s space and vice versa, and the swarm can move through any opening large enough for a Tiny insect. The swarm can\'t regain hit points or gain temporary hit points.' },
    ],
    actions: [
      { name: 'Bites', type: 'attack', description: 'Melee Weapon Attack: +3 to hit, reach 0 ft., one target in the swarm\'s space. Hit: 10 (4d4) piercing damage, or 5 (2d4) piercing damage if the swarm has half of its hit points or fewer.', attackBonus: 3, damage: '4d4 piercing' },
    ],
    tags: ['beast', 'swarm', 'insect', 'vermin'],
  },
  // ─── RIDING/WORK ANIMALS ──────────────────────────────────────────────────
  {
    id: 'beast-riding-horse',
    name: 'Riding Horse',
    cr: 0.25,
    size: 'Large',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 10,
    hitPoints: 13,
    hitDice: '2d10+2',
    speed: '60 ft.',
    abilities: { str: 16, dex: 10, con: 12, int: 2, wis: 11, cha: 7 },
    senses: ['Passive Perception 10'],
    actions: [
      { name: 'Hooves', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 8 (2d4+3) bludgeoning damage.', attackBonus: 5, damage: '2d4+3 bludgeoning' },
    ],
    tags: ['beast', 'horse', 'mount', 'common'],
  },
  {
    id: 'beast-warhorse',
    name: 'Warhorse',
    cr: 0.5,
    size: 'Large',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 11,
    hitPoints: 19,
    hitDice: '3d10+3',
    speed: '60 ft.',
    abilities: { str: 18, dex: 12, con: 13, int: 2, wis: 12, cha: 7 },
    senses: ['Passive Perception 11'],
    traits: [
      { name: 'Trampling Charge', type: 'trait', description: 'If the horse moves at least 20 ft. straight toward a creature and then hits it with a hooves attack on the same turn, that target must succeed on a DC 14 Strength saving throw or be knocked prone. If the target is prone, the horse can make another attack with its hooves against it as a bonus action.', saveDc: 14, saveType: 'str' },
    ],
    actions: [
      { name: 'Hooves', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 11 (2d6+4) bludgeoning damage.', attackBonus: 6, damage: '2d6+4 bludgeoning' },
    ],
    tags: ['beast', 'horse', 'mount', 'combat'],
  },
  {
    id: 'beast-mastiff',
    name: 'Mastiff',
    cr: 0.125,
    size: 'Medium',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 12,
    hitPoints: 5,
    hitDice: '1d8+1',
    speed: '40 ft.',
    abilities: { str: 13, dex: 14, con: 12, int: 3, wis: 12, cha: 7 },
    skills: ['Perception +3'],
    senses: ['Passive Perception 13'],
    traits: [
      { name: 'Keen Hearing and Smell', type: 'trait', description: 'The mastiff has advantage on Wisdom (Perception) checks that rely on hearing or smell.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6+1) piercing damage. If the target is a creature, it must succeed on a DC 11 Strength saving throw or be knocked prone.', attackBonus: 3, damage: '1d6+1 piercing', saveDc: 11, saveType: 'str' },
    ],
    tags: ['beast', 'dog', 'mount', 'guard'],
  },
  {
    id: 'beast-giant-centipede',
    name: 'Giant Centipede',
    cr: 0.25,
    size: 'Small',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 13,
    hitPoints: 4,
    hitDice: '1d6+1',
    speed: '30 ft., climb 30 ft.',
    abilities: { str: 5, dex: 14, con: 12, int: 1, wis: 7, cha: 3 },
    senses: ['Blindsight 30 ft.', 'Passive Perception 8'],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 4 (1d4+2) piercing damage, and the target must succeed on a DC 11 Constitution saving throw or take 10 (3d6) poison damage. If the poison damage reduces the target to 0 hit points, the target is stable but poisoned for 1 hour even after regaining hit points, and is paralyzed while poisoned in this way.', attackBonus: 4, damage: '1d4+2 piercing', saveDc: 11, saveType: 'con' },
    ],
    tags: ['beast', 'insect', 'poison', 'small'],
  },
  {
    id: 'beast-poisonous-snake',
    name: 'Poisonous Snake',
    cr: 0.125,
    size: 'Tiny',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 13,
    hitPoints: 2,
    hitDice: '1d4',
    speed: '30 ft., swim 30 ft.',
    abilities: { str: 2, dex: 16, con: 11, int: 1, wis: 10, cha: 3 },
    senses: ['Blindsight 10 ft.', 'Passive Perception 10'],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 1 piercing damage, and the target must make a DC 10 Constitution saving throw, taking 5 (2d4) poison damage on a failed save, or half as much on a successful one.', attackBonus: 5, damage: '1 piercing', saveDc: 10, saveType: 'con' },
    ],
    tags: ['beast', 'snake', 'tiny', 'poison'],
  },
  {
    id: 'beast-giant-poisonous-snake',
    name: 'Giant Poisonous Snake',
    cr: 0.25,
    size: 'Medium',
    type: 'beast',
    alignment: 'unaligned',
    armorClass: 14,
    hitPoints: 11,
    hitDice: '2d8+2',
    speed: '30 ft., swim 30 ft.',
    abilities: { str: 10, dex: 18, con: 13, int: 2, wis: 10, cha: 3 },
    skills: ['Perception +2'],
    senses: ['Blindsight 10 ft.', 'Passive Perception 12'],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 10 ft., one target. Hit: 6 (1d4+4) piercing damage, and the target must make a DC 11 Constitution saving throw, taking 10 (3d6) poison damage on a failed save, or half as much on a successful one.', attackBonus: 6, damage: '1d4+4 piercing', saveDc: 11, saveType: 'con' },
    ],
    tags: ['beast', 'snake', 'poison'],
  },
  {
    id: 'beast-death-dog',
    name: 'Death Dog',
    cr: 1,
    size: 'Medium',
    type: 'beast',
    alignment: 'neutral evil',
    armorClass: 12,
    hitPoints: 39,
    hitDice: '6d8+12',
    speed: '40 ft.',
    abilities: { str: 15, dex: 14, con: 14, int: 3, wis: 13, cha: 6 },
    skills: ['Perception +5', 'Stealth +4'],
    senses: ['Darkvision 120 ft.', 'Passive Perception 15'],
    traits: [
      { name: 'Two-Headed', type: 'trait', description: 'The dog has advantage on Wisdom (Perception) checks and on saving throws against being blinded, charmed, deafened, frightened, stunned, or knocked unconscious.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The dog makes two bite attacks.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6+2) piercing damage. If the target is a creature, it must succeed on a DC 12 Constitution saving throw against disease or until the disease is cured, the target can\'t regain hit points except by magical means, and the target\'s hit point maximum decreases by 5 (1d10) every 24 hours.', attackBonus: 4, damage: '1d6+2 piercing', saveDc: 12, saveType: 'con' },
    ],
    tags: ['beast', 'canine', 'two-headed', 'disease', 'underdark'],
  },
]
