import type { Monster } from './types'

export const CELESTIALS: Monster[] = [
  {
    id: 'celestial-couatl',
    name: 'Couatl',
    cr: 4,
    size: 'Medium',
    type: 'celestial',
    alignment: 'lawful good',
    armorClass: 19,
    hitPoints: 97,
    hitDice: '13d8+39',
    speed: '30 ft., fly 90 ft.',
    abilities: { str: 16, dex: 20, con: 17, int: 18, wis: 20, cha: 18 },
    senses: ['Truesight 120 ft.', 'Passive Perception 15'],
    languages: ['all languages', 'telepathy 120 ft.'],
    traits: [
      { name: 'Innate Spellcasting', type: 'trait', description: 'The couatl\'s innate spellcasting ability is Charisma (spell save DC 14). It can innately cast the following spells requiring no material components. At will: detect evil and good, detect magic, detect thoughts. 3/day each: bless, create food and water, cure wounds, lesser restoration, protection from poison, sanctuary, shield. 1/day each: dream, greater restoration, scrying.' },
      { name: 'Magic Weapons', type: 'trait', description: 'The couatl\'s weapon attacks are magical.' },
      { name: 'Shielded Mind', type: 'trait', description: 'The couatl is immune to scrying and to any effect that would sense its emotions, read its thoughts, or detect its location.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +8 to hit, reach 5 ft., one creature. Hit: 8 (1d6+5) piercing damage, and the target must succeed on a DC 13 Constitution saving throw or be poisoned for 24 hours. Until this poison ends, the target is unconscious.', attackBonus: 8, damage: '1d6+5 piercing', saveDc: 13, saveType: 'con' },
      { name: 'Constrict', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 10 ft., one Medium or smaller creature. Hit: 10 (2d6+3) bludgeoning damage, and the target is grappled (escape DC 15). Until this grapple ends, the target is restrained.', attackBonus: 6, damage: '2d6+3 bludgeoning' },
      { name: 'Change Shape', type: 'ability', description: 'The couatl magically polymorphs into a humanoid or beast that has a challenge rating equal to or less than its own, or back into its true form. It reverts to its true form if it dies.' },
    ],
    tags: ['celestial', 'serpent', 'spellcaster'],
  },
  {
    id: 'celestial-deva',
    name: 'Deva',
    cr: 10,
    size: 'Medium',
    type: 'celestial',
    alignment: 'lawful good',
    armorClass: 17,
    hitPoints: 136,
    hitDice: '16d8+64',
    speed: '30 ft., fly 90 ft.',
    abilities: { str: 18, dex: 18, con: 18, int: 17, wis: 20, cha: 20 },
    skills: ['Insight +9', 'Perception +9'],
    senses: ['Darkvision 120 ft.', 'Passive Perception 19'],
    languages: ['all languages', 'telepathy 120 ft.'],
    traits: [
      { name: 'Angelic Weapons', type: 'trait', description: 'The deva\'s weapon attacks are magical. When the deva hits with any weapon, the weapon deals an extra 4d8 radiant damage (included in the attack).' },
      { name: 'Innate Spellcasting', type: 'trait', description: 'The deva\'s innate spellcasting ability is Charisma (spell save DC 17). It can innately cast the following spells requiring only verbal components. At will: detect evil and good. 1/day each: commune, raise dead.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The deva has advantage on saving throws against spells and other magical effects.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The deva makes two melee attacks.' },
      { name: 'Mace', type: 'attack', description: 'Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 7 (1d6+4) bludgeoning damage plus 18 (4d8) radiant damage.', attackBonus: 8, damage: '1d6+4 bludgeoning + 4d8 radiant' },
      { name: 'Healing Touch (3/Day)', type: 'ability', description: 'The deva touches another creature. The target magically regains 20 (4d8+2) hit points and is freed from any curse, disease, poison, blindness, or deafness.' },
      { name: 'Change Shape', type: 'ability', description: 'The deva magically polymorphs into a humanoid or beast that has a challenge rating equal to or less than its own, or back into its true form.' },
    ],
    tags: ['angel', 'celestial', 'legendary'],
  },
  {
    id: 'celestial-pegasus',
    name: 'Pegasus',
    cr: 2,
    size: 'Large',
    type: 'celestial',
    alignment: 'chaotic good',
    armorClass: 12,
    hitPoints: 59,
    hitDice: '7d10+21',
    speed: '60 ft., fly 90 ft.',
    abilities: { str: 18, dex: 15, con: 16, int: 10, wis: 15, cha: 13 },
    skills: ['Perception +6'],
    senses: ['Passive Perception 16'],
    languages: ['understands Celestial, Common, Elvish, and Sylvan but cannot speak'],
    actions: [
      { name: 'Hooves', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 11 (2d6+4) bludgeoning damage.', attackBonus: 6, damage: '2d6+4 bludgeoning' },
    ],
    tags: ['mount', 'flying'],
  },
  {
    id: 'celestial-planetar',
    name: 'Planetar',
    cr: 16,
    size: 'Large',
    type: 'celestial',
    alignment: 'lawful good',
    armorClass: 19,
    hitPoints: 200,
    hitDice: '16d10+112',
    speed: '40 ft., fly 120 ft.',
    abilities: { str: 24, dex: 20, con: 24, int: 19, wis: 22, cha: 25 },
    skills: ['Perception +11', 'Insight +11'],
    senses: ['Truesight 120 ft.', 'Passive Perception 21'],
    languages: ['all languages', 'telepathy 120 ft.'],
    traits: [
      { name: 'Angelic Weapons', type: 'trait', description: 'The planetar\'s weapon attacks are magical. When the planetar hits with any weapon, the weapon deals an extra 5d8 radiant damage (included in the attack).' },
      { name: 'Divine Awareness', type: 'trait', description: 'The planetar knows if it hears a lie.' },
      { name: 'Innate Spellcasting', type: 'trait', description: 'Spell save DC 20. At will: detect evil and good, invisibility (self only). 3/day each: blade barrier, dispel evil and good, flame strike, raise dead. 1/day each: commune, control weather, insect plague.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The planetar has advantage on saving throws against spells and other magical effects.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The planetar makes two melee attacks.' },
      { name: 'Greatsword', type: 'attack', description: 'Melee Weapon Attack: +12 to hit, reach 5 ft., one target. Hit: 21 (4d6+7) slashing damage plus 22 (5d8) radiant damage.', attackBonus: 12, damage: '4d6+7 slashing + 5d8 radiant' },
      { name: 'Healing Touch (4/Day)', type: 'ability', description: 'The planetar touches another creature. The target magically regains 30 (6d8+3) hit points and is freed from any curse, disease, poison, blindness, or deafness.' },
    ],
    tags: ['angel', 'celestial', 'legendary'],
  },
  {
    id: 'celestial-solar',
    name: 'Solar',
    cr: 21,
    size: 'Large',
    type: 'celestial',
    alignment: 'lawful good',
    armorClass: 21,
    hitPoints: 243,
    hitDice: '18d10+144',
    speed: '50 ft., fly 150 ft.',
    abilities: { str: 26, dex: 22, con: 26, int: 25, wis: 25, cha: 30 },
    skills: ['Perception +14', 'Insight +14'],
    senses: ['Truesight 120 ft.', 'Passive Perception 24'],
    languages: ['all languages', 'telepathy 120 ft.'],
    traits: [
      { name: 'Angelic Weapons', type: 'trait', description: 'The solar\'s weapon attacks are magical. When the solar hits with any weapon, the weapon deals an extra 6d8 radiant damage.' },
      { name: 'Divine Awareness', type: 'trait', description: 'The solar knows if it hears a lie.' },
      { name: 'Innate Spellcasting', type: 'trait', description: 'Spell save DC 23. At will: detect evil and good, invisibility (self only). 3/day each: blade barrier, dispel evil and good, resurrection. 1/day each: commune, control weather.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The solar has advantage on saving throws against spells and other magical effects.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The solar makes two greatsword attacks.' },
      { name: 'Greatsword', type: 'attack', description: 'Melee Weapon Attack: +15 to hit, reach 5 ft., one target. Hit: 22 (4d6+8) slashing damage plus 27 (6d8) radiant damage.', attackBonus: 15, damage: '4d6+8 slashing + 6d8 radiant' },
      { name: 'Slaying Longbow', type: 'attack', description: 'Ranged Weapon Attack: +13 to hit, range 150/600 ft., one target. Hit: 15 (2d8+6) piercing damage plus 27 (6d8) radiant damage. If the target is a creature that has fewer than 100 HP, it must succeed on a DC 15 Constitution saving throw or die.', attackBonus: 13, damage: '2d8+6 piercing + 6d8 radiant', saveDc: 15, saveType: 'con' },
      { name: 'Healing Touch (4/Day)', type: 'ability', description: 'The solar touches another creature. The target magically regains 40 (8d8+4) hit points and is freed from any curse, disease, poison, blindness, or deafness.' },
      { name: 'Change Shape', type: 'ability', description: 'The solar magically polymorphs into a humanoid or beast that has a challenge rating equal to or less than its own, or back into its true form.' },
    ],
    legendaryActions: [
      { name: 'Teleport', type: 'ability', description: 'The solar magically teleports, along with any equipment it is wearing or carrying, up to 120 ft. to an unoccupied space it can see.' },
      { name: 'Searing Burst (Costs 2 Actions)', type: 'ability', description: 'The solar emits magical, divine energy. Each creature of its choice in a 10-ft. radius must make a DC 23 Dexterity saving throw, taking 14 (4d6) fire damage plus 14 (4d6) radiant damage on a failed save, or half on a success.', saveDc: 23, saveType: 'dex' },
      { name: 'Blinding Gaze (Costs 3 Actions)', type: 'ability', description: 'The solar targets one creature it can see within 30 ft. If the target can see it, the target must succeed on a DC 15 Constitution saving throw or be blinded until magic such as the lesser restoration spell removes the blindness.', saveDc: 15, saveType: 'con' },
    ],
    tags: ['angel', 'celestial', 'legendary', 'mythic'],
  },
  {
    id: 'celestial-unicorn',
    name: 'Unicorn',
    cr: 5,
    size: 'Large',
    type: 'celestial',
    alignment: 'lawful good',
    armorClass: 12,
    hitPoints: 67,
    hitDice: '9d10+18',
    speed: '50 ft.',
    abilities: { str: 18, dex: 14, con: 15, int: 11, wis: 17, cha: 16 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 13'],
    languages: ['Celestial', 'Elvish', 'Sylvan', 'telepathy 60 ft.'],
    traits: [
      { name: 'Charge', type: 'trait', description: 'If the unicorn moves at least 20 ft. straight toward a target and then hits it with a horn attack, the target takes an extra 9 (2d8) piercing damage. If the target is a creature, it must succeed on a DC 15 Strength saving throw or be knocked prone.', saveDc: 15, saveType: 'str' },
      { name: 'Innate Spellcasting', type: 'trait', description: 'Spell save DC 14. At will: detect evil and good, druidcraft, pass without trace. 1/day each: calm emotions, dispel evil and good, entangle.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The unicorn has advantage on saving throws against spells and other magical effects.' },
      { name: 'Magic Weapons', type: 'trait', description: 'The unicorn\'s weapon attacks are magical.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The unicorn makes two attacks: one with its hooves and one with its horn.' },
      { name: 'Hooves', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 11 (2d6+4) bludgeoning damage.', attackBonus: 7, damage: '2d6+4 bludgeoning' },
      { name: 'Horn', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 8 (1d8+4) piercing damage.', attackBonus: 7, damage: '1d8+4 piercing' },
      { name: 'Healing Touch (3/Day)', type: 'ability', description: 'The unicorn touches another creature with its horn. The target magically regains 11 (2d8+2) hit points. In addition, the touch removes all diseases and neutralizes all poisons afflicting the target.' },
      { name: 'Teleport (1/Day)', type: 'ability', description: 'The unicorn magically teleports itself and up to three willing creatures it can see within 5 ft. of it, along with any equipment they are wearing or carrying, to a location the unicorn is familiar with, up to 1 mile away.' },
    ],
    legendaryActions: [
      { name: 'Hooves', type: 'attack', description: 'The unicorn makes one attack with its hooves.', attackBonus: 7, damage: '2d6+4 bludgeoning' },
      { name: 'Shimmering Shield (Costs 2 Actions)', type: 'ability', description: 'The unicorn creates a shimmering, magical field around itself or another creature it can see within 60 ft. The target gains a +2 bonus to AC until the end of the unicorn\'s next turn.' },
      { name: 'Heal Self (Costs 3 Actions)', type: 'ability', description: 'The unicorn magically regains 11 (2d8+2) hit points.' },
    ],
    tags: ['legendary', 'fey forest', 'healer'],
  },
]
