import type { Monster } from './types'

export const CONSTRUCTS: Monster[] = [
  {
    id: 'construct-animated-armor',
    name: 'Animated Armor',
    cr: 1,
    size: 'Medium',
    type: 'construct',
    alignment: 'unaligned',
    armorClass: 18,
    hitPoints: 33,
    hitDice: '6d8+6',
    speed: '25 ft.',
    abilities: { str: 14, dex: 11, con: 13, int: 1, wis: 3, cha: 1 },
    senses: ['Blindsight 60 ft. (blind beyond this radius)', 'Passive Perception 6'],
    traits: [
      { name: 'Antimagic Susceptibility', type: 'trait', description: 'The armor is incapacitated while in the area of an antimagic field. If targeted by dispel magic, the armor must succeed on a Constitution saving throw against the caster\'s spell save DC or fall unconscious for 1 minute.' },
      { name: 'False Appearance', type: 'trait', description: 'While the armor remains motionless, it is indistinguishable from a normal suit of armor.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The armor makes two melee attacks.' },
      { name: 'Slam', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6+2) bludgeoning damage.', attackBonus: 4, damage: '1d6+2 bludgeoning' },
    ],
    tags: ['construct', 'guardian'],
  },
  {
    id: 'construct-clay-golem',
    name: 'Clay Golem',
    cr: 9,
    size: 'Large',
    type: 'construct',
    alignment: 'unaligned',
    armorClass: 14,
    hitPoints: 133,
    hitDice: '14d10+56',
    speed: '20 ft.',
    abilities: { str: 20, dex: 9, con: 18, int: 3, wis: 8, cha: 1 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 9'],
    languages: ['understands the languages of its creator but cannot speak'],
    traits: [
      { name: 'Acid Absorption', type: 'trait', description: 'Whenever the golem is subjected to acid damage, it takes no damage and instead regains a number of hit points equal to the acid damage dealt.' },
      { name: 'Berserk', type: 'trait', description: 'Whenever the golem starts its turn with 60 hit points or fewer, roll a d6. On a 6, the golem goes berserk. On each of its turns while berserk, the golem attacks the nearest creature it can see. The golem becomes docile if restored to more than 60 HP.' },
      { name: 'Immutable Form', type: 'trait', description: 'The golem is immune to any spell or effect that would alter its form.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The golem has advantage on saving throws against spells and other magical effects.' },
      { name: 'Magic Weapons', type: 'trait', description: 'The golem\'s weapon attacks are magical.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The golem makes two slam attacks.' },
      { name: 'Slam', type: 'attack', description: 'Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 16 (2d10+5) bludgeoning damage. If the target is a creature, it must succeed on a DC 15 Constitution saving throw or have its hit point maximum reduced by the damage taken.', attackBonus: 8, damage: '2d10+5 bludgeoning', saveDc: 15, saveType: 'con' },
      { name: 'Haste (Recharge 5-6)', type: 'ability', description: 'Until the end of its next turn, the golem magically gains a +2 bonus to its AC, has advantage on Dexterity saving throws, and can make one additional slam attack whenever it takes the Attack action.' },
    ],
    tags: ['golem', 'construct', 'guardian'],
  },
  {
    id: 'construct-flesh-golem',
    name: 'Flesh Golem',
    cr: 5,
    size: 'Medium',
    type: 'construct',
    alignment: 'neutral',
    armorClass: 9,
    hitPoints: 93,
    hitDice: '11d8+44',
    speed: '30 ft.',
    abilities: { str: 19, dex: 9, con: 18, int: 6, wis: 10, cha: 5 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 10'],
    languages: ['understands the languages of its creator but speaks in broken sentences'],
    traits: [
      { name: 'Berserk', type: 'trait', description: 'Whenever the golem starts its turn with 40 hit points or fewer, roll a d6. On a 6, it goes berserk. On each of its turns while berserk, the golem attacks the nearest creature it can see.' },
      { name: 'Aversion of Fire', type: 'trait', description: 'If the golem takes fire damage, it has disadvantage on attack rolls and ability checks until the end of its next turn.' },
      { name: 'Immutable Form', type: 'trait', description: 'The golem is immune to any spell or effect that would alter its form.' },
      { name: 'Lightning Absorption', type: 'trait', description: 'Whenever the golem is subjected to lightning damage, it takes no damage and instead regains HP equal to the lightning damage dealt.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The golem has advantage on saving throws against spells and other magical effects.' },
      { name: 'Magic Weapons', type: 'trait', description: 'The golem\'s weapon attacks are magical.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The golem makes two slam attacks.' },
      { name: 'Slam', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 13 (2d8+4) bludgeoning damage.', attackBonus: 7, damage: '2d8+4 bludgeoning' },
    ],
    tags: ['golem', 'construct', 'frankenstein'],
  },
  {
    id: 'construct-flying-sword',
    name: 'Flying Sword',
    cr: 0.25,
    size: 'Small',
    type: 'construct',
    alignment: 'unaligned',
    armorClass: 17,
    hitPoints: 17,
    hitDice: '5d6',
    speed: '0 ft., fly 50 ft. (hover)',
    abilities: { str: 12, dex: 15, con: 11, int: 1, wis: 5, cha: 1 },
    senses: ['Blindsight 60 ft. (blind beyond this radius)', 'Passive Perception 7'],
    traits: [
      { name: 'Antimagic Susceptibility', type: 'trait', description: 'The sword is incapacitated while in the area of an antimagic field. If targeted by dispel magic, the sword must succeed on a Constitution saving throw against the caster\'s spell save DC or fall unconscious for 1 minute.' },
      { name: 'False Appearance', type: 'trait', description: 'While the sword remains motionless and isn\'t flying, it is indistinguishable from a normal sword.' },
    ],
    actions: [
      { name: 'Longsword', type: 'attack', description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 5 (1d8+1) slashing damage.', attackBonus: 3, damage: '1d8+1 slashing' },
    ],
    tags: ['construct', 'weapon'],
  },
  {
    id: 'construct-iron-golem',
    name: 'Iron Golem',
    cr: 16,
    size: 'Large',
    type: 'construct',
    alignment: 'unaligned',
    armorClass: 20,
    hitPoints: 210,
    hitDice: '20d10+100',
    speed: '30 ft.',
    abilities: { str: 24, dex: 9, con: 20, int: 3, wis: 11, cha: 1 },
    senses: ['Darkvision 120 ft.', 'Passive Perception 10'],
    languages: ['understands the languages of its creator but cannot speak'],
    traits: [
      { name: 'Fire Absorption', type: 'trait', description: 'Whenever the golem is subjected to fire damage, it takes no damage and instead regains HP equal to the fire damage dealt.' },
      { name: 'Immutable Form', type: 'trait', description: 'The golem is immune to any spell or effect that would alter its form.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The golem has advantage on saving throws against spells and other magical effects.' },
      { name: 'Magic Weapons', type: 'trait', description: 'The golem\'s weapon attacks are magical.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The golem makes two melee attacks.' },
      { name: 'Slam', type: 'attack', description: 'Melee Weapon Attack: +13 to hit, reach 5 ft., one target. Hit: 20 (3d8+7) bludgeoning damage.', attackBonus: 13, damage: '3d8+7 bludgeoning' },
      { name: 'Sword', type: 'attack', description: 'Melee Weapon Attack: +13 to hit, reach 10 ft., one target. Hit: 23 (3d10+7) slashing damage.', attackBonus: 13, damage: '3d10+7 slashing' },
      { name: 'Poison Breath (Recharge 6)', type: 'ability', description: 'The golem exhales poisonous gas in a 15-ft. cone. Each creature in that area must make a DC 19 Constitution saving throw, taking 45 (10d8) poison damage on a failed save, or half as much on a successful one.', saveDc: 19, saveType: 'con' },
    ],
    tags: ['golem', 'construct', 'legendary guardian'],
  },
  {
    id: 'construct-rug-of-smothering',
    name: 'Rug of Smothering',
    cr: 2,
    size: 'Large',
    type: 'construct',
    alignment: 'unaligned',
    armorClass: 12,
    hitPoints: 33,
    hitDice: '6d10',
    speed: '10 ft.',
    abilities: { str: 17, dex: 14, con: 10, int: 1, wis: 3, cha: 1 },
    senses: ['Blindsight 60 ft. (blind beyond this radius)', 'Passive Perception 6'],
    traits: [
      { name: 'Antimagic Susceptibility', type: 'trait', description: 'The rug is incapacitated while in the area of an antimagic field. If targeted by dispel magic, the rug must succeed on a Constitution saving throw against the caster\'s spell save DC or fall unconscious for 1 minute.' },
      { name: 'Damage Transfer', type: 'trait', description: 'While it is grappling a creature, the rug takes only half the damage dealt to it, and the creature grappled by the rug takes the other half.' },
      { name: 'False Appearance', type: 'trait', description: 'While the rug remains motionless, it is indistinguishable from a normal rug.' },
    ],
    actions: [
      { name: 'Smother', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one Medium or smaller creature. Hit: The creature is grappled (escape DC 13). Until this grapple ends, the target is restrained, blinded, and at risk of suffocating, and the rug can\'t smother another target.', attackBonus: 5, damage: '0' },
    ],
    tags: ['construct', 'trap', 'ambusher'],
  },
  {
    id: 'construct-shield-guardian',
    name: 'Shield Guardian',
    cr: 7,
    size: 'Large',
    type: 'construct',
    alignment: 'unaligned',
    armorClass: 17,
    hitPoints: 142,
    hitDice: '15d10+60',
    speed: '30 ft.',
    abilities: { str: 18, dex: 8, con: 18, int: 7, wis: 10, cha: 3 },
    senses: ['Blindsight 10 ft.', 'Darkvision 60 ft.', 'Passive Perception 10'],
    languages: ['understands commands given in any language but cannot speak'],
    traits: [
      { name: 'Bound', type: 'trait', description: 'The shield guardian is magically bound to an amulet. As long as the guardian and its amulet are on the same plane, the amulet\'s wearer can telepathically call the guardian to travel to it.' },
      { name: 'Regeneration', type: 'trait', description: 'The shield guardian regains 10 hit points at the start of its turn if it has at least 1 hit point.' },
      { name: 'Spell Storing', type: 'trait', description: 'A spellcaster who wears the shield guardian\'s amulet can cause the guardian to store one spell of 4th level or lower. The guardian can cast the stored spell (save DC 13).' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The guardian makes two fist attacks.' },
      { name: 'Fist', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 11 (2d6+4) bludgeoning damage.', attackBonus: 7, damage: '2d6+4 bludgeoning' },
    ],
    tags: ['construct', 'guardian', 'protector'],
  },
  {
    id: 'construct-stone-golem',
    name: 'Stone Golem',
    cr: 10,
    size: 'Large',
    type: 'construct',
    alignment: 'unaligned',
    armorClass: 17,
    hitPoints: 178,
    hitDice: '17d10+85',
    speed: '30 ft.',
    abilities: { str: 22, dex: 9, con: 20, int: 3, wis: 11, cha: 1 },
    senses: ['Darkvision 120 ft.', 'Passive Perception 10'],
    languages: ['understands the languages of its creator but cannot speak'],
    traits: [
      { name: 'Immutable Form', type: 'trait', description: 'The golem is immune to any spell or effect that would alter its form.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The golem has advantage on saving throws against spells and other magical effects.' },
      { name: 'Magic Weapons', type: 'trait', description: 'The golem\'s weapon attacks are magical.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The golem makes two slam attacks.' },
      { name: 'Slam', type: 'attack', description: 'Melee Weapon Attack: +10 to hit, reach 5 ft., one target. Hit: 19 (3d8+6) bludgeoning damage.', attackBonus: 10, damage: '3d8+6 bludgeoning' },
      { name: 'Slow (Recharge 5-6)', type: 'ability', description: 'The golem targets one or more creatures it can see within 10 ft. Each target must make a DC 17 Wisdom saving throw against this magic. On a failed save, a target can\'t use reactions, its speed is halved, and it can\'t make more than one attack on its turn. In addition, the target can take either an action or a bonus action on its turn, not both.', saveDc: 17, saveType: 'wis' },
    ],
    tags: ['golem', 'construct', 'guardian'],
  },
]
