import type { Monster } from './types'

export const DRAGONS: Monster[] = [
  // ─── WYRMLINGS ────────────────────────────────────────────────────────────
  {
    id: 'dragon-black-wyrmling',
    name: 'Black Dragon Wyrmling',
    cr: 2,
    size: 'Medium',
    type: 'dragon',
    alignment: 'chaotic evil',
    armorClass: 17,
    hitPoints: 33,
    hitDice: '6d8+6',
    speed: '30 ft., fly 60 ft., swim 30 ft.',
    abilities: { str: 15, dex: 14, con: 13, int: 10, wis: 11, cha: 13 },
    skills: ['Perception +4', 'Stealth +4'],
    senses: ['Blindsight 10 ft.', 'Darkvision 60 ft.', 'Passive Perception 14'],
    languages: ['Draconic'],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (1d10+2) piercing damage plus 2 (1d4) acid damage.', attackBonus: 4, damage: '1d10+2 piercing + 1d4 acid' },
      { name: 'Acid Breath (Recharge 5-6)', type: 'ability', description: 'The dragon exhales acid in a 15-ft. line that is 5 ft. wide. Each creature in that line must make a DC 11 Dexterity saving throw, taking 22 (5d8) acid damage on a failed save, or half as much on a successful one.', saveDc: 11, saveType: 'dex' },
    ],
    tags: ['dragon', 'wyrmling', 'acid', 'swamp'],
  },
  {
    id: 'dragon-blue-wyrmling',
    name: 'Blue Dragon Wyrmling',
    cr: 3,
    size: 'Medium',
    type: 'dragon',
    alignment: 'lawful evil',
    armorClass: 17,
    hitPoints: 52,
    hitDice: '8d8+16',
    speed: '30 ft., burrow 15 ft., fly 60 ft.',
    abilities: { str: 17, dex: 10, con: 15, int: 12, wis: 11, cha: 15 },
    skills: ['Perception +4', 'Stealth +2'],
    senses: ['Blindsight 10 ft.', 'Darkvision 60 ft.', 'Passive Perception 14'],
    languages: ['Draconic'],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 8 (1d10+3) piercing damage plus 3 (1d6) lightning damage.', attackBonus: 5, damage: '1d10+3 piercing + 1d6 lightning' },
      { name: 'Lightning Breath (Recharge 5-6)', type: 'ability', description: 'The dragon exhales lightning in a 30-ft. line that is 5 ft. wide. Each creature in that line must make a DC 12 Dexterity saving throw, taking 22 (4d10) lightning damage on a failed save, or half as much on a successful one.', saveDc: 12, saveType: 'dex' },
    ],
    tags: ['dragon', 'wyrmling', 'lightning', 'desert'],
  },
  {
    id: 'dragon-green-wyrmling',
    name: 'Green Dragon Wyrmling',
    cr: 2,
    size: 'Medium',
    type: 'dragon',
    alignment: 'lawful evil',
    armorClass: 17,
    hitPoints: 38,
    hitDice: '7d8+7',
    speed: '30 ft., fly 60 ft., swim 30 ft.',
    abilities: { str: 15, dex: 12, con: 13, int: 14, wis: 11, cha: 13 },
    skills: ['Deception +3', 'Perception +4', 'Stealth +3'],
    senses: ['Blindsight 10 ft.', 'Darkvision 60 ft.', 'Passive Perception 14'],
    languages: ['Draconic'],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (1d10+2) piercing damage plus 3 (1d6) poison damage.', attackBonus: 4, damage: '1d10+2 piercing + 1d6 poison' },
      { name: 'Poison Breath (Recharge 5-6)', type: 'ability', description: 'The dragon exhales poisonous gas in a 15-ft. cone. Each creature in that area must make a DC 11 Constitution saving throw, taking 21 (6d6) poison damage on a failed save, or half as much on a successful one.', saveDc: 11, saveType: 'con' },
    ],
    tags: ['dragon', 'wyrmling', 'poison', 'forest'],
  },
  {
    id: 'dragon-red-wyrmling',
    name: 'Red Dragon Wyrmling',
    cr: 4,
    size: 'Medium',
    type: 'dragon',
    alignment: 'chaotic evil',
    armorClass: 17,
    hitPoints: 75,
    hitDice: '10d8+30',
    speed: '30 ft., climb 30 ft., fly 60 ft.',
    abilities: { str: 19, dex: 10, con: 17, int: 12, wis: 11, cha: 15 },
    skills: ['Perception +4', 'Stealth +2'],
    senses: ['Blindsight 10 ft.', 'Darkvision 60 ft.', 'Passive Perception 14'],
    languages: ['Draconic'],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 9 (1d10+4) piercing damage plus 3 (1d6) fire damage.', attackBonus: 6, damage: '1d10+4 piercing + 1d6 fire' },
      { name: 'Fire Breath (Recharge 5-6)', type: 'ability', description: 'The dragon exhales fire in a 15-ft. cone. Each creature in that area must make a DC 13 Dexterity saving throw, taking 24 (7d6) fire damage on a failed save, or half as much on a successful one.', saveDc: 13, saveType: 'dex' },
    ],
    tags: ['dragon', 'wyrmling', 'fire', 'mountain'],
  },
  {
    id: 'dragon-white-wyrmling',
    name: 'White Dragon Wyrmling',
    cr: 2,
    size: 'Medium',
    type: 'dragon',
    alignment: 'chaotic evil',
    armorClass: 16,
    hitPoints: 32,
    hitDice: '5d8+10',
    speed: '30 ft., burrow 15 ft., fly 60 ft., swim 30 ft.',
    abilities: { str: 14, dex: 10, con: 14, int: 5, wis: 10, cha: 11 },
    skills: ['Perception +4', 'Stealth +2'],
    senses: ['Blindsight 10 ft.', 'Darkvision 60 ft.', 'Passive Perception 14'],
    languages: ['Draconic'],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (1d10+2) piercing damage plus 2 (1d4) cold damage.', attackBonus: 4, damage: '1d10+2 piercing + 1d4 cold' },
      { name: 'Cold Breath (Recharge 5-6)', type: 'ability', description: 'The dragon exhales an icy blast of cold air in a 15-ft. cone. Each creature in that area must make a DC 12 Constitution saving throw, taking 22 (5d8) cold damage on a failed save, or half as much on a successful one.', saveDc: 12, saveType: 'con' },
    ],
    tags: ['dragon', 'wyrmling', 'cold', 'arctic'],
  },
  // ─── YOUNG DRAGONS ────────────────────────────────────────────────────────
  {
    id: 'dragon-young-black',
    name: 'Young Black Dragon',
    cr: 7,
    size: 'Large',
    type: 'dragon',
    alignment: 'chaotic evil',
    armorClass: 18,
    hitPoints: 127,
    hitDice: '15d10+45',
    speed: '40 ft., fly 80 ft., swim 40 ft.',
    abilities: { str: 19, dex: 14, con: 17, int: 12, wis: 11, cha: 15 },
    skills: ['Perception +6', 'Stealth +5'],
    senses: ['Blindsight 30 ft.', 'Darkvision 120 ft.', 'Passive Perception 16'],
    languages: ['Common', 'Draconic'],
    traits: [
      { name: 'Amphibious', type: 'trait', description: 'The dragon can breathe air and water.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The dragon makes three attacks: one with its bite and two with its claws.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 10 ft., one target. Hit: 15 (2d10+4) piercing damage plus 4 (1d8) acid damage.', attackBonus: 7, damage: '2d10+4 piercing + 1d8 acid' },
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 11 (2d6+4) slashing damage.', attackBonus: 7, damage: '2d6+4 slashing' },
      { name: 'Acid Breath (Recharge 5-6)', type: 'ability', description: 'The dragon exhales acid in a 30-ft. line that is 5 ft. wide. Each creature in that line must make a DC 14 Dexterity saving throw, taking 49 (11d8) acid damage on a failed save, or half as much on a successful one.', saveDc: 14, saveType: 'dex' },
    ],
    tags: ['dragon', 'young', 'acid', 'swamp'],
  },
  {
    id: 'dragon-young-red',
    name: 'Young Red Dragon',
    cr: 10,
    size: 'Large',
    type: 'dragon',
    alignment: 'chaotic evil',
    armorClass: 18,
    hitPoints: 178,
    hitDice: '17d10+85',
    speed: '40 ft., climb 40 ft., fly 80 ft.',
    abilities: { str: 23, dex: 10, con: 21, int: 14, wis: 11, cha: 19 },
    skills: ['Perception +8', 'Stealth +4'],
    senses: ['Blindsight 30 ft.', 'Darkvision 120 ft.', 'Passive Perception 18'],
    languages: ['Common', 'Draconic'],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The dragon makes three attacks: one with its bite and two with its claws.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +10 to hit, reach 10 ft., one target. Hit: 17 (2d10+6) piercing damage plus 3 (1d6) fire damage.', attackBonus: 10, damage: '2d10+6 piercing + 1d6 fire' },
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +10 to hit, reach 5 ft., one target. Hit: 13 (2d6+6) slashing damage.', attackBonus: 10, damage: '2d6+6 slashing' },
      { name: 'Fire Breath (Recharge 5-6)', type: 'ability', description: 'The dragon exhales fire in a 30-ft. cone. Each creature in that area must make a DC 17 Dexterity saving throw, taking 56 (16d6) fire damage on a failed save, or half as much on a successful one.', saveDc: 17, saveType: 'dex' },
    ],
    tags: ['dragon', 'young', 'fire', 'mountain'],
  },
  {
    id: 'dragon-young-green',
    name: 'Young Green Dragon',
    cr: 8,
    size: 'Large',
    type: 'dragon',
    alignment: 'lawful evil',
    armorClass: 18,
    hitPoints: 136,
    hitDice: '16d10+48',
    speed: '40 ft., fly 80 ft., swim 40 ft.',
    abilities: { str: 19, dex: 12, con: 17, int: 16, wis: 13, cha: 15 },
    skills: ['Deception +5', 'Perception +7', 'Persuasion +5', 'Stealth +4'],
    senses: ['Blindsight 30 ft.', 'Darkvision 120 ft.', 'Passive Perception 17'],
    languages: ['Common', 'Draconic'],
    traits: [
      { name: 'Amphibious', type: 'trait', description: 'The dragon can breathe air and water.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The dragon makes three attacks: one with its bite and two with its claws.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 10 ft., one target. Hit: 15 (2d10+4) piercing damage plus 7 (2d6) poison damage.', attackBonus: 7, damage: '2d10+4 piercing + 2d6 poison' },
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 11 (2d6+4) slashing damage.', attackBonus: 7, damage: '2d6+4 slashing' },
      { name: 'Poison Breath (Recharge 5-6)', type: 'ability', description: 'The dragon exhales poisonous gas in a 30-ft. cone. Each creature in that area must make a DC 14 Constitution saving throw, taking 42 (12d6) poison damage on a failed save, or half as much on a successful one.', saveDc: 14, saveType: 'con' },
    ],
    tags: ['dragon', 'young', 'poison', 'forest'],
  },
  // ─── ADULT DRAGONS ────────────────────────────────────────────────────────
  {
    id: 'dragon-adult-black',
    name: 'Adult Black Dragon',
    cr: 14,
    size: 'Huge',
    type: 'dragon',
    alignment: 'chaotic evil',
    armorClass: 19,
    hitPoints: 195,
    hitDice: '17d12+85',
    speed: '40 ft., fly 80 ft., swim 40 ft.',
    abilities: { str: 23, dex: 14, con: 21, int: 14, wis: 13, cha: 17 },
    skills: ['Perception +11', 'Stealth +7'],
    senses: ['Blindsight 60 ft.', 'Darkvision 120 ft.', 'Passive Perception 21'],
    languages: ['Common', 'Draconic'],
    traits: [
      { name: 'Amphibious', type: 'trait', description: 'The dragon can breathe air and water.' },
      { name: 'Legendary Resistance (3/Day)', type: 'trait', description: 'If the dragon fails a saving throw, it can choose to succeed instead.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The dragon can use its Frightful Presence. It then makes three attacks: one with its bite and two with its claws.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +11 to hit, reach 10 ft., one target. Hit: 17 (2d10+6) piercing damage plus 4 (1d8) acid damage.', attackBonus: 11, damage: '2d10+6 piercing + 1d8 acid' },
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +11 to hit, reach 5 ft., one target. Hit: 13 (2d6+6) slashing damage.', attackBonus: 11, damage: '2d6+6 slashing' },
      { name: 'Tail', type: 'attack', description: 'Melee Weapon Attack: +11 to hit, reach 15 ft., one target. Hit: 15 (2d8+6) bludgeoning damage.', attackBonus: 11, damage: '2d8+6 bludgeoning' },
      { name: 'Frightful Presence', type: 'ability', description: 'Each creature of the dragon\'s choice that is within 120 ft. of the dragon and aware of it must succeed on a DC 16 Wisdom saving throw or become frightened for 1 minute.', saveDc: 16, saveType: 'wis' },
      { name: 'Acid Breath (Recharge 5-6)', type: 'ability', description: 'The dragon exhales acid in a 60-ft. line that is 5 ft. wide. Each creature in that line must make a DC 18 Dexterity saving throw, taking 54 (12d8) acid damage on a failed save, or half as much on a successful one.', saveDc: 18, saveType: 'dex' },
    ],
    legendaryActions: [
      { name: 'Detect', type: 'ability', description: 'The dragon makes a Wisdom (Perception) check.' },
      { name: 'Tail Attack', type: 'attack', description: 'The dragon makes a tail attack.', attackBonus: 11, damage: '2d8+6 bludgeoning' },
      { name: 'Wing Attack (Costs 2 Actions)', type: 'ability', description: 'The dragon beats its wings. Each creature within 10 ft. of the dragon must succeed on a DC 19 Dexterity saving throw or take 13 (2d6+6) bludgeoning damage and be knocked prone.', saveDc: 19, saveType: 'dex' },
    ],
    tags: ['dragon', 'adult', 'legendary', 'acid', 'swamp'],
  },
  {
    id: 'dragon-adult-red',
    name: 'Adult Red Dragon',
    cr: 17,
    size: 'Huge',
    type: 'dragon',
    alignment: 'chaotic evil',
    armorClass: 19,
    hitPoints: 256,
    hitDice: '19d12+114',
    speed: '40 ft., climb 40 ft., fly 80 ft.',
    abilities: { str: 27, dex: 10, con: 25, int: 16, wis: 13, cha: 21 },
    skills: ['Perception +13', 'Stealth +6'],
    senses: ['Blindsight 60 ft.', 'Darkvision 120 ft.', 'Passive Perception 23'],
    languages: ['Common', 'Draconic'],
    traits: [
      { name: 'Legendary Resistance (3/Day)', type: 'trait', description: 'If the dragon fails a saving throw, it can choose to succeed instead.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The dragon can use its Frightful Presence. It then makes three attacks: one with its bite and two with its claws.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +14 to hit, reach 10 ft., one target. Hit: 19 (2d10+8) piercing damage plus 7 (2d6) fire damage.', attackBonus: 14, damage: '2d10+8 piercing + 2d6 fire' },
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +14 to hit, reach 5 ft., one target. Hit: 15 (2d6+8) slashing damage.', attackBonus: 14, damage: '2d6+8 slashing' },
      { name: 'Tail', type: 'attack', description: 'Melee Weapon Attack: +14 to hit, reach 15 ft., one target. Hit: 17 (2d8+8) bludgeoning damage.', attackBonus: 14, damage: '2d8+8 bludgeoning' },
      { name: 'Frightful Presence', type: 'ability', description: 'Each creature within 120 ft. must succeed on a DC 21 Wisdom saving throw or become frightened for 1 minute.', saveDc: 21, saveType: 'wis' },
      { name: 'Fire Breath (Recharge 5-6)', type: 'ability', description: 'The dragon exhales fire in a 60-ft. cone. Each creature in that area must make a DC 21 Dexterity saving throw, taking 63 (18d6) fire damage on a failed save, or half as much on a successful one.', saveDc: 21, saveType: 'dex' },
    ],
    legendaryActions: [
      { name: 'Detect', type: 'ability', description: 'The dragon makes a Wisdom (Perception) check.' },
      { name: 'Tail Attack', type: 'attack', description: 'The dragon makes a tail attack.', attackBonus: 14, damage: '2d8+8 bludgeoning' },
      { name: 'Wing Attack (Costs 2 Actions)', type: 'ability', description: 'The dragon beats its wings. Each creature within 10 ft. must succeed on a DC 22 Dexterity saving throw or take 15 (2d6+8) bludgeoning damage and be knocked prone.', saveDc: 22, saveType: 'dex' },
    ],
    tags: ['dragon', 'adult', 'legendary', 'fire', 'mountain'],
  },
  // ─── ANCIENT DRAGONS ──────────────────────────────────────────────────────
  {
    id: 'dragon-ancient-red',
    name: 'Ancient Red Dragon',
    cr: 24,
    size: 'Gargantuan',
    type: 'dragon',
    alignment: 'chaotic evil',
    armorClass: 22,
    hitPoints: 546,
    hitDice: '28d20+252',
    speed: '40 ft., climb 40 ft., fly 80 ft.',
    abilities: { str: 30, dex: 10, con: 29, int: 18, wis: 15, cha: 23 },
    skills: ['Perception +16', 'Stealth +7'],
    senses: ['Blindsight 60 ft.', 'Darkvision 120 ft.', 'Passive Perception 26'],
    languages: ['Common', 'Draconic'],
    traits: [
      { name: 'Legendary Resistance (3/Day)', type: 'trait', description: 'If the dragon fails a saving throw, it can choose to succeed instead.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The dragon can use its Frightful Presence. It then makes three attacks: one with its bite and two with its claws.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +17 to hit, reach 15 ft., one target. Hit: 21 (2d10+10) piercing damage plus 14 (4d6) fire damage.', attackBonus: 17, damage: '2d10+10 piercing + 4d6 fire' },
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +17 to hit, reach 10 ft., one target. Hit: 17 (2d6+10) slashing damage.', attackBonus: 17, damage: '2d6+10 slashing' },
      { name: 'Tail', type: 'attack', description: 'Melee Weapon Attack: +17 to hit, reach 20 ft., one target. Hit: 19 (2d8+10) bludgeoning damage.', attackBonus: 17, damage: '2d8+10 bludgeoning' },
      { name: 'Frightful Presence', type: 'ability', description: 'Each creature within 120 ft. must succeed on a DC 21 Wisdom saving throw or become frightened for 1 minute.', saveDc: 21, saveType: 'wis' },
      { name: 'Fire Breath (Recharge 5-6)', type: 'ability', description: 'The dragon exhales fire in a 90-ft. cone. Each creature in that area must make a DC 24 Dexterity saving throw, taking 91 (26d6) fire damage on a failed save, or half as much on a successful one.', saveDc: 24, saveType: 'dex' },
    ],
    legendaryActions: [
      { name: 'Detect', type: 'ability', description: 'The dragon makes a Wisdom (Perception) check.' },
      { name: 'Tail Attack', type: 'attack', description: 'The dragon makes a tail attack.', attackBonus: 17, damage: '2d8+10 bludgeoning' },
      { name: 'Wing Attack (Costs 2 Actions)', type: 'ability', description: 'The dragon beats its wings. Each creature within 15 ft. must succeed on a DC 25 Dexterity saving throw or take 17 (2d6+10) bludgeoning damage and be knocked prone.', saveDc: 25, saveType: 'dex' },
    ],
    tags: ['dragon', 'ancient', 'legendary', 'fire', 'mountain', 'boss'],
  },
  {
    id: 'dragon-ancient-green',
    name: 'Ancient Green Dragon',
    cr: 22,
    size: 'Gargantuan',
    type: 'dragon',
    alignment: 'lawful evil',
    armorClass: 21,
    hitPoints: 385,
    hitDice: '22d20+154',
    speed: '40 ft., fly 80 ft., swim 40 ft.',
    abilities: { str: 27, dex: 12, con: 25, int: 20, wis: 17, cha: 19 },
    skills: ['Deception +11', 'Insight +10', 'Perception +17', 'Persuasion +11', 'Stealth +8'],
    senses: ['Blindsight 60 ft.', 'Darkvision 120 ft.', 'Passive Perception 27'],
    languages: ['Common', 'Draconic'],
    traits: [
      { name: 'Amphibious', type: 'trait', description: 'The dragon can breathe air and water.' },
      { name: 'Legendary Resistance (3/Day)', type: 'trait', description: 'If the dragon fails a saving throw, it can choose to succeed instead.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The dragon can use its Frightful Presence. It then makes three attacks: one with its bite and two with its claws.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +15 to hit, reach 15 ft., one target. Hit: 19 (2d10+8) piercing damage plus 10 (3d6) poison damage.', attackBonus: 15, damage: '2d10+8 piercing + 3d6 poison' },
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +15 to hit, reach 10 ft., one target. Hit: 22 (4d6+8) slashing damage.', attackBonus: 15, damage: '4d6+8 slashing' },
      { name: 'Tail', type: 'attack', description: 'Melee Weapon Attack: +15 to hit, reach 20 ft., one target. Hit: 17 (2d8+8) bludgeoning damage.', attackBonus: 15, damage: '2d8+8 bludgeoning' },
      { name: 'Frightful Presence', type: 'ability', description: 'Each creature within 120 ft. must succeed on a DC 19 Wisdom saving throw or become frightened for 1 minute.', saveDc: 19, saveType: 'wis' },
      { name: 'Poison Breath (Recharge 5-6)', type: 'ability', description: 'The dragon exhales poisonous gas in a 90-ft. cone. Each creature in that area must make a DC 22 Constitution saving throw, taking 77 (22d6) poison damage on a failed save, or half as much on a successful one.', saveDc: 22, saveType: 'con' },
    ],
    legendaryActions: [
      { name: 'Detect', type: 'ability', description: 'The dragon makes a Wisdom (Perception) check.' },
      { name: 'Tail Attack', type: 'attack', description: 'The dragon makes a tail attack.', attackBonus: 15, damage: '2d8+8 bludgeoning' },
      { name: 'Wing Attack (Costs 2 Actions)', type: 'ability', description: 'Each creature within 15 ft. must succeed on a DC 23 Dexterity saving throw or take 15 (2d6+8) bludgeoning damage and be knocked prone.', saveDc: 23, saveType: 'dex' },
    ],
    tags: ['dragon', 'ancient', 'legendary', 'poison', 'forest', 'boss'],
  },
  // ─── OTHER DRAGONS ────────────────────────────────────────────────────────
  {
    id: 'dragon-pseudodragon',
    name: 'Pseudodragon',
    cr: 0.25,
    size: 'Tiny',
    type: 'dragon',
    alignment: 'neutral good',
    armorClass: 13,
    hitPoints: 7,
    hitDice: '2d4+2',
    speed: '15 ft., fly 60 ft.',
    abilities: { str: 6, dex: 15, con: 13, int: 10, wis: 12, cha: 10 },
    skills: ['Perception +3', 'Stealth +4'],
    senses: ['Blindsight 10 ft.', 'Darkvision 60 ft.', 'Passive Perception 13'],
    languages: ['understands Common and Draconic but can\'t speak'],
    traits: [
      { name: 'Keen Senses', type: 'trait', description: 'The pseudodragon has advantage on Wisdom (Perception) checks that rely on sight, hearing, or smell.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The pseudodragon has advantage on saving throws against spells and other magical effects.' },
      { name: 'Limited Telepathy', type: 'trait', description: 'The pseudodragon can magically communicate simple ideas, emotions, and images telepathically with any creature within 100 ft. of it that can understand a language.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4+2) piercing damage.', attackBonus: 4, damage: '1d4+2 piercing' },
      { name: 'Sting', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 4 (1d4+2) piercing damage, and the target must succeed on a DC 11 Constitution saving throw or become poisoned for 1 hour. If the saving throw fails by 5 or more, the target falls unconscious for the same duration, or until it takes damage or another creature uses an action to shake it awake.', attackBonus: 4, damage: '1d4+2 piercing', saveDc: 11, saveType: 'con' },
    ],
    tags: ['dragon', 'tiny', 'familiar', 'good'],
  },
  {
    id: 'dragon-dragon-turtle',
    name: 'Dragon Turtle',
    cr: 17,
    size: 'Gargantuan',
    type: 'dragon',
    alignment: 'neutral',
    armorClass: 20,
    hitPoints: 341,
    hitDice: '22d20+110',
    speed: '20 ft., swim 40 ft.',
    abilities: { str: 25, dex: 10, con: 20, int: 10, wis: 12, cha: 12 },
    skills: ['Perception +7'],
    senses: ['Darkvision 120 ft.', 'Passive Perception 17'],
    languages: ['Aquan', 'Draconic'],
    traits: [
      { name: 'Amphibious', type: 'trait', description: 'The dragon turtle can breathe air and water.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The dragon turtle makes three attacks: one with its bite and two with its claws. It can make one tail attack in place of its two claw attacks.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +13 to hit, reach 15 ft., one target. Hit: 26 (3d12+7) piercing damage.', attackBonus: 13, damage: '3d12+7 piercing' },
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +13 to hit, reach 10 ft., one target. Hit: 16 (2d8+7) slashing damage.', attackBonus: 13, damage: '2d8+7 slashing' },
      { name: 'Tail', type: 'attack', description: 'Melee Weapon Attack: +13 to hit, reach 15 ft., one target. Hit: 26 (3d12+7) bludgeoning damage. If the target is a creature, it must succeed on a DC 20 Strength saving throw or be pushed up to 10 ft. away from the dragon turtle and knocked prone.', attackBonus: 13, damage: '3d12+7 bludgeoning', saveDc: 20, saveType: 'str' },
      { name: 'Steam Breath (Recharge 5-6)', type: 'ability', description: 'The dragon turtle exhales scalding steam in a 60-ft. cone. Each creature in that area must make a DC 18 Constitution saving throw, taking 52 (15d6) fire damage on a failed save, or half as much on a successful one. Being underwater doesn\'t grant resistance against this damage.', saveDc: 18, saveType: 'con' },
    ],
    tags: ['dragon', 'sea', 'legendary', 'turtle'],
  },
  {
    id: 'dragon-wyvern',
    name: 'Wyvern',
    cr: 6,
    size: 'Large',
    type: 'dragon',
    alignment: 'unaligned',
    armorClass: 13,
    hitPoints: 110,
    hitDice: '13d10+39',
    speed: '20 ft., fly 80 ft.',
    abilities: { str: 19, dex: 10, con: 16, int: 5, wis: 12, cha: 6 },
    skills: ['Perception +4'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 14'],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The wyvern makes two attacks: one with its bite and one with its stinger. While flying, it can use its claws in place of one other attack.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 10 ft., one creature. Hit: 11 (2d6+4) piercing damage.', attackBonus: 7, damage: '2d6+4 piercing' },
      { name: 'Claws', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 13 (2d8+4) slashing damage.', attackBonus: 7, damage: '2d8+4 slashing' },
      { name: 'Stinger', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 10 ft., one creature. Hit: 11 (2d6+4) piercing damage. The target must make a DC 15 Constitution saving throw, taking 24 (7d6) poison damage on a failed save, or half as much on a successful one.', attackBonus: 7, damage: '2d6+4 piercing', saveDc: 15, saveType: 'con' },
    ],
    tags: ['dragon', 'flying', 'poison', 'lesser dragon'],
  },
]
