import type { Monster } from './types'

export const ELEMENTALS: Monster[] = [
  {
    id: 'elemental-air-elemental',
    name: 'Air Elemental',
    cr: 5,
    size: 'Large',
    type: 'elemental',
    alignment: 'neutral',
    armorClass: 15,
    hitPoints: 90,
    hitDice: '12d10+24',
    speed: '0 ft., fly 90 ft. (hover)',
    abilities: { str: 14, dex: 20, con: 14, int: 6, wis: 10, cha: 6 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 10'],
    languages: ['Auran'],
    traits: [
      { name: 'Air Form', type: 'trait', description: 'The elemental can enter a hostile creature\'s space and stop there. It can move through a space as narrow as 1 inch wide without squeezing.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The elemental makes two slam attacks.' },
      { name: 'Slam', type: 'attack', description: 'Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 14 (2d8+5) bludgeoning damage.', attackBonus: 8, damage: '2d8+5 bludgeoning' },
      { name: 'Whirlwind (Recharge 4-6)', type: 'ability', description: 'Each creature in the elemental\'s space must make a DC 13 Strength saving throw. On a failure, a target takes 15 (3d8+2) bludgeoning damage and is flung up 20 ft. away in a random direction and knocked prone. If a thrown target strikes an object, the target takes 3 (1d6) bludgeoning damage for every 10 ft. it was thrown.', saveDc: 13, saveType: 'str' },
    ],
    tags: ['elemental', 'air', 'wind'],
  },
  {
    id: 'elemental-djinni',
    name: 'Djinni',
    cr: 11,
    size: 'Large',
    type: 'elemental',
    alignment: 'chaotic good',
    armorClass: 17,
    hitPoints: 161,
    hitDice: '14d10+84',
    speed: '30 ft., fly 90 ft.',
    abilities: { str: 21, dex: 15, con: 22, int: 15, wis: 16, cha: 20 },
    skills: ['Perception +7'],
    senses: ['Darkvision 120 ft.', 'Passive Perception 17'],
    languages: ['Auran'],
    traits: [
      { name: 'Elemental Demise', type: 'trait', description: 'If the djinni dies, its body disintegrates into a warm breeze, leaving behind only equipment the djinni was wearing or carrying.' },
      { name: 'Innate Spellcasting', type: 'trait', description: 'Spellcasting ability is Charisma (spell save DC 17). At will: detect evil and good, detect magic, thunderwave. 3/day each: create food and water, tongues, wind walk. 1/day each: conjure elemental (air elemental only), creation, gaseous form, invisibility, major image, plane shift.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The djinni makes three scimitar attacks.' },
      { name: 'Scimitar', type: 'attack', description: 'Melee Weapon Attack: +9 to hit, reach 5 ft., one target. Hit: 12 (2d6+5) slashing damage plus 3 (1d6) lightning or thunder damage (djinni\'s choice).', attackBonus: 9, damage: '2d6+5 slashing + 1d6 lightning' },
      { name: 'Create Whirlwind', type: 'ability', description: 'A 5-ft. radius, 30-ft. tall cylinder of swirling air magically forms on a point the djinni can see within 120 ft. The whirlwind lasts as long as the djinni maintains concentration (as if concentrating on a spell). Any creature but the djinni that enters the whirlwind must succeed on a DC 18 Strength saving throw or be restrained by it until the whirlwind ends.', saveDc: 18, saveType: 'str' },
    ],
    tags: ['elemental', 'genie', 'air', 'wish'],
  },
  {
    id: 'elemental-earth-elemental',
    name: 'Earth Elemental',
    cr: 5,
    size: 'Large',
    type: 'elemental',
    alignment: 'neutral',
    armorClass: 17,
    hitPoints: 126,
    hitDice: '12d10+60',
    speed: '30 ft., burrow 30 ft.',
    abilities: { str: 20, dex: 8, con: 20, int: 5, wis: 10, cha: 5 },
    senses: ['Darkvision 60 ft.', 'Tremorsense 60 ft.', 'Passive Perception 10'],
    languages: ['Terran'],
    traits: [
      { name: 'Earth Glide', type: 'trait', description: 'The elemental can burrow through nonmagical, unworked earth and stone. While doing so, the elemental doesn\'t disturb the material it moves through.' },
      { name: 'Siege Monster', type: 'trait', description: 'The elemental deals double damage to objects and structures.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The elemental makes two slam attacks.' },
      { name: 'Slam', type: 'attack', description: 'Melee Weapon Attack: +8 to hit, reach 10 ft., one target. Hit: 14 (2d8+5) bludgeoning damage.', attackBonus: 8, damage: '2d8+5 bludgeoning' },
    ],
    tags: ['elemental', 'earth', 'stone'],
  },
  {
    id: 'elemental-efreeti',
    name: 'Efreeti',
    cr: 11,
    size: 'Large',
    type: 'elemental',
    alignment: 'lawful evil',
    armorClass: 17,
    hitPoints: 200,
    hitDice: '16d10+112',
    speed: '40 ft., fly 60 ft.',
    abilities: { str: 22, dex: 12, con: 24, int: 16, wis: 15, cha: 16 },
    skills: ['Perception +6'],
    senses: ['Darkvision 120 ft.', 'Passive Perception 16'],
    languages: ['Ignan'],
    traits: [
      { name: 'Elemental Demise', type: 'trait', description: 'If the efreeti dies, its body disintegrates in a flash of fire and puff of smoke, leaving behind only equipment the efreeti was wearing or carrying.' },
      { name: 'Innate Spellcasting', type: 'trait', description: 'Spellcasting ability is Charisma (spell save DC 15). At will: detect magic. 3/day each: enlarge/reduce, tongues. 1/day each: conjure elemental (fire elemental only), gaseous form, invisibility, major image, plane shift, wall of fire.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The efreeti makes two scimitar attacks or uses its Hurl Flame twice.' },
      { name: 'Scimitar', type: 'attack', description: 'Melee Weapon Attack: +10 to hit, reach 5 ft., one target. Hit: 13 (2d6+6) slashing damage plus 7 (2d6) fire damage.', attackBonus: 10, damage: '2d6+6 slashing + 2d6 fire' },
      { name: 'Hurl Flame', type: 'attack', description: 'Ranged Spell Attack: +7 to hit, range 120 ft., one target. Hit: 17 (5d6) fire damage.', attackBonus: 7, damage: '5d6 fire' },
    ],
    tags: ['elemental', 'genie', 'fire', 'wish'],
  },
  {
    id: 'elemental-fire-elemental',
    name: 'Fire Elemental',
    cr: 5,
    size: 'Large',
    type: 'elemental',
    alignment: 'neutral',
    armorClass: 13,
    hitPoints: 102,
    hitDice: '12d10+36',
    speed: '50 ft.',
    abilities: { str: 10, dex: 17, con: 16, int: 6, wis: 10, cha: 7 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 10'],
    languages: ['Ignan'],
    traits: [
      { name: 'Fire Form', type: 'trait', description: 'The elemental can move through a space as narrow as 1 inch wide without squeezing. A creature that touches the elemental or hits it with a melee attack while within 5 ft. of it takes 5 (1d10) fire damage. In addition, the elemental can enter a hostile creature\'s space and stop there. The first time it enters a creature\'s space on a turn, that creature takes 5 (1d10) fire damage and catches fire.' },
      { name: 'Illumination', type: 'trait', description: 'The elemental sheds bright light in a 30-ft. radius and dim light in an additional 30 ft.' },
      { name: 'Water Susceptibility', type: 'trait', description: 'For every 5 ft. the elemental moves in water, or for every gallon of water splashed on it, it takes 1 cold damage.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The elemental makes two touch attacks.' },
      { name: 'Touch', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 10 (2d6+3) fire damage. If the target is a creature or a flammable object, it ignites. Until a creature takes an action to douse the fire, the target takes 5 (1d10) fire damage at the start of each of its turns.', attackBonus: 6, damage: '2d6+3 fire' },
    ],
    tags: ['elemental', 'fire', 'burning'],
  },
  {
    id: 'elemental-gargoyle',
    name: 'Gargoyle',
    cr: 2,
    size: 'Medium',
    type: 'elemental',
    alignment: 'chaotic evil',
    armorClass: 15,
    hitPoints: 52,
    hitDice: '7d8+21',
    speed: '30 ft., fly 60 ft.',
    abilities: { str: 15, dex: 11, con: 16, int: 6, wis: 11, cha: 7 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 10'],
    languages: ['Terran'],
    traits: [
      { name: 'False Appearance', type: 'trait', description: 'While the gargoyle remains motionless, it is indistinguishable from an inanimate statue.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The gargoyle makes two attacks: one with its bite and one with its claws.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6+2) piercing damage.', attackBonus: 4, damage: '1d6+2 piercing' },
      { name: 'Claws', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6+2) slashing damage.', attackBonus: 4, damage: '1d6+2 slashing' },
    ],
    tags: ['elemental', 'stone', 'guardian', 'ambusher'],
  },
  {
    id: 'elemental-invisible-stalker',
    name: 'Invisible Stalker',
    cr: 6,
    size: 'Medium',
    type: 'elemental',
    alignment: 'neutral',
    armorClass: 14,
    hitPoints: 104,
    hitDice: '16d8+32',
    speed: '50 ft., fly 50 ft. (hover)',
    abilities: { str: 16, dex: 19, con: 14, int: 10, wis: 15, cha: 11 },
    skills: ['Perception +8', 'Stealth +10'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 18'],
    languages: ['Auran', 'understands Common but doesn\'t speak it'],
    traits: [
      { name: 'Invisibility', type: 'trait', description: 'The stalker is invisible.' },
      { name: 'Faultless Tracker', type: 'trait', description: 'The stalker is given a quarry by its summoner. The stalker knows the direction and distance to its quarry as long as the two of them are on the same plane of existence. The stalker also knows the location of its summoner.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The stalker makes two slam attacks.' },
      { name: 'Slam', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 10 (2d6+3) bludgeoning damage.', attackBonus: 6, damage: '2d6+3 bludgeoning' },
    ],
    tags: ['elemental', 'air', 'invisible', 'tracker'],
  },
  {
    id: 'elemental-magmin',
    name: 'Magmin',
    cr: 0.5,
    size: 'Small',
    type: 'elemental',
    alignment: 'chaotic neutral',
    armorClass: 14,
    hitPoints: 9,
    hitDice: '2d6+2',
    speed: '30 ft.',
    abilities: { str: 7, dex: 15, con: 12, int: 8, wis: 11, cha: 10 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 10'],
    languages: ['Ignan'],
    traits: [
      { name: 'Death Burst', type: 'trait', description: 'When the magmin dies, it explodes in a burst of fire and magma. Each creature within 10 ft. of it must make a DC 11 Dexterity saving throw, taking 7 (2d6) fire damage on a failed save, or half as much on a successful one. Flammable objects that aren\'t being worn or carried in that area are ignited.', saveDc: 11, saveType: 'dex' },
      { name: 'Ignited Illumination', type: 'trait', description: 'As a bonus action, the magmin can set itself ablaze or extinguish its flames. While ablaze, the magmin sheds bright light in a 10-ft. radius and dim light for an additional 10 ft.' },
    ],
    actions: [
      { name: 'Touch', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d6) fire damage. If the target is a creature or a flammable object, it ignites. Until a creature takes an action to douse the fire, the target takes 3 (1d6) fire damage at the start of each of its turns.', attackBonus: 4, damage: '2d6 fire' },
    ],
    tags: ['elemental', 'fire', 'small'],
  },
  {
    id: 'elemental-nightmare',
    name: 'Nightmare',
    cr: 3,
    size: 'Large',
    type: 'fiend',
    alignment: 'neutral evil',
    armorClass: 13,
    hitPoints: 68,
    hitDice: '8d10+24',
    speed: '60 ft., fly 90 ft.',
    abilities: { str: 18, dex: 15, con: 16, int: 10, wis: 13, cha: 15 },
    senses: ['Passive Perception 11'],
    languages: ['understands Abyssal, Common, and Infernal but can\'t speak'],
    traits: [
      { name: 'Confer Fire Resistance', type: 'trait', description: 'The nightmare can grant resistance to fire damage to anyone riding it.' },
      { name: 'Illumination', type: 'trait', description: 'The nightmare sheds bright light in a 10-ft. radius and dim light for an additional 10 ft.' },
    ],
    actions: [
      { name: 'Hooves', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 13 (2d8+4) bludgeoning damage plus 7 (2d6) fire damage.', attackBonus: 6, damage: '2d8+4 bludgeoning + 2d6 fire' },
      { name: 'Ethereal Stride', type: 'ability', description: 'The nightmare and up to three willing creatures within 5 ft. of it magically enter the Ethereal Plane from the Material Plane, or vice versa.' },
    ],
    tags: ['fiend', 'horse', 'fire', 'mount', 'evil'],
  },
  {
    id: 'elemental-salamander',
    name: 'Salamander',
    cr: 5,
    size: 'Large',
    type: 'elemental',
    alignment: 'neutral evil',
    armorClass: 15,
    hitPoints: 90,
    hitDice: '12d10+24',
    speed: '30 ft.',
    abilities: { str: 18, dex: 14, con: 15, int: 11, wis: 10, cha: 12 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 10'],
    languages: ['Ignan'],
    traits: [
      { name: 'Heated Body', type: 'trait', description: 'A creature that touches the salamander or hits it with a melee attack while within 5 ft. of it takes 7 (2d6) fire damage.' },
      { name: 'Heated Weapons', type: 'trait', description: 'Any metal melee weapon the salamander wields deals an extra 3 (1d6) fire damage on a hit (included in the attack).' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The salamander makes two attacks: one with its spear and one with its tail.' },
      { name: 'Spear', type: 'attack', description: 'Melee or Ranged Weapon Attack: +7 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 11 (2d6+4) piercing damage, or 13 (2d8+4) piercing damage if used with two hands to make a melee attack, plus 3 (1d6) fire damage.', attackBonus: 7, damage: '2d6+4 piercing + 1d6 fire' },
      { name: 'Tail', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 10 ft., one target. Hit: 11 (2d6+4) bludgeoning damage plus 7 (2d6) fire damage, and the target is grappled (escape DC 14). Until this grapple ends, the target is restrained, the salamander can automatically hit the target with its tail, and the salamander can\'t make tail attacks against other targets.', attackBonus: 7, damage: '2d6+4 bludgeoning + 2d6 fire' },
    ],
    tags: ['elemental', 'fire', 'snake-like'],
  },
  {
    id: 'elemental-water-elemental',
    name: 'Water Elemental',
    cr: 5,
    size: 'Large',
    type: 'elemental',
    alignment: 'neutral',
    armorClass: 14,
    hitPoints: 114,
    hitDice: '12d10+48',
    speed: '30 ft., swim 90 ft.',
    abilities: { str: 18, dex: 14, con: 18, int: 5, wis: 10, cha: 8 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 10'],
    languages: ['Aquan'],
    traits: [
      { name: 'Freeze', type: 'trait', description: 'If the elemental takes cold damage, it partially freezes; its speed is reduced by 20 ft. until the end of its next turn.' },
      { name: 'Water Form', type: 'trait', description: 'The elemental can enter a hostile creature\'s space and stop there. It can move through a space as narrow as 1 inch wide without squeezing.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The elemental makes two slam attacks.' },
      { name: 'Slam', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 13 (2d8+4) bludgeoning damage.', attackBonus: 7, damage: '2d8+4 bludgeoning' },
      { name: 'Whelm (Recharge 4-6)', type: 'ability', description: 'Each creature in the elemental\'s space must make a DC 15 Strength saving throw. On a failure, a target takes 13 (2d8+4) bludgeoning damage. If it is Large or smaller, it is also grappled (escape DC 14). Until this grapple ends, the target is restrained and unable to breathe unless it can breathe water. If the saving throw is successful, the target is pushed out of the elemental\'s space.', saveDc: 15, saveType: 'str' },
    ],
    tags: ['elemental', 'water', 'drowning'],
  },
  {
    id: 'elemental-xorn',
    name: 'Xorn',
    cr: 5,
    size: 'Medium',
    type: 'elemental',
    alignment: 'neutral',
    armorClass: 19,
    hitPoints: 73,
    hitDice: '7d8+42',
    speed: '20 ft., burrow 20 ft.',
    abilities: { str: 17, dex: 10, con: 22, int: 11, wis: 10, cha: 11 },
    skills: ['Perception +6', 'Stealth +3'],
    senses: ['Darkvision 60 ft.', 'Tremorsense 60 ft.', 'Passive Perception 16'],
    languages: ['Terran'],
    traits: [
      { name: 'Earth Glide', type: 'trait', description: 'The xorn can burrow through nonmagical, unworked earth and stone. While doing so, the xorn doesn\'t disturb the material it moves through.' },
      { name: 'Stone Camouflage', type: 'trait', description: 'The xorn has advantage on Dexterity (Stealth) checks made to hide in rocky terrain.' },
      { name: 'Treasure Sense', type: 'trait', description: 'The xorn can pinpoint, by scent, the location of precious metals and stones, such as coins and gems, within 60 ft. of it.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The xorn makes three claw attacks and one bite attack.' },
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 6 (1d6+3) slashing damage.', attackBonus: 6, damage: '1d6+3 slashing' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 13 (3d6+3) piercing damage.', attackBonus: 6, damage: '3d6+3 piercing' },
    ],
    tags: ['elemental', 'earth', 'treasure', 'underdark'],
  },
]
