import type { Monster } from './types'

export const FEY: Monster[] = [
  {
    id: 'fey-dryad',
    name: 'Dryad',
    cr: 1,
    size: 'Medium',
    type: 'fey',
    alignment: 'neutral',
    armorClass: 11,
    hitPoints: 22,
    hitDice: '5d8',
    speed: '30 ft.',
    abilities: { str: 10, dex: 12, con: 11, int: 14, wis: 15, cha: 20 },
    skills: ['Perception +4', 'Stealth +5'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 14'],
    languages: ['Elvish', 'Sylvan'],
    traits: [
      { name: 'Innate Spellcasting', type: 'trait', description: 'Spellcasting ability is Charisma (spell save DC 14). At will: druidcraft, guidance, mending, poison spray, produce flame, shillelagh, spare the dying, thunderwave. 3/day each: charm person, healing word, invisibility (self only), barkskin, pass without trace, shillelagh. 1/day each: entangle, goodberry, sleep, spike growth, wall of thorns.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The dryad has advantage on saving throws against spells and other magical effects.' },
      { name: 'Speak with Beasts and Plants', type: 'trait', description: 'The dryad can communicate with beasts and plants as if they shared a language.' },
      { name: 'Tree Stride', type: 'trait', description: 'Once on her turn, the dryad can use 10 ft. of her movement to step magically into one living tree within her reach and emerge from a second living tree within 60 ft. of the first tree, appearing in an unoccupied space within 5 ft. of the second tree. Both trees must be Large or bigger.' },
    ],
    actions: [
      { name: 'Club', type: 'attack', description: 'Melee Weapon Attack: +2 to hit (+6 to hit with shillelagh), reach 5 ft., one target. Hit: 2 (1d4) bludgeoning damage, or 8 (1d8+4) bludgeoning damage with shillelagh.', attackBonus: 2, damage: '1d4 bludgeoning' },
      { name: 'Fey Charm', type: 'ability', description: 'The dryad targets one humanoid or beast that she can see within 30 ft. of her. If the target can see the dryad, it must succeed on a DC 14 Wisdom saving throw or be magically charmed. The charmed creature regards the dryad as a trusted friend to be heeded and protected.', saveDc: 14, saveType: 'wis' },
    ],
    tags: ['fey', 'forest', 'nature', 'charm'],
  },
  {
    id: 'fey-green-hag',
    name: 'Green Hag',
    cr: 3,
    size: 'Medium',
    type: 'fey',
    alignment: 'neutral evil',
    armorClass: 17,
    hitPoints: 82,
    hitDice: '11d8+33',
    speed: '30 ft.',
    abilities: { str: 18, dex: 12, con: 16, int: 13, wis: 14, cha: 14 },
    skills: ['Arcana +3', 'Deception +4', 'Perception +4', 'Stealth +3'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 14'],
    languages: ['Common', 'Draconic', 'Sylvan'],
    traits: [
      { name: 'Amphibious', type: 'trait', description: 'The hag can breathe air and water.' },
      { name: 'Innate Spellcasting', type: 'trait', description: 'Spellcasting ability is Charisma (spell save DC 12). At will: dancing lights, minor illusion, vicious mockery.' },
      { name: 'Mimicry', type: 'trait', description: 'The hag can mimic animal sounds and humanoid voices. A creature that hears the sounds can tell they are imitations with a successful DC 14 Wisdom (Insight) check.' },
    ],
    actions: [
      { name: 'Claws', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 13 (2d8+4) slashing damage.', attackBonus: 6, damage: '2d8+4 slashing' },
      { name: 'Illusory Appearance', type: 'ability', description: 'The hag covers herself and anything she is wearing or carrying with a magical illusion that makes her look like another creature of her general size and humanoid shape. The illusion ends if the hag takes a bonus action to end it or if she dies.' },
      { name: 'Invisible Passage', type: 'ability', description: 'The hag magically turns invisible until she attacks or casts a spell, or until her concentration ends. While invisible, she leaves no physical evidence of her passage, so she can be tracked only by magic.' },
    ],
    tags: ['fey', 'hag', 'witch', 'illusion'],
  },
  {
    id: 'fey-night-hag',
    name: 'Night Hag',
    cr: 5,
    size: 'Medium',
    type: 'fiend',
    alignment: 'neutral evil',
    armorClass: 17,
    hitPoints: 112,
    hitDice: '15d8+45',
    speed: '30 ft.',
    abilities: { str: 18, dex: 15, con: 16, int: 16, wis: 14, cha: 16 },
    skills: ['Deception +7', 'Insight +6', 'Perception +6', 'Stealth +6'],
    senses: ['Darkvision 120 ft.', 'Passive Perception 16'],
    languages: ['Abyssal', 'Common', 'Infernal', 'Primordial'],
    traits: [
      { name: 'Innate Spellcasting', type: 'trait', description: 'Spellcasting ability is Charisma (spell save DC 14). At will: detect magic, magic missile. 2/day each: plane shift (self only), ray of enfeeblement, sleep.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The hag has advantage on saving throws against spells and other magical effects.' },
    ],
    actions: [
      { name: 'Claws (Hag Form Only)', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 13 (2d8+4) slashing damage.', attackBonus: 7, damage: '2d8+4 slashing' },
      { name: 'Change Shape', type: 'ability', description: 'The hag magically polymorphs into a Small or Medium female humanoid, or back into her true form. Her statistics are the same in each form.' },
      { name: 'Etherealness', type: 'ability', description: 'The hag magically enters the Ethereal Plane from the Material Plane, or vice versa. To do so, the hag must have a heartstone in her possession.' },
      { name: 'Nightmare Haunting (1/Day)', type: 'ability', description: 'While on the Ethereal Plane, the hag magically touches a sleeping humanoid on the Material Plane. A protection from evil and good spell cast on the target prevents this contact, as does a magic circle. As long as the contact persists, the target has dreadful visions. If these visions last for at least 1 hour, the target gains no benefit from its rest, and its hit point maximum is reduced by 5 (1d10). If this effect reduces the target\'s hit point maximum to 0, the target dies, and if the target was evil, its soul is trapped in the hag\'s soul bag.' },
    ],
    tags: ['fiend', 'hag', 'nightmare', 'dream'],
  },
  {
    id: 'fey-pixie',
    name: 'Pixie',
    cr: 0.25,
    size: 'Tiny',
    type: 'fey',
    alignment: 'neutral good',
    armorClass: 15,
    hitPoints: 1,
    hitDice: '1d4-1',
    speed: '10 ft., fly 30 ft.',
    abilities: { str: 2, dex: 20, con: 8, int: 10, wis: 14, cha: 15 },
    skills: ['Perception +4', 'Stealth +7'],
    senses: ['Passive Perception 14'],
    languages: ['Sylvan'],
    traits: [
      { name: 'Innate Spellcasting', type: 'trait', description: 'Spellcasting ability is Charisma (spell save DC 12). At will: druidcraft, vicious mockery. 1/day each: confusion, dancing lights, detect evil and good, detect thoughts, dispel magic, entangle, fly, phantasmal force, polymorph, sleep.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The pixie has advantage on saving throws against spells and other magical effects.' },
    ],
    actions: [
      { name: 'Shortsword', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 1 piercing damage.', attackBonus: 7, damage: '1 piercing' },
      { name: 'Superior Invisibility', type: 'ability', description: 'The pixie magically turns invisible until its concentration ends (as if concentrating on a spell). Any equipment the pixie wears or carries is invisible with it.' },
    ],
    tags: ['fey', 'tiny', 'trickster', 'forest'],
  },
  {
    id: 'fey-satyr',
    name: 'Satyr',
    cr: 0.5,
    size: 'Medium',
    type: 'fey',
    alignment: 'chaotic neutral',
    armorClass: 14,
    hitPoints: 31,
    hitDice: '7d8',
    speed: '40 ft.',
    abilities: { str: 12, dex: 16, con: 11, int: 12, wis: 10, cha: 14 },
    skills: ['Perception +2', 'Performance +6', 'Stealth +5'],
    senses: ['Passive Perception 12'],
    languages: ['Common', 'Elvish', 'Sylvan'],
    traits: [
      { name: 'Magic Resistance', type: 'trait', description: 'The satyr has advantage on saving throws against spells and other magical effects.' },
    ],
    actions: [
      { name: 'Ram', type: 'attack', description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 6 (2d4+1) bludgeoning damage.', attackBonus: 3, damage: '2d4+1 bludgeoning' },
      { name: 'Shortsword', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6+3) piercing damage.', attackBonus: 5, damage: '1d6+3 piercing' },
      { name: 'Shortbow', type: 'attack', description: 'Ranged Weapon Attack: +5 to hit, range 80/320 ft., one target. Hit: 6 (1d6+3) piercing damage.', attackBonus: 5, damage: '1d6+3 piercing' },
    ],
    tags: ['fey', 'forest', 'music', 'revelry'],
  },
  {
    id: 'fey-sea-hag',
    name: 'Sea Hag',
    cr: 2,
    size: 'Medium',
    type: 'fey',
    alignment: 'chaotic evil',
    armorClass: 14,
    hitPoints: 52,
    hitDice: '7d8+21',
    speed: '30 ft., swim 40 ft.',
    abilities: { str: 16, dex: 13, con: 16, int: 12, wis: 12, cha: 13 },
    skills: ['Arcana +3', 'Deception +3', 'Insight +3', 'Perception +3', 'Stealth +3'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 13'],
    languages: ['Aquan', 'Common', 'Giant'],
    traits: [
      { name: 'Amphibious', type: 'trait', description: 'The hag can breathe air and water.' },
      { name: 'Horrific Appearance', type: 'trait', description: 'Any humanoid that starts its turn within 30 ft. of the hag and can see the hag\'s true form must make a DC 11 Wisdom saving throw. On a failed save, the creature is frightened for 1 minute.', saveDc: 11, saveType: 'wis' },
    ],
    actions: [
      { name: 'Claws', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6+3) slashing damage.', attackBonus: 5, damage: '2d6+3 slashing' },
      { name: 'Death Glare', type: 'ability', description: 'The hag targets one frightened creature she can see within 30 ft. of her. If the target can see the hag, it must succeed on a DC 11 Wisdom saving throw against this magic or drop to 0 hit points.', saveDc: 11, saveType: 'wis' },
      { name: 'Illusory Appearance', type: 'ability', description: 'The hag covers herself and anything she is wearing or carrying with a magical illusion that makes her look like an ugly creature of her general size and humanoid shape. The illusion ends if the hag takes a bonus action to end it or if she dies. A creature that uses its action to examine the hag can determine that it is a disguise with a successful DC 16 Intelligence (Investigation) check.' },
    ],
    tags: ['fey', 'hag', 'sea', 'horror'],
  },
  {
    id: 'fey-sprite',
    name: 'Sprite',
    cr: 0.25,
    size: 'Tiny',
    type: 'fey',
    alignment: 'neutral good',
    armorClass: 15,
    hitPoints: 2,
    hitDice: '1d4',
    speed: '10 ft., fly 40 ft.',
    abilities: { str: 3, dex: 18, con: 10, int: 14, wis: 13, cha: 11 },
    skills: ['Perception +3', 'Stealth +8'],
    senses: ['Passive Perception 13'],
    languages: ['Common', 'Elvish', 'Sylvan'],
    actions: [
      { name: 'Longsword', type: 'attack', description: 'Melee Weapon Attack: +2 to hit, reach 5 ft., one target. Hit: 1 slashing damage.', attackBonus: 2, damage: '1 slashing' },
      { name: 'Shortbow', type: 'attack', description: 'Ranged Weapon Attack: +6 to hit, range 40/160 ft., one target. Hit: 1 piercing damage, and the target must succeed on a DC 10 Constitution saving throw or become poisoned for 1 minute. If its saving throw result is 5 or lower, the poisoned target falls unconscious for the same duration, or until it takes damage or another creature takes an action to shake it awake.', attackBonus: 6, damage: '1 piercing', saveDc: 10, saveType: 'con' },
      { name: 'Heart Sight', type: 'ability', description: 'The sprite touches a creature and magically knows the creature\'s current emotional state. If the target fails a DC 10 Charisma saving throw, the sprite also knows the creature\'s alignment. Celestials, fiends, and undead automatically fail the saving throw.', saveDc: 10, saveType: 'cha' },
      { name: 'Invisibility', type: 'ability', description: 'The sprite magically turns invisible until it attacks or casts a spell, or until its concentration ends. Any equipment the sprite wears or carries is invisible with it.' },
    ],
    tags: ['fey', 'tiny', 'forest', 'scout'],
  },
  {
    id: 'fey-lamia',
    name: 'Lamia',
    cr: 4,
    size: 'Large',
    type: 'monstrosity',
    alignment: 'chaotic evil',
    armorClass: 13,
    hitPoints: 97,
    hitDice: '13d10+26',
    speed: '30 ft.',
    abilities: { str: 16, dex: 13, con: 15, int: 14, wis: 15, cha: 16 },
    skills: ['Deception +7', 'Insight +4', 'Stealth +3'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 12'],
    languages: ['Abyssal', 'Common'],
    traits: [
      { name: 'Innate Spellcasting', type: 'trait', description: 'Spellcasting ability is Charisma (spell save DC 13). At will: disguise self (any humanoid form), major image. 3/day each: charm person, mirror image, scrying, suggestion. 1/day: geas.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The lamia makes two attacks: one with its claws and one with its dagger or Intoxicating Touch.' },
      { name: 'Claws', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 14 (2d10+3) slashing damage.', attackBonus: 5, damage: '2d10+3 slashing' },
      { name: 'Dagger', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 5 (1d4+3) piercing damage.', attackBonus: 5, damage: '1d4+3 piercing' },
      { name: 'Intoxicating Touch', type: 'ability', description: 'Melee Spell Attack: +5 to hit, reach 5 ft., one creature. Hit: The target is magically cursed for 1 hour. Until the curse ends, the target has disadvantage on Wisdom saving throws and all ability checks.', attackBonus: 5, damage: '0' },
    ],
    tags: ['monstrosity', 'desert', 'charm', 'lion-woman'],
  },
]
