import type { Monster } from './types'

// Demons, Devils, and other Fiends from the SRD
export const FIENDS: Monster[] = [
  // ─── DEMONS ────────────────────────────────────────────────────────────────
  {
    id: 'fiend-balor',
    name: 'Balor',
    cr: 19,
    size: 'Huge',
    type: 'fiend',
    alignment: 'chaotic evil',
    armorClass: 19,
    hitPoints: 262,
    hitDice: '21d12+126',
    speed: '40 ft., fly 80 ft.',
    abilities: { str: 26, dex: 15, con: 22, int: 20, wis: 16, cha: 22 },
    senses: ['Truesight 120 ft.', 'Passive Perception 13'],
    languages: ['Abyssal', 'telepathy 120 ft.'],
    traits: [
      { name: 'Death Throes', type: 'trait', description: 'When the balor dies, it explodes, and each creature within 30 ft. of it must make a DC 20 Dexterity saving throw, taking 70 (20d6) fire damage on a failed save, or half as much on a successful one. The explosion also destroys the balor\'s weapons.', saveDc: 20, saveType: 'dex' },
      { name: 'Fire Aura', type: 'trait', description: 'At the start of each of the balor\'s turns, each creature within 5 ft. of it takes 10 (3d6) fire damage, and flammable objects in the aura that aren\'t being worn or carried ignite. A creature that touches the balor or hits it with a melee attack while within 5 ft. of it takes 10 (3d6) fire damage.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The balor has advantage on saving throws against spells and other magical effects.' },
      { name: 'Magic Weapons', type: 'trait', description: 'The balor\'s weapon attacks are magical.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The balor makes two attacks: one with its longsword and one with its whip.' },
      { name: 'Longsword', type: 'attack', description: 'Melee Weapon Attack: +14 to hit, reach 10 ft., one target. Hit: 21 (3d8+8) slashing damage plus 13 (3d8) lightning damage. If the balor scores a critical hit, it rolls damage dice three times, instead of twice.', attackBonus: 14, damage: '3d8+8 slashing + 3d8 lightning' },
      { name: 'Whip', type: 'attack', description: 'Melee Weapon Attack: +14 to hit, reach 30 ft., one target. Hit: 15 (2d6+8) slashing damage plus 10 (3d6) fire damage, and the target must succeed on a DC 20 Strength saving throw or be pulled up to 25 ft. toward the balor.', attackBonus: 14, damage: '2d6+8 slashing + 3d6 fire', saveDc: 20, saveType: 'str' },
      { name: 'Teleport', type: 'ability', description: 'The balor magically teleports, along with any equipment it is wearing or carrying, up to 120 ft. to an unoccupied space it can see.' },
    ],
    tags: ['demon', 'fiend', 'legendary', 'boss'],
  },
  {
    id: 'fiend-barlgura',
    name: 'Barlgura',
    cr: 5,
    size: 'Large',
    type: 'fiend',
    alignment: 'chaotic evil',
    armorClass: 15,
    hitPoints: 68,
    hitDice: '8d10+24',
    speed: '40 ft., climb 40 ft.',
    abilities: { str: 18, dex: 15, con: 16, int: 7, wis: 14, cha: 9 },
    skills: ['Perception +5', 'Stealth +5'],
    senses: ['Blindsight 30 ft.', 'Darkvision 120 ft.', 'Passive Perception 15'],
    languages: ['Abyssal', 'telepathy 120 ft.'],
    traits: [
      { name: 'Innate Spellcasting', type: 'trait', description: 'Spellcasting ability is Wisdom (spell save DC 13). 1/day each: entangle, phantasmal force. 2/day each: disguise self, invisibility (self only).' },
      { name: 'Reckless', type: 'trait', description: 'At the start of its turn, the barlgura can gain advantage on all melee weapon attack rolls it makes during that turn, but attack rolls against it have advantage until the start of its next turn.' },
      { name: 'Running Leap', type: 'trait', description: 'With a 10-ft. running start, the barlgura can long jump up to 40 ft.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The barlgura makes three attacks: one with its bite and two with its fists.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 11 (2d6+4) piercing damage.', attackBonus: 7, damage: '2d6+4 piercing' },
      { name: 'Fist', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 9 (2d4+4) bludgeoning damage.', attackBonus: 7, damage: '2d4+4 bludgeoning' },
    ],
    tags: ['demon', 'fiend', 'ape-like'],
  },
  {
    id: 'fiend-dretch',
    name: 'Dretch',
    cr: 0.25,
    size: 'Small',
    type: 'fiend',
    alignment: 'chaotic evil',
    armorClass: 11,
    hitPoints: 18,
    hitDice: '4d6+4',
    speed: '20 ft.',
    abilities: { str: 11, dex: 11, con: 12, int: 5, wis: 8, cha: 3 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 9'],
    languages: ['Abyssal', 'telepathy 60 ft. (works only with creatures that understand Abyssal)'],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The dretch makes two attacks: one with its bite and one with its claws.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +2 to hit, reach 5 ft., one target. Hit: 3 (1d6) piercing damage.', attackBonus: 2, damage: '1d6 piercing' },
      { name: 'Claws', type: 'attack', description: 'Melee Weapon Attack: +2 to hit, reach 5 ft., one target. Hit: 5 (2d4) slashing damage.', attackBonus: 2, damage: '2d4 slashing' },
      { name: 'Fetid Cloud (1/Day)', type: 'ability', description: 'A 10-ft. radius of disgusting green gas extends out from the dretch. The gas spreads around corners, and its area is lightly obscured. It lasts for 1 minute or until a strong wind disperses it. Any creature that starts its turn in that area must succeed on a DC 11 Constitution saving throw or be poisoned until the start of its next turn.', saveDc: 11, saveType: 'con' },
    ],
    tags: ['demon', 'fiend', 'weak', 'minion'],
  },
  {
    id: 'fiend-glabrezu',
    name: 'Glabrezu',
    cr: 9,
    size: 'Large',
    type: 'fiend',
    alignment: 'chaotic evil',
    armorClass: 17,
    hitPoints: 157,
    hitDice: '15d10+75',
    speed: '40 ft.',
    abilities: { str: 20, dex: 15, con: 21, int: 19, wis: 17, cha: 16 },
    senses: ['Truesight 120 ft.', 'Passive Perception 13'],
    languages: ['Abyssal', 'telepathy 120 ft.'],
    traits: [
      { name: 'Innate Spellcasting', type: 'trait', description: 'Spellcasting ability is Intelligence (spell save DC 16). At will: darkness, detect magic, dispel magic. 1/day each: confusion, fly, power word stun.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The glabrezu has advantage on saving throws against spells and other magical effects.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The glabrezu makes four attacks: two with its pincers and two with its fists. Alternatively, it makes two attacks with its pincers and casts one spell.' },
      { name: 'Pincer', type: 'attack', description: 'Melee Weapon Attack: +9 to hit, reach 10 ft., one target. Hit: 16 (2d10+5) bludgeoning damage. If the target is a Medium or smaller creature, it is grappled (escape DC 15). The glabrezu has two pincers, each of which can grapple only one target.', attackBonus: 9, damage: '2d10+5 bludgeoning' },
      { name: 'Fist', type: 'attack', description: 'Melee Weapon Attack: +9 to hit, reach 5 ft., one target. Hit: 7 (2d4) bludgeoning damage.', attackBonus: 9, damage: '2d4 bludgeoning' },
    ],
    tags: ['demon', 'fiend', 'powerful', 'spellcaster'],
  },
  {
    id: 'fiend-hezrou',
    name: 'Hezrou',
    cr: 8,
    size: 'Large',
    type: 'fiend',
    alignment: 'chaotic evil',
    armorClass: 16,
    hitPoints: 136,
    hitDice: '13d10+65',
    speed: '30 ft.',
    abilities: { str: 19, dex: 17, con: 20, int: 5, wis: 12, cha: 13 },
    senses: ['Darkvision 120 ft.', 'Passive Perception 11'],
    languages: ['Abyssal', 'telepathy 120 ft.'],
    traits: [
      { name: 'Magic Resistance', type: 'trait', description: 'The hezrou has advantage on saving throws against spells and other magical effects.' },
      { name: 'Stench', type: 'trait', description: 'Any creature that starts its turn within 10 ft. of the hezrou must succeed on a DC 14 Constitution saving throw or be poisoned until the start of its next turn. On a successful saving throw, the creature is immune to the hezrou\'s stench for 24 hours.', saveDc: 14, saveType: 'con' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The hezrou makes three attacks: one with its bite and two with its claws.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 15 (2d10+4) piercing damage.', attackBonus: 7, damage: '2d10+4 piercing' },
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 11 (2d6+4) slashing damage.', attackBonus: 7, damage: '2d6+4 slashing' },
    ],
    tags: ['demon', 'fiend', 'frog-like', 'stench'],
  },
  {
    id: 'fiend-manes',
    name: 'Manes',
    cr: 0.125,
    size: 'Small',
    type: 'fiend',
    alignment: 'chaotic evil',
    armorClass: 9,
    hitPoints: 9,
    hitDice: '2d6+2',
    speed: '20 ft.',
    abilities: { str: 10, dex: 9, con: 13, int: 3, wis: 8, cha: 4 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 9'],
    languages: ['understands Abyssal but cannot speak'],
    actions: [
      { name: 'Claws', type: 'attack', description: 'Melee Weapon Attack: +2 to hit, reach 5 ft., one target. Hit: 5 (2d4) slashing damage.', attackBonus: 2, damage: '2d4 slashing' },
    ],
    tags: ['demon', 'fiend', 'weakest', 'minion'],
  },
  {
    id: 'fiend-marilith',
    name: 'Marilith',
    cr: 16,
    size: 'Large',
    type: 'fiend',
    alignment: 'chaotic evil',
    armorClass: 18,
    hitPoints: 189,
    hitDice: '18d10+90',
    speed: '40 ft.',
    abilities: { str: 18, dex: 20, con: 20, int: 18, wis: 16, cha: 20 },
    senses: ['Truesight 120 ft.', 'Passive Perception 13'],
    languages: ['Abyssal', 'telepathy 120 ft.'],
    traits: [
      { name: 'Magic Resistance', type: 'trait', description: 'The marilith has advantage on saving throws against spells and other magical effects.' },
      { name: 'Magic Weapons', type: 'trait', description: 'The marilith\'s weapon attacks are magical.' },
      { name: 'Reactive', type: 'trait', description: 'The marilith can take one reaction on every turn in a combat.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The marilith makes seven attacks: six with its longswords and one with its tail.' },
      { name: 'Longsword', type: 'attack', description: 'Melee Weapon Attack: +9 to hit, reach 5 ft., one target. Hit: 13 (2d8+4) slashing damage.', attackBonus: 9, damage: '2d8+4 slashing' },
      { name: 'Tail', type: 'attack', description: 'Melee Weapon Attack: +9 to hit, reach 10 ft., one creature. Hit: 15 (2d10+4) bludgeoning damage. If the target is Medium or smaller, it is grappled (escape DC 19). Until this grapple ends, the target is restrained, the marilith can automatically hit the target with its tail, and the marilith can\'t make tail attacks against other targets.', attackBonus: 9, damage: '2d10+4 bludgeoning' },
      { name: 'Teleport', type: 'ability', description: 'The marilith magically teleports, along with any equipment it is wearing or carrying, up to 120 ft. to an unoccupied space it can see.' },
    ],
    legendaryActions: [
      { name: 'Attack', type: 'attack', description: 'The marilith makes one attack with its longsword or tail.', attackBonus: 9, damage: '2d8+4 slashing' },
      { name: 'Parry', type: 'ability', description: 'The marilith adds 6 to its AC against one melee attack that would hit it. To do so, the marilith must see the attacker and be wielding a melee weapon.' },
      { name: 'Teleport', type: 'ability', description: 'The marilith uses its Teleport action.' },
    ],
    tags: ['demon', 'fiend', 'legendary', 'six-armed', 'serpentine'],
  },
  {
    id: 'fiend-quasit',
    name: 'Quasit',
    cr: 1,
    size: 'Tiny',
    type: 'fiend',
    alignment: 'chaotic evil',
    armorClass: 13,
    hitPoints: 7,
    hitDice: '3d4',
    speed: '40 ft.',
    abilities: { str: 5, dex: 17, con: 10, int: 7, wis: 10, cha: 10 },
    skills: ['Stealth +5'],
    senses: ['Darkvision 120 ft.', 'Passive Perception 10'],
    languages: ['Abyssal', 'Common'],
    traits: [
      { name: 'Magic Resistance', type: 'trait', description: 'The quasit has advantage on saving throws against spells and other magical effects.' },
      { name: 'Shapechanger', type: 'trait', description: 'The quasit can use its action to polymorph into a beast form that resembles a bat (speed 10 ft., fly 40 ft.), a centipede (40 ft., climb 40 ft.), or a toad (40 ft., swim 40 ft.), or back into its true form.' },
    ],
    actions: [
      { name: 'Claws (Quasit Form Only)', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d4+3) piercing damage, and the target must succeed on a DC 10 Constitution saving throw or take 5 (2d4) poison damage and become poisoned for 1 minute.', attackBonus: 4, damage: '1d4+3 piercing', saveDc: 10, saveType: 'con' },
      { name: 'Scare (1/Day)', type: 'ability', description: 'One creature of the quasit\'s choice within 20 ft. must succeed on a DC 10 Wisdom saving throw or be frightened for 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.', saveDc: 10, saveType: 'wis' },
      { name: 'Invisibility', type: 'ability', description: 'The quasit magically turns invisible until it attacks or uses Scare, or until its concentration ends. Any equipment the quasit wears or carries is invisible with it.' },
    ],
    tags: ['demon', 'fiend', 'familiar', 'small'],
  },
  {
    id: 'fiend-vrock',
    name: 'Vrock',
    cr: 6,
    size: 'Large',
    type: 'fiend',
    alignment: 'chaotic evil',
    armorClass: 15,
    hitPoints: 104,
    hitDice: '11d10+44',
    speed: '40 ft., fly 60 ft.',
    abilities: { str: 17, dex: 15, con: 18, int: 8, wis: 13, cha: 8 },
    senses: ['Darkvision 120 ft.', 'Passive Perception 11'],
    languages: ['Abyssal', 'telepathy 120 ft.'],
    traits: [
      { name: 'Magic Resistance', type: 'trait', description: 'The vrock has advantage on saving throws against spells and other magical effects.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The vrock makes two attacks: one with its beak and one with its talons.' },
      { name: 'Beak', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 10 (2d6+3) piercing damage.', attackBonus: 6, damage: '2d6+3 piercing' },
      { name: 'Talons', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 14 (2d10+3) slashing damage.', attackBonus: 6, damage: '2d10+3 slashing' },
      { name: 'Spores (Recharge 6)', type: 'ability', description: 'A 15-ft. radius cloud of toxic spores extends out from the vrock. The spores spread around corners. Each creature in that area must succeed on a DC 14 Constitution saving throw or become poisoned. While poisoned in this way, a target takes 5 (1d10) poison damage at the start of each of its turns. A target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.', saveDc: 14, saveType: 'con' },
      { name: 'Stunning Screech (1/Day)', type: 'ability', description: 'The vrock emits a horrific screech. Each creature within 20 ft. that can hear it must succeed on a DC 14 Constitution saving throw or be stunned until the end of the vrock\'s next turn.', saveDc: 14, saveType: 'con' },
    ],
    tags: ['demon', 'fiend', 'vulture-like', 'flying'],
  },

  // ─── DEVILS ─────────────────────────────────────────────────────────────────
  {
    id: 'fiend-barbed-devil',
    name: 'Barbed Devil',
    cr: 5,
    size: 'Medium',
    type: 'fiend',
    alignment: 'lawful evil',
    armorClass: 15,
    hitPoints: 110,
    hitDice: '13d8+52',
    speed: '30 ft.',
    abilities: { str: 16, dex: 17, con: 18, int: 12, wis: 14, cha: 14 },
    skills: ['Deception +5', 'Insight +5', 'Perception +8', 'Stealth +6'],
    senses: ['Darkvision 120 ft.', 'Passive Perception 18'],
    languages: ['Infernal', 'telepathy 120 ft.'],
    traits: [
      { name: 'Barbed Hide', type: 'trait', description: 'At the start of each of its turns, the barbed devil deals 5 (1d10) piercing damage to any creature grappling it.' },
      { name: 'Devil\'s Sight', type: 'trait', description: 'Magical darkness doesn\'t impede the devil\'s darkvision.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The devil has advantage on saving throws against spells and other magical effects.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The devil makes three melee attacks: one with its tail and two with its claws. Alternatively, it can use Hurl Flame twice.' },
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 6 (1d6+3) piercing damage.', attackBonus: 6, damage: '1d6+3 piercing' },
      { name: 'Tail', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 10 (2d6+3) piercing damage.', attackBonus: 6, damage: '2d6+3 piercing' },
      { name: 'Hurl Flame', type: 'attack', description: 'Ranged Spell Attack: +5 to hit, range 150 ft., one target. Hit: 10 (3d6) fire damage. If the target is a flammable object that isn\'t being worn or carried, it also catches fire.', attackBonus: 5, damage: '3d6 fire' },
    ],
    tags: ['devil', 'fiend', 'spiny', 'guard'],
  },
  {
    id: 'fiend-bone-devil',
    name: 'Bone Devil',
    cr: 9,
    size: 'Large',
    type: 'fiend',
    alignment: 'lawful evil',
    armorClass: 19,
    hitPoints: 142,
    hitDice: '15d10+60',
    speed: '40 ft., fly 40 ft.',
    abilities: { str: 18, dex: 16, con: 18, int: 13, wis: 14, cha: 16 },
    skills: ['Deception +7', 'Insight +6', 'Perception +6', 'Stealth +7'],
    senses: ['Darkvision 120 ft.', 'Passive Perception 16'],
    languages: ['Infernal', 'telepathy 120 ft.'],
    traits: [
      { name: 'Devil\'s Sight', type: 'trait', description: 'Magical darkness doesn\'t impede the devil\'s darkvision.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The devil has advantage on saving throws against spells and other magical effects.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The devil makes three attacks: two with its claws and one with its sting.' },
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +8 to hit, reach 10 ft., one target. Hit: 8 (1d8+4) slashing damage.', attackBonus: 8, damage: '1d8+4 slashing' },
      { name: 'Sting', type: 'attack', description: 'Melee Weapon Attack: +8 to hit, reach 10 ft., one target. Hit: 13 (2d8+4) piercing damage plus 17 (5d6) poison damage, and the target must succeed on a DC 14 Constitution saving throw or become poisoned for 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.', attackBonus: 8, damage: '2d8+4 piercing + 5d6 poison', saveDc: 14, saveType: 'con' },
    ],
    tags: ['devil', 'fiend', 'skeletal', 'poison'],
  },
  {
    id: 'fiend-chain-devil',
    name: 'Chain Devil',
    cr: 8,
    size: 'Medium',
    type: 'fiend',
    alignment: 'lawful evil',
    armorClass: 16,
    hitPoints: 85,
    hitDice: '10d8+40',
    speed: '30 ft.',
    abilities: { str: 18, dex: 15, con: 18, int: 11, wis: 12, cha: 14 },
    skills: ['Perception +4'],
    senses: ['Darkvision 120 ft.', 'Passive Perception 14'],
    languages: ['Infernal', 'telepathy 120 ft.'],
    traits: [
      { name: 'Devil\'s Sight', type: 'trait', description: 'Magical darkness doesn\'t impede the devil\'s darkvision.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The devil has advantage on saving throws against spells and other magical effects.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The devil makes two attacks with its chains.' },
      { name: 'Chain', type: 'attack', description: 'Melee Weapon Attack: +8 to hit, reach 10 ft., one target. Hit: 11 (2d6+4) slashing damage. The target is grappled (escape DC 14) if the devil isn\'t already grappling a creature. Until this grapple ends, the target is restrained and takes 7 (2d6) piercing damage at the start of each of its turns.', attackBonus: 8, damage: '2d6+4 slashing' },
      { name: 'Animate Chains (Recharges after a Short or Long Rest)', type: 'ability', description: 'Up to four chains the devil can see within 60 ft. of it magically sprout razor-edged barbs and animate under the devil\'s control, provided that the chains aren\'t being worn or carried. Each animated chain is an object with AC 20, 20 hit points, resistance to piercing damage, and immunity to psychic and thunder damage.' },
      { name: 'Unnerving Mask', type: 'ability', description: 'The chain devil\'s face becomes an illusory visage of one of its tormentor\'s most recent friends or family members until the start of its next turn. Each creature within 30 ft. that can see the mask must succeed on a DC 14 Wisdom saving throw or be frightened for 1 minute.', saveDc: 14, saveType: 'wis' },
    ],
    tags: ['devil', 'fiend', 'chains', 'restrainer'],
  },
  {
    id: 'fiend-erinyes',
    name: 'Erinyes',
    cr: 12,
    size: 'Medium',
    type: 'fiend',
    alignment: 'lawful evil',
    armorClass: 18,
    hitPoints: 153,
    hitDice: '18d8+72',
    speed: '30 ft., fly 60 ft.',
    abilities: { str: 18, dex: 16, con: 18, int: 14, wis: 14, cha: 18 },
    skills: ['Deception +8', 'Insight +6', 'Perception +6', 'Perception +10'],
    senses: ['Truesight 120 ft.', 'Passive Perception 16'],
    languages: ['Infernal', 'telepathy 120 ft.'],
    traits: [
      { name: 'Hellish Weapons', type: 'trait', description: 'The erinyes\'s weapon attacks are magical and deal an extra 13 (3d8) poison damage on a hit (included in the attacks).' },
      { name: 'Magic Resistance', type: 'trait', description: 'The erinyes has advantage on saving throws against spells and other magical effects.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The erinyes makes three attacks.' },
      { name: 'Longsword', type: 'attack', description: 'Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 8 (1d8+4) slashing damage, or 9 (1d10+4) slashing damage if used with two hands, plus 13 (3d8) poison damage.', attackBonus: 8, damage: '1d8+4 slashing + 3d8 poison' },
      { name: 'Longbow', type: 'attack', description: 'Ranged Weapon Attack: +7 to hit, range 150/600 ft., one target. Hit: 7 (1d8+3) piercing damage plus 13 (3d8) poison damage, and the target must succeed on a DC 14 Constitution saving throw or be poisoned. The poison lasts until it is removed by the lesser restoration spell or similar magic.', attackBonus: 7, damage: '1d8+3 piercing + 3d8 poison', saveDc: 14, saveType: 'con' },
    ],
    tags: ['devil', 'fiend', 'winged', 'archer', 'fallen angel'],
  },
  {
    id: 'fiend-ice-devil',
    name: 'Ice Devil',
    cr: 14,
    size: 'Large',
    type: 'fiend',
    alignment: 'lawful evil',
    armorClass: 18,
    hitPoints: 180,
    hitDice: '19d10+76',
    speed: '40 ft.',
    abilities: { str: 21, dex: 14, con: 18, int: 18, wis: 15, cha: 18 },
    skills: ['Perception +7'],
    senses: ['Blindsight 60 ft.', 'Darkvision 120 ft.', 'Passive Perception 17'],
    languages: ['Infernal', 'telepathy 120 ft.'],
    traits: [
      { name: 'Devil\'s Sight', type: 'trait', description: 'Magical darkness doesn\'t impede the devil\'s darkvision.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The devil has advantage on saving throws against spells and other magical effects.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The devil makes three attacks: one with its bite, one with its claws, and one with its tail.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +10 to hit, reach 5 ft., one target. Hit: 12 (2d6+5) piercing damage plus 10 (3d6) cold damage.', attackBonus: 10, damage: '2d6+5 piercing + 3d6 cold' },
      { name: 'Claws', type: 'attack', description: 'Melee Weapon Attack: +10 to hit, reach 5 ft., one target. Hit: 10 (2d4+5) slashing damage plus 10 (3d6) cold damage.', attackBonus: 10, damage: '2d4+5 slashing + 3d6 cold' },
      { name: 'Tail', type: 'attack', description: 'Melee Weapon Attack: +10 to hit, reach 10 ft., one target. Hit: 12 (2d6+5) bludgeoning damage plus 10 (3d6) cold damage.', attackBonus: 10, damage: '2d6+5 bludgeoning + 3d6 cold' },
      { name: 'Wall of Ice (Recharge 6)', type: 'ability', description: 'The devil magically forms an opaque wall of ice on a solid surface it can see within 60 ft. of it. The wall is 1 ft. thick and up to 30 ft. long and 10 ft. high, or it\'s a hemispherical dome up to 20 ft. in diameter. A creature in the wall\'s space when it appears must make a DC 17 Dexterity saving throw. On a success, the creature is pushed to one side of the wall (the creature\'s choice). On a failure, the creature takes 35 (10d6) cold damage and is encased in the ice.', saveDc: 17, saveType: 'dex' },
    ],
    tags: ['devil', 'fiend', 'cold', 'elite'],
  },
  {
    id: 'fiend-imp',
    name: 'Imp',
    cr: 1,
    size: 'Tiny',
    type: 'fiend',
    alignment: 'lawful evil',
    armorClass: 13,
    hitPoints: 10,
    hitDice: '3d4+3',
    speed: '20 ft., fly 40 ft.',
    abilities: { str: 6, dex: 17, con: 13, int: 11, wis: 12, cha: 14 },
    skills: ['Deception +4', 'Insight +3', 'Persuasion +4', 'Stealth +5'],
    senses: ['Darkvision 120 ft.', 'Passive Perception 11'],
    languages: ['Infernal', 'Common'],
    traits: [
      { name: 'Devil\'s Sight', type: 'trait', description: 'Magical darkness doesn\'t impede the imp\'s darkvision.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The imp has advantage on saving throws against spells and other magical effects.' },
      { name: 'Shapechanger', type: 'trait', description: 'The imp can use its action to polymorph into a beast form that resembles a rat (speed 20 ft.), a raven (20 ft., fly 60 ft.), or a spider (20 ft., climb 20 ft.), or back into its true form.' },
    ],
    actions: [
      { name: 'Sting (Bite in Beast Form)', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 5 (1d4+3) piercing damage, and the target must make a DC 11 Constitution saving throw, taking 10 (3d6) poison damage on a failed save, or half as much on a successful one.', attackBonus: 5, damage: '1d4+3 piercing', saveDc: 11, saveType: 'con' },
      { name: 'Invisibility', type: 'ability', description: 'The imp magically turns invisible until it attacks or until its concentration ends. Any equipment the imp wears or carries is invisible with it.' },
    ],
    tags: ['devil', 'fiend', 'familiar', 'tiny', 'shapeshifter'],
  },
  {
    id: 'fiend-lemure',
    name: 'Lemure',
    cr: 0,
    size: 'Medium',
    type: 'fiend',
    alignment: 'lawful evil',
    armorClass: 7,
    hitPoints: 13,
    hitDice: '3d8',
    speed: '15 ft.',
    abilities: { str: 10, dex: 5, con: 11, int: 1, wis: 11, cha: 3 },
    senses: ['Darkvision 120 ft.', 'Passive Perception 10'],
    languages: ['understands Infernal but cannot speak'],
    traits: [
      { name: 'Devil\'s Sight', type: 'trait', description: 'Magical darkness doesn\'t impede the lemure\'s darkvision.' },
      { name: 'Hellish Rejuvenation', type: 'trait', description: 'A lemure that dies in the Nine Hells comes back to life with all its hit points in 1d10 days unless it is killed by a good-aligned creature with the bless spell cast on it or its remains are sprinkled with holy water.' },
    ],
    actions: [
      { name: 'Fist', type: 'attack', description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 2 (1d4) bludgeoning damage.', attackBonus: 3, damage: '1d4 bludgeoning' },
    ],
    tags: ['devil', 'fiend', 'weakest', 'minion'],
  },
  {
    id: 'fiend-pit-fiend',
    name: 'Pit Fiend',
    cr: 20,
    size: 'Large',
    type: 'fiend',
    alignment: 'lawful evil',
    armorClass: 19,
    hitPoints: 300,
    hitDice: '24d10+168',
    speed: '30 ft., fly 60 ft.',
    abilities: { str: 26, dex: 14, con: 24, int: 22, wis: 18, cha: 24 },
    skills: ['Perception +10'],
    senses: ['Truesight 120 ft.', 'Passive Perception 20'],
    languages: ['Infernal', 'telepathy 120 ft.'],
    traits: [
      { name: 'Aura of Fear', type: 'trait', description: 'Each creature of the pit fiend\'s choice that is within 20 ft. of the pit fiend and aware of it must succeed on a DC 21 Wisdom saving throw or become frightened for 1 minute.', saveDc: 21, saveType: 'wis' },
      { name: 'Devil\'s Sight', type: 'trait', description: 'Magical darkness doesn\'t impede the devil\'s darkvision.' },
      { name: 'Innate Spellcasting', type: 'trait', description: 'Spellcasting ability is Charisma (spell save DC 21). At will: detect magic, fireball. 3/day each: hold monster, wall of fire.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The pit fiend has advantage on saving throws against spells and other magical effects.' },
      { name: 'Magic Weapons', type: 'trait', description: 'The pit fiend\'s weapon attacks are magical.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The pit fiend makes four attacks: one with its bite, one with its claw, one with its mace, and one with its tail.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +14 to hit, reach 5 ft., one target. Hit: 22 (4d6+8) piercing damage. The target must succeed on a DC 21 Constitution saving throw or become poisoned. While poisoned in this way, the target can\'t regain hit points, and it takes 21 (6d6) poison damage at the start of each of its turns. The poisoned target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.', attackBonus: 14, damage: '4d6+8 piercing', saveDc: 21, saveType: 'con' },
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +14 to hit, reach 10 ft., one target. Hit: 17 (2d8+8) slashing damage.', attackBonus: 14, damage: '2d8+8 slashing' },
      { name: 'Mace', type: 'attack', description: 'Melee Weapon Attack: +14 to hit, reach 10 ft., one target. Hit: 15 (2d6+8) bludgeoning damage plus 21 (6d6) fire damage.', attackBonus: 14, damage: '2d6+8 bludgeoning + 6d6 fire' },
      { name: 'Tail', type: 'attack', description: 'Melee Weapon Attack: +14 to hit, reach 10 ft., one target. Hit: 24 (3d10+8) bludgeoning damage.', attackBonus: 14, damage: '3d10+8 bludgeoning' },
    ],
    tags: ['devil', 'fiend', 'legendary', 'boss', 'arch-devil'],
  },

  // ─── OTHER FIENDS ────────────────────────────────────────────────────────────
  {
    id: 'fiend-incubus',
    name: 'Incubus',
    cr: 4,
    size: 'Medium',
    type: 'fiend',
    alignment: 'neutral evil',
    armorClass: 13,
    hitPoints: 66,
    hitDice: '12d8+12',
    speed: '30 ft., fly 60 ft.',
    abilities: { str: 8, dex: 17, con: 13, int: 15, wis: 12, cha: 20 },
    skills: ['Deception +9', 'Insight +5', 'Perception +5', 'Persuasion +9', 'Stealth +7'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 15'],
    languages: ['Abyssal', 'Common', 'Infernal', 'telepathy 60 ft.'],
    traits: [
      { name: 'Telepathic Bond', type: 'trait', description: 'The fiend ignores the range restriction on its telepathy when communicating with a creature it has charmed. The two don\'t even need to be on the same plane of existence.' },
      { name: 'Shapechanger', type: 'trait', description: 'The fiend can use its action to polymorph into a Small or Medium humanoid, or back into its true form.' },
    ],
    actions: [
      { name: 'Claw (Fiend Form Only)', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6+3) slashing damage.', attackBonus: 5, damage: '1d6+3 slashing' },
      { name: 'Charm', type: 'ability', description: 'One humanoid the fiend can see within 30 ft. must succeed on a DC 15 Wisdom saving throw or be magically charmed for 1 day. The charmed target obeys the fiend\'s verbal or telepathic commands. If the target suffers any harm or receives a suicidal command, it can repeat the saving throw. If the fiend or one of its companions harms the target, the condition ends immediately.', saveDc: 15, saveType: 'wis' },
      { name: 'Draining Kiss', type: 'ability', description: 'The fiend kisses a creature charmed by it or a willing creature. The target must make a DC 15 Constitution saving throw against this magic, taking 32 (5d10+5) psychic damage on a failed save, or half as much on a successful one. The target\'s hit point maximum is reduced by an amount equal to the damage taken. This reduction lasts until the target finishes a long rest.', saveDc: 15, saveType: 'con' },
      { name: 'Etherealness', type: 'ability', description: 'The fiend magically enters the Ethereal Plane from the Material Plane, or vice versa.' },
    ],
    tags: ['fiend', 'demon', 'charm', 'shapeshifter', 'seductive'],
  },
  {
    id: 'fiend-rakshasa',
    name: 'Rakshasa',
    cr: 13,
    size: 'Medium',
    type: 'fiend',
    alignment: 'lawful evil',
    armorClass: 16,
    hitPoints: 110,
    hitDice: '13d8+52',
    speed: '40 ft.',
    abilities: { str: 14, dex: 17, con: 18, int: 13, wis: 16, cha: 20 },
    skills: ['Deception +10', 'Insight +8'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 13'],
    languages: ['Common', 'Infernal'],
    traits: [
      { name: 'Limited Magic Immunity', type: 'trait', description: 'The rakshasa can\'t be affected or detected by spells of 6th level or lower unless it wishes to be. It has advantage on saving throws against all other spells and magical effects.' },
      { name: 'Innate Spellcasting', type: 'trait', description: 'Spellcasting ability is Charisma (spell save DC 18). At will: detect thoughts, disguise self, mage hand, minor illusion. 3/day each: charm person, detect magic, invisibility, major image, suggestion. 1/day each: dominate person, fly, plane shift, true seeing.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The rakshasa makes two claw attacks.' },
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 9 (2d6+2) slashing damage, and the target is cursed if it is a creature. The magical curse takes effect whenever the target takes a short or long rest, filling the target\'s thoughts with horrible images and dreams. The cursed target gains no benefit from finishing a short or long rest. The curse lasts until it is lifted by a remove curse spell or similar magic.', attackBonus: 7, damage: '2d6+2 slashing' },
    ],
    tags: ['fiend', 'shapeshifter', 'spellcaster', 'curse', 'tiger-faced'],
  },
]
