import type { Monster } from './types'

export const GIANTS: Monster[] = [
  {
    id: 'giant-cloud-giant',
    name: 'Cloud Giant',
    cr: 9,
    size: 'Huge',
    type: 'giant',
    alignment: 'neutral good (50%) or neutral evil (50%)',
    armorClass: 14,
    hitPoints: 200,
    hitDice: '16d12+96',
    speed: '40 ft.',
    abilities: { str: 27, dex: 10, con: 22, int: 12, wis: 16, cha: 16 },
    skills: ['Insight +7', 'Perception +7'],
    senses: ['Passive Perception 17'],
    languages: ['Common', 'Giant'],
    traits: [
      { name: 'Keen Smell', type: 'trait', description: 'The giant has advantage on Wisdom (Perception) checks that rely on smell.' },
      { name: 'Innate Spellcasting', type: 'trait', description: 'Spellcasting ability is Charisma (spell save DC 15). At will: detect magic, fog cloud, light. 3/day each: feather fall, fly, misty step, telekinesis. 1/day each: control weather, gaseous form.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The giant makes two morningstar attacks.' },
      { name: 'Morningstar', type: 'attack', description: 'Melee Weapon Attack: +12 to hit, reach 10 ft., one target. Hit: 21 (3d8+8) piercing damage.', attackBonus: 12, damage: '3d8+8 piercing' },
      { name: 'Rock', type: 'attack', description: 'Ranged Weapon Attack: +12 to hit, range 60/240 ft., one target. Hit: 30 (4d10+8) bludgeoning damage.', attackBonus: 12, damage: '4d10+8 bludgeoning' },
    ],
    tags: ['giant', 'cloud', 'spellcaster'],
  },
  {
    id: 'giant-cyclops',
    name: 'Cyclops',
    cr: 6,
    size: 'Huge',
    type: 'giant',
    alignment: 'chaotic neutral',
    armorClass: 14,
    hitPoints: 138,
    hitDice: '12d12+60',
    speed: '30 ft.',
    abilities: { str: 22, dex: 11, con: 20, int: 8, wis: 6, cha: 10 },
    senses: ['Passive Perception 8'],
    languages: ['Giant'],
    traits: [
      { name: 'Poor Depth Perception', type: 'trait', description: 'The cyclops has disadvantage on any attack roll against a target more than 30 ft. away.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The cyclops makes two greatclub attacks.' },
      { name: 'Greatclub', type: 'attack', description: 'Melee Weapon Attack: +9 to hit, reach 10 ft., one target. Hit: 19 (3d8+6) bludgeoning damage.', attackBonus: 9, damage: '3d8+6 bludgeoning' },
      { name: 'Rock', type: 'attack', description: 'Ranged Weapon Attack: +9 to hit, range 30/120 ft., one target. Hit: 28 (4d10+6) bludgeoning damage. If the target is a creature, it must succeed on a DC 17 Strength saving throw or be knocked prone.', attackBonus: 9, damage: '4d10+6 bludgeoning', saveDc: 17, saveType: 'str' },
    ],
    tags: ['giant', 'one-eyed', 'brute'],
  },
  {
    id: 'giant-ettin',
    name: 'Ettin',
    cr: 4,
    size: 'Large',
    type: 'giant',
    alignment: 'chaotic evil',
    armorClass: 12,
    hitPoints: 85,
    hitDice: '10d10+30',
    speed: '40 ft.',
    abilities: { str: 21, dex: 8, con: 17, int: 6, wis: 10, cha: 8 },
    skills: ['Perception +4'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 14'],
    languages: ['Giant', 'Orc'],
    traits: [
      { name: 'Two Heads', type: 'trait', description: 'The ettin has advantage on Wisdom (Perception) checks and on saving throws against being blinded, charmed, deafened, frightened, stunned, and knocked unconscious.' },
      { name: 'Wakeful', type: 'trait', description: 'When one of the ettin\'s heads is asleep, its other head is awake.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The ettin makes two attacks: one with its battleaxe and one with its morningstar.' },
      { name: 'Battleaxe', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 14 (2d8+5) slashing damage.', attackBonus: 7, damage: '2d8+5 slashing' },
      { name: 'Morningstar', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 14 (2d8+5) piercing damage.', attackBonus: 7, damage: '2d8+5 piercing' },
    ],
    tags: ['giant', 'two-headed', 'orc ally'],
  },
  {
    id: 'giant-fire-giant',
    name: 'Fire Giant',
    cr: 9,
    size: 'Huge',
    type: 'giant',
    alignment: 'lawful evil',
    armorClass: 18,
    hitPoints: 162,
    hitDice: '13d12+78',
    speed: '30 ft.',
    abilities: { str: 25, dex: 9, con: 23, int: 10, wis: 14, cha: 13 },
    skills: ['Athletics +11', 'Perception +6'],
    senses: ['Passive Perception 16'],
    languages: ['Giant'],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The giant makes two greatsword attacks.' },
      { name: 'Greatsword', type: 'attack', description: 'Melee Weapon Attack: +11 to hit, reach 10 ft., one target. Hit: 28 (6d6+7) slashing damage.', attackBonus: 11, damage: '6d6+7 slashing' },
      { name: 'Rock', type: 'attack', description: 'Ranged Weapon Attack: +11 to hit, range 60/240 ft., one target. Hit: 29 (4d10+7) bludgeoning damage.', attackBonus: 11, damage: '4d10+7 bludgeoning' },
    ],
    tags: ['giant', 'fire', 'soldier'],
  },
  {
    id: 'giant-frost-giant',
    name: 'Frost Giant',
    cr: 8,
    size: 'Huge',
    type: 'giant',
    alignment: 'neutral evil',
    armorClass: 15,
    hitPoints: 138,
    hitDice: '12d12+60',
    speed: '40 ft.',
    abilities: { str: 23, dex: 9, con: 21, int: 9, wis: 10, cha: 12 },
    skills: ['Athletics +9', 'Perception +3'],
    senses: ['Passive Perception 13'],
    languages: ['Giant'],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The giant makes two greataxe attacks.' },
      { name: 'Greataxe', type: 'attack', description: 'Melee Weapon Attack: +9 to hit, reach 10 ft., one target. Hit: 25 (3d12+6) slashing damage.', attackBonus: 9, damage: '3d12+6 slashing' },
      { name: 'Rock', type: 'attack', description: 'Ranged Weapon Attack: +9 to hit, range 60/240 ft., one target. Hit: 28 (4d10+6) bludgeoning damage.', attackBonus: 9, damage: '4d10+6 bludgeoning' },
    ],
    tags: ['giant', 'cold', 'raider'],
  },
  {
    id: 'giant-hill-giant',
    name: 'Hill Giant',
    cr: 5,
    size: 'Huge',
    type: 'giant',
    alignment: 'chaotic evil',
    armorClass: 13,
    hitPoints: 105,
    hitDice: '10d12+40',
    speed: '40 ft.',
    abilities: { str: 21, dex: 8, con: 19, int: 5, wis: 9, cha: 6 },
    skills: ['Perception +2'],
    senses: ['Passive Perception 12'],
    languages: ['Giant'],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The giant makes two greatclub attacks.' },
      { name: 'Greatclub', type: 'attack', description: 'Melee Weapon Attack: +8 to hit, reach 10 ft., one target. Hit: 18 (3d8+5) bludgeoning damage.', attackBonus: 8, damage: '3d8+5 bludgeoning' },
      { name: 'Rock', type: 'attack', description: 'Ranged Weapon Attack: +8 to hit, range 60/240 ft., one target. Hit: 21 (3d10+5) bludgeoning damage.', attackBonus: 8, damage: '3d10+5 bludgeoning' },
    ],
    tags: ['giant', 'hill', 'brute'],
  },
  {
    id: 'giant-ogre',
    name: 'Ogre',
    cr: 2,
    size: 'Large',
    type: 'giant',
    alignment: 'chaotic evil',
    armorClass: 11,
    hitPoints: 59,
    hitDice: '7d10+21',
    speed: '40 ft.',
    abilities: { str: 19, dex: 8, con: 16, int: 5, wis: 7, cha: 7 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 8'],
    languages: ['Common', 'Giant'],
    actions: [
      { name: 'Greatclub', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 13 (2d8+4) bludgeoning damage.', attackBonus: 6, damage: '2d8+4 bludgeoning' },
      { name: 'Javelin', type: 'attack', description: 'Melee or Ranged Weapon Attack: +6 to hit, reach 5 ft. or range 30/120 ft., one target. Hit: 11 (2d6+4) piercing damage.', attackBonus: 6, damage: '2d6+4 piercing' },
    ],
    tags: ['giant', 'brute', 'low level'],
  },
  {
    id: 'giant-oni',
    name: 'Oni',
    cr: 7,
    size: 'Large',
    type: 'giant',
    alignment: 'lawful evil',
    armorClass: 16,
    hitPoints: 110,
    hitDice: '13d10+39',
    speed: '30 ft., fly 30 ft.',
    abilities: { str: 19, dex: 11, con: 16, int: 14, wis: 12, cha: 15 },
    skills: ['Arcana +5', 'Deception +8', 'Perception +4'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 14'],
    languages: ['Common', 'Giant'],
    traits: [
      { name: 'Innate Spellcasting', type: 'trait', description: 'Spellcasting ability is Charisma (spell save DC 13). At will: darkness, invisibility. 1/day each: charm person, cone of cold, gaseous form, sleep.' },
      { name: 'Magic Weapons', type: 'trait', description: 'The oni\'s weapon attacks are magical.' },
      { name: 'Regeneration', type: 'trait', description: 'The oni regains 10 hit points at the start of its turn if it has at least 1 hit point.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The oni makes two attacks, either with its claws or its glaive.' },
      { name: 'Claw (Oni Form Only)', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 8 (1d8+4) slashing damage.', attackBonus: 7, damage: '1d8+4 slashing' },
      { name: 'Glaive', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 10 ft., one target. Hit: 15 (2d10+4) slashing damage, or 9 (1d10+4) slashing damage in Small or Medium form.', attackBonus: 7, damage: '2d10+4 slashing' },
      { name: 'Change Shape', type: 'ability', description: 'The oni magically polymorphs into a Small or Medium humanoid, into a Large giant, or back into its true form. Its statistics, other than its size, are the same in each form.' },
    ],
    tags: ['giant', 'shapeshifter', 'spellcaster', 'japanese'],
  },
  {
    id: 'giant-stone-giant',
    name: 'Stone Giant',
    cr: 7,
    size: 'Huge',
    type: 'giant',
    alignment: 'neutral',
    armorClass: 17,
    hitPoints: 126,
    hitDice: '11d12+55',
    speed: '40 ft.',
    abilities: { str: 23, dex: 15, con: 20, int: 10, wis: 12, cha: 9 },
    skills: ['Athletics +12', 'Perception +4'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 14'],
    languages: ['Giant'],
    traits: [
      { name: 'Stone Camouflage', type: 'trait', description: 'The giant has advantage on Dexterity (Stealth) checks made to hide in rocky terrain.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The giant makes two greatclub attacks.' },
      { name: 'Greatclub', type: 'attack', description: 'Melee Weapon Attack: +9 to hit, reach 15 ft., one target. Hit: 19 (3d8+6) bludgeoning damage.', attackBonus: 9, damage: '3d8+6 bludgeoning' },
      { name: 'Rock', type: 'attack', description: 'Ranged Weapon Attack: +9 to hit, range 60/240 ft., one target. Hit: 28 (4d10+6) bludgeoning damage. If the target is a creature, it must succeed on a DC 17 Strength saving throw or be knocked prone.', attackBonus: 9, damage: '4d10+6 bludgeoning', saveDc: 17, saveType: 'str' },
    ],
    tags: ['giant', 'stone', 'cave'],
  },
  {
    id: 'giant-storm-giant',
    name: 'Storm Giant',
    cr: 13,
    size: 'Huge',
    type: 'giant',
    alignment: 'chaotic good',
    armorClass: 16,
    hitPoints: 230,
    hitDice: '20d12+100',
    speed: '50 ft., swim 50 ft.',
    abilities: { str: 29, dex: 14, con: 20, int: 16, wis: 18, cha: 18 },
    skills: ['Arcana +8', 'Athletics +14', 'History +8', 'Perception +9'],
    senses: ['Passive Perception 19'],
    languages: ['Common', 'Giant'],
    traits: [
      { name: 'Amphibious', type: 'trait', description: 'The giant can breathe air and water.' },
      { name: 'Innate Spellcasting', type: 'trait', description: 'Spellcasting ability is Charisma (spell save DC 17). At will: detect magic, feather fall, levitate, light. 3/day each: control weather, water breathing.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The giant makes two greatsword attacks.' },
      { name: 'Greatsword', type: 'attack', description: 'Melee Weapon Attack: +14 to hit, reach 10 ft., one target. Hit: 30 (6d6+9) slashing damage.', attackBonus: 14, damage: '6d6+9 slashing' },
      { name: 'Rock', type: 'attack', description: 'Ranged Weapon Attack: +14 to hit, range 60/240 ft., one target. Hit: 35 (4d12+9) bludgeoning damage.', attackBonus: 14, damage: '4d12+9 bludgeoning' },
      { name: 'Lightning Strike (Recharge 5-6)', type: 'ability', description: 'The giant hurls a magical lightning bolt at a point it can see within 500 ft. Each creature within 10 ft. of that point must make a DC 17 Dexterity saving throw, taking 54 (12d8) lightning damage on a failed save, or half as much on a successful one.', saveDc: 17, saveType: 'dex' },
    ],
    tags: ['giant', 'storm', 'lightning', 'sea'],
  },
  {
    id: 'giant-troll',
    name: 'Troll',
    cr: 5,
    size: 'Large',
    type: 'giant',
    alignment: 'chaotic evil',
    armorClass: 15,
    hitPoints: 84,
    hitDice: '8d10+40',
    speed: '30 ft.',
    abilities: { str: 18, dex: 13, con: 20, int: 7, wis: 9, cha: 7 },
    skills: ['Perception +2'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 12'],
    languages: ['Giant'],
    traits: [
      { name: 'Keen Smell', type: 'trait', description: 'The troll has advantage on Wisdom (Perception) checks that rely on smell.' },
      { name: 'Regeneration', type: 'trait', description: 'The troll regains 10 hit points at the start of its turn. If the troll takes acid or fire damage, this trait doesn\'t function at the start of the troll\'s next turn. The troll dies only if it starts its turn with 0 hit points and doesn\'t regenerate.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The troll makes three attacks: one with its bite and two with its claws.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 7 (1d6+4) piercing damage.', attackBonus: 7, damage: '1d6+4 piercing' },
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 11 (2d6+4) slashing damage.', attackBonus: 7, damage: '2d6+4 slashing' },
    ],
    tags: ['giant', 'regeneration', 'fire weakness'],
  },
]
