import type { Monster } from './types'

export const HUMANOIDS: Monster[] = [
  {
    id: 'humanoid-acolyte',
    name: 'Acolyte',
    cr: 0.25,
    size: 'Medium',
    type: 'humanoid',
    alignment: 'any alignment',
    armorClass: 10,
    hitPoints: 9,
    hitDice: '2d8',
    speed: '30 ft.',
    abilities: { str: 10, dex: 10, con: 10, int: 10, wis: 14, cha: 11 },
    skills: ['Medicine +4', 'Religion +2'],
    senses: ['Passive Perception 12'],
    languages: ['any one language'],
    traits: [
      { name: 'Spellcasting', type: 'trait', description: 'The acolyte is a 1st-level spellcaster. Its spellcasting ability is Wisdom (spell save DC 12, +4 to hit with spell attacks). It has the following cleric spells prepared: Cantrips: light, sacred flame, thaumaturgy. 1st level (3 slots): bless, cure wounds, sanctuary.' },
    ],
    actions: [
      { name: 'Club', type: 'attack', description: 'Melee Weapon Attack: +2 to hit, reach 5 ft., one target. Hit: 2 (1d4) bludgeoning damage.', attackBonus: 2, damage: '1d4 bludgeoning' },
    ],
    tags: ['humanoid', 'npc', 'priest', 'spellcaster'],
  },
  {
    id: 'humanoid-assassin',
    name: 'Assassin',
    cr: 8,
    size: 'Medium',
    type: 'humanoid',
    alignment: 'any non-good alignment',
    armorClass: 15,
    hitPoints: 78,
    hitDice: '12d8+24',
    speed: '30 ft.',
    abilities: { str: 11, dex: 16, con: 14, int: 13, wis: 11, cha: 10 },
    skills: ['Acrobatics +6', 'Deception +3', 'Perception +3', 'Stealth +9'],
    senses: ['Passive Perception 13'],
    languages: ['Thieves\' cant plus any two languages'],
    traits: [
      { name: 'Assassinate', type: 'trait', description: 'During its first turn, the assassin has advantage on attack rolls against any creature that hasn\'t taken a turn. Any hit the assassin scores against a surprised creature is a critical hit.' },
      { name: 'Evasion', type: 'trait', description: 'If the assassin is subjected to an effect that allows it to make a Dexterity saving throw to take only half damage, the assassin instead takes no damage if it succeeds on the saving throw, and only half damage if it fails.' },
      { name: 'Sneak Attack (1/Turn)', type: 'trait', description: 'The assassin deals an extra 14 (4d6) damage when it hits a target with a weapon attack and has advantage on the attack roll, or when the target is within 5 ft. of an ally of the assassin that isn\'t incapacitated and the assassin doesn\'t have disadvantage on the attack roll.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The assassin makes two shortsword attacks.' },
      { name: 'Shortsword', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 6 (1d6+3) piercing damage, and the target must make a DC 15 Constitution saving throw, taking 24 (7d6) poison damage on a failed save, or half as much on a successful one.', attackBonus: 6, damage: '1d6+3 piercing', saveDc: 15, saveType: 'con' },
      { name: 'Light Crossbow', type: 'attack', description: 'Ranged Weapon Attack: +6 to hit, range 80/320 ft., one target. Hit: 7 (1d8+3) piercing damage, and the target must make a DC 15 Constitution saving throw, taking 24 (7d6) poison damage on a failed save, or half as much on a successful one.', attackBonus: 6, damage: '1d8+3 piercing', saveDc: 15, saveType: 'con' },
    ],
    tags: ['humanoid', 'npc', 'rogue', 'poison'],
  },
  {
    id: 'humanoid-bandit-captain',
    name: 'Bandit Captain',
    cr: 2,
    size: 'Medium',
    type: 'humanoid',
    alignment: 'any non-lawful alignment',
    armorClass: 15,
    hitPoints: 65,
    hitDice: '10d8+20',
    speed: '30 ft.',
    abilities: { str: 15, dex: 16, con: 14, int: 14, wis: 11, cha: 14 },
    skills: ['Athletics +4', 'Deception +4'],
    senses: ['Passive Perception 10'],
    languages: ['any two languages'],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The captain makes three melee attacks: two with its scimitar and one with its dagger. Or the captain makes two ranged attacks with its daggers.' },
      { name: 'Scimitar', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6+3) slashing damage.', attackBonus: 5, damage: '1d6+3 slashing' },
      { name: 'Dagger', type: 'attack', description: 'Melee or Ranged Weapon Attack: +5 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 5 (1d4+3) piercing damage.', attackBonus: 5, damage: '1d4+3 piercing' },
    ],
    tags: ['humanoid', 'npc', 'leader', 'bandit'],
  },
  {
    id: 'humanoid-berserker',
    name: 'Berserker',
    cr: 2,
    size: 'Medium',
    type: 'humanoid',
    alignment: 'any chaotic alignment',
    armorClass: 13,
    hitPoints: 67,
    hitDice: '9d8+27',
    speed: '30 ft.',
    abilities: { str: 16, dex: 12, con: 17, int: 9, wis: 11, cha: 9 },
    senses: ['Passive Perception 10'],
    languages: ['any one language'],
    traits: [
      { name: 'Reckless', type: 'trait', description: 'At the start of its turn, the berserker can gain advantage on all melee weapon attack rolls during that turn, but attack rolls against it have advantage until the start of its next turn.' },
    ],
    actions: [
      { name: 'Greataxe', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 9 (1d12+3) slashing damage.', attackBonus: 5, damage: '1d12+3 slashing' },
    ],
    tags: ['humanoid', 'npc', 'barbarian', 'reckless'],
  },
  {
    id: 'humanoid-commoner',
    name: 'Commoner',
    cr: 0,
    size: 'Medium',
    type: 'humanoid',
    alignment: 'any alignment',
    armorClass: 10,
    hitPoints: 4,
    hitDice: '1d8',
    speed: '30 ft.',
    abilities: { str: 10, dex: 10, con: 10, int: 10, wis: 10, cha: 10 },
    senses: ['Passive Perception 10'],
    languages: ['any one language'],
    actions: [
      { name: 'Club', type: 'attack', description: 'Melee Weapon Attack: +2 to hit, reach 5 ft., one target. Hit: 2 (1d4) bludgeoning damage.', attackBonus: 2, damage: '1d4 bludgeoning' },
    ],
    tags: ['humanoid', 'npc', 'civilian'],
  },
  {
    id: 'humanoid-cult-fanatic',
    name: 'Cult Fanatic',
    cr: 2,
    size: 'Medium',
    type: 'humanoid',
    alignment: 'any non-good alignment',
    armorClass: 13,
    hitPoints: 33,
    hitDice: '6d8+6',
    speed: '30 ft.',
    abilities: { str: 11, dex: 14, con: 12, int: 10, wis: 13, cha: 14 },
    skills: ['Deception +4', 'Persuasion +4', 'Religion +2'],
    senses: ['Passive Perception 11'],
    languages: ['any one language'],
    traits: [
      { name: 'Dark Devotion', type: 'trait', description: 'The fanatic has advantage on saving throws against being charmed or frightened.' },
      { name: 'Spellcasting', type: 'trait', description: 'The fanatic is a 4th-level spellcaster. Its spellcasting ability is Wisdom (spell save DC 11, +3 to hit). It has the following cleric spells: Cantrips: light, sacred flame, thaumaturgy. 1st level (4 slots): command, inflict wounds, shield of faith. 2nd level (3 slots): hold person, spiritual weapon.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The fanatic makes two melee attacks.' },
      { name: 'Dagger', type: 'attack', description: 'Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 20/60 ft., one creature. Hit: 4 (1d4+2) piercing damage.', attackBonus: 4, damage: '1d4+2 piercing' },
    ],
    tags: ['humanoid', 'npc', 'cult', 'spellcaster'],
  },
  {
    id: 'humanoid-cultist',
    name: 'Cultist',
    cr: 0.125,
    size: 'Medium',
    type: 'humanoid',
    alignment: 'any non-good alignment',
    armorClass: 12,
    hitPoints: 9,
    hitDice: '2d8',
    speed: '30 ft.',
    abilities: { str: 11, dex: 12, con: 10, int: 10, wis: 11, cha: 10 },
    skills: ['Deception +2', 'Religion +2'],
    senses: ['Passive Perception 10'],
    languages: ['any one language'],
    traits: [
      { name: 'Dark Devotion', type: 'trait', description: 'The cultist has advantage on saving throws against being charmed or frightened.' },
    ],
    actions: [
      { name: 'Scimitar', type: 'attack', description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one creature. Hit: 4 (1d6+1) slashing damage.', attackBonus: 3, damage: '1d6+1 slashing' },
    ],
    tags: ['humanoid', 'npc', 'cult', 'minion'],
  },
  {
    id: 'humanoid-druid',
    name: 'Druid',
    cr: 2,
    size: 'Medium',
    type: 'humanoid',
    alignment: 'any alignment',
    armorClass: 11,
    hitPoints: 27,
    hitDice: '5d8+5',
    speed: '30 ft.',
    abilities: { str: 10, dex: 12, con: 13, int: 12, wis: 15, cha: 11 },
    skills: ['Medicine +4', 'Nature +3', 'Perception +4'],
    senses: ['Passive Perception 14'],
    languages: ['Druidic plus any two languages'],
    traits: [
      { name: 'Spellcasting', type: 'trait', description: 'The druid is a 4th-level spellcaster. Its spellcasting ability is Wisdom (spell save DC 12, +4 to hit). It has the following druid spells: Cantrips: druidcraft, produce flame, shillelagh. 1st level (4 slots): entangle, longstrider, speak with animals, thunderwave. 2nd level (3 slots): animal messenger, barkskin.' },
    ],
    actions: [
      { name: 'Quarterstaff', type: 'attack', description: 'Melee Weapon Attack: +2 to hit (+4 to hit with shillelagh), reach 5 ft., one target. Hit: 3 (1d6) bludgeoning damage, 4 (1d6+1) bludgeoning damage if wielded with two hands, or 6 (1d8+2) bludgeoning damage with shillelagh.', attackBonus: 2, damage: '1d6 bludgeoning' },
    ],
    tags: ['humanoid', 'npc', 'druid', 'spellcaster', 'nature'],
  },
  {
    id: 'humanoid-gladiator',
    name: 'Gladiator',
    cr: 5,
    size: 'Medium',
    type: 'humanoid',
    alignment: 'any alignment',
    armorClass: 16,
    hitPoints: 112,
    hitDice: '15d8+45',
    speed: '30 ft.',
    abilities: { str: 18, dex: 15, con: 16, int: 10, wis: 12, cha: 15 },
    skills: ['Athletics +10', 'Intimidation +5'],
    senses: ['Passive Perception 11'],
    languages: ['any one language'],
    traits: [
      { name: 'Brave', type: 'trait', description: 'The gladiator has advantage on saving throws against being frightened.' },
      { name: 'Brute', type: 'trait', description: 'A melee weapon deals one extra die of its damage when the gladiator hits with it (included in the attack).' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The gladiator makes three melee attacks or two ranged attacks.' },
      { name: 'Spear', type: 'attack', description: 'Melee or Ranged Weapon Attack: +7 to hit, reach 5 ft. and range 20/60 ft., one target. Hit: 11 (2d6+4) piercing damage, or 13 (2d8+4) piercing damage if used with two hands to make a melee attack.', attackBonus: 7, damage: '2d6+4 piercing' },
      { name: 'Shield Bash', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one creature. Hit: 9 (2d4+4) bludgeoning damage. If the target is Medium or smaller, it must succeed on a DC 15 Strength saving throw or be knocked prone.', attackBonus: 7, damage: '2d4+4 bludgeoning', saveDc: 15, saveType: 'str' },
    ],
    tags: ['humanoid', 'npc', 'fighter', 'arena'],
  },
  {
    id: 'humanoid-guard',
    name: 'Guard',
    cr: 0.125,
    size: 'Medium',
    type: 'humanoid',
    alignment: 'any alignment',
    armorClass: 16,
    hitPoints: 11,
    hitDice: '2d8+2',
    speed: '30 ft.',
    abilities: { str: 13, dex: 12, con: 12, int: 10, wis: 11, cha: 10 },
    skills: ['Perception +2'],
    senses: ['Passive Perception 12'],
    languages: ['any one language'],
    actions: [
      { name: 'Spear', type: 'attack', description: 'Melee or Ranged Weapon Attack: +3 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 4 (1d6+1) piercing damage.', attackBonus: 3, damage: '1d6+1 piercing' },
    ],
    tags: ['humanoid', 'npc', 'soldier', 'city'],
  },
  {
    id: 'humanoid-knight',
    name: 'Knight',
    cr: 3,
    size: 'Medium',
    type: 'humanoid',
    alignment: 'any alignment',
    armorClass: 18,
    hitPoints: 52,
    hitDice: '8d8+16',
    speed: '30 ft.',
    abilities: { str: 16, dex: 11, con: 14, int: 11, wis: 11, cha: 15 },
    skills: ['History +2', 'Perception +2'],
    senses: ['Passive Perception 12'],
    languages: ['any one language'],
    traits: [
      { name: 'Brave', type: 'trait', description: 'The knight has advantage on saving throws against being frightened.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The knight makes two melee attacks.' },
      { name: 'Greatsword', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6+3) slashing damage.', attackBonus: 5, damage: '2d6+3 slashing' },
      { name: 'Heavy Crossbow', type: 'attack', description: 'Ranged Weapon Attack: +2 to hit, range 100/400 ft., one target. Hit: 5 (1d10) piercing damage.', attackBonus: 2, damage: '1d10 piercing' },
      { name: 'Leadership (Recharges after a Short or Long Rest)', type: 'ability', description: 'For 1 minute, the knight can utter a special command or warning whenever a nonhostile creature that it can see within 30 ft. of it makes an attack roll or a saving throw. That creature can add a d4 to its roll provided it can hear and understand the knight.' },
    ],
    tags: ['humanoid', 'npc', 'fighter', 'elite', 'noble'],
  },
  {
    id: 'humanoid-mage',
    name: 'Mage',
    cr: 6,
    size: 'Medium',
    type: 'humanoid',
    alignment: 'any alignment',
    armorClass: 12,
    hitPoints: 40,
    hitDice: '9d8',
    speed: '30 ft.',
    abilities: { str: 9, dex: 14, con: 11, int: 17, wis: 12, cha: 11 },
    skills: ['Arcana +6', 'History +6'],
    senses: ['Passive Perception 11'],
    languages: ['any four languages'],
    traits: [
      { name: 'Spellcasting', type: 'trait', description: 'The mage is a 9th-level spellcaster. Its spellcasting ability is Intelligence (spell save DC 14, +6 to hit). It has the following wizard spells: Cantrips: fire bolt, light, mage hand, prestidigitation. 1st level (4 slots): detect magic, mage armor, magic missile, shield. 2nd level (3 slots): misty step, suggestion. 3rd level (3 slots): counterspell, fireball, fly. 4th level (3 slots): greater invisibility, ice storm. 5th level (1 slot): cone of cold.' },
    ],
    actions: [
      { name: 'Dagger', type: 'attack', description: 'Melee or Ranged Weapon Attack: +5 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 4 (1d4+2) piercing damage.', attackBonus: 5, damage: '1d4+2 piercing' },
    ],
    tags: ['humanoid', 'npc', 'wizard', 'spellcaster'],
  },
  {
    id: 'humanoid-noble',
    name: 'Noble',
    cr: 0.125,
    size: 'Medium',
    type: 'humanoid',
    alignment: 'any alignment',
    armorClass: 15,
    hitPoints: 9,
    hitDice: '2d8',
    speed: '30 ft.',
    abilities: { str: 11, dex: 12, con: 11, int: 12, wis: 14, cha: 16 },
    skills: ['Deception +5', 'Insight +4', 'Persuasion +5'],
    senses: ['Passive Perception 12'],
    languages: ['any two languages'],
    actions: [
      { name: 'Rapier', type: 'attack', description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 5 (1d8+1) piercing damage.', attackBonus: 3, damage: '1d8+1 piercing' },
    ],
    tags: ['humanoid', 'npc', 'social', 'city'],
  },
  {
    id: 'humanoid-priest',
    name: 'Priest',
    cr: 2,
    size: 'Medium',
    type: 'humanoid',
    alignment: 'any alignment',
    armorClass: 13,
    hitPoints: 27,
    hitDice: '5d8+5',
    speed: '30 ft.',
    abilities: { str: 10, dex: 10, con: 12, int: 13, wis: 16, cha: 13 },
    skills: ['Medicine +7', 'Persuasion +3', 'Religion +4'],
    senses: ['Passive Perception 13'],
    languages: ['any two languages'],
    traits: [
      { name: 'Divine Eminence', type: 'trait', description: 'As a bonus action, the priest can expend a spell slot to cause its melee weapon attacks to magically deal an extra 10 (3d6) radiant damage to a target on a hit. This benefit lasts until the end of the turn. If the priest expends a spell slot of 2nd level or higher, the extra damage increases by 1d6 for each level above 1st.' },
      { name: 'Spellcasting', type: 'trait', description: 'The priest is a 5th-level spellcaster. Its spellcasting ability is Wisdom (spell save DC 13, +5 to hit). It has the following cleric spells: Cantrips: light, sacred flame, thaumaturgy. 1st level (4 slots): cure wounds, guiding bolt, sanctuary. 2nd level (3 slots): lesser restoration, spiritual weapon. 3rd level (2 slots): dispel magic, spirit guardians.' },
    ],
    actions: [
      { name: 'Mace', type: 'attack', description: 'Melee Weapon Attack: +2 to hit, reach 5 ft., one target. Hit: 3 (1d6) bludgeoning damage.', attackBonus: 2, damage: '1d6 bludgeoning' },
    ],
    tags: ['humanoid', 'npc', 'cleric', 'spellcaster', 'healer'],
  },
  {
    id: 'humanoid-scout',
    name: 'Scout',
    cr: 0.5,
    size: 'Medium',
    type: 'humanoid',
    alignment: 'any alignment',
    armorClass: 13,
    hitPoints: 16,
    hitDice: '3d8+3',
    speed: '30 ft.',
    abilities: { str: 11, dex: 14, con: 12, int: 11, wis: 13, cha: 11 },
    skills: ['Nature +4', 'Perception +5', 'Stealth +6', 'Survival +5'],
    senses: ['Passive Perception 15'],
    languages: ['any one language'],
    traits: [
      { name: 'Keen Hearing and Sight', type: 'trait', description: 'The scout has advantage on Wisdom (Perception) checks that rely on hearing or sight.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The scout makes two melee attacks or two ranged attacks.' },
      { name: 'Shortsword', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6+2) piercing damage.', attackBonus: 4, damage: '1d6+2 piercing' },
      { name: 'Longbow', type: 'attack', description: 'Ranged Weapon Attack: +4 to hit, range 150/600 ft., one target. Hit: 6 (1d8+2) piercing damage.', attackBonus: 4, damage: '1d8+2 piercing' },
    ],
    tags: ['humanoid', 'npc', 'ranger', 'forest'],
  },
  {
    id: 'humanoid-spy',
    name: 'Spy',
    cr: 1,
    size: 'Medium',
    type: 'humanoid',
    alignment: 'any alignment',
    armorClass: 12,
    hitPoints: 27,
    hitDice: '6d8',
    speed: '30 ft.',
    abilities: { str: 10, dex: 15, con: 10, int: 12, wis: 14, cha: 16 },
    skills: ['Deception +5', 'Insight +4', 'Investigation +5', 'Perception +6', 'Persuasion +5', 'Sleight of Hand +4', 'Stealth +4'],
    senses: ['Passive Perception 16'],
    languages: ['any two languages'],
    traits: [
      { name: 'Cunning Action', type: 'trait', description: 'On each of its turns, the spy can use a bonus action to take the Dash, Disengage, or Hide action.' },
      { name: 'Sneak Attack (1/Turn)', type: 'trait', description: 'The spy deals an extra 7 (2d6) damage when it hits a target with a weapon attack and has advantage on the attack roll, or when the target is within 5 ft. of an ally of the spy that isn\'t incapacitated and the spy doesn\'t have disadvantage on the attack roll.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The spy makes two melee attacks.' },
      { name: 'Shortsword', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6+2) piercing damage.', attackBonus: 4, damage: '1d6+2 piercing' },
      { name: 'Hand Crossbow', type: 'attack', description: 'Ranged Weapon Attack: +4 to hit, range 30/120 ft., one target. Hit: 5 (1d6+2) piercing damage.', attackBonus: 4, damage: '1d6+2 piercing' },
    ],
    tags: ['humanoid', 'npc', 'rogue', 'stealth'],
  },
  {
    id: 'humanoid-thug',
    name: 'Thug',
    cr: 0.5,
    size: 'Medium',
    type: 'humanoid',
    alignment: 'any non-good alignment',
    armorClass: 11,
    hitPoints: 32,
    hitDice: '5d8+10',
    speed: '30 ft.',
    abilities: { str: 15, dex: 11, con: 14, int: 10, wis: 10, cha: 11 },
    skills: ['Intimidation +2'],
    senses: ['Passive Perception 10'],
    languages: ['any one language'],
    traits: [
      { name: 'Pack Tactics', type: 'trait', description: 'The thug has advantage on an attack roll against a creature if at least one of the thug\'s allies is adjacent to the creature and the ally isn\'t incapacitated.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The thug makes two melee attacks.' },
      { name: 'Mace', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 5 (1d6+2) bludgeoning damage.', attackBonus: 4, damage: '1d6+2 bludgeoning' },
      { name: 'Heavy Crossbow', type: 'attack', description: 'Ranged Weapon Attack: +2 to hit, range 100/400 ft., one target. Hit: 5 (1d10) piercing damage.', attackBonus: 2, damage: '1d10 piercing' },
    ],
    tags: ['humanoid', 'npc', 'bully', 'gang'],
  },
  {
    id: 'humanoid-tribal-warrior',
    name: 'Tribal Warrior',
    cr: 0.125,
    size: 'Medium',
    type: 'humanoid',
    alignment: 'any alignment',
    armorClass: 12,
    hitPoints: 11,
    hitDice: '2d8+2',
    speed: '30 ft.',
    abilities: { str: 13, dex: 11, con: 12, int: 8, wis: 11, cha: 8 },
    senses: ['Passive Perception 10'],
    languages: ['any one language'],
    traits: [
      { name: 'Pack Tactics', type: 'trait', description: 'The warrior has advantage on an attack roll against a creature if at least one of the warrior\'s allies is adjacent to the creature and the ally isn\'t incapacitated.' },
    ],
    actions: [
      { name: 'Spear', type: 'attack', description: 'Melee or Ranged Weapon Attack: +3 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 4 (1d6+1) piercing damage.', attackBonus: 3, damage: '1d6+1 piercing' },
    ],
    tags: ['humanoid', 'npc', 'primitive', 'pack'],
  },
  {
    id: 'humanoid-veteran',
    name: 'Veteran',
    cr: 3,
    size: 'Medium',
    type: 'humanoid',
    alignment: 'any alignment',
    armorClass: 17,
    hitPoints: 58,
    hitDice: '9d8+18',
    speed: '30 ft.',
    abilities: { str: 16, dex: 13, con: 14, int: 10, wis: 11, cha: 10 },
    skills: ['Athletics +5', 'Perception +2'],
    senses: ['Passive Perception 12'],
    languages: ['any one language'],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The veteran makes two longsword attacks. If it has a shortsword drawn, it can also make a shortsword attack.' },
      { name: 'Longsword', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 7 (1d8+3) slashing damage, or 8 (1d10+3) slashing damage if used with two hands.', attackBonus: 5, damage: '1d8+3 slashing' },
      { name: 'Shortsword', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6+3) piercing damage.', attackBonus: 5, damage: '1d6+3 piercing' },
      { name: 'Heavy Crossbow', type: 'attack', description: 'Ranged Weapon Attack: +3 to hit, range 100/400 ft., one target. Hit: 6 (1d10+1) piercing damage.', attackBonus: 3, damage: '1d10+1 piercing' },
    ],
    tags: ['humanoid', 'npc', 'fighter', 'soldier', 'experienced'],
  },
]
