import type { Monster } from './types'

export const MONSTROSITIES: Monster[] = [
  {
    id: 'monstrosity-basilisk',
    name: 'Basilisk',
    cr: 3,
    size: 'Medium',
    type: 'monstrosity',
    alignment: 'unaligned',
    armorClass: 15,
    hitPoints: 52,
    hitDice: '8d8+16',
    speed: '20 ft.',
    abilities: { str: 16, dex: 8, con: 15, int: 2, wis: 8, cha: 7 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 9'],
    traits: [
      { name: 'Petrifying Gaze', type: 'trait', description: 'If a creature starts its turn within 30 ft. of the basilisk and the two of them can see each other, the basilisk can force the creature to make a DC 12 Constitution saving throw if the basilisk isn\'t incapacitated. On a failed save, the creature magically begins to turn to stone and is restrained. It must repeat the saving throw at the end of its next turn. On a success, the effect ends. On a failure, the creature is petrified until freed by the greater restoration spell or similar magic.', saveDc: 12, saveType: 'con' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6+3) piercing damage.', attackBonus: 5, damage: '2d6+3 piercing' },
    ],
    tags: ['monstrosity', 'petrification', 'cave', 'eight-legged'],
  },
  {
    id: 'monstrosity-behir',
    name: 'Behir',
    cr: 11,
    size: 'Huge',
    type: 'monstrosity',
    alignment: 'neutral evil',
    armorClass: 17,
    hitPoints: 168,
    hitDice: '16d12+64',
    speed: '50 ft., climb 40 ft.',
    abilities: { str: 23, dex: 16, con: 18, int: 7, wis: 14, cha: 12 },
    skills: ['Perception +6', 'Stealth +7'],
    senses: ['Darkvision 90 ft.', 'Passive Perception 16'],
    languages: ['Draconic'],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The behir makes two attacks: one with its bite and one to constrict.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +10 to hit, reach 10 ft., one target. Hit: 22 (3d10+6) piercing damage.', attackBonus: 10, damage: '3d10+6 piercing' },
      { name: 'Constrict', type: 'attack', description: 'Melee Weapon Attack: +10 to hit, reach 5 ft., one Large or smaller creature. Hit: 17 (2d10+6) bludgeoning damage plus 17 (2d10+6) slashing damage. The target is grappled (escape DC 16) if the behir isn\'t already constricting a creature, and the target is restrained until this grapple ends.', attackBonus: 10, damage: '2d10+6 bludgeoning + 2d10+6 slashing' },
      { name: 'Lightning Breath (Recharge 5-6)', type: 'ability', description: 'The behir exhales a line of lightning that is 20 ft. long and 5 ft. wide. Each creature in that line must make a DC 16 Dexterity saving throw, taking 66 (12d10) lightning damage on a failed save, or half as much on a successful one.', saveDc: 16, saveType: 'dex' },
      { name: 'Swallow', type: 'ability', description: 'The behir makes one bite attack against a Medium or smaller target it is grappling. If the attack hits, the target is also swallowed, and the grapple ends. While swallowed, the target is blinded and restrained, it has total cover against attacks and other effects outside the behir, and it takes 21 (6d6) acid damage at the start of each of the behir\'s turns.' },
    ],
    tags: ['monstrosity', 'lightning', 'serpentine', 'swallow'],
  },
  {
    id: 'monstrosity-bulette',
    name: 'Bulette',
    cr: 5,
    size: 'Large',
    type: 'monstrosity',
    alignment: 'unaligned',
    armorClass: 17,
    hitPoints: 94,
    hitDice: '9d10+45',
    speed: '40 ft., burrow 40 ft.',
    abilities: { str: 19, dex: 11, con: 21, int: 2, wis: 10, cha: 5 },
    skills: ['Perception +6'],
    senses: ['Darkvision 60 ft.', 'Tremorsense 60 ft.', 'Passive Perception 16'],
    traits: [
      { name: 'Standing Leap', type: 'trait', description: 'The bulette\'s long jump is up to 30 ft. and its high jump is up to 15 ft., with or without a running start.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 30 (4d12+4) piercing damage.', attackBonus: 7, damage: '4d12+4 piercing' },
      { name: 'Deadly Leap', type: 'ability', description: 'If the bulette jumps at least 15 ft. as part of its movement, it can then use this action to land on its feet in a space that contains one or more other creatures. Each of those creatures must succeed on a DC 16 Strength or Dexterity saving throw (target\'s choice) or be knocked prone and take 14 (3d6+4) bludgeoning damage plus 14 (3d6+4) slashing damage. On a successful save, the creature takes only half the damage, isn\'t knocked prone, and is pushed 5 ft. out of the bulette\'s space into an unoccupied space of the creature\'s choice.', saveDc: 16, saveType: 'str' },
    ],
    tags: ['monstrosity', 'land shark', 'burrow', 'ambusher'],
  },
  {
    id: 'monstrosity-carrion-crawler',
    name: 'Carrion Crawler',
    cr: 2,
    size: 'Large',
    type: 'monstrosity',
    alignment: 'unaligned',
    armorClass: 13,
    hitPoints: 51,
    hitDice: '6d10+18',
    speed: '30 ft., climb 30 ft.',
    abilities: { str: 14, dex: 13, con: 16, int: 1, wis: 12, cha: 5 },
    skills: ['Perception +3'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 13'],
    traits: [
      { name: 'Keen Smell', type: 'trait', description: 'The carrion crawler has advantage on Wisdom (Perception) checks that rely on smell.' },
      { name: 'Spider Climb', type: 'trait', description: 'The carrion crawler can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The carrion crawler makes two attacks: one with its tentacles and one with its bite.' },
      { name: 'Tentacles', type: 'attack', description: 'Melee Weapon Attack: +8 to hit, reach 10 ft., one creature. Hit: 4 (1d4+2) poison damage, and the target must succeed on a DC 13 Constitution saving throw or be poisoned for 1 minute. Until this poison ends, the target is paralyzed.', attackBonus: 8, damage: '1d4+2 poison', saveDc: 13, saveType: 'con' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4+2) piercing damage.', attackBonus: 4, damage: '2d4+2 piercing' },
    ],
    tags: ['monstrosity', 'underdark', 'paralysis', 'scavenger'],
  },
  {
    id: 'monstrosity-centaur',
    name: 'Centaur',
    cr: 2,
    size: 'Large',
    type: 'monstrosity',
    alignment: 'neutral good',
    armorClass: 12,
    hitPoints: 45,
    hitDice: '6d10+12',
    speed: '50 ft.',
    abilities: { str: 18, dex: 14, con: 14, int: 9, wis: 13, cha: 11 },
    skills: ['Athletics +6', 'Perception +3', 'Survival +3'],
    senses: ['Passive Perception 13'],
    languages: ['Elvish', 'Sylvan'],
    traits: [
      { name: 'Charge', type: 'trait', description: 'If the centaur moves at least 30 ft. straight toward a target and then hits it with a pike attack on the same turn, the target takes an extra 10 (3d6) piercing damage.', },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The centaur makes two attacks: one with its pike and one with its hooves or two with its longbow.' },
      { name: 'Pike', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 10 ft., one target. Hit: 9 (1d10+4) piercing damage.', attackBonus: 6, damage: '1d10+4 piercing' },
      { name: 'Hooves', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 11 (2d6+4) bludgeoning damage.', attackBonus: 6, damage: '2d6+4 bludgeoning' },
      { name: 'Longbow', type: 'attack', description: 'Ranged Weapon Attack: +4 to hit, range 150/600 ft., one target. Hit: 6 (1d8+2) piercing damage.', attackBonus: 4, damage: '1d8+2 piercing' },
    ],
    tags: ['monstrosity', 'forest', 'archer'],
  },
  {
    id: 'monstrosity-chimera',
    name: 'Chimera',
    cr: 6,
    size: 'Large',
    type: 'monstrosity',
    alignment: 'chaotic evil',
    armorClass: 14,
    hitPoints: 114,
    hitDice: '12d10+48',
    speed: '30 ft., fly 60 ft.',
    abilities: { str: 19, dex: 11, con: 19, int: 3, wis: 14, cha: 10 },
    skills: ['Perception +8'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 18'],
    languages: ['understands Draconic but can\'t speak it'],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The chimera makes three attacks: one with its bite, one with its horns, and one with its claws. When its fire breath is available, it can use the breath in place of its bite or horns.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 11 (2d6+4) piercing damage.', attackBonus: 7, damage: '2d6+4 piercing' },
      { name: 'Horns', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 10 (1d12+4) bludgeoning damage.', attackBonus: 7, damage: '1d12+4 bludgeoning' },
      { name: 'Claws', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 11 (2d6+4) slashing damage.', attackBonus: 7, damage: '2d6+4 slashing' },
      { name: 'Fire Breath (Recharge 5-6)', type: 'ability', description: 'The dragon head exhales fire in a 15-ft. cone. Each creature in that area must make a DC 15 Dexterity saving throw, taking 31 (7d8) fire damage on a failed save, or half as much on a successful one.', saveDc: 15, saveType: 'dex' },
    ],
    tags: ['monstrosity', 'three-headed', 'flying', 'fire'],
  },
  {
    id: 'monstrosity-cockatrice',
    name: 'Cockatrice',
    cr: 0.5,
    size: 'Small',
    type: 'monstrosity',
    alignment: 'unaligned',
    armorClass: 11,
    hitPoints: 27,
    hitDice: '6d6+6',
    speed: '20 ft., fly 40 ft.',
    abilities: { str: 6, dex: 12, con: 12, int: 2, wis: 13, cha: 5 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 11'],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one creature. Hit: 3 (1d4+1) piercing damage, and the target must succeed on a DC 11 Constitution saving throw against being magically petrified. On a failed save, the creature begins to turn to stone and is restrained. It must repeat the saving throw at the end of its next turn. On a success, the effect ends. On a failure, the creature is petrified for 24 hours.', attackBonus: 3, damage: '1d4+1 piercing', saveDc: 11, saveType: 'con' },
    ],
    tags: ['monstrosity', 'petrification', 'small', 'flying'],
  },
  {
    id: 'monstrosity-ettercap',
    name: 'Ettercap',
    cr: 2,
    size: 'Medium',
    type: 'monstrosity',
    alignment: 'neutral evil',
    armorClass: 13,
    hitPoints: 44,
    hitDice: '8d8+8',
    speed: '30 ft., climb 30 ft.',
    abilities: { str: 14, dex: 15, con: 13, int: 7, wis: 12, cha: 8 },
    skills: ['Perception +3', 'Stealth +4', 'Survival +3'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 13'],
    traits: [
      { name: 'Spider Climb', type: 'trait', description: 'The ettercap can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check.' },
      { name: 'Web Sense', type: 'trait', description: 'While in contact with a web, the ettercap knows the exact location of any other creature in contact with the same web.' },
      { name: 'Web Walker', type: 'trait', description: 'The ettercap ignores movement restrictions caused by webbing.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The ettercap makes two attacks: one with its bite and one with its claws.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 6 (1d8+2) piercing damage plus 4 (1d8) poison damage. The target must succeed on a DC 11 Constitution saving throw or be poisoned for 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.', attackBonus: 4, damage: '1d8+2 piercing + 1d8 poison', saveDc: 11, saveType: 'con' },
      { name: 'Claws', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4+2) slashing damage.', attackBonus: 4, damage: '2d4+2 slashing' },
      { name: 'Web (Recharge 5-6)', type: 'ability', description: 'Ranged Weapon Attack: +4 to hit, range 30/60 ft., one Large or smaller creature. Hit: The creature is restrained by webbing. As an action, the restrained creature can make a DC 11 Strength check, escaping from the webbing on a success.', attackBonus: 4, damage: '0' },
    ],
    tags: ['monstrosity', 'spider', 'web', 'forest'],
  },
  {
    id: 'monstrosity-griffon',
    name: 'Griffon',
    cr: 2,
    size: 'Large',
    type: 'monstrosity',
    alignment: 'unaligned',
    armorClass: 12,
    hitPoints: 59,
    hitDice: '7d10+21',
    speed: '30 ft., fly 80 ft.',
    abilities: { str: 18, dex: 15, con: 16, int: 2, wis: 13, cha: 8 },
    skills: ['Perception +5'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 15'],
    traits: [
      { name: 'Keen Sight', type: 'trait', description: 'The griffon has advantage on Wisdom (Perception) checks that rely on sight.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The griffon makes two attacks: one with its beak and one with its claws.' },
      { name: 'Beak', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 8 (1d8+4) piercing damage.', attackBonus: 6, damage: '1d8+4 piercing' },
      { name: 'Claws', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 11 (2d6+4) slashing damage.', attackBonus: 6, damage: '2d6+4 slashing' },
    ],
    tags: ['monstrosity', 'flying', 'mount', 'lion-eagle'],
  },
  {
    id: 'monstrosity-harpy',
    name: 'Harpy',
    cr: 1,
    size: 'Medium',
    type: 'monstrosity',
    alignment: 'chaotic evil',
    armorClass: 11,
    hitPoints: 38,
    hitDice: '7d8+7',
    speed: '20 ft., fly 40 ft.',
    abilities: { str: 12, dex: 13, con: 12, int: 7, wis: 10, cha: 13 },
    senses: ['Passive Perception 10'],
    languages: ['Common'],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The harpy makes two attacks: one with its claws and one with its club.' },
      { name: 'Claws', type: 'attack', description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 6 (2d4+1) slashing damage.', attackBonus: 3, damage: '2d4+1 slashing' },
      { name: 'Club', type: 'attack', description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 3 (1d4+1) bludgeoning damage.', attackBonus: 3, damage: '1d4+1 bludgeoning' },
      { name: 'Luring Song', type: 'ability', description: 'The harpy sings a magical melody. Every humanoid and giant within 300 ft. of the harpy that can hear the song must succeed on a DC 11 Wisdom saving throw or be charmed until the song ends. The harpy must take a bonus action on its subsequent turns to continue singing. It can stop singing at any time. The song ends if the harpy is incapacitated. While charmed by the harpy, a target is incapacitated and ignores the songs of other harpies. If the charmed target is more than 5 ft. away from the harpy, the target must move on its turn toward the harpy by the most direct route.', saveDc: 11, saveType: 'wis' },
    ],
    tags: ['monstrosity', 'flying', 'charm', 'song'],
  },
  {
    id: 'monstrosity-hell-hound',
    name: 'Hell Hound',
    cr: 3,
    size: 'Medium',
    type: 'fiend',
    alignment: 'lawful evil',
    armorClass: 15,
    hitPoints: 45,
    hitDice: '7d8+14',
    speed: '50 ft.',
    abilities: { str: 17, dex: 12, con: 14, int: 6, wis: 13, cha: 6 },
    skills: ['Perception +5'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 15'],
    languages: ['understands Infernal but can\'t speak it'],
    traits: [
      { name: 'Keen Hearing and Smell', type: 'trait', description: 'The hound has advantage on Wisdom (Perception) checks that rely on hearing or smell.' },
      { name: 'Pack Tactics', type: 'trait', description: 'The hound has advantage on an attack roll against a creature if at least one of the hound\'s allies is adjacent to the creature and the ally isn\'t incapacitated.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 7 (1d8+3) piercing damage plus 7 (2d6) fire damage.', attackBonus: 5, damage: '1d8+3 piercing + 2d6 fire' },
      { name: 'Fire Breath (Recharge 5-6)', type: 'ability', description: 'The hound exhales fire in a 15-ft. cone. Each creature in that area must make a DC 12 Dexterity saving throw, taking 21 (6d6) fire damage on a failed save, or half as much on a successful one.', saveDc: 12, saveType: 'dex' },
    ],
    tags: ['fiend', 'dog', 'fire', 'pack'],
  },
  {
    id: 'monstrosity-hippogriff',
    name: 'Hippogriff',
    cr: 1,
    size: 'Large',
    type: 'monstrosity',
    alignment: 'unaligned',
    armorClass: 11,
    hitPoints: 19,
    hitDice: '3d10+3',
    speed: '40 ft., fly 60 ft.',
    abilities: { str: 17, dex: 13, con: 13, int: 2, wis: 12, cha: 8 },
    skills: ['Perception +5'],
    senses: ['Passive Perception 15'],
    traits: [
      { name: 'Keen Sight', type: 'trait', description: 'The hippogriff has advantage on Wisdom (Perception) checks that rely on sight.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The hippogriff makes two attacks: one with its beak and one with its claws.' },
      { name: 'Beak', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 8 (1d10+3) piercing damage.', attackBonus: 5, damage: '1d10+3 piercing' },
      { name: 'Claws', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6+3) slashing damage.', attackBonus: 5, damage: '2d6+3 slashing' },
    ],
    tags: ['monstrosity', 'flying', 'mount', 'horse-eagle'],
  },
  {
    id: 'monstrosity-hydra',
    name: 'Hydra',
    cr: 8,
    size: 'Huge',
    type: 'monstrosity',
    alignment: 'unaligned',
    armorClass: 15,
    hitPoints: 172,
    hitDice: '15d12+75',
    speed: '30 ft., swim 30 ft.',
    abilities: { str: 20, dex: 12, con: 20, int: 2, wis: 10, cha: 7 },
    skills: ['Perception +6'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 16'],
    traits: [
      { name: 'Hold Breath', type: 'trait', description: 'The hydra can hold its breath for 1 hour.' },
      { name: 'Multiple Heads', type: 'trait', description: 'The hydra has five heads. While it has more than one head, the hydra has advantage on saving throws against being blinded, charmed, deafened, frightened, stunned, and knocked unconscious. Whenever the hydra takes 25 or more damage in a single turn, one of its heads dies. If all its heads die, the hydra dies. At the end of its turn, it grows two heads for each of its heads that died since its last turn, unless it took fire damage since its last turn. The hydra regains 10 hit points for each head regrown this way.' },
      { name: 'Reactive Heads', type: 'trait', description: 'For each head the hydra has beyond one, it gets an extra reaction that can be used only for opportunity attacks.' },
      { name: 'Wakeful', type: 'trait', description: 'While the hydra sleeps, at least one of its heads is awake.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The hydra makes as many bite attacks as it has heads.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +8 to hit, reach 10 ft., one target. Hit: 10 (1d10+5) piercing damage.', attackBonus: 8, damage: '1d10+5 piercing' },
    ],
    tags: ['monstrosity', 'multi-headed', 'water', 'regeneration'],
  },
  {
    id: 'monstrosity-kraken',
    name: 'Kraken',
    cr: 23,
    size: 'Gargantuan',
    type: 'monstrosity',
    alignment: 'chaotic evil',
    armorClass: 18,
    hitPoints: 472,
    hitDice: '27d20+189',
    speed: '20 ft., swim 60 ft.',
    abilities: { str: 30, dex: 11, con: 25, int: 22, wis: 18, cha: 20 },
    skills: ['Perception +11'],
    senses: ['Truesight 120 ft.', 'Passive Perception 21'],
    languages: ['understands Abyssal, Celestial, Infernal, and Primordial but can\'t speak; telepathy 120 ft.'],
    traits: [
      { name: 'Amphibious', type: 'trait', description: 'The kraken can breathe air and water.' },
      { name: 'Freedom of Movement', type: 'trait', description: 'The kraken ignores difficult terrain, and magical effects can\'t reduce its speed or cause it to be restrained. It can spend 5 ft. of movement to escape from nonmagical restraints or being grappled.' },
      { name: 'Siege Monster', type: 'trait', description: 'The kraken deals double damage to objects and structures.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The kraken makes three tentacle attacks, each of which it can replace with one use of Fling.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +17 to hit, reach 5 ft., one target. Hit: 23 (3d8+10) piercing damage. If the target is a Large or smaller creature grappled by the kraken, that creature is swallowed, and the grapple ends.', attackBonus: 17, damage: '3d8+10 piercing' },
      { name: 'Tentacle', type: 'attack', description: 'Melee Weapon Attack: +17 to hit, reach 30 ft., one target. Hit: 20 (3d6+10) bludgeoning damage, and the target is grappled (escape DC 18). Until this grapple ends, the target is restrained. The kraken has ten tentacles, each of which can grapple one target.', attackBonus: 17, damage: '3d6+10 bludgeoning' },
      { name: 'Fling', type: 'ability', description: 'One Large or smaller object held or creature grappled by the kraken is thrown up to 60 ft. in a random direction and knocked prone. If a thrown target strikes a solid surface, the target takes 3 (1d6) bludgeoning damage for every 10 ft. it was thrown.' },
      { name: 'Lightning Storm', type: 'ability', description: 'The kraken magically creates three bolts of lightning, each of which can strike a target the kraken can see within 120 ft. of it. A target must make a DC 23 Dexterity saving throw, taking 22 (4d10) lightning damage on a failed save, or half as much on a successful one.', saveDc: 23, saveType: 'dex' },
    ],
    legendaryActions: [
      { name: 'Tentacle Attack or Fling', type: 'attack', description: 'The kraken makes one tentacle attack or uses its Fling.', attackBonus: 17, damage: '3d6+10 bludgeoning' },
      { name: 'Lightning Storm (Costs 2 Actions)', type: 'ability', description: 'The kraken uses Lightning Storm.', saveDc: 23, saveType: 'dex' },
      { name: 'Ink Cloud (Costs 3 Actions)', type: 'ability', description: 'While underwater, the kraken expels an ink cloud in a 60-ft. radius. The cloud spreads around corners, and that area is heavily obscured to creatures other than the kraken. Each creature other than the kraken that ends its turn there must succeed on a DC 23 Constitution saving throw, taking 16 (3d10) poison damage on a failed save, or half as much on a successful one.', saveDc: 23, saveType: 'con' },
    ],
    tags: ['monstrosity', 'legendary', 'sea', 'boss', 'mythic'],
  },
  {
    id: 'monstrosity-manticore',
    name: 'Manticore',
    cr: 3,
    size: 'Large',
    type: 'monstrosity',
    alignment: 'lawful evil',
    armorClass: 14,
    hitPoints: 68,
    hitDice: '8d10+24',
    speed: '30 ft., fly 50 ft.',
    abilities: { str: 17, dex: 16, con: 17, int: 7, wis: 12, cha: 8 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 11'],
    languages: ['Common'],
    traits: [
      { name: 'Tail Spike Regrowth', type: 'trait', description: 'The manticore has twenty-four tail spikes. Used spikes regrow when the manticore finishes a long rest.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The manticore makes three attacks: one with its bite and two with its claws or three with its tail spikes.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 7 (1d8+3) piercing damage.', attackBonus: 5, damage: '1d8+3 piercing' },
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6+3) slashing damage.', attackBonus: 5, damage: '1d6+3 slashing' },
      { name: 'Tail Spike', type: 'attack', description: 'Ranged Weapon Attack: +5 to hit, range 100/200 ft., one target. Hit: 7 (1d8+3) piercing damage.', attackBonus: 5, damage: '1d8+3 piercing' },
    ],
    tags: ['monstrosity', 'flying', 'lion', 'spikes'],
  },
  {
    id: 'monstrosity-medusa',
    name: 'Medusa',
    cr: 6,
    size: 'Medium',
    type: 'monstrosity',
    alignment: 'lawful evil',
    armorClass: 15,
    hitPoints: 127,
    hitDice: '17d8+51',
    speed: '30 ft.',
    abilities: { str: 10, dex: 15, con: 16, int: 12, wis: 13, cha: 15 },
    skills: ['Deception +5', 'Insight +4', 'Perception +4', 'Stealth +5'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 14'],
    languages: ['Common'],
    traits: [
      { name: 'Petrifying Gaze', type: 'trait', description: 'When a creature that can see the medusa\'s eyes starts its turn within 30 ft. of the medusa, the medusa can force it to make a DC 14 Constitution saving throw if the medusa isn\'t incapacitated and can see the creature. If the saving throw fails by 5 or more, the creature is instantly petrified. Otherwise, on a failed save, the creature is restrained and must repeat the saving throw at the end of its next turn. On a success, the effect ends. On a failure, the creature is petrified until freed by the greater restoration spell or similar magic.', saveDc: 14, saveType: 'con' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The medusa makes either three melee attacks—one with its snake hair and two with its shortsword—or two ranged attacks with its longbow.' },
      { name: 'Snake Hair', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one creature. Hit: 4 (1d4+2) piercing damage plus 14 (4d6) poison damage.', attackBonus: 5, damage: '1d4+2 piercing + 4d6 poison' },
      { name: 'Shortsword', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 5 (1d6+2) piercing damage.', attackBonus: 5, damage: '1d6+2 piercing' },
      { name: 'Longbow', type: 'attack', description: 'Ranged Weapon Attack: +5 to hit, range 150/600 ft., one target. Hit: 6 (1d8+2) piercing damage plus 7 (2d6) poison damage.', attackBonus: 5, damage: '1d8+2 piercing + 2d6 poison' },
    ],
    tags: ['monstrosity', 'petrification', 'snake hair', 'gaze'],
  },
  {
    id: 'monstrosity-minotaur',
    name: 'Minotaur',
    cr: 3,
    size: 'Large',
    type: 'monstrosity',
    alignment: 'chaotic evil',
    armorClass: 14,
    hitPoints: 76,
    hitDice: '9d10+27',
    speed: '40 ft.',
    abilities: { str: 18, dex: 11, con: 16, int: 6, wis: 16, cha: 9 },
    skills: ['Perception +7'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 17'],
    languages: ['Abyssal'],
    traits: [
      { name: 'Charge', type: 'trait', description: 'If the minotaur moves at least 10 ft. straight toward a target and then hits it with a gore attack on the same turn, the target takes an extra 9 (2d8) piercing damage. If the target is a creature, it must succeed on a DC 14 Strength saving throw or be pushed up to 10 ft. away and knocked prone.', saveDc: 14, saveType: 'str' },
      { name: 'Labyrinthine Recall', type: 'trait', description: 'The minotaur can perfectly recall any path it has traveled.' },
      { name: 'Reckless', type: 'trait', description: 'At the start of its turn, the minotaur can gain advantage on all melee weapon attack rolls it makes during that turn, but attack rolls against it have advantage until the start of its next turn.' },
    ],
    actions: [
      { name: 'Greataxe', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 17 (2d12+4) slashing damage.', attackBonus: 6, damage: '2d12+4 slashing' },
      { name: 'Gore', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 13 (2d8+4) piercing damage.', attackBonus: 6, damage: '2d8+4 piercing' },
    ],
    tags: ['monstrosity', 'bull', 'labyrinth', 'charge'],
  },
  {
    id: 'monstrosity-owlbear',
    name: 'Owlbear',
    cr: 3,
    size: 'Large',
    type: 'monstrosity',
    alignment: 'unaligned',
    armorClass: 13,
    hitPoints: 59,
    hitDice: '7d10+21',
    speed: '40 ft.',
    abilities: { str: 20, dex: 12, con: 17, int: 3, wis: 12, cha: 7 },
    skills: ['Perception +3'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 13'],
    traits: [
      { name: 'Keen Sight and Smell', type: 'trait', description: 'The owlbear has advantage on Wisdom (Perception) checks that rely on sight or smell.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The owlbear makes two attacks: one with its beak and one with its claws.' },
      { name: 'Beak', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one creature. Hit: 10 (1d10+5) piercing damage.', attackBonus: 7, damage: '1d10+5 piercing' },
      { name: 'Claws', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 14 (2d8+5) slashing damage.', attackBonus: 7, damage: '2d8+5 slashing' },
    ],
    tags: ['monstrosity', 'forest', 'bear-owl', 'classic'],
  },
  {
    id: 'monstrosity-phase-spider',
    name: 'Phase Spider',
    cr: 3,
    size: 'Large',
    type: 'monstrosity',
    alignment: 'unaligned',
    armorClass: 13,
    hitPoints: 32,
    hitDice: '5d10+5',
    speed: '30 ft., climb 30 ft.',
    abilities: { str: 15, dex: 15, con: 12, int: 6, wis: 10, cha: 6 },
    skills: ['Stealth +6'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 10'],
    traits: [
      { name: 'Ethereal Jaunt', type: 'trait', description: 'As a bonus action, the spider can magically shift from the Material Plane to the Ethereal Plane, or vice versa.' },
      { name: 'Spider Climb', type: 'trait', description: 'The spider can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check.' },
      { name: 'Web Walker', type: 'trait', description: 'The spider ignores movement restrictions caused by webbing.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 7 (1d10+2) piercing damage, and the target must make a DC 11 Constitution saving throw, taking 18 (4d8) poison damage on a failed save, or half as much on a successful one. If the poison damage reduces the target to 0 hit points, the target is stable but poisoned for 1 hour, even after regaining hit points, and is paralyzed while poisoned in this way.', attackBonus: 4, damage: '1d10+2 piercing', saveDc: 11, saveType: 'con' },
    ],
    tags: ['monstrosity', 'spider', 'ethereal', 'poison'],
  },
  {
    id: 'monstrosity-purple-worm',
    name: 'Purple Worm',
    cr: 15,
    size: 'Gargantuan',
    type: 'monstrosity',
    alignment: 'unaligned',
    armorClass: 18,
    hitPoints: 247,
    hitDice: '15d20+90',
    speed: '50 ft., burrow 30 ft.',
    abilities: { str: 28, dex: 7, con: 22, int: 1, wis: 8, cha: 4 },
    senses: ['Blindsight 30 ft.', 'Tremorsense 60 ft.', 'Passive Perception 9'],
    traits: [
      { name: 'Tunneler', type: 'trait', description: 'The worm can burrow through solid rock at half its burrow speed and leaves a 10-ft.-diameter tunnel in its wake.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The worm makes two attacks: one with its bite and one with its tail stinger.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +14 to hit, reach 10 ft., one target. Hit: 22 (3d8+9) piercing damage. If the target is a Large or smaller creature, it must succeed on a DC 19 Dexterity saving throw or be swallowed by the worm. A swallowed creature is blinded and restrained, it has total cover against attacks and other effects outside the worm, and it takes 21 (6d6) acid damage at the start of each of the worm\'s turns.', attackBonus: 14, damage: '3d8+9 piercing', saveDc: 19, saveType: 'dex' },
      { name: 'Tail Stinger', type: 'attack', description: 'Melee Weapon Attack: +14 to hit, reach 10 ft., one creature. Hit: 19 (3d6+9) piercing damage, and the target must make a DC 19 Constitution saving throw, taking 42 (12d6) poison damage on a failed save, or half as much on a successful one.', attackBonus: 14, damage: '3d6+9 piercing', saveDc: 19, saveType: 'con' },
    ],
    tags: ['monstrosity', 'colossal', 'underdark', 'swallow', 'burrower'],
  },
  {
    id: 'monstrosity-rust-monster',
    name: 'Rust Monster',
    cr: 0.5,
    size: 'Medium',
    type: 'monstrosity',
    alignment: 'unaligned',
    armorClass: 14,
    hitPoints: 27,
    hitDice: '5d8+5',
    speed: '40 ft.',
    abilities: { str: 13, dex: 12, con: 13, int: 2, wis: 13, cha: 6 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 11'],
    traits: [
      { name: 'Iron Scent', type: 'trait', description: 'The rust monster can pinpoint, by scent, the location of ferrous metal within 30 ft. of it.' },
      { name: 'Rust Metal', type: 'trait', description: 'Any nonmagical weapon made of metal that hits the rust monster corrodes. After dealing damage, the weapon takes a permanent and cumulative -1 penalty to damage rolls. If its penalty drops to -5, the weapon is destroyed. Nonmagical ammunition made of metal that hits the rust monster is destroyed after dealing damage.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 5 (1d8+1) piercing damage.', attackBonus: 3, damage: '1d8+1 piercing' },
      { name: 'Antennae', type: 'ability', description: 'The rust monster corrodes a nonmagical ferrous metal object it can see within 5 ft. of it. If the object isn\'t being worn or carried, the touch destroys a 1-foot cube of it. If the object is being worn or carried by a creature, the creature can make a DC 11 Dexterity saving throw to avoid the rust monster\'s touch. If the object touched is either metal armor or a metal shield being worn or carried, its takes a permanent and cumulative -1 penalty to the AC it offers. Armor reduced to an AC of 10 or a shield that drops to a +0 bonus is destroyed. If the object touched is a held metal weapon, it rusts as described in the Rust Metal trait.', saveDc: 11, saveType: 'dex' },
    ],
    tags: ['monstrosity', 'anti-magic-item', 'rust', 'equipment-destroyer'],
  },
  {
    id: 'monstrosity-tarrasque',
    name: 'Tarrasque',
    cr: 30,
    size: 'Gargantuan',
    type: 'monstrosity',
    alignment: 'unaligned',
    armorClass: 25,
    hitPoints: 676,
    hitDice: '33d20+330',
    speed: '40 ft.',
    abilities: { str: 30, dex: 11, con: 30, int: 3, wis: 11, cha: 11 },
    senses: ['Blindsight 120 ft.', 'Passive Perception 10'],
    traits: [
      { name: 'Legendary Resistance (3/Day)', type: 'trait', description: 'If the tarrasque fails a saving throw, it can choose to succeed instead.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The tarrasque has advantage on saving throws against spells and other magical effects.' },
      { name: 'Reflective Carapace', type: 'trait', description: 'Any time the tarrasque is targeted by a magic missile spell, a line spell, or a spell that requires a ranged attack roll, roll a d6. On a 1 to 5, the tarrasque is unaffected. On a 6, the tarrasque is unaffected, and the effect is reflected back at the caster as though it originated from the tarrasque, turning the caster into the target.' },
      { name: 'Siege Monster', type: 'trait', description: 'The tarrasque deals double damage to objects and structures.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The tarrasque can use its Frightful Presence. It then makes five attacks: one with its bite, two with its claws, one with its horns, and one with its tail. It can use its Swallow instead of its bite.' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +19 to hit, reach 10 ft., one target. Hit: 36 (4d12+10) piercing damage. If the target is a creature, it is grappled (escape DC 20). Until this grapple ends, the target is restrained, and the tarrasque can\'t bite another target.', attackBonus: 19, damage: '4d12+10 piercing' },
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +19 to hit, reach 15 ft., one target. Hit: 28 (4d8+10) slashing damage.', attackBonus: 19, damage: '4d8+10 slashing' },
      { name: 'Horns', type: 'attack', description: 'Melee Weapon Attack: +19 to hit, reach 10 ft., one target. Hit: 32 (4d10+10) piercing damage.', attackBonus: 19, damage: '4d10+10 piercing' },
      { name: 'Tail', type: 'attack', description: 'Melee Weapon Attack: +19 to hit, reach 20 ft., one target. Hit: 24 (4d6+10) bludgeoning damage. If the target is a creature, it must succeed on a DC 20 Strength saving throw or be knocked prone.', attackBonus: 19, damage: '4d6+10 bludgeoning', saveDc: 20, saveType: 'str' },
      { name: 'Frightful Presence', type: 'ability', description: 'Each creature of the tarrasque\'s choice within 120 ft. and aware of it must succeed on a DC 17 Wisdom saving throw or become frightened for 1 minute. A creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.', saveDc: 17, saveType: 'wis' },
      { name: 'Swallow', type: 'ability', description: 'The tarrasque makes one bite attack against a Large or smaller creature it is grappling. If the attack hits, the target takes the bite\'s damage, the target is swallowed, and the grapple ends. While swallowed, the creature is blinded and restrained, it has total cover against attacks and other effects outside the tarrasque, and it takes 56 (16d6) acid damage at the start of each of the tarrasque\'s turns.' },
    ],
    legendaryActions: [
      { name: 'Attack', type: 'attack', description: 'The tarrasque makes one claw attack or tail attack.', attackBonus: 19, damage: '4d8+10 slashing' },
      { name: 'Move', type: 'ability', description: 'The tarrasque moves up to half its speed.' },
      { name: 'Chomp (Costs 2 Actions)', type: 'ability', description: 'The tarrasque makes one bite attack or uses its Swallow.' },
    ],
    tags: ['monstrosity', 'legendary', 'mythic', 'apocalypse', 'boss'],
  },
  {
    id: 'monstrosity-yuan-ti-pureblood',
    name: 'Yuan-ti Pureblood',
    cr: 1,
    size: 'Medium',
    type: 'humanoid',
    alignment: 'neutral evil',
    armorClass: 11,
    hitPoints: 40,
    hitDice: '9d8',
    speed: '30 ft.',
    abilities: { str: 11, dex: 12, con: 11, int: 13, wis: 12, cha: 14 },
    skills: ['Deception +6', 'Persuasion +6', 'Stealth +3'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 11'],
    languages: ['Abyssal', 'Common', 'Draconic'],
    traits: [
      { name: 'Innate Spellcasting (Psionics)', type: 'trait', description: 'Spellcasting ability is Charisma (spell save DC 12). At will: animal friendship (snakes only). 3/day: suggestion. 1/day: fear.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The yuan-ti has advantage on saving throws against spells and other magical effects.' },
      { name: 'Poison Immunity', type: 'trait', description: 'The yuan-ti is immune to poison damage and the poisoned condition.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The yuan-ti makes two melee attacks or two ranged attacks.' },
      { name: 'Scimitar', type: 'attack', description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6+1) slashing damage.', attackBonus: 3, damage: '1d6+1 slashing' },
      { name: 'Shortbow', type: 'attack', description: 'Ranged Weapon Attack: +3 to hit, range 80/320 ft., one target. Hit: 4 (1d6+1) piercing damage plus 7 (2d6) poison damage.', attackBonus: 3, damage: '1d6+1 piercing + 2d6 poison' },
    ],
    tags: ['humanoid', 'yuan-ti', 'serpent', 'cultist'],
  },
  {
    id: 'monstrosity-yuan-ti-malison',
    name: 'Yuan-ti Malison',
    cr: 3,
    size: 'Medium',
    type: 'monstrosity',
    alignment: 'neutral evil',
    armorClass: 12,
    hitPoints: 66,
    hitDice: '12d8+12',
    speed: '30 ft.',
    abilities: { str: 16, dex: 12, con: 13, int: 14, wis: 12, cha: 16 },
    skills: ['Perception +3', 'Stealth +3'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 13'],
    languages: ['Abyssal', 'Common', 'Draconic'],
    traits: [
      { name: 'Innate Spellcasting (Psionics)', type: 'trait', description: 'Spellcasting ability is Charisma (spell save DC 13). At will: animal friendship (snakes only). 3/day: suggestion. 1/day: fear.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The yuan-ti has advantage on saving throws against spells and other magical effects.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The yuan-ti makes two ranged attacks or two melee attacks, but can use its bite only once.' },
      { name: 'Bite (Snake Lower Body Only)', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one creature. Hit: 5 (1d4+3) piercing damage, and the target must make a DC 11 Constitution saving throw, taking 18 (4d8) poison damage on a failed save, or half on a successful one.', attackBonus: 5, damage: '1d4+3 piercing', saveDc: 11, saveType: 'con' },
      { name: 'Constrict', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6+3) bludgeoning damage, and the target is grappled (escape DC 14). Until this grapple ends, the target is restrained and the yuan-ti can\'t constrict another target.', attackBonus: 5, damage: '2d6+3 bludgeoning' },
      { name: 'Scimitar (Human Torso and Humanoid Form Only)', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6+3) slashing damage.', attackBonus: 5, damage: '1d6+3 slashing' },
    ],
    tags: ['monstrosity', 'yuan-ti', 'serpent', 'half-snake'],
  },
]
