import type { Monster } from './types'

export const OOZES: Monster[] = [
  {
    id: 'ooze-black-pudding',
    name: 'Black Pudding',
    cr: 4,
    size: 'Large',
    type: 'ooze',
    alignment: 'unaligned',
    armorClass: 7,
    hitPoints: 85,
    hitDice: '10d10+30',
    speed: '20 ft., climb 20 ft.',
    abilities: { str: 16, dex: 5, con: 16, int: 1, wis: 6, cha: 1 },
    senses: ['Blindsight 60 ft. (blind beyond this radius)', 'Passive Perception 8'],
    traits: [
      { name: 'Amorphous', type: 'trait', description: 'The pudding can move through a space as narrow as 1 inch wide without squeezing.' },
      { name: 'Corrosive Form', type: 'trait', description: 'A creature that touches the pudding or hits it with a melee attack while within 5 ft. of it takes 4 (1d8) acid damage. Any nonmagical weapon made of metal or wood that hits the pudding corrodes. After dealing damage, the weapon takes a permanent and cumulative -1 penalty to damage rolls. Metal armor or shield that touches the pudding corrodes similarly.' },
      { name: 'Spider Climb', type: 'trait', description: 'The pudding can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check.' },
    ],
    actions: [
      { name: 'Pseudopod', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6+3) bludgeoning damage plus 18 (4d8) acid damage. In addition, nonmagical armor worn by the target is partly dissolved and takes a permanent and cumulative -1 penalty to the AC it offers.', attackBonus: 5, damage: '1d6+3 bludgeoning + 4d8 acid' },
    ],
    tags: ['ooze', 'acid', 'corrosive'],
  },
  {
    id: 'ooze-gelatinous-cube',
    name: 'Gelatinous Cube',
    cr: 2,
    size: 'Large',
    type: 'ooze',
    alignment: 'unaligned',
    armorClass: 6,
    hitPoints: 84,
    hitDice: '8d10+40',
    speed: '15 ft.',
    abilities: { str: 14, dex: 3, con: 20, int: 1, wis: 6, cha: 1 },
    senses: ['Blindsight 60 ft. (blind beyond this radius)', 'Passive Perception 8'],
    traits: [
      { name: 'Ooze Cube', type: 'trait', description: 'The cube takes up its entire space. Other creatures can enter the space, but a creature that does so is subjected to the cube\'s Engulf and has disadvantage on the saving throw.' },
      { name: 'Transparent', type: 'trait', description: 'Even when the cube is in plain sight, it takes a successful DC 15 Wisdom (Perception) check to spot a cube that has neither moved nor attacked. A creature that tries to enter the cube\'s space while unaware is surprised by the cube.' },
    ],
    actions: [
      { name: 'Pseudopod', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 10 (3d6) acid damage.', attackBonus: 4, damage: '3d6 acid' },
      { name: 'Engulf', type: 'ability', description: 'The cube moves up to its speed. While doing so, it can enter Large or smaller creatures\' spaces. Whenever the cube enters a creature\'s space, the creature must make a DC 12 Dexterity saving throw. On a failed save, the creature is engulfed. An engulfed creature can\'t breathe, is restrained, and takes 21 (6d6) acid damage at the start of each of the cube\'s turns.', saveDc: 12, saveType: 'dex' },
    ],
    tags: ['ooze', 'dungeon', 'acid', 'transparent'],
  },
  {
    id: 'ooze-gray-ooze',
    name: 'Gray Ooze',
    cr: 0.5,
    size: 'Medium',
    type: 'ooze',
    alignment: 'unaligned',
    armorClass: 8,
    hitPoints: 22,
    hitDice: '3d8+9',
    speed: '10 ft., climb 10 ft.',
    abilities: { str: 12, dex: 6, con: 16, int: 1, wis: 6, cha: 2 },
    skills: ['Stealth +2'],
    senses: ['Blindsight 60 ft. (blind beyond this radius)', 'Passive Perception 8'],
    traits: [
      { name: 'Amorphous', type: 'trait', description: 'The ooze can move through a space as narrow as 1 inch wide without squeezing.' },
      { name: 'Corrode Metal', type: 'trait', description: 'Any nonmagical weapon made of metal that hits the ooze corrodes. After dealing damage, the weapon takes a permanent and cumulative -1 penalty to damage rolls.' },
      { name: 'False Appearance', type: 'trait', description: 'While the ooze remains motionless, it is indistinguishable from an oily puddle or wet rock.' },
    ],
    actions: [
      { name: 'Pseudopod', type: 'attack', description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6+1) bludgeoning damage plus 7 (2d6) acid damage, and any nonmagical metal armor worn by the target is partly dissolved and takes a permanent and cumulative -1 penalty to its AC.', attackBonus: 3, damage: '1d6+1 bludgeoning + 2d6 acid' },
    ],
    tags: ['ooze', 'acid', 'cave'],
  },
  {
    id: 'ooze-ochre-jelly',
    name: 'Ochre Jelly',
    cr: 2,
    size: 'Large',
    type: 'ooze',
    alignment: 'unaligned',
    armorClass: 8,
    hitPoints: 45,
    hitDice: '6d10+12',
    speed: '10 ft., climb 10 ft.',
    abilities: { str: 15, dex: 6, con: 14, int: 2, wis: 6, cha: 1 },
    senses: ['Blindsight 60 ft. (blind beyond this radius)', 'Passive Perception 8'],
    traits: [
      { name: 'Amorphous', type: 'trait', description: 'The jelly can move through a space as narrow as 1 inch wide without squeezing.' },
      { name: 'Spider Climb', type: 'trait', description: 'The jelly can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check.' },
    ],
    actions: [
      { name: 'Pseudopod', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 9 (2d6+2) bludgeoning damage plus 3 (1d6) acid damage.', attackBonus: 4, damage: '2d6+2 bludgeoning + 1d6 acid' },
    ],
    tags: ['ooze', 'acid', 'split'],
  },
]
