import type { Monster } from './types'

export const PLANTS: Monster[] = [
  {
    id: 'plant-gas-spore',
    name: 'Gas Spore',
    cr: 0.5,
    size: 'Large',
    type: 'plant',
    alignment: 'unaligned',
    armorClass: 5,
    hitPoints: 1,
    hitDice: '1d10',
    speed: '0 ft., fly 10 ft. (hover)',
    abilities: { str: 5, dex: 1, con: 10, int: 1, wis: 1, cha: 1 },
    senses: ['Blindsight 30 ft. (blind beyond this radius)', 'Passive Perception 5'],
    traits: [
      { name: 'Death Burst', type: 'trait', description: 'When the gas spore dies, it explodes in a cloud of deadly spores. Each creature within 20 ft. must succeed on a DC 15 Constitution saving throw or take 10 (3d6) poison damage and become infected with a disease. The infected creature has disadvantage on Wisdom checks. After 24 hours, the creature must succeed on a DC 15 Constitution saving throw or its hit point maximum is reduced by 5 (1d10). The creature dies if this reduces its hit point maximum to 0.', saveDc: 15, saveType: 'con' },
      { name: 'Eerie Resemblance', type: 'trait', description: 'The gas spore resembles a beholder. A creature that can see the gas spore and has seen a beholder can tell them apart with a successful DC 15 Intelligence (Nature) check.' },
    ],
    actions: [
      { name: 'Touch', type: 'attack', description: 'Melee Weapon Attack: +0 to hit, reach 5 ft., one creature. Hit: 1 poison damage and the target must succeed on a DC 10 Constitution saving throw or become infected with a disease that is harmless.', attackBonus: 0, damage: '1 poison' },
    ],
    tags: ['plant', 'fungus', 'trap', 'beholder-mimic'],
  },
  {
    id: 'plant-myconid-sprout',
    name: 'Myconid Sprout',
    cr: 0,
    size: 'Small',
    type: 'plant',
    alignment: 'lawful neutral',
    armorClass: 10,
    hitPoints: 7,
    hitDice: '2d6',
    speed: '10 ft.',
    abilities: { str: 8, dex: 10, con: 10, int: 8, wis: 11, cha: 5 },
    senses: ['Darkvision 120 ft.', 'Passive Perception 10'],
    languages: ['—'],
    traits: [
      { name: 'Distress Spores', type: 'trait', description: 'When the myconid takes damage, all other myconids within 240 ft. of it can sense its pain.' },
      { name: 'Sun Sickness', type: 'trait', description: 'While in sunlight, the myconid has disadvantage on ability checks, attack rolls, and saving throws. The myconid dies if it spends more than 1 hour in direct sunlight.' },
    ],
    actions: [
      { name: 'Fist', type: 'attack', description: 'Melee Weapon Attack: +1 to hit, reach 5 ft., one target. Hit: 1 (1d4-1) bludgeoning damage plus 2 (1d4) poison damage.', attackBonus: 1, damage: '1d4-1 bludgeoning + 1d4 poison' },
      { name: 'Rapport Spores (3/Day)', type: 'ability', description: 'A 10-ft. radius of spores extends from the myconid. These spores can affect only beasts and humanoids that aren\'t undead or constructs. The affected creature can communicate telepathically with other creatures affected by these rapport spores within 30 ft.' },
    ],
    tags: ['plant', 'fungus', 'underdark', 'peaceful'],
  },
  {
    id: 'plant-myconid-adult',
    name: 'Myconid Adult',
    cr: 0.5,
    size: 'Medium',
    type: 'plant',
    alignment: 'lawful neutral',
    armorClass: 12,
    hitPoints: 22,
    hitDice: '4d8+4',
    speed: '20 ft.',
    abilities: { str: 10, dex: 10, con: 12, int: 10, wis: 13, cha: 7 },
    senses: ['Darkvision 120 ft.', 'Passive Perception 11'],
    traits: [
      { name: 'Distress Spores', type: 'trait', description: 'When the myconid takes damage, all other myconids within 240 ft. of it can sense its pain.' },
      { name: 'Sun Sickness', type: 'trait', description: 'While in sunlight, the myconid has disadvantage on ability checks, attack rolls, and saving throws. The myconid dies if it spends more than 1 hour in direct sunlight.' },
    ],
    actions: [
      { name: 'Fist', type: 'attack', description: 'Melee Weapon Attack: +2 to hit, reach 5 ft., one target. Hit: 5 (2d4) bludgeoning damage plus 5 (2d4) poison damage.', attackBonus: 2, damage: '2d4 bludgeoning + 2d4 poison' },
      { name: 'Pacifying Spores (3/Day)', type: 'ability', description: 'The myconid ejects spores at one creature it can see within 5 ft. of it. The target must succeed on a DC 11 Constitution saving throw or be stunned for 1 minute. The target can repeat the saving throw at the end of each of its turns.', saveDc: 11, saveType: 'con' },
      { name: 'Rapport Spores', type: 'ability', description: 'A 20-ft. radius of spores extends from the myconid. These spores can affect beasts and humanoids. The affected creature can communicate telepathically with other rapport-spore-affected creatures within 30 ft.' },
    ],
    tags: ['plant', 'fungus', 'underdark'],
  },
  {
    id: 'plant-myconid-sovereign',
    name: 'Myconid Sovereign',
    cr: 2,
    size: 'Large',
    type: 'plant',
    alignment: 'lawful neutral',
    armorClass: 13,
    hitPoints: 60,
    hitDice: '8d10+16',
    speed: '30 ft.',
    abilities: { str: 12, dex: 10, con: 14, int: 13, wis: 15, cha: 10 },
    senses: ['Darkvision 120 ft.', 'Passive Perception 12'],
    traits: [
      { name: 'Distress Spores', type: 'trait', description: 'When the myconid takes damage, all other myconids within 240 ft. of it can sense its pain.' },
      { name: 'Sun Sickness', type: 'trait', description: 'While in sunlight, the myconid has disadvantage on ability checks, attack rolls, and saving throws. The myconid dies if it spends more than 1 hour in direct sunlight.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The myconid sovereign uses either Pacifying Spores or Hallucination Spores, and makes one fist attack.' },
      { name: 'Fist', type: 'attack', description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 8 (3d4+1) bludgeoning damage plus 7 (3d4) poison damage.', attackBonus: 3, damage: '3d4+1 bludgeoning + 3d4 poison' },
      { name: 'Animating Spores (6/Day)', type: 'ability', description: 'The sovereign targets one corpse of a humanoid or beast within 5 ft. of it and releases spores at the corpse. In 24 hours, the corpse rises as a spore servant.' },
      { name: 'Hallucination Spores', type: 'ability', description: 'The sovereign ejects spores at one creature it can see within 5 ft. The target must succeed on a DC 12 Constitution saving throw or be poisoned for 1 minute. While poisoned, the creature is incapacitated and spends its movement moving in a random direction.', saveDc: 12, saveType: 'con' },
      { name: 'Pacifying Spores', type: 'ability', description: 'The sovereign ejects spores at one creature within 5 ft. The target must succeed on a DC 12 Constitution saving throw or be stunned for 1 minute.', saveDc: 12, saveType: 'con' },
      { name: 'Rapport Spores', type: 'ability', description: 'A 30-ft. radius of spores extends from the sovereign, affecting beasts and humanoids. Affected creatures can communicate telepathically with other rapport-spore-affected creatures within 30 ft.' },
    ],
    tags: ['plant', 'fungus', 'underdark', 'leader'],
  },
  {
    id: 'plant-shambling-mound',
    name: 'Shambling Mound',
    cr: 5,
    size: 'Large',
    type: 'plant',
    alignment: 'unaligned',
    armorClass: 15,
    hitPoints: 136,
    hitDice: '16d10+48',
    speed: '20 ft., swim 20 ft.',
    abilities: { str: 18, dex: 8, con: 16, int: 5, wis: 10, cha: 5 },
    skills: ['Stealth +2'],
    senses: ['Blindsight 5 ft.', 'Darkvision 60 ft.', 'Passive Perception 10'],
    traits: [
      { name: 'Lightning Absorption', type: 'trait', description: 'Whenever the shambling mound is subjected to lightning damage, it takes no damage and regains a number of hit points equal to the lightning damage dealt.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The shambling mound makes two slam attacks. If both attacks hit a Medium or smaller target, the target is grappled (escape DC 14), and the shambling mound uses its Engulf on it.' },
      { name: 'Slam', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 13 (2d8+4) bludgeoning damage.', attackBonus: 7, damage: '2d8+4 bludgeoning' },
      { name: 'Engulf', type: 'ability', description: 'The shambling mound engulfs a Medium or smaller creature grappled by it. The engulfed target is blinded, restrained, and unable to breathe, and it must succeed on a DC 14 Constitution saving throw at the start of each of the mound\'s turns or take 13 (2d8+4) bludgeoning damage.', saveDc: 14, saveType: 'con' },
    ],
    tags: ['plant', 'swamp', 'grappler'],
  },
  {
    id: 'plant-shrieker',
    name: 'Shrieker',
    cr: 0,
    size: 'Medium',
    type: 'plant',
    alignment: 'unaligned',
    armorClass: 5,
    hitPoints: 13,
    hitDice: '3d8',
    speed: '0 ft.',
    abilities: { str: 1, dex: 1, con: 10, int: 1, wis: 3, cha: 1 },
    senses: ['Blindsight 30 ft. (blind beyond this radius)', 'Passive Perception 6'],
    traits: [
      { name: 'False Appearance', type: 'trait', description: 'While the shrieker remains motionless, it is indistinguishable from an ordinary fungus.' },
    ],
    actions: [
      { name: 'Shriek', type: 'ability', description: 'When bright light or a creature is within 30 ft. of the shrieker, it emits a shriek audible within 300 ft. of it. The shrieker continues to shriek until the disturbance moves out of range and for 1d4 of the shrieker\'s turns afterward.' },
    ],
    tags: ['plant', 'fungus', 'alarm', 'underdark'],
  },
  {
    id: 'plant-treant',
    name: 'Treant',
    cr: 9,
    size: 'Huge',
    type: 'plant',
    alignment: 'chaotic good',
    armorClass: 16,
    hitPoints: 138,
    hitDice: '12d12+60',
    speed: '30 ft.',
    abilities: { str: 23, dex: 8, con: 21, int: 12, wis: 16, cha: 12 },
    senses: ['Passive Perception 13'],
    languages: ['Common', 'Druidic', 'Elvish', 'Sylvan'],
    traits: [
      { name: 'False Appearance', type: 'trait', description: 'While the treant remains motionless, it is indistinguishable from a normal tree.' },
      { name: 'Siege Monster', type: 'trait', description: 'The treant deals double damage to objects and structures.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The treant makes two slam attacks.' },
      { name: 'Slam', type: 'attack', description: 'Melee Weapon Attack: +10 to hit, reach 5 ft., one target. Hit: 16 (3d6+6) bludgeoning damage.', attackBonus: 10, damage: '3d6+6 bludgeoning' },
      { name: 'Rock', type: 'attack', description: 'Ranged Weapon Attack: +10 to hit, range 60/180 ft., one target. Hit: 28 (4d10+6) bludgeoning damage.', attackBonus: 10, damage: '4d10+6 bludgeoning' },
      { name: 'Animate Trees (1/Day)', type: 'ability', description: 'The treant magically animates one or two trees it can see within 60 ft. of it. These trees have the same statistics as a treant, except they have Intelligence and Charisma scores of 1, they can\'t speak, and they have only the Slam action. An animated tree acts as an ally of the treant. The tree remains animate for 1 day or until it dies; until the treant dies or is more than 120 ft. from the tree; or until the treant takes a bonus action to turn it back into an inanimate tree.' },
    ],
    tags: ['plant', 'forest', 'guardian', 'siege'],
  },
  {
    id: 'plant-violet-fungus',
    name: 'Violet Fungus',
    cr: 0.25,
    size: 'Medium',
    type: 'plant',
    alignment: 'unaligned',
    armorClass: 5,
    hitPoints: 18,
    hitDice: '4d8',
    speed: '5 ft.',
    abilities: { str: 3, dex: 1, con: 10, int: 1, wis: 3, cha: 1 },
    senses: ['Blindsight 30 ft. (blind beyond this radius)', 'Passive Perception 6'],
    traits: [
      { name: 'False Appearance', type: 'trait', description: 'While the violet fungus remains motionless, it is indistinguishable from an ordinary fungus.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The fungus makes 1d4 Rotting Touch attacks.' },
      { name: 'Rotting Touch', type: 'attack', description: 'Melee Weapon Attack: +2 to hit, reach 10 ft., one creature. Hit: 4 (1d8) necrotic damage.', attackBonus: 2, damage: '1d8 necrotic' },
    ],
    tags: ['plant', 'fungus', 'underdark'],
  },
]
