import type { Monster } from './types'

export const UNDEAD: Monster[] = [
  {
    id: 'undead-banshee',
    name: 'Banshee',
    cr: 4,
    size: 'Medium',
    type: 'undead',
    alignment: 'chaotic evil',
    armorClass: 12,
    hitPoints: 58,
    hitDice: '13d8',
    speed: '0 ft., fly 40 ft. (hover)',
    abilities: { str: 1, dex: 14, con: 10, int: 12, wis: 11, cha: 17 },
    skills: ['Perception +2'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 12'],
    languages: ['Common', 'Elvish'],
    traits: [
      { name: 'Detect Life', type: 'trait', description: 'The banshee can magically sense the presence of living creatures up to 5 miles away. She knows the general direction they\'re in but not their exact locations.' },
      { name: 'Incorporeal Movement', type: 'trait', description: 'The banshee can move through other creatures and objects as if they were difficult terrain. She takes 5 (1d10) force damage if she ends her turn inside an object.' },
    ],
    actions: [
      { name: 'Corrupting Touch', type: 'attack', description: 'Melee Spell Attack: +4 to hit, reach 5 ft., one target. Hit: 12 (3d6+2) necrotic damage.', attackBonus: 4, damage: '3d6+2 necrotic' },
      { name: 'Horrifying Visage', type: 'ability', description: 'Each non-undead creature within 60 ft. that can see the banshee must succeed on a DC 13 Wisdom saving throw or be frightened for 1 minute. A frightened target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success. If a target\'s saving throw is successful or the effect ends for it, the target is immune to the banshee\'s Horrifying Visage for 24 hours.', saveDc: 13, saveType: 'wis' },
      { name: 'Wail (1/Day)', type: 'ability', description: 'The banshee releases a mournful wail, provided that she isn\'t in sunlight. This wail has no effect on constructs and undead. All other creatures within 30 ft. that can hear her must make a DC 13 Constitution saving throw. On a failure, a creature drops to 0 hit points. On a success, a creature takes 3d6+3 psychic damage.', saveDc: 13, saveType: 'con' },
    ],
    tags: ['undead', 'wail', 'ghost', 'elven'],
  },
  {
    id: 'undead-crawling-claw',
    name: 'Crawling Claw',
    cr: 0,
    size: 'Tiny',
    type: 'undead',
    alignment: 'neutral evil',
    armorClass: 12,
    hitPoints: 2,
    hitDice: '1d4',
    speed: '20 ft., climb 20 ft.',
    abilities: { str: 13, dex: 14, con: 11, int: 5, wis: 10, cha: 4 },
    senses: ['Blindsight 30 ft. (blind beyond this radius)', 'Passive Perception 10'],
    traits: [
      { name: 'Turn Immunity', type: 'trait', description: 'The crawling claw is immune to effects that turn undead.' },
    ],
    actions: [
      { name: 'Claw', type: 'attack', description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 3 (1d4+1) bludgeoning or slashing damage (the crawling claw\'s choice).', attackBonus: 3, damage: '1d4+1 bludgeoning' },
    ],
    tags: ['undead', 'minion', 'tiny'],
  },
  {
    id: 'undead-death-knight',
    name: 'Death Knight',
    cr: 17,
    size: 'Medium',
    type: 'undead',
    alignment: 'chaotic evil',
    armorClass: 20,
    hitPoints: 180,
    hitDice: '19d8+95',
    speed: '30 ft.',
    abilities: { str: 20, dex: 11, con: 20, int: 12, wis: 16, cha: 18 },
    skills: ['Perception +9'],
    senses: ['Darkvision 120 ft.', 'Passive Perception 19'],
    languages: ['Abyssal', 'Common'],
    traits: [
      { name: 'Marshal Undead', type: 'trait', description: 'Unless the death knight is incapacitated, it and undead creatures of its choice within 60 ft. of it have advantage on saving throws against features that turn undead.' },
      { name: 'Spellcasting', type: 'trait', description: 'The death knight is a 19th-level spellcaster. Its spellcasting ability is Charisma (spell save DC 17, +9 to hit with spell attacks). It has the following paladin spells: 1st level (4 slots): command, compelled duel, searing smite. 2nd level (3 slots): hold person, magic weapon. 3rd level (3 slots): dispel magic, elemental weapon. 4th level (3 slots): banishment, staggering smite. 5th level (2 slots): destructive wave (necrotic).' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The death knight makes three longsword attacks.' },
      { name: 'Longsword', type: 'attack', description: 'Melee Weapon Attack: +11 to hit, reach 5 ft., one target. Hit: 9 (1d8+5) slashing damage, or 10 (1d10+5) slashing damage if used with two hands, plus 18 (4d8) necrotic damage.', attackBonus: 11, damage: '1d8+5 slashing + 4d8 necrotic' },
      { name: 'Hellfire Orb (1/Day)', type: 'ability', description: 'The death knight hurls a magical ball of fire that explodes at a point it can see within 120 ft. Each creature in a 20-ft. radius sphere centered on that point must make a DC 18 Dexterity saving throw. The sphere spreads around corners. A creature takes 35 (10d6) fire damage and 35 (10d6) necrotic damage on a failed save, or half as much on a successful one.', saveDc: 18, saveType: 'dex' },
    ],
    tags: ['undead', 'paladin', 'legendary', 'fallen warrior'],
  },
  {
    id: 'undead-flameskull',
    name: 'Flameskull',
    cr: 4,
    size: 'Tiny',
    type: 'undead',
    alignment: 'neutral evil',
    armorClass: 13,
    hitPoints: 40,
    hitDice: '9d4+18',
    speed: '0 ft., fly 40 ft. (hover)',
    abilities: { str: 1, dex: 17, con: 14, int: 16, wis: 10, cha: 11 },
    skills: ['Arcana +5', 'Perception +2'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 12'],
    languages: ['Common', 'one other language known in life'],
    traits: [
      { name: 'Illumination', type: 'trait', description: 'The flameskull sheds either dim light in a 15-ft. radius, or bright light in a 15-ft. radius and dim light for an additional 15 ft. It can switch between the options as a bonus action.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The flameskull has advantage on saving throws against spells and other magical effects.' },
      { name: 'Rejuvenation', type: 'trait', description: 'If the flameskull is destroyed, it regains all its hit points in 1 hour unless holy water is sprinkled on its remains or a dispel magic or remove curse spell is cast on them.' },
      { name: 'Spellcasting', type: 'trait', description: 'The flameskull is a 5th-level spellcaster. Spellcasting ability is Intelligence (spell save DC 13, +5 to hit). Cantrips: mage hand. 1st level (4 slots): magic missile, shield. 2nd level (3 slots): blur, flaming sphere. 3rd level (2 slots): fireball.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The flameskull uses Fire Ray twice.' },
      { name: 'Fire Ray', type: 'attack', description: 'Ranged Spell Attack: +5 to hit, range 30 ft., one target. Hit: 10 (3d6) fire damage.', attackBonus: 5, damage: '3d6 fire' },
    ],
    tags: ['undead', 'spellcaster', 'skull', 'fire'],
  },
  {
    id: 'undead-ghost',
    name: 'Ghost',
    cr: 4,
    size: 'Medium',
    type: 'undead',
    alignment: 'any alignment',
    armorClass: 11,
    hitPoints: 45,
    hitDice: '10d8',
    speed: '0 ft., fly 40 ft. (hover)',
    abilities: { str: 7, dex: 13, con: 10, int: 10, wis: 12, cha: 17 },
    skills: ['Perception +3', 'Stealth +3'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 13'],
    languages: ['any languages it knew in life'],
    traits: [
      { name: 'Ethereal Sight', type: 'trait', description: 'The ghost can see 60 ft. into the Ethereal Plane when it is on the Material Plane, and vice versa.' },
      { name: 'Incorporeal Movement', type: 'trait', description: 'The ghost can move through other creatures and objects as if they were difficult terrain. It takes 5 (1d10) force damage if it ends its turn inside an object.' },
    ],
    actions: [
      { name: 'Withering Touch', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 17 (4d6+3) necrotic damage.', attackBonus: 5, damage: '4d6+3 necrotic' },
      { name: 'Etherealness', type: 'ability', description: 'The ghost enters the Ethereal Plane from the Material Plane, or vice versa. It is visible on the Material Plane while it is in the Border Ethereal, and vice versa, yet it can\'t affect or be affected by anything on the other plane.' },
      { name: 'Horrifying Visage', type: 'ability', description: 'Each non-undead creature within 60 ft. that can see the ghost must succeed on a DC 13 Wisdom saving throw or be frightened for 1 minute. A frightened target can repeat the saving throw at the end of each of its turns. If a target\'s saving throw is successful or the effect ends for it, the target is immune to this ghost\'s Horrifying Visage for 24 hours.', saveDc: 13, saveType: 'wis' },
      { name: 'Possession (Recharge 6)', type: 'ability', description: 'One humanoid that the ghost can see within 5 ft. must succeed on a DC 13 Charisma saving throw or be possessed by the ghost. The ghost now controls the body but doesn\'t deprive the target of awareness. The ghost can\'t be targeted by any attack, spell, or other effect, except ones that turn undead, and it retains its alignment, Intelligence, Wisdom, Charisma, and immunity to being charmed and frightened.', saveDc: 13, saveType: 'cha' },
    ],
    tags: ['undead', 'incorporeal', 'haunting'],
  },
  {
    id: 'undead-ghast',
    name: 'Ghast',
    cr: 2,
    size: 'Medium',
    type: 'undead',
    alignment: 'chaotic evil',
    armorClass: 13,
    hitPoints: 36,
    hitDice: '8d8',
    speed: '30 ft.',
    abilities: { str: 16, dex: 17, con: 10, int: 11, wis: 10, cha: 8 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 10'],
    languages: ['Common'],
    traits: [
      { name: 'Stench', type: 'trait', description: 'Any creature that starts its turn within 5 ft. of the ghast must succeed on a DC 10 Constitution saving throw or be poisoned until the start of its next turn.', saveDc: 10, saveType: 'con' },
      { name: 'Turning Defiance', type: 'trait', description: 'The ghast and any ghouls within 30 ft. of it have advantage on saving throws against effects that turn undead.' },
    ],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one creature. Hit: 12 (2d8+3) piercing damage.', attackBonus: 3, damage: '2d8+3 piercing' },
      { name: 'Claws', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6+3) slashing damage. If the target is a creature other than an undead, it must succeed on a DC 10 Constitution saving throw or be paralyzed for 1 minute.', attackBonus: 5, damage: '2d6+3 slashing', saveDc: 10, saveType: 'con' },
    ],
    tags: ['undead', 'ghoul', 'paralysis'],
  },
  {
    id: 'undead-ghoul',
    name: 'Ghoul',
    cr: 1,
    size: 'Medium',
    type: 'undead',
    alignment: 'chaotic evil',
    armorClass: 12,
    hitPoints: 22,
    hitDice: '5d8',
    speed: '30 ft.',
    abilities: { str: 13, dex: 15, con: 10, int: 7, wis: 10, cha: 6 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 10'],
    languages: ['Common'],
    actions: [
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +2 to hit, reach 5 ft., one creature. Hit: 9 (2d6+2) piercing damage.', attackBonus: 2, damage: '2d6+2 piercing' },
      { name: 'Claws', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4+2) slashing damage. If the target is a creature other than an elf or undead, it must succeed on a DC 10 Constitution saving throw or be paralyzed for 1 minute.', attackBonus: 4, damage: '2d4+2 slashing', saveDc: 10, saveType: 'con' },
    ],
    tags: ['undead', 'paralysis', 'pack'],
  },
  {
    id: 'undead-lich',
    name: 'Lich',
    cr: 21,
    size: 'Medium',
    type: 'undead',
    alignment: 'any evil alignment',
    armorClass: 17,
    hitPoints: 135,
    hitDice: '18d8+54',
    speed: '30 ft.',
    abilities: { str: 11, dex: 16, con: 16, int: 20, wis: 14, cha: 16 },
    skills: ['Arcana +18', 'History +12', 'Insight +9', 'Perception +9'],
    senses: ['Truesight 120 ft.', 'Passive Perception 19'],
    languages: ['Common plus up to five other languages'],
    traits: [
      { name: 'Legendary Resistance (3/Day)', type: 'trait', description: 'If the lich fails a saving throw, it can choose to succeed instead.' },
      { name: 'Rejuvenation', type: 'trait', description: 'If it has a phylactery, a destroyed lich gains a new body in 1d10 days, regaining all its hit points and becoming active again. The new body appears within 5 ft. of the phylactery.' },
      { name: 'Spellcasting', type: 'trait', description: 'The lich is an 18th-level spellcaster. Spellcasting ability is Intelligence (spell save DC 20, +12 to hit). Cantrips: mage hand, prestidigitation, ray of frost. 1st level (4 slots): detect magic, magic missile, shield, thunderwave. 2nd level (3 slots): detect thoughts, invisibility, Melf\'s acid arrow, mirror image. 3rd level (3 slots): animate dead, counterspell, dispel magic, fireball. 4th level (3 slots): blight, dimension door. 5th level (3 slots): cloudkill, scrying. 6th level (1 slot): disintegrate, globe of invulnerability. 7th level (1 slot): finger of death, plane shift. 8th level (1 slot): dominate monster, power word stun. 9th level (1 slot): power word kill.' },
      { name: 'Turn Resistance', type: 'trait', description: 'The lich has advantage on saving throws against any effect that turns undead.' },
    ],
    actions: [
      { name: 'Paralyzing Touch', type: 'attack', description: 'Melee Spell Attack: +12 to hit, reach 5 ft., one creature. Hit: 10 (3d6) cold damage. The target must succeed on a DC 18 Constitution saving throw or be paralyzed for 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.', attackBonus: 12, damage: '3d6 cold', saveDc: 18, saveType: 'con' },
    ],
    legendaryActions: [
      { name: 'Cantrip', type: 'ability', description: 'The lich casts a cantrip.' },
      { name: 'Paralyzing Touch (Costs 2 Actions)', type: 'attack', description: 'The lich uses its Paralyzing Touch.', attackBonus: 12, damage: '3d6 cold' },
      { name: 'Frightening Gaze (Costs 2 Actions)', type: 'ability', description: 'The lich fixes its gaze on one creature it can see within 10 ft. of it. The target must succeed on a DC 18 Wisdom saving throw against this magic or become frightened for 1 minute. The frightened target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.', saveDc: 18, saveType: 'wis' },
      { name: 'Disrupt Life (Costs 3 Actions)', type: 'ability', description: 'Each non-undead creature within 20 ft. of the lich must make a DC 18 Constitution saving throw against this magic, taking 21 (6d6) necrotic damage on a failed save, or half as much on a successful one.', saveDc: 18, saveType: 'con' },
    ],
    tags: ['undead', 'legendary', 'spellcaster', 'boss', 'mythic'],
  },
  {
    id: 'undead-mummy',
    name: 'Mummy',
    cr: 3,
    size: 'Medium',
    type: 'undead',
    alignment: 'lawful evil',
    armorClass: 11,
    hitPoints: 58,
    hitDice: '9d8+18',
    speed: '20 ft.',
    abilities: { str: 16, dex: 8, con: 15, int: 6, wis: 10, cha: 12 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 10'],
    languages: ['the languages it knew in life'],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The mummy can use its Dreadful Glare and makes one attack with its rotting fist.' },
      { name: 'Rotting Fist', type: 'attack', description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6+3) bludgeoning damage plus 10 (3d6) necrotic damage. If the target is a creature, it must succeed on a DC 12 Constitution saving throw or be cursed with mummy rot.', attackBonus: 5, damage: '2d6+3 bludgeoning + 3d6 necrotic', saveDc: 12, saveType: 'con' },
      { name: 'Dreadful Glare', type: 'ability', description: 'The mummy targets one creature it can see within 60 ft. of it. If the target can see the mummy, it must succeed on a DC 11 Wisdom saving throw against this magic or become frightened until the end of the mummy\'s next turn. If the target fails the saving throw by 5 or more, it is also paralyzed for the same duration.', saveDc: 11, saveType: 'wis' },
    ],
    tags: ['undead', 'curse', 'tomb', 'egyptian'],
  },
  {
    id: 'undead-mummy-lord',
    name: 'Mummy Lord',
    cr: 15,
    size: 'Medium',
    type: 'undead',
    alignment: 'lawful evil',
    armorClass: 17,
    hitPoints: 97,
    hitDice: '13d8+39',
    speed: '20 ft.',
    abilities: { str: 18, dex: 10, con: 17, int: 11, wis: 18, cha: 16 },
    skills: ['History +5', 'Religion +5'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 14'],
    languages: ['the languages it knew in life'],
    traits: [
      { name: 'Legendary Resistance (3/Day)', type: 'trait', description: 'If the mummy lord fails a saving throw, it can choose to succeed instead.' },
      { name: 'Magic Resistance', type: 'trait', description: 'The mummy lord has advantage on saving throws against spells and other magical effects.' },
      { name: 'Rejuvenation', type: 'trait', description: 'A destroyed mummy lord gains a new body in 24 hours if its heart is intact, regaining all its hit points and becoming active again.' },
      { name: 'Spellcasting', type: 'trait', description: 'The mummy lord is a 10th-level spellcaster. Spellcasting ability is Wisdom (spell save DC 17, +9 to hit). 1st level (4 slots): command, guiding bolt, shield of faith. 2nd level (3 slots): hold person, silence, spiritual weapon. 3rd level (3 slots): animate dead, dispel magic. 4th level (3 slots): divination, guardian of faith. 5th level (2 slots): contagion, insect plague. 6th level (1 slot): harm.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The mummy lord can use its Dreadful Glare and makes one attack with its rotting fist.' },
      { name: 'Rotting Fist', type: 'attack', description: 'Melee Weapon Attack: +9 to hit, reach 5 ft., one target. Hit: 14 (3d6+4) bludgeoning damage plus 21 (6d6) necrotic damage. If the target is a creature, it must succeed on a DC 16 Constitution saving throw or be cursed with mummy rot.', attackBonus: 9, damage: '3d6+4 bludgeoning + 6d6 necrotic', saveDc: 16, saveType: 'con' },
      { name: 'Dreadful Glare', type: 'ability', description: 'The mummy lord targets one creature it can see within 60 ft. The target must succeed on a DC 16 Wisdom saving throw or be frightened until the end of the mummy lord\'s next turn. If the target fails by 5 or more, it is also paralyzed for the same duration.', saveDc: 16, saveType: 'wis' },
    ],
    legendaryActions: [
      { name: 'Attack', type: 'attack', description: 'The mummy lord makes one attack with its rotting fist or uses its Dreadful Glare.', attackBonus: 9, damage: '3d6+4 bludgeoning + 6d6 necrotic' },
      { name: 'Blinding Dust', type: 'ability', description: 'Blinding dust and sand swirls magically around the mummy lord. Each creature within 5 ft. must succeed on a DC 16 Constitution saving throw or be blinded until the end of the creature\'s next turn.', saveDc: 16, saveType: 'con' },
      { name: 'Blasphemous Word (Costs 2 Actions)', type: 'ability', description: 'The mummy lord utters a blasphemous word. Each non-undead creature within 10 ft. must succeed on a DC 16 Constitution saving throw or be stunned until the end of the mummy lord\'s next turn.', saveDc: 16, saveType: 'con' },
      { name: 'Channel Negative Energy (Costs 2 Actions)', type: 'ability', description: 'The mummy lord magically unleashes negative energy. Creatures within 60 ft. that are concentrating on a spell must make a DC 16 Constitution saving throw or lose their concentration.', saveDc: 16, saveType: 'con' },
      { name: 'Whirlwind of Sand (Costs 2 Actions)', type: 'ability', description: 'The mummy lord magically transforms into a whirlwind of sand, moves up to 60 ft., and reverts to its normal form. While in whirlwind form, the mummy lord is immune to all damage, and it doesn\'t provoke opportunity attacks.' },
    ],
    tags: ['undead', 'legendary', 'spellcaster', 'boss', 'egyptian'],
  },
  {
    id: 'undead-revenant',
    name: 'Revenant',
    cr: 5,
    size: 'Medium',
    type: 'undead',
    alignment: 'neutral',
    armorClass: 13,
    hitPoints: 136,
    hitDice: '16d8+64',
    speed: '30 ft.',
    abilities: { str: 18, dex: 14, con: 18, int: 13, wis: 16, cha: 18 },
    skills: ['Athletics +7', 'Intimidation +7', 'Perception +6'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 16'],
    languages: ['the languages it knew in life'],
    traits: [
      { name: 'Regeneration', type: 'trait', description: 'The revenant regains 10 hit points at the start of its turn. If the revenant takes fire or radiant damage, this trait doesn\'t function at the start of the revenant\'s next turn. The revenant dies only if it starts its turn with 0 hit points and doesn\'t regenerate.' },
      { name: 'Undead Fortitude', type: 'trait', description: 'The revenant exists for a single purpose: to exact vengeance. The revenant knows the distance to and direction of its quarry, even on other planes.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The revenant makes two fist attacks.' },
      { name: 'Fist', type: 'attack', description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 11 (2d6+4) bludgeoning damage. If the target is the revenant\'s quarry, the target takes an extra 14 (4d6) bludgeoning damage.', attackBonus: 7, damage: '2d6+4 bludgeoning' },
      { name: 'Haunting Eyes', type: 'ability', description: 'The revenant gazes at one creature within 30 ft. The target must make a DC 15 Charisma saving throw. On a failed save, the target is paralyzed for 1 minute. A paralyzed target can repeat its saving throw at the end of each of its turns.', saveDc: 15, saveType: 'cha' },
    ],
    tags: ['undead', 'vengeance', 'hunter'],
  },
  {
    id: 'undead-shadow',
    name: 'Shadow',
    cr: 0.5,
    size: 'Medium',
    type: 'undead',
    alignment: 'chaotic evil',
    armorClass: 12,
    hitPoints: 16,
    hitDice: '3d8+3',
    speed: '40 ft.',
    abilities: { str: 6, dex: 14, con: 13, int: 6, wis: 10, cha: 8 },
    skills: ['Stealth +4'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 10'],
    traits: [
      { name: 'Amorphous', type: 'trait', description: 'The shadow can move through a space as narrow as 1 inch wide without squeezing.' },
      { name: 'Shadow Stealth', type: 'trait', description: 'While in dim light or darkness, the shadow can take the Hide action as a bonus action.' },
      { name: 'Sunlight Weakness', type: 'trait', description: 'While in sunlight, the shadow has disadvantage on attack rolls, ability checks, and saving throws.' },
    ],
    actions: [
      { name: 'Strength Drain', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 9 (2d6+2) necrotic damage, and the target\'s Strength score is reduced by 1d4. The target dies if this reduces its Strength to 0. Otherwise, the reduction lasts until the target finishes a short or long rest. If a non-evil humanoid dies from this attack, a new shadow rises from the corpse 1d4 hours later.', attackBonus: 4, damage: '2d6+2 necrotic' },
    ],
    tags: ['undead', 'strength drain', 'stealth'],
  },
  {
    id: 'undead-skeleton',
    name: 'Skeleton',
    cr: 0.25,
    size: 'Medium',
    type: 'undead',
    alignment: 'lawful evil',
    armorClass: 13,
    hitPoints: 13,
    hitDice: '2d8+4',
    speed: '30 ft.',
    abilities: { str: 10, dex: 14, con: 15, int: 6, wis: 8, cha: 5 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 9'],
    languages: ['understands all languages it spoke in life but cannot speak'],
    actions: [
      { name: 'Shortsword', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6+2) piercing damage.', attackBonus: 4, damage: '1d6+2 piercing' },
      { name: 'Shortbow', type: 'attack', description: 'Ranged Weapon Attack: +4 to hit, range 80/320 ft., one target. Hit: 5 (1d6+2) piercing damage.', attackBonus: 4, damage: '1d6+2 piercing' },
    ],
    tags: ['undead', 'minion', 'basic'],
  },
  {
    id: 'undead-specter',
    name: 'Specter',
    cr: 1,
    size: 'Medium',
    type: 'undead',
    alignment: 'chaotic evil',
    armorClass: 12,
    hitPoints: 22,
    hitDice: '5d8',
    speed: '0 ft., fly 50 ft. (hover)',
    abilities: { str: 1, dex: 14, con: 11, int: 10, wis: 10, cha: 11 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 10'],
    languages: ['understands all languages it knew in life but cannot speak'],
    traits: [
      { name: 'Incorporeal Movement', type: 'trait', description: 'The specter can move through other creatures and objects as if they were difficult terrain. It takes 5 (1d10) force damage if it ends its turn inside an object.' },
      { name: 'Sunlight Sensitivity', type: 'trait', description: 'While in sunlight, the specter has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight.' },
    ],
    actions: [
      { name: 'Life Drain', type: 'attack', description: 'Melee Spell Attack: +4 to hit, reach 5 ft., one creature. Hit: 10 (3d6) necrotic damage. The target must succeed on a DC 10 Constitution saving throw or its hit point maximum is reduced by an amount equal to the damage taken. This reduction lasts until the creature finishes a long rest. The target dies if this effect reduces its hit point maximum to 0.', attackBonus: 4, damage: '3d6 necrotic', saveDc: 10, saveType: 'con' },
    ],
    tags: ['undead', 'incorporeal', 'life drain'],
  },
  {
    id: 'undead-vampire',
    name: 'Vampire',
    cr: 13,
    size: 'Medium',
    type: 'undead',
    alignment: 'lawful evil',
    armorClass: 16,
    hitPoints: 144,
    hitDice: '17d8+68',
    speed: '30 ft.',
    abilities: { str: 18, dex: 18, con: 18, int: 17, wis: 15, cha: 18 },
    skills: ['Perception +7', 'Stealth +9'],
    senses: ['Darkvision 120 ft.', 'Passive Perception 17'],
    languages: ['the languages it knew in life'],
    traits: [
      { name: 'Legendary Resistance (3/Day)', type: 'trait', description: 'If the vampire fails a saving throw, it can choose to succeed instead.' },
      { name: 'Misty Escape', type: 'trait', description: 'When it drops to 0 hit points outside its resting place, the vampire transforms into a cloud of mist (as in the Shapechanger trait) instead of falling unconscious, provided that it isn\'t in running water or sunlight. If it can\'t transform, it is destroyed.' },
      { name: 'Regeneration', type: 'trait', description: 'The vampire regains 20 hit points at the start of its turn if it has at least 1 hit point and isn\'t in sunlight or running water. If the vampire takes radiant damage or damage from holy water, this trait doesn\'t function at the start of the vampire\'s next turn.' },
      { name: 'Shapechanger', type: 'trait', description: 'If the vampire isn\'t in sunlight or running water, it can use its action to polymorph into a Tiny bat or a Medium cloud of mist, or back into its true form.' },
      { name: 'Spider Climb', type: 'trait', description: 'The vampire can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check.' },
      { name: 'Vampire Weaknesses', type: 'trait', description: 'Forbiddance: Can\'t enter a residence without an invitation. Harmed by Running Water: Takes 20 acid damage when it ends its turn in running water. Stake to the Heart: Impaled through the heart while incapacitated in its resting place, the vampire is paralyzed. Sunlight Hypersensitivity: Takes 20 radiant damage when it starts its turn in sunlight.' },
    ],
    actions: [
      { name: 'Multiattack (Vampire Form Only)', type: 'ability', description: 'The vampire makes two attacks, only one of which can be a bite attack.' },
      { name: 'Unarmed Strike (Vampire Form Only)', type: 'attack', description: 'Melee Weapon Attack: +9 to hit, reach 5 ft., one creature. Hit: 8 (1d8+4) bludgeoning damage. Instead of dealing damage, the vampire can grapple the target (escape DC 18).', attackBonus: 9, damage: '1d8+4 bludgeoning' },
      { name: 'Bite (Bat or Vampire Form Only)', type: 'attack', description: 'Melee Weapon Attack: +9 to hit, reach 5 ft., one willing creature, or a creature that is grappled by the vampire, incapacitated, or restrained. Hit: 7 (1d6+4) piercing damage plus 10 (3d6) necrotic damage. The target\'s hit point maximum is reduced by an amount equal to the necrotic damage taken, and the vampire regains hit points equal to that amount.', attackBonus: 9, damage: '1d6+4 piercing + 3d6 necrotic' },
      { name: 'Charm', type: 'ability', description: 'The vampire targets one humanoid it can see within 30 ft. The target must succeed on a DC 17 Wisdom saving throw or be magically charmed. The charmed target regards the vampire as a trusted friend to be heeded and protected. Although the target isn\'t under the vampire\'s control, it takes the vampire\'s requests or actions in the most favorable way it can.', saveDc: 17, saveType: 'wis' },
      { name: 'Children of the Night (1/Day)', type: 'ability', description: 'The vampire magically calls 2d4 swarms of bats or rats (night or underground only), or 3d6 wolves. The called creatures arrive in 1d4 rounds, acting as allies of the vampire and obeying its spoken commands.' },
    ],
    legendaryActions: [
      { name: 'Move', type: 'ability', description: 'The vampire moves up to its speed without provoking opportunity attacks.' },
      { name: 'Unarmed Strike', type: 'attack', description: 'The vampire makes one unarmed strike.', attackBonus: 9, damage: '1d8+4 bludgeoning' },
      { name: 'Bite (Costs 2 Actions)', type: 'attack', description: 'The vampire makes one bite attack.', attackBonus: 9, damage: '1d6+4 piercing + 3d6 necrotic' },
    ],
    tags: ['undead', 'legendary', 'boss', 'vampire', 'charismatic'],
  },
  {
    id: 'undead-vampire-spawn',
    name: 'Vampire Spawn',
    cr: 5,
    size: 'Medium',
    type: 'undead',
    alignment: 'neutral evil',
    armorClass: 15,
    hitPoints: 82,
    hitDice: '11d8+33',
    speed: '30 ft.',
    abilities: { str: 16, dex: 16, con: 16, int: 11, wis: 10, cha: 12 },
    skills: ['Perception +4', 'Stealth +7'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 14'],
    languages: ['the languages it knew in life'],
    traits: [
      { name: 'Regeneration', type: 'trait', description: 'The vampire regains 10 hit points at the start of its turn if it has at least 1 hit point and isn\'t in sunlight or running water. If the vampire takes radiant damage or damage from holy water, this trait doesn\'t function at the start of the vampire\'s next turn.' },
      { name: 'Spider Climb', type: 'trait', description: 'The vampire can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check.' },
      { name: 'Vampire Weaknesses', type: 'trait', description: 'Forbiddance, Harmed by Running Water (20 acid damage), Stake to the Heart (paralyzed), Sunlight Hypersensitivity (20 radiant damage when starting turn in sunlight).' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The vampire makes two attacks, only one of which can be a bite attack.' },
      { name: 'Claws', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one creature. Hit: 8 (2d4+3) slashing damage. Instead of dealing damage, the vampire can grapple the target (escape DC 13).', attackBonus: 6, damage: '2d4+3 slashing' },
      { name: 'Bite', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one willing creature, grappled by the vampire, incapacitated, or restrained. Hit: 6 (1d6+3) piercing damage plus 7 (2d6) necrotic damage. The target\'s hit point maximum is reduced by an amount equal to the necrotic damage taken.', attackBonus: 6, damage: '1d6+3 piercing + 2d6 necrotic' },
    ],
    tags: ['undead', 'vampire', 'minion'],
  },
  {
    id: 'undead-wight',
    name: 'Wight',
    cr: 3,
    size: 'Medium',
    type: 'undead',
    alignment: 'neutral evil',
    armorClass: 14,
    hitPoints: 45,
    hitDice: '6d8+18',
    speed: '30 ft.',
    abilities: { str: 15, dex: 14, con: 16, int: 10, wis: 13, cha: 15 },
    skills: ['Perception +3', 'Stealth +4'],
    senses: ['Darkvision 60 ft.', 'Passive Perception 13'],
    languages: ['the languages it knew in life'],
    traits: [
      { name: 'Sunlight Sensitivity', type: 'trait', description: 'While in sunlight, the wight has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight.' },
    ],
    actions: [
      { name: 'Multiattack', type: 'ability', description: 'The wight makes two longsword attacks or two longbow attacks. It can use its Life Drain in place of one longsword attack.' },
      { name: 'Life Drain', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 5 (1d6+2) necrotic damage. The target must succeed on a DC 13 Constitution saving throw or its hit point maximum is reduced by an amount equal to the damage taken. This reduction lasts until the target finishes a long rest. The target dies if this effect reduces its hit point maximum to 0.', attackBonus: 4, damage: '1d6+2 necrotic', saveDc: 13, saveType: 'con' },
      { name: 'Longsword', type: 'attack', description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 6 (1d8+2) slashing damage, or 7 (1d10+2) slashing damage if used with two hands.', attackBonus: 4, damage: '1d8+2 slashing' },
      { name: 'Longbow', type: 'attack', description: 'Ranged Weapon Attack: +4 to hit, range 150/600 ft., one target. Hit: 6 (1d8+2) piercing damage.', attackBonus: 4, damage: '1d8+2 piercing' },
    ],
    tags: ['undead', 'life drain', 'soldier'],
  },
  {
    id: 'undead-will-o-wisp',
    name: "Will-o'-Wisp",
    cr: 2,
    size: 'Tiny',
    type: 'undead',
    alignment: 'chaotic evil',
    armorClass: 19,
    hitPoints: 22,
    hitDice: '9d4',
    speed: '0 ft., fly 50 ft. (hover)',
    abilities: { str: 1, dex: 28, con: 10, int: 13, wis: 14, cha: 11 },
    senses: ['Darkvision 120 ft.', 'Passive Perception 12'],
    languages: ['the languages it knew in life'],
    traits: [
      { name: 'Consume Life', type: 'trait', description: 'As a bonus action, the will-o\'-wisp can target one creature it can see within 5 ft. of it that has 0 hit points and is still alive. The target must succeed on a DC 10 Constitution saving throw against this magic or die. If the target dies, the will-o\'-wisp regains 10 (3d6) hit points.' },
      { name: 'Ephemeral', type: 'trait', description: 'The will-o\'-wisp can\'t wear or carry anything.' },
      { name: 'Incorporeal Movement', type: 'trait', description: 'The will-o\'-wisp can move through other creatures and objects as if they were difficult terrain. It takes 5 (1d10) force damage if it ends its turn inside an object.' },
      { name: 'Variable Illumination', type: 'trait', description: 'The will-o\'-wisp sheds bright light in a 5- to 20-ft. radius and dim light for an additional number of ft. equal to the chosen radius. The will-o\'-wisp can alter the radius as a bonus action.' },
    ],
    actions: [
      { name: 'Shock', type: 'attack', description: 'Melee Spell Attack: +4 to hit, reach 5 ft., one creature. Hit: 9 (2d8) lightning damage.', attackBonus: 4, damage: '2d8 lightning' },
      { name: 'Invisibility', type: 'ability', description: 'The will-o\'-wisp and its light magically become invisible until it attacks or uses its Consume Life, or until its concentration ends (as if concentrating on a spell).' },
    ],
    tags: ['undead', 'incorporeal', 'swamp', 'mislead'],
  },
  {
    id: 'undead-wraith',
    name: 'Wraith',
    cr: 5,
    size: 'Medium',
    type: 'undead',
    alignment: 'neutral evil',
    armorClass: 13,
    hitPoints: 67,
    hitDice: '9d8+27',
    speed: '0 ft., fly 60 ft. (hover)',
    abilities: { str: 6, dex: 16, con: 16, int: 12, wis: 14, cha: 15 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 12'],
    languages: ['the languages it knew in life'],
    traits: [
      { name: 'Incorporeal Movement', type: 'trait', description: 'The wraith can move through other creatures and objects as if they were difficult terrain. It takes 5 (1d10) force damage if it ends its turn inside an object.' },
      { name: 'Sunlight Sensitivity', type: 'trait', description: 'While in sunlight, the wraith has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight.' },
    ],
    actions: [
      { name: 'Life Drain', type: 'attack', description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one creature. Hit: 21 (4d8+3) necrotic damage. The target must succeed on a DC 14 Constitution saving throw or its hit point maximum is reduced by an amount equal to the damage taken. This reduction lasts until the target finishes a long rest. The target dies if this effect reduces its hit point maximum to 0.', attackBonus: 6, damage: '4d8+3 necrotic', saveDc: 14, saveType: 'con' },
      { name: 'Create Specter', type: 'ability', description: 'The wraith targets a humanoid within 10 ft. of it that has been dead for no longer than 1 minute and died violently. The target\'s spirit rises as a specter in the space of its corpse or in the nearest unoccupied space. The specter is under the wraith\'s control.' },
    ],
    tags: ['undead', 'incorporeal', 'life drain'],
  },
  {
    id: 'undead-zombie',
    name: 'Zombie',
    cr: 0.25,
    size: 'Medium',
    type: 'undead',
    alignment: 'neutral evil',
    armorClass: 8,
    hitPoints: 22,
    hitDice: '3d8+9',
    speed: '20 ft.',
    abilities: { str: 13, dex: 6, con: 16, int: 3, wis: 6, cha: 5 },
    senses: ['Darkvision 60 ft.', 'Passive Perception 8'],
    languages: ['understands the languages it knew in life but cannot speak'],
    traits: [
      { name: 'Undead Fortitude', type: 'trait', description: 'If damage reduces the zombie to 0 hit points, it must make a Constitution saving throw with a DC of 5 + the damage taken, unless the damage is radiant or from a critical hit. On a success, the zombie drops to 1 hit point instead.', saveDc: 5, saveType: 'con' },
    ],
    actions: [
      { name: 'Slam', type: 'attack', description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6+1) bludgeoning damage.', attackBonus: 3, damage: '1d6+1 bludgeoning' },
    ],
    tags: ['undead', 'minion', 'basic'],
  },
]
