// src/lib/shopItems/tierA.ts
// Tier A — free once per session. Minor one-time-use consumables.
// Every item here is single-use: it leaves the inventory when used.

import type { ShopItem } from '../shopData'

/** Compact builder — id, name, desc (+optional url). All tier A, free, consumable. */
function a(id: string, name: string, desc: string, url: string | null = null): ShopItem {
  return { id, tier: 'A', name, desc, category: 'consumable', url }
}

export const TIER_A_ITEMS: ShopItem[] = [
  // Legacy ids — keep stable for the Python bot + old purchases.
  a('healing_potion', 'Potion of Healing', 'Drink to regain 2d4+2 hit points.',
    'https://www.dndbeyond.com/magic-items/8960-potion-of-healing'),
  a('holy_water', 'Holy Water', 'Deals 2d6 radiant damage to undead or fiends on a hit.',
    'https://www.dndbeyond.com/equipment/507-holy-water'),
  a('antitoxin', 'Antitoxin', 'Advantage on saving throws against poison for 1 hour.',
    'https://www.dndbeyond.com/equipment/488-antitoxin'),

  a('a_bandage_roll', 'Field Bandage', 'Stabilizes a dying creature without a check when applied as an action.'),
  a('a_smelling_salts', 'Smelling Salts', 'Wakes an unconscious (not dying) creature instantly.'),
  a('a_chalk_glow', 'Glowing Chalk', 'Marks glow faintly for 8 hours — never lose your way in a dungeon.'),
  a('a_candle_hour', 'Hour Candle', 'Burns exactly one hour, shedding dim light in a 10-ft radius.'),
  a('a_flint_strike', 'Quickstrike Flint', 'Lights any mundane fire as a free action, even in wind or rain.'),
  a('a_whetstone_keen', 'Traveler\'s Whetstone', 'Hone one blade: +1 damage on the first hit after sharpening.'),
  a('a_lucky_copper', 'Lucky Copper', 'Flip before a d20 roll: heads, add +1 to the result. One use.'),
  a('a_ration_sweet', 'Honeyed Ration', 'A delicious meal that also grants 1 temporary hit point.'),
  a('a_waterskin_pure', 'Purified Waterskin', 'Clean water for a day; cures mild nausea when drunk.'),
  a('a_torch_ever', 'Long-Burn Torch', 'A torch treated with alchemical wax — burns 2 hours instead of 1.'),
  a('a_soap_lye', 'Scentless Soap', 'Wash away your scent: beasts tracking you by smell have disadvantage for 8 hours.'),
  a('a_string_wax', 'Waxed Twine (50 ft)', 'Waterproof line strong enough for snares and trip-cords. Single spool.'),
  a('a_bell_tiny', 'Tin Warning Bell', 'Rig to a door or line: rings loudly when disturbed. One rigging.'),
  a('a_mirror_shard', 'Polished Mirror Shard', 'Peek around a corner without exposing yourself. Shatters after rough use.'),
  a('a_chewing_root', 'Bitterwake Root', 'Chew to shrug off drowsiness — ignore one level of exhaustion for 1 hour.'),
  a('a_salt_pack', 'Pack of Salt', 'Preserves rations, or lay a line certain spirits will not cross (GM\'s call).'),
  a('a_garlic_braid', 'Garlic Braid', 'Pungent ward: some undead hesitate. Advantage on one Intimidation vs. vampiric foes.'),
  a('a_incense_stick', 'Calming Incense', 'Burn during a short rest: everyone resting nearby regains +1 hit point.'),
  a('a_bird_whistle', 'Bird Call Whistle', 'Perfectly mimics a songbird — a discreet signal only your party knows.'),
  a('a_fish_hooks', 'Fisher\'s Kit', 'Hooks and line good for one day of fishing — or one improvised trap.'),
  a('a_grease_pot', 'Pot of Axle Grease', 'Slick one 5-ft square: DC 10 Dex save or fall prone. One use.'),
  a('a_pepper_dust', 'Pepper Dust Pouch', 'Fling at a face: target sneezes, disadvantage on its next attack roll.'),
  a('a_firewood_dry', 'Dry Kindling Bundle', 'Guaranteed campfire even after rain. One night\'s warmth.'),
  a('a_map_scrap', 'Scrap of an Old Map', 'A fragment of local geography — advantage on one Survival check to navigate.'),
  a('a_journal_page', 'Blank Vellum Page', 'Fine vellum that takes ink beautifully — worth a copy of any one document.'),
  a('a_ink_vial', 'Vial of Oak-Gall Ink', 'Enough ink for a day of writing or one detailed map.'),
  a('a_sewing_kit', 'Mending Kit', 'Repair one torn garment, strap, or pack on a short rest.'),
  a('a_boot_nails', 'Hobnail Grips', 'Fit to boots: advantage on one check to keep footing on ice or slick stone.'),
  a('a_ear_wax', 'Wax Ear Plugs', 'Advantage on one save against a harmful sound or a siren\'s song.'),
  a('a_nose_plugs', 'Nose Plugs', 'Ignore stench effects (like a troglodyte\'s) for 1 hour.'),
  a('a_dice_bone', 'Bone Dice Set', 'Loaded — win one mundane tavern game. Don\'t get caught.'),
  a('a_cards_marked', 'Deck of Marked Cards', 'Subtly marked. Advantage on one Sleight of Hand check at cards.'),
  a('a_tea_healer', 'Healer\'s Tea', 'Brew at camp: one creature regains 1d4 hit points over a short rest.'),
  a('a_broth_hearty', 'Hearty Broth Cube', 'Dissolve in hot water — a warm meal that steadies nerves: +1 on your next save vs. fear.'),
  a('a_jerky_wolf', 'Wolf Jerky Strip', 'Tough, salty, sustaining. Counts as a day\'s food for one person.'),
  a('a_biscuit_iron', 'Iron Biscuit', 'Nearly unbreakable trail bread. Also usable once as an improvised sling stone (1d4).'),
  a('a_apple_orchard', 'Orchard Apple', 'Crisp and sweet. Feeding it to a mount grants the mount +5 ft speed for 1 hour.'),
  a('a_sugar_lump', 'Sugar Lumps', 'Calm a nervous mount or bribe a small beast — advantage on one Animal Handling check.'),
  a('a_carrot_bunch', 'Bunch of Carrots', 'A favorite of horses and rabbits alike. Advantage on one check to befriend a herbivore.'),
  a('a_bone_dog', 'Meaty Bone', 'Distract one guard dog or similar beast for up to 10 minutes.'),
  a('a_cheese_wheel_s', 'Small Cheese Wheel', 'Shareable snack: up to four creatures each gain 1 temporary hit point.'),
  a('a_wine_skin', 'Skin of Table Wine', 'Loosens tongues: advantage on one Persuasion check made over a shared drink.'),
  a('a_ale_bottle', 'Bottled Dark Ale', 'Liquid courage: +1 on your next save against fear, -1 on your next Dex check.'),
  a('a_flower_pressed', 'Pressed Moonflower', 'A romantic token. Advantage on one Persuasion check with someone charmed by beauty.'),
  a('a_ribbon_silk', 'Silk Ribbon', 'A fine gift or a marker visible at 100 ft in daylight.'),
  a('a_button_brass', 'Brass Uniform Button', 'From a city guard\'s coat — a prop for one Deception check to pass as one of them.'),
  a('a_coin_foreign', 'Foreign Coin', 'Odd currency from a far land. A curiosity that can open one conversation with a collector.'),
  a('a_feather_raven', 'Raven Feather Quill', 'Writes beautifully; scribes value it. Advantage on one check to forge handwriting.'),
  a('a_wig_horsehair', 'Horsehair Wig', 'A passable disguise element — +1 on one Deception check while disguised.'),
  a('a_mask_plain', 'Plain Festival Mask', 'Conceals your face at a masquerade or in a crowd. One event\'s anonymity.'),
  a('a_gloves_cotton', 'Cotton Gloves', 'Leave no fingerprints — foil mundane attempts to identify you by touch. One job.'),
  a('a_rag_oily', 'Oiled Rag', 'Muffle a squeaky hinge or clean a fouled blade. One use.'),
  a('a_wedge_door', 'Iron Door Wedge', 'Jam a door shut (DC 15 Strength to force) or hold it open. Single wedge.'),
  a('a_spike_wood', 'Wooden Stake', 'Sharpened hardwood. You know what it\'s for. (1d4 piercing, 2d4 vs. a restrained vampire.)'),
  a('a_hammer_tack', 'Tack Hammer & Nails', 'Fix a board, seal a crate, or rig one simple trap component.'),
  a('a_line_plumb', 'Plumb Line', 'Find true vertical — advantage on one check to detect a sloped or trick floor.'),
  a('a_lens_reading', 'Reading Lens', 'Magnifies fine print: advantage on one Investigation check on a document.'),
  a('a_powder_itch', 'Itching Powder', 'Slip into clothing: victim has disadvantage on concentration for 10 minutes.'),
  a('a_snuff_pinch', 'Pinch of Snuff', 'A sharp sniff clears the head: end the dazed feeling of one failed Perception check and look again.'),
  a('a_stone_skipping', 'Perfect Skipping Stone', 'Uncannily well balanced. +2 on one improvised thrown attack (1d4).'),
  a('a_twig_dowsing', 'Dowsing Twig', 'Twitches over water: find drinkable water within a mile, once.'),
  a('a_bark_willow', 'Willow Bark Strips', 'Chew to dull pain: +1 hit point when you spend any Hit Die this rest.'),
  a('a_moss_dry', 'Dry Tinder Moss', 'Catches a spark instantly — light a fire as part of another action, once.'),
  a('a_leaf_mint', 'Mint Leaves', 'Freshens breath before a delicate audience: +1 on one Persuasion check made face-to-face.'),
  a('a_clay_lump', 'Lump of Soft Clay', 'Take an impression of a key, seal, or footprint. One impression.'),
  a('a_string_music', 'Spare Lute String', 'Replace a snapped string mid-performance — save one Performance check from disaster.'),
  a('a_rosin_cake', 'Cake of Rosin', 'Grip for bow or hands: +1 on one Athletics check to climb or grapple.'),
  a('a_patch_leather', 'Leather Patch Kit', 'Mend a boot, strap, or waterskin during a short rest.'),
  a('a_tallow_candle', 'Tallow Stub', 'A humble candle stub — 30 minutes of dim light in a 5-ft radius.'),
]
