// src/lib/shopItems/tierB.ts
// Tier B — free once per day. One-time-use consumables, slightly more
// situational than tier A. No `always` flags in this tier by design:
// list B is 'Potion of Healing' + 4 seeded-random uniques.

import type { ShopItem } from '../shopData'

function b(id: string, name: string, desc: string, url: string | null = null, category: ShopItem['category'] = 'consumable'): ShopItem {
  return { id, tier: 'B', name, desc, category, url }
}

export const TIER_B_ITEMS: ShopItem[] = [
  // Legacy ids — keep stable.
  b('torch_bundle', 'Bundle of Torches', 'Five torches, each burning 20 ft bright + 20 ft dim light for 1 hour.', null, 'gear'),
  b('trail_rations', 'Trail Rations', 'One day of rations — keeps an adventurer going on the road.'),
  b('rope_hempen', 'Hempen Rope (50 ft)', 'Strong rope bearing up to 900 lbs. An adventurer staple.', null, 'gear'),

  b('b_oil_lamp', 'Flask of Lamp Oil', 'Fuels a lantern for 6 hours — or splashes one 5-ft square (1d4 fire if ignited).'),
  b('b_grapple_cord', 'Knotted Climbing Cord (25 ft)', 'Pre-knotted line: climb it without a check. Frays after one descent.'),
  b('b_chain_light', 'Light Chain (10 ft)', 'Binds a door or wrists (DC 14 Strength to burst). Single length.'),
  b('b_lock_simple', 'Simple Padlock', 'Secure a chest or door against casual thieves (DC 12 to pick). One lock, one key.'),
  b('b_tent_one', 'One-Night Tent', 'A compact shelter that keeps one sleeper dry — negates weather penalties for one long rest.'),
  b('b_bedroll_warm', 'Wool Bedroll', 'Sleep warm anywhere: one comfortable long rest even in cold conditions.'),
  b('b_blanket_wool', 'Heavy Wool Blanket', 'Wrap against the cold: advantage on one save vs. natural cold exposure.'),
  b('b_net_fishing', 'Weighted Net', 'Throw (10 ft): Large or smaller target is restrained until it escapes (DC 10 Str). Tears after one use.'),
  b('b_sack_burlap', 'Reinforced Sack', 'Holds 60 lbs without splitting — or one uncooperative goblin (they hate this).'),
  b('b_crowbar_iron', 'Iron Crowbar', 'Advantage on one Strength check to force something open, then the tip snaps.', null, 'gear'),
  b('b_shovel_camp', 'Folding Camp Shovel', 'Dig a firepit, latrine, or shallow cache in half the usual time. Handle cracks after a day\'s digging.', null, 'gear'),
  b('b_ladder_rope', 'Rope Ladder (15 ft)', 'Deploys in seconds; climbing requires no check. Rungs give out after one heavy trip.', null, 'gear'),
  b('b_pole_ten', 'Collapsible 10-ft Pole', 'The dungeon classic — probe for traps ahead of every footstep. Splinters on the first trap it springs.', null, 'gear'),
  b('b_pit_kit', 'Snare Kit', 'Rig one snare: first Small/Medium creature through must save (DC 12 Dex) or hang restrained.'),
  b('b_caltrops_tin', 'Tin of Caltrops', 'Cover one 5-ft square: entering creatures take 1 piercing and stop moving. One scatter.'),
  b('b_marbles_bag', 'Bag of Marbles', 'Scatter over 10 ft: DC 10 Dex save or fall prone. Impossible to fully recover.'),
  b('b_ballbearings', 'Pouch of Ball Bearings', 'A rolling hazard across a 10-ft square — DC 10 Dex save or prone. One pour.'),
  b('b_powder_flash', 'Flash Powder Packet', 'Toss into flame: blinding flash, creatures within 10 ft save (DC 12 Con) or blinded 1 round.'),
  b('b_smoke_candle', 'Smoke Candle', 'Fills a 10-ft cube with gray smoke over 1 minute — light obscurement while it burns.'),
  b('b_firecracker', 'String of Firecrackers', 'A staccato racket for 2 rounds — perfect distraction, 60 ft away from where you are.'),
  b('b_whistle_shrill', 'Shrill Signal Whistle', 'Heard a half-mile away. Guaranteed to wake a sleeping camp — yours or theirs.'),
  b('b_lantern_dark', 'Hooded Dark-Lantern', 'Shutter the light instantly: swap between bright 30 ft and total darkness as a bonus action. Wick lasts one night.', null, 'gear'),
  b('b_candle_black', 'Black Beeswax Candle', 'Burns with almost no smoke or scent — read at night without giving away your camp. 3 hours.'),
  b('b_ink_invisible', 'Invisible Ink Vial', 'Write one hidden message — revealed only by gentle heat.'),
  b('b_seal_wax', 'Sealing Wax & Blank Signet', 'Seal one letter convincingly; the blank signet takes one crest impression.'),
  b('b_paper_oil', 'Oilskin Document Wrap', 'Keeps one document or map bone-dry through river, rain, or ale-spill.'),
  b('b_glue_pot', 'Pot of Strong Glue', 'Bonds anything to anything in 1 minute (DC 14 Strength to separate). One pot.'),
  b('b_solvent_vial', 'Vial of Solvent', 'Dissolves glue, tar, or sovereign-glue-adjacent problems on one surface.'),
  b('b_acid_weak', 'Vial of Weak Acid', 'Eats one mundane lock or hinge in 10 minutes — silent entry, no check.'),
  b('b_oil_slick', 'Slick Oil Flask', 'Coat a 10-ft-square surface: creatures crossing save (DC 11 Dex) or fall prone. One flask.'),
  b('b_tar_pot', 'Pot of Tar', 'Sticky coating for one square: speed halved crossing it until scraped clean.'),
  b('b_resin_torch', 'Resin-Soaked Torch', 'Burns even in rain and wind — 1 hour of stubborn light.', null, 'gear'),
  b('b_matchsticks', 'Alchemical Matches (5)', 'Strike anywhere. Light a fire as a free action, five times total (one bundle).'),
  b('b_beacon_dye', 'Signal Dye Packet', 'Dyes a stream or pool bright crimson for an hour — an unmissable marker or warning.'),
  b('b_kit_healer', 'Healer\'s Satchel (1 use)', 'One expertly-packed treatment: stabilize a creature AND restore 1 hit point.'),
  b('b_splint_set', 'Splint & Sling Set', 'Immobilize one injury: the patient can travel without worsening a broken limb.'),
  b('b_tonic_iron', 'Iron Tonic', 'A bracing draught: +2 temporary hit points for 8 hours.'),
  b('b_tonic_spring', 'Spring Tonic', 'Refreshing herbal blend: remove one level of exhaustion after a short rest. Once.'),
  b('b_drops_eye', 'Clearsight Eye Drops', 'Rinse the eyes: end blindness caused by dust, sand, or irritants instantly.'),
  b('b_balm_burn', 'Burn Balm', 'Soothe scorched skin: regain 1d4 hit points if your last damage taken was fire.'),
  b('b_salve_frost', 'Frostbite Salve', 'Warming ointment: regain 1d4 hit points if your last damage taken was cold.'),
  b('b_chalk_case', 'Case of Chalk Sticks (10)', 'Mark a whole dungeon level\'s worth of turns and doors.'),
  b('b_twine_spool', 'Great Spool of Twine (300 ft)', 'The labyrinth solution — pay it out behind you and never be lost. One spool.'),
  b('b_pegs_iron', 'Iron Pitons (6)', 'Anchor ropes on a cliff face: climbing your fixed line needs no check. Pegs stay behind.', null, 'gear'),
  b('b_hammock_net', 'Tree Hammock', 'Sleep safely off the forest floor — ignore ground-crawling nuisances for one long rest.', null, 'gear'),
  b('b_repellent_bug', 'Insect Repellent Salve', 'Swarms of ordinary insects avoid you for 8 hours; insect swarm attacks vs. you have disadvantage once.'),
  b('b_musk_deer', 'Masking Musk', 'Smell like prey animal, not person: predators tracking by scent are confused for 4 hours.'),
  b('b_bait_beast', 'Beast Bait Chunk', 'Irresistible to carnivores: lure one beast up to 60 ft to the bait\'s location.'),
  b('b_feed_horse', 'Feed Bag (Oats)', 'A full day\'s feed for one mount — it travels 1 extra hour today without a check.'),
  b('b_shoes_horse', 'Spare Horseshoes & Nails', 'Re-shoe one mount: fixes lameness from a thrown shoe on a short rest.'),
  b('b_kit_mess', 'Traveler\'s Mess Kit', 'Cook a real meal from foraged food: everyone who shares it regains +1 HP per Hit Die spent tonight.', null, 'gear'),
  b('b_spices_pouch', 'Pouch of Cooking Spices', 'Turn iron rations into a feast: the party gains advantage on the next morale-adjacent Charisma check together.'),
  b('b_coffee_dark', 'Dark Roast Coffee Pouch', 'Brew at dawn: one creature ignores the effects of a poor night\'s sleep today.'),
  b('b_tea_black', 'Strong Black Tea Brick', 'Keeps one watch-stander alert: advantage on one Perception check made on watch tonight.'),
  b('b_rum_ration', 'Sailor\'s Rum Ration', 'Steadies sea-legs and nerves: advantage on one save vs. fear, made within the hour.'),
  b('b_grog_flask', 'Flask of Grog', 'Share a swig around: the party\'s next group check gains +1 from camaraderie.'),
  b('b_dice_weighted', 'Subtly Weighted Dice', 'Win one dice game against a mundane opponent. Melts suspiciously if detect magic is cast on it (it isn\'t magic — it\'s wax).'),
  b('b_disguise_paint', 'Face Paint Pots', 'Enough theatrical paint for one full disguise: +2 on the associated Deception check.'),
  b('b_costume_guard', 'Patchwork Guard Tabard', 'A convincing-at-a-distance uniform for one infiltration. Falls apart if examined closely.'),
  b('b_papers_travel', 'Blank Travel Papers', 'Officially-watermarked stock — one forged pass with advantage on the forgery check.'),
  b('b_pouch_coin_decoy', 'Decoy Coin Pouch', 'Jingles like 50 gold, contains washers. Throw it to end one pursuit by greedy bandits.'),
  b('b_pigeon_homing', 'Homing Pigeon (1 flight)', 'Carries one small message back to where you bought it — even across a province.'),
  b('b_map_region', 'Regional Road Map', 'Accurate roads and inns: halve the chance of getting lost on one journey.'),
  b('b_almanac_page', 'Almanac Page', 'Today\'s weather, tides, and moon: advantage on one Nature or Survival check to plan around them.'),
  b('b_holy_symbol_tin', 'Tin Holy Symbol', 'A humble but consecrated focus — works for one casting if yours is lost.'),
  b('b_censer_hand', 'Hand Censer & Incense', 'One hour of sanctified smoke: advantage on one Religion check performed during a rite.'),
  b('b_offering_candles', 'Votive Offering Candles', 'Proper form at any shrine: one favorable first impression with its keepers.'),
]
